README file for entries-api
web-platform-tests/wpt pull request #10003
Opened 2018-03-13 18:16 UTC by inexorabletash

2018-03-13 18:21 UTC, aliams requested changes

2018-03-13 18:21 UTC, aliams commented on entries-api/README.md
> +clone of the repo for access to the `entries-api/support` files.
...local clone of the repo *is required* for access...?

2018-03-13 18:26 UTC, aliams approved these changes

2018-03-13 18:44 UTC, w3c-bots commented
# Build PASSED

Started: 2018-03-13 18:35:23
Finished: 2018-03-13 18:42:31





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25876)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/352982005)

2018-03-13 19:40 UTC, mkruisselbrink commented on entries-api/README.md
> +clone of the repo is required for access to the `entries-api/support` files.
It wasn't obvious to me until looking at the entries-api/support directory why you would need access to those files. Maybe explicitly mention that the test data it is talking about lives in that directory?

2018-03-14 17:03 UTC, inexorabletash commented
Thanks - how's this rewording?

2018-03-14 17:40 UTC, mkruisselbrink approved these changes
thanks!

2018-03-14 17:41 UTC, merged