Changing WebDriver test_parent_htmldocument to expect error
web-platform-tests/wpt pull request #10058
Opened 2018-03-15 20:04 UTC by jimevans

When the context element is `document.documentElement`, and an attempt is
made to find elements from that context element using an XPath of `..`, a
snapshot is returned containing the `document` object. While this is
apparently the correct behavior for XPath, the WebDriver spec says that if
the object in the snapshot is not an element, we should return an error
with error code "invalid selector." The test_parent_htmldocument test in
both find_element_from_element.py and find_elements_from_element.py expect
a success in this case. This commit changes the tests to correctly expect
an error from the driver.

2018-03-15 20:16 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26047)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/354017317)

2018-03-16 09:07 UTC, andreastt requested changes
You are correct that the XPath selector `..` on the `<html>` element (the document element) should return an invalid selector error. This is consistent with the behaviour described in https://bugzilla.mozilla.org/show_bug.cgi?id=1424635#c0.

That said, I don’t think this is the correct patch for the issue. `test_parent_htmldocument` tests that it is possible to retrieve a parent HTMLDocument node that is `Node.DOCUMENT_NODE`. We have to test this specifically because the `nodeType` differs from other regular elements, and this matters in implementations such as Gecko.

I think we should fix this test to use `<body>` as the `from_element`, then write a new test for getting the relative ancestor of `<html>` and returning an invalid selector error.

Does that make sense?

2018-03-16 09:08 UTC, andreastt commented
See also https://hg.mozilla.org/mozilla-central/rev/3870805aea81 for the background for why we have this test.

2018-03-16 14:13 UTC, andreastt approved these changes

2018-03-16 14:46 UTC, merged