Get rid of last web-platform.test, make host_ip always present
web-platform-tests/wpt pull request #10078
Opened 2018-03-16 16:56 UTC by gsnedders

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/web-platform-tests/10078)

2018-03-16 17:21 UTC, w3c-bots commented
# Build PASSED

Started: 2018-03-16 16:58:01
Finished: 2018-03-16 17:12:39





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26115)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/354413305)

2018-03-19 13:35 UTC, jgraham commented
Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[tools/serve/serve.py, line 679 at r1](https://reviewable.io:443/reviews/w3c/web-platform-tests/10078#-L7ySN55KjtcSDY3_-Om:-L7ySN59jDaLC0ReLuqQ:bv39gg6) ([raw file](https://github.com/w3c/web-platform-tests/blob/6942d58e2a78eccfc404f444acc06b580c66fd79/tools/serve/serve.py#L679)):*
> ```Python
>     config_["bind_address"] = bind_address
>     if config.get("host_ip", None) is None:
>         config_["host_ip"] = host
> ```

This seems very confusing. I don't know what the better option is, but I'm pretty sure this is going to cause trouble.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/10078)*
<!-- Sent from Reviewable.io -->

2018-03-19 15:25 UTC, jgraham requested changes

2018-03-19 15:25 UTC, jgraham commented on tools/wptserve/wptserve/server.py
> +            Server.config = {"browser_host": server_address[0],
This doesn't seem very meaningful, to put `browser_host` and `server_host` and set them to o the same value.

2018-03-19 15:29 UTC, jgraham approved these changes

2018-03-19 16:03 UTC, merged