adds tests for the missing members of RTCRtpHeaderExtensionParameters
web-platform-tests/wpt pull request #10282
Opened 2018-04-03 16:09 UTC by kritisingh1

Closes #10253 
@foolip please review and let me know further changes required, if any.
Thanks

2018-04-03 16:18 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26775)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/361710503)

2018-04-19 19:02 UTC, kritisingh1 commented
@jgraham could you please review this and tell me if any further changes are required? Thanks :)

2018-11-03 04:46 UTC, alvestrand requested changes
Sorry, I don't think that this proposal for more tests makes sense.
It's not possible to add RTP extensions that the browser doesn't support - they require code deep in the WebRTC RTP engine, which you can't add through the API.
See http://w3c.github.io/webrtc-pc/#rtcrtpparameters - the header extensions is a read-only parameter.
I don't have any idea how you can verify that these mandatory fields in a read-only parameter are mandatory, but this approach won't work.

2018-11-03 04:46 UTC, alvestrand commented on webrtc/RTCRtpParameters-headerExtensions.html
> +  }, `setParameters() with modified headerExtensions should reject with InvalidModificationError, checks that id is a required field`);
This test doesn't test anything at all. You can't add new header extensions, and the error code (InvalidModificationError) is the same for all cases.

2018-11-03 04:46 UTC, alvestrand commented
Closing this PR, since a different approach is required (and I don't know what it is).

2018-11-03 04:46 UTC, closed without merging