Web Animations: Add test for Document::getAnimations across iframes
web-platform-tests/wpt pull request #10291
Opened 2018-04-03 21:37 UTC by stephenmcgruer

2018-04-03 21:51 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/26805)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/361856722)

2018-04-04 00:04 UTC, birtles commented
Looks good, but I'm curious if we actually need the separate iframe document? Elsewhere we just create an empty `<iframe>`:

* web-animations/timing-model/timelines/timelines.html
* web-animations/interfaces/Animation/constructor.html

Or just use a locally defined empty `<iframe>`:

* web-animations/interfaces/Animatable/animate.html
* web-animations/interfaces/Document/timeline.html

2018-04-04 00:05 UTC, birtles commented on web-animations/interfaces/Document/getAnimations.html
> +        10000);
10s is pretty short -- we should probably use `100 * MS_PER_SEC`.

2018-04-04 00:05 UTC, birtles commented on web-animations/interfaces/Document/getAnimations.html
> +        [ { backgroundColor: 'green' }, { backgroundColor: 'red' } ],
(Nit: I'm not sure we actually need any keyframes here. In the interest of keeping this test minimal perhaps we should drop them?)

2018-04-04 00:11 UTC, ahmadmiz approved these changes

2018-04-04 00:17 UTC, birtles requested changes
We might decide to drop the extra iframe document if it's not necessary, but at very least we should fix the 10s duration.

2018-04-04 11:20 UTC, stephenmcgruer reviewed
Removed the iframe, addressed the other comments.

2018-04-05 01:51 UTC, birtles approved these changes
Thanks!

2018-05-06 23:18 UTC, merged

2018-05-09 21:34 UTC, hiikezoe commented
I am wondering we don't normally squash this kind of modifications into the first commit?

2018-05-10 00:33 UTC, birtles commented
I probably just hit the wrong button when I merged it.