[wptrunner] Re-enable return code
web-platform-tests/wpt pull request #10742
Opened 2018-05-01 20:01 UTC by jugglinmike

In a previous commit [1] the WPT CLI was modified to ignore the return
value of the `wptrunner.start` method. Although this behavior is
convenient in cases where there is no expectation data, it obscures
errors that are relevant in any context.

Specifically, the `start` method returns a non-zero value when no tests
are run, but this is a reliable indicator of an erroneous configuration.
Because the `wpt run` command is used to validate the infrastructure of
the web-platform-tests project, ignoring this case allows
mis-configurations to go unnoticed [2].

Re-enable observance of the value returned by `wptrunner.start` and
update the code generated for the TaskCluster service to ignore this
value.

[1] 5a1b0365267b540c7f4feac3e0a85e9146997fcd
[2] https://github.com/w3c/web-platform-tests/pull/10721

2018-05-01 20:29 UTC, Hexcles commented on tools/ci/taskgraph.py
> +            (
Why is a subshell needed here?

2018-05-01 21:05 UTC, jugglinmike commented on tools/ci/taskgraph.py
> +            (
That's a good question. It isn't!

2018-05-01 22:17 UTC, Hexcles commented
```
 1:29.49 TEST_START: /infrastructure/browsers/firefox/prefs.html
 1:29.50 INFO Setting pref browser.display.foreground_color ('#00FF00')
 1:39.60 pid:6627 JavaScript error: executormarionette.py, line 84: TypeError: window.win.timeout is not a function
 1:44.66 TEST_END: TIMEOUT, expected OK
```

Hmm, weird.

2018-05-02 01:35 UTC, jugglinmike commented
That is strange. I'll investigate tomorrow

2018-05-02 19:55 UTC, jugglinmike commented
It turns out that test has been timing out since [its introduction](https://github.com/w3c/web-platform-tests/pull/10406) (see [this build report, for example](https://travis-ci.org/w3c/web-platform-tests/jobs/373261174)), but we haven't been aware of it because we've been ignoring the status code. I've rebased this branch and added a separate commit to fix that bug ([the original version of this branch is available here](https://github.com/w3c/web-platform-tests/compare/master...bocoup:wpt-fail-on-error-orig)).

2018-05-02 21:25 UTC, Hexcles approved these changes
Yikes... Thanks for fixing this!

2018-05-02 22:30 UTC, gsnedders commented
Can you add a test in `tools/wpt/tests` for this? At least the "exits with non-zero when there are no matching tests" case should be easy enough.

2018-05-03 09:11 UTC, jgraham requested changes

2018-05-03 09:36 UTC, jgraham commented
So I apparently forgot to press "submit" on my review. Sorry. The gist is that we should make it possible to return success when there are unexpected results without making it necessary to ignore errors entirely. I think both my original patch and this one address the problem in the wrong layer and we should fix wptrunner to work the way we want (e.g. with another command line flag).

2018-05-05 01:29 UTC, jugglinmike commented
Thanks for the feedback @jgraham. I've implemented the new feature as part of this pull request.

Recent changes in `master` introduced merge conflicts in this patch, so I had to rebase this branch in order for it to apply cleanly. [The original version of the branch is available here](https://github.com/w3c/web-platform-tests/compare/master...bocoup:wpt-fail-on-error-orig-2) in case that's of interest to any of you folks.

The text stating that the new tests "don't work on Windows for path reasons" is copied from the surrounding tests; the tests are failing for me in Windows, and I presume that this is the same issue.

2018-05-09 18:15 UTC, jgraham approved these changes

2018-05-09 18:15 UTC, jgraham commented on tools/ci/ci_taskcluster.sh
> +    ./wpt run chrome --log-tbpl==../artifacts/log_tbpl.log --log-tbpl-level=info --log-wptreport=../artifacts/wpt_report.json --log-mach=- --this-chunk=$3 --total-chunks=$4 --test-type=$2 -y  --no-pa
You don't want to do a drive-by fixup of the `==` that somehow got landed here despite (your?) earlier review comment pointing it out, do you?

2018-05-09 19:58 UTC, merged