Testdriver API to switch to a window
web-platform-tests/wpt pull request #10752
Opened 2018-05-02 02:48 UTC by kereliuk

This is a PR that adds a testdriver APi to switch to a window given a handle. There needs to be a way to get the required handle name so this feature depends on #10749 and #10747 for now.

(It also needs some docs and an infra test)

2018-05-07 17:46 UTC, kereliuk commented
An example and requested use case for this is for testing lifecycle APIs with page states.

For now I am leaving the infra test for a follow-up CL since I will want other commands that get me the window handles for that :)

2018-05-08 13:45 UTC, kereliuk commented
@gsnedders PTAL :)

2018-05-22 16:31 UTC, gsnedders requested changes
Couple of small comments, and needs some in-tree implementation (strongly) preferably. @jgraham might have more comments?

2018-05-22 16:31 UTC, gsnedders commented on resources/testdriver.js
> +            return window.test_driver_internal.switch_to_window(window_handle);
This is just calling itself; should probably be a promise that rejects like the above

2018-05-22 16:31 UTC, gsnedders commented on tools/wptrunner/wptrunner/executors/executorselenium.py
> +    def send_keys(self, element, keys):
This is the wrong protocol

2018-09-06 14:58 UTC, foolip commented
This is tracked by https://github.com/web-platform-tests/wpt/issues/10666, closing.

2018-09-06 14:58 UTC, closed without merging