Add netinfo/OWNERS
web-platform-tests/wpt pull request #10780
Opened 2018-05-02 13:25 UTC by zcorpan

cc @ferjm

2018-05-02 13:32 UTC, jkarlin approved these changes
lgtm

2018-05-02 15:04 UTC, igrigorik commented on netinfo/OWNERS
> +@ferjm
I'd also like to nominate @tarunban. :)

2018-05-02 15:51 UTC, marcoscaceres approved these changes
Ok from me

2018-05-02 15:52 UTC, marcoscaceres commented on netinfo/OWNERS
> +@ferjm
Done

2018-05-02 16:12 UTC, igrigorik approved these changes
lgtm!

2018-05-02 16:13 UTC, igrigorik commented on netinfo/OWNERS
> +@ferjm
ty!

2018-05-02 16:13 UTC, tarunban commented
thank you!

2018-05-04 07:38 UTC, ferjm requested changes
I am not following this spec anymore, so please remove my name from the list of owners. Thanks!

2018-05-04 08:47 UTC, zcorpan commented
Done

2018-05-04 08:48 UTC, merged