stability/verify unification
web-platform-tests/wpt pull request #10988
Opened 2018-05-14 14:48 UTC by gsnedders

Fixes #10921, and will fix #9874.

2018-05-16 14:38 UTC, gsnedders commented
Seems like I posted https://github.com/w3c/web-platform-tests/issues/9874#issuecomment-388892276 in the wrong place:

> So what I haven't done so far is move over to running the multi-part verify (with/without restarts, with/without chaos mode in Firefox), but it does now use the verify code.
>
> At the moment, it's still calling into the code through Python, rather than letting it run separately and then reading the logs. If we want to avoid going through the logs, we'd need to either make `check_stability` (in tools/wptrunner/wptrunner/stability.py) return something useful or call get_steps ourselves.

2018-05-23 12:41 UTC, jgraham requested changes
Just a few small changes to request.

Can you push an unstable test, and a stable one, to this PR so that we can see how the travis output looks?

2018-05-23 12:41 UTC, jgraham commented on tools/wptrunner/wptrunner/wptcommandline.py
> +                                 help="(DEPRECATED) Run a basic stability check on the selected tests")
You can use `help = argparse.SUPPRESS` to remove this option from the help.

2018-05-23 12:41 UTC, jgraham commented on tools/wptrunner/wptrunner/wptrunner.py
> +        kwargs['verify_max_time'] = None
Maybe log a warning here.

2018-05-28 16:36 UTC, gsnedders commented
@jgraham now done; sorry I missed your comments before!

2018-05-30 09:36 UTC, foolip commented
> Can you push an unstable test, and a stable one, to this PR so that we can see how the travis output looks?

Ping @gsnedders

2018-05-30 17:24 UTC, gsnedders commented
Um, yeah, seems I deleted them locally. Now readded.

2018-05-30 17:24 UTC, gsnedders commented
(labelled because that commit needs to go before merging)

2018-05-31 08:03 UTC, foolip commented
The Travis output looks about the same as before, so that seems to be working.

2018-06-05 10:45 UTC, jgraham approved these changes
Please remove the [DO NOT MERGE] commit :)

2018-06-05 14:40 UTC, merged