Add basic solid color test.
web-platform-tests/wpt pull request #10986
Opened 2018-05-14 13:26 UTC by Tavmjong

A basic solid color test.

2018-05-14 13:30 UTC, Ms2ger commented on svg/pservers/reftests/solidcolor-basic-001-ref.svg
> +          <!-- YYYY-MM-DD -->
Remove, we don't use rel=reviewer anymore.

2018-05-19 21:03 UTC, svgeesus commented on svg/pservers/reftests/solidcolor-basic-001-ref.svg
> +    <html:link rel="copyright"
Do we need individual copyright and license links, rather than a wpt-wide license and copyright?

2018-05-19 21:05 UTC, svgeesus commented on svg/pservers/reftests/solidcolor-basic-001-ref.svg
> +    <html:link rel="help"
remove rel=help links from reference files. These should only be in the actual tests.

2018-05-19 21:06 UTC, svgeesus commented on svg/pservers/reftests/solidcolor-basic-001.svg
> +    <title>Hatch: Basic hatch.</title>
Update title to what is actually being tested 9this is not a hatch test)

2018-05-19 21:08 UTC, svgeesus requested changes
The actual tested functionality is good, once the comments on test structure are addressed.

2018-05-28 09:43 UTC, Tavmjong commented
Solid color removed from SVG 2.0 and 2.1.

2018-05-28 09:43 UTC, closed without merging