[presentation-api] Modify the test to check NotFoundError on reconnecting
web-platform-tests/wpt pull request #11371
Opened 2018-06-06 05:52 UTC by tomoyukilabs

This PR modifies controlling-ua/reconnectToPresentation_notfound_error.https.html by:

- Adding a step to reconnect with a presentation ID on a presentation request with a different URL
- Changing the test to a manual test, because starting a presentation is needed to generate an actual presentation ID

2018-09-12 01:58 UTC, tomoyukilabs commented
ping @tidoust @louaybassbouss

2018-09-12 14:53 UTC, tidoust approved these changes
Thanks, that looks good.

One minor suggestion which you may ignore: I would rename `connection` into `connection1` to make the link with `request1` more explicit. In particular, this would make it more obvious why the first line below is meant to fail and why the second is meant to succeed:

```js
await promise_rejects(t, 'NotFoundError', request2.reconnect(connection1.id), '...');
await request1.reconnect(connection1.id);
```

2018-09-13 04:26 UTC, tomoyukilabs commented
@tidoust Okay, I've committed the change for renaming.

2018-09-13 07:43 UTC, tidoust requested changes
See inline

2018-09-13 07:43 UTC, tidoust commented on presentation-api/controlling-ua/reconnectToPresentation_notfound_error-manual.https.html
>          if (connection.state === 'closed')
s/connection/connection1

2018-09-13 07:43 UTC, tidoust commented on presentation-api/controlling-ua/reconnectToPresentation_notfound_error-manual.https.html
>            connection.terminate();
s/connection/connection1

2018-09-13 09:00 UTC, tomoyukilabs commented
Sorry. I've fixed them.

2018-09-13 09:49 UTC, tidoust approved these changes

2018-09-13 09:49 UTC, merged