Ported the wptserve tests over to pytest
web-platform-tests/wpt pull request #11429
Opened 2018-06-08 12:12 UTC by dhdavvie

2018-06-08 13:11 UTC, jgraham requested changes

2018-06-08 13:11 UTC, jgraham commented on tools/wptserve/tests/functional/base.py
> +class TestUsingServer:
Let's create a `conftest.py` file and use pytest fixtures rather than this kind of class-based setup.

2018-06-08 13:11 UTC, jgraham commented on tools/wptserve/tests/functional/test_cookies.py
>  class TestResponseSetCookie(TestUsingServer):
If we move to pytest fixtures, I think we can also remove the class wrappers here and just use normal functions.

2020-10-20 13:19 UTC, stephenmcgruer commented
The wptserve tests have changed significantly (50+ changes) since June 2018, so I don't think its worth trying to keep this PR alive. If we want to make this change, I think we'd have to start over.

2020-10-20 13:19 UTC, closed without merging