SVG ellipse supports rx/ry properties
web-platform-tests/wpt pull request #11844
Opened 2018-07-07 21:49 UTC by ewilligers

Spec: https://svgwg.org/svg2-draft/shapes.html#EllipseElement

When only rx is not auto, rx is used for both dimensions.
When only ry is not auto, ry is used for both dimensions.

2018-07-07 22:11 UTC, fsoder requested changes

2018-07-07 22:11 UTC, fsoder commented on svg/shapes/ellipse-02-ref.svg
> +  <ellipse cx="50" cy="50" rx="40" ry="40" fill="none" stroke="red" stroke-width="5"/>
stroke=orange

2018-07-07 22:11 UTC, fsoder commented on svg/shapes/ellipse-02.svg
> +    <link xmlns="http://www.w3.org/1999/xhtml" rel="help" href="http://www.w3.org/TR/SVG2/shapes.html#RectElement"/>
Same comment as in -01.

2018-07-07 22:11 UTC, fsoder commented on svg/shapes/ellipse-03-ref.svg
> +  <ellipse cx="50" cy="50" rx="30" ry="30" fill="none" stroke="red" stroke-width="5"/>
stroke=orange

2018-07-07 22:11 UTC, fsoder commented on svg/shapes/ellipse-03.svg
> +    <link xmlns="http://www.w3.org/1999/xhtml" rel="help" href="http://www.w3.org/TR/SVG2/shapes.html#RectElement"/>
URL

2018-07-07 22:11 UTC, fsoder commented on svg/shapes/ellipse-04.svg
> +    <link xmlns="http://www.w3.org/1999/xhtml" rel="help" href="http://www.w3.org/TR/SVG2/shapes.html#RectElement"/>
URL

2018-07-07 22:11 UTC, fsoder commented on svg/shapes/ellipse-04.svg
> +  <ellipse cx="50" cy="50" fill="none" stroke="orange" stroke-width="5"/>
Maybe here it'd make sense to actually use 'red' as the stroke color (to clearly show if there's an error.)

2018-07-07 22:11 UTC, fsoder commented on svg/shapes/ellipse-04-ref.svg
> +  <ellipse cx="50" cy="50" rx="0" ry="0" fill="none" stroke="red" stroke-width="5"/>
Seem like this ref could trivially be an "empty" SVG - otherwise there's a risk that '0' & 'auto' is mishandled, but the test still passes.

2018-07-07 23:43 UTC, AmeliaBR commented
These look good, thanks Eric.

Other things to test:

- for `auto` in one direction and percentage value in the other, the computed value of the percentage is used for the dimension in which it was specified (you'll need a non-square SVG to test this).

- check that an `auto` value is used as the default for a missing attribute/unspecified property (not defaulting to 0).

2018-07-08 05:31 UTC, ewilligers commented
Tests added.

2018-07-08 08:45 UTC, fsoder approved these changes

2018-07-08 10:09 UTC, merged