Fetch/XHR/Beacon: test locked/disturbed ReadableStream
web-platform-tests/wpt pull request #12639
Opened 2018-08-23 09:58 UTC by annevk

See https://github.com/whatwg/fetch/pull/801 for context.

2018-08-23 15:02 UTC, igrigorik reviewed
LGTM from this end for the sendBeacon portion. Although, I'd love to get @yutakahirano sanity check too.

2018-08-24 01:28 UTC, yutakahirano requested changes

2018-08-24 01:28 UTC, yutakahirano commented on beacon/beacon-readablestream.window.js
> +function assert_beacon(stream) {
Beacon with streams is never going to work because it's keepalive + ReadableStream which is rejected by another reason.

2018-08-24 04:44 UTC, annevk commented
@yutakahirano good point, fixed.

2018-08-24 06:17 UTC, yutakahirano commented on fetch/api/request/request-init-stream.any.js
> +  assert_throws(new TypeError(), () => fetch(input, init), "fetch()");
await missing?

2018-08-24 06:42 UTC, annevk commented on fetch/api/request/request-init-stream.any.js
> +  assert_throws(new TypeError(), () => fetch(input, init), "fetch()");
Oh my, thanks for spotting that.

2018-08-24 07:00 UTC, annevk commented
I think I fixed that too.

2018-08-24 07:20 UTC, yutakahirano approved these changes

2018-08-24 07:34 UTC, merged