Don't try to normalise the channel if we don't have data for a product.
web-platform-tests/wpt pull request #12877
Opened 2018-09-06 18:07 UTC by jgraham

2018-09-06 18:23 UTC, gsnedders requested changes
Please add tests so we don't regress `wpt run`. We should make sure `setup_wptrunner` can work with all known products.

2018-09-10 14:18 UTC, gsnedders commented
@jgraham any idea what caused this to fail CI? the tests that fail are all from @jugglinmike's #10998.

2018-09-10 15:58 UTC, gsnedders requested changes

2018-09-10 15:58 UTC, gsnedders commented on tools/wpt/tests/test_run.py
> +def test_setup_wptrunner(product):
This test seems to change some global state, making later tests fail.

`tox -e py27 -- --no-cov -k 'test_run_firefox or test_setup_wptrunner'` is sufficient to observe a failure; Travis has many more.

2018-10-15 16:43 UTC, jgraham commented
I made the requested changes some time ago. @gsnedders please re-review.

2018-10-15 20:14 UTC, gsnedders approved these changes

2018-10-15 20:14 UTC, merged

2018-10-17 13:24 UTC, Hexcles reviewed
Found two bugs caused by this PR.

2018-10-17 13:36 UTC, foolip commented
Given the regression in https://github.com/web-platform-tests/wpt/pull/13567, what sort of test coverage are we missing here?