[docs] Deprecate `async_test`
web-platform-tests/wpt pull request #13530
Opened 2018-10-15 19:32 UTC by jugglinmike

This may be a little too aggressive. [We know that test contributors dislike the `step`-based API of `async_test`](http://lists.w3.org/Archives/Public/public-test-infra/2018JulSep/0011.html), but [using `promise_test` for a callback-driven API carries it's own overhead](http://lists.w3.org/Archives/Public/public-test-infra/2018OctDec/0000.html). The web platform may not be sufficiently Promise-based to make `promise_test` an ergonomic default. There may also be other reasons to keep `async_test` around (e.g. cases where parallel testing is a hard requirement). A pull request seemed like the best way to prompt the discussion.

2018-10-15 21:27 UTC, jgraham requested changes
I am strongly opposed to this change for the reasons set out in my comment.

2018-10-15 22:39 UTC, foolip commented
This is ambitious, well worth considering I think.

This is a bit of a detour, but bear with me. We now have `promise_test` which you can use as `promise_test(async t => { ... })`, an `async_test` that *can't* be used with "async functions", and a `test` which also doesn't allow any value to be returned from the callback.

This makes it not too obvious how to write async tests I think.

2018-10-15 22:46 UTC, youennf commented
FWIW, in WebKit, I am pushing people to use one async_test in a file, otherwise use promise_test.
We have some issues with unreliable ordering of console logging with several async_test in a given file.

2018-10-15 22:49 UTC, youennf commented
To be clear, I am not pushing for async_test, I am pushing against more than one async_test in a file...

2018-10-15 22:55 UTC, foolip commented
Oops, posted too early.

It would be quite nice if we had `test` and a new `parallel_test` both able to accept thenable-vending callbacks. Details to be worked out, but basically the current flavor of `async_test` would be one of the modes of `parallel_test`, the other being parallel promise tests which currently cannot be done.

I think we shouldn't really be deprecating things but instead doing the work to change all the call sites if we think it's important enough. The name `async_test` is very entrenched, but it's also very unfortunate how it collides with modern JS nomenclature, and that might be fixable with some effort.

2018-10-15 22:56 UTC, foolip commented
> We have some issues with unreliable ordering of console logging with several async_test in a given file.

We have this in Blink too. We didn't really solve it I'm afraid, just marked those few tests as flaky. There weren't enough in the end to justify doing more we thought. @Hexcles.

2018-10-15 23:08 UTC, jugglinmike commented
@youennf For [single page tests](https://github.com/web-platform-tests/wpt/blob/4ba3cd24c69a859d8c7864d15958d2656ef16173/docs/_writing-tests/testharness-api.md), there's no need to use `t.step`, `t.step_func`, etc.  because uncaught exceptions are interpreted as errors. Given that you have other reasons to encourage a 1-to-1 test-to-file ratio, advocating for single page tests instead would reduce the overhead for test authors. That might make it a convenient benefit.

Pardon me if you're aware of this; Simon and Jory's survey found that not everyone knows about the feature.

2018-10-15 23:19 UTC, youennf commented
Right!
I heard about single page tests recently by Simon and agrees this looks nicer.
I actually started advertising it and will continue doing so.

2018-10-16 16:49 UTC, foolip commented
I realize I've confused two different issues: subtest ordering and console output. For console output I think we ended up redirecting it to stderr so that it's not part of the baseline, and for subtest order we considered fixing it, but it just doesn't affect very many tests so we left it be. I don't think either of these concerns are reasons to change/replace `async_test`, especially log output which affects all test types.

2020-10-21 12:32 UTC, stephenmcgruer commented
This never got much traction, so closing. If anyone was interested in pushing for this, nowadays [an RFC](https://github.com/web-platform-tests/rfcs) would be required.

2020-10-21 12:32 UTC, closed without merging