[testdriver.js] Relax test for Actions
web-platform-tests/wpt pull request #13741
Opened 2018-10-26 17:44 UTC by jugglinmike

The sequence of actions scheduled within the same tick is undefined.
Relax the test concerning this behavior to reflect the non-determinism.

2018-10-26 17:56 UTC, jugglinmike commented
testdriver.js's "actions" feature is intended to match [the corresponding behavior in the W3C WebDriver
specification](https://w3c.github.io/webdriver/#actions). Today, that text is slightly incorrect. I've proposed a fix via https://github.com/w3c/webdriver/pull/1323, and this patch aligns with the new text. We may want to wait to merge this until that pull request is accepted.

2018-10-29 11:01 UTC, jgraham commented
Eh, I'm concerned by this. Inside an event loop everything has defined ordering and it is fully intended that the actions are scheduled in the order resulting from a transpose of the input array i.e. so that the actions from the first defined device are placed on the event loop first).

2018-10-29 16:42 UTC, jgraham requested changes
The ordering of actions within a tick is intended to be well-defined and should remain so. The one consession that the webdriver spec makes is that `pointerMove` of non-zero duration may wait before starting to move, and after the move starts the generated events need not be deterministically ordered, but there's no defined duration in this case, so the order is again well-defined.

2018-10-30 17:49 UTC, jugglinmike commented
We addressed this via a change to the spec: https://github.com/w3c/webdriver/pull/1323

2018-10-30 17:49 UTC, closed without merging