[testharness.js] Disallow use of null byte in name
web-platform-tests/wpt pull request #14245
Opened 2018-11-27 00:01 UTC by jugglinmike

Because the null byte is a non-printable character, its use in test
names can be difficult for humans to interpret. Further, the Edge
browser is currently incapable of reporting data that includes the null
byte.

Rename all tests which previously included the null byte to instead
reference it via its JavaScript escape sequence. Update testharness.js
to disallow the character in test names.

---

Although this change is motivated by [a deficiency in Edge](https://github.com/web-platform-tests/wpt/issues/14003), I think there's good reason to enforce it as a constraint on test authors. Test names are intended for human use, so non-printable characters are generally inappropriate.

This could be addressed completely within testharness.js by silently sanitizing the test titles prior to reporting results. In some ways, that would be preferable because we could translate *all* non-printable characters (not just the problematic null byte) without modifying a single test. I'm suggesting that we implement this as a constraint instead because it seems important to avoid any changes between what test authors write and what they see reported.

To validate this patch, I [inserted a null byte in an existing test name and logged all infractions to disk (`suspicious.txt`)](https://github.com/bocoup/wpt/commit/35c7ac8f2719f298b513fce3ea6642a8de7af8bd). I added that commit to [a new branch on Bocoup's fork of WPT](https://github.com/bocoup/wpt/commits/testharness-disallow-null-byte-verify), triggering [a complete trial in Chrome and Firefox](https://tools.taskcluster.net/groups/P0PCeY7MRcywRe4dT-Dx6g). When it was through, I collected the contents of the log files and verified that only the "control" null byte was reported:

    $ ./wpt tc-download --ref testharness-disallow-null-byte-verify --artifact-name suspicious.txt --repo-name bocoup/wpt --out-dir edge-2        
    INFO:tc-download:edge-2/wpt-chrome-dev-testharness-4-ANkbKtjhRXCDecRxGAUIFQ-suspicious.txt
    INFO:tc-download:edge-2/wpt-firefox-nightly-testharness-4-GAj8QqurSLeHO_bBa8Y9JQ-suspicious.txt
    $ cat edge-2/*
    http://web-platform.test:8000/dom/events/CustomEvent.html - "CustomEvent [\u0000] dispatching."
    http://web-platform.test:8000/dom/events/CustomEvent.html - "CustomEvent [\u0000] dispatching."

2018-11-27 08:44 UTC, annevk reviewed
I don't like this approach. If we really need to do this, why not adjust the title in the harness? (I'm also not a fan of not addressing the root issue, Edge, and instead letting everyone bear the cost.)

2018-11-27 10:30 UTC, annevk requested changes
Explicitly marking as requesting changes as I'm not comfortable with the changes to tests I help maintain.

2018-11-27 14:19 UTC, domenic commented
I agree that having testharness make these changes would be ideal. Perhaps by replacing the bytes with their corresponding [control character pictures](https://en.wikipedia.org/wiki/Unicode_control_characters#Control_pictures)

2018-11-27 14:30 UTC, jgraham commented
Yeah, I think having testharness deal with null and lone surrogates would be good (I already had to change wptreport to replace lone surrogates with U+XXXX escapes since they are not trivially supported in languages with UTF-enforcing String types, and treating all the names as bytes is surprisingly difficult).

2018-11-27 14:44 UTC, foolip commented
Where does that replacing happen? I guess strings get converted to UTF-8 first when they go in WebDriver response, so in testharness.js itself? More escaping there seems reasonable.

2018-11-27 14:56 UTC, jgraham commented
Heh, such optimisim.

The WebDriver response of course has to be UTF-8. But JSON escapes are based on UCS2 for (reasons not known to me) and so you can smuggle surrogate pairs pairs through as `\ud801` or whatever. The Python JSON library is happy with this because Python 2 strings are UCS2/4 internally. On the other hand in e.g. Rust where the strings are UTF-8 you can't get away with that (even if you choose some bytes type for the name field; the library point blank refuses to deserialise escaped unpaird surrogates). So since wptreport.json is the main interchange format we started stripping out the escapes there.

Doing it all in testharness seems sensible, but you could still have a case where someone put something bad into the title or message of another test type e.g. wdspec tests (reftests are a little harder because filesystems, but certainly not impossible).

2018-11-27 15:34 UTC, lukebjerring commented
@foolip re: wpt.fyi: having the UI reflect non-printed chars seems reasonable. File and issue, with a specific example attached, and I'll have someone (probably me) take a look.

2018-11-27 17:52 UTC, jugglinmike commented
> If we really need to do this, why not adjust the title in the harness?

It seems important to avoid any changes between what test authors write and what they see reported. Do you think there's value in that?

> I'm also not a fan of not addressing the root issue, Edge, and instead > letting everyone bear the cost.

I agree that the bug should be fixed in Edge. That's why [I also submitted WebDriver tests for the expected behavior](https://github.com/web-platform-tests/wpt/pull/13880#issuecomment-441341286).  We can't know when/if the bug will be fixed, but in the mean time, many other people are already bearing the cost. The visitors to wpt.fyi see confusing results for tests which have nothing to do with WebDriver (see, e.g. gh-14003).  Even if it was reasonable to expect them to understand what was going wrong, they have no agency over the issue. This patch alerts folks who *can* understand and avoid the problem.

> What is the point where Edge truncates strings at U+0000? I tried > `JSON.stringify"A\u0000B")` and that was fine. Is it with `postMessage`?

It's in WebDriver--see gh-13880 for a description of the issue.

2018-11-27 18:19 UTC, jgraham commented
> > If we really need to do this, why not adjust the title in the harness?
> 
> It seems important to avoid any changes between what test authors write and what they see reported. Do you think there's value in that?

I think "is there any value in that" is the wrong framing. Clearly it's possible to imagine cases where there is value in the title being byte-for-byte identical to what the author put in the js file. But on the other hand
* I suspect a lot of cases where there are unusual codepoints, the origin is a list rather than something else
* The title shouldn't be affecting the test result, so changing test titles theoretically doesn't matter much, as long as you don't end up causing clashes between tests.

2018-11-28 16:13 UTC, jugglinmike commented
> I think "is there any value in that" is the wrong framing.

The addition of the word "any" makes my comment seem more like a straw man, but it was an honest question. There's a subjective component to the decision, and I'm open to alternatives. I'd like to understand the trade offs and have them documented here.

> The title shouldn't be affecting the test result

Could you expand on why that's important?

2018-11-30 12:13 UTC, annevk commented
The title doesn't really matter, so putting constraints on test authors (who often generate titles and would have to write more complicated code to do so) is worse than doing some general escaping in the library.

2019-11-15 23:39 UTC, foolip commented
I've closed https://github.com/web-platform-tests/wpt/issues/14003 which this is a fix for, and would recommend closing this as well, since the issue no longer affects any configuration we're still running regularly.

2019-11-16 01:00 UTC, jugglinmike commented
Yeah, I think there was a more fundamental disagreement about the purpose of test titles.

2019-11-16 01:00 UTC, closed without merging