Add CEReactions tests
web-platform-tests/wpt pull request #14711
Opened 2019-01-04 06:02 UTC by kaixinjxq

part of issue #5727
- HTMLMapElement
- HTMLCanvasElement
- HTMLDataElement
- HTMLDetailsElement
- HTMLModElement
- HTMLOListElement
- HTMLQuoteElement
- HTMLSlotElement
- HTMLTimeElement

2019-01-24 21:33 UTC, domenic commented
w3c-test:mirror

2019-01-24 22:14 UTC, domenic requested changes
Tests are wrong with boolean attributes; unclear what's going on with

2019-01-24 22:14 UTC, domenic commented on custom-elements/reactions/HTMLDetailsElement.html
> +testReflectAttribute('open', 'open', 'true', 'false', 'open on HTMLDetailsElement', 'details', HTMLDetailsElement);
Boolean attributes don't get reflected by the strings "true" and "false". They get reflected by the removal or addition of the attribute.

2019-01-24 22:14 UTC, domenic commented on custom-elements/reactions/HTMLModElement.html
> +testReflectAttribute('cite', 'cite', '../resources/custom-elements-helpers.js', './resources/reactions.js', 'cite on ins use HTMLModElement', 'ins', HTMLModElement);
This test fails on Chrome. I believe it is because the attribute name is `datetime`, not `dateTime`.

2019-01-24 22:14 UTC, domenic commented on custom-elements/reactions/HTMLOListElement.html
> +testReflectAttribute('reversed', 'reversed', 'true', 'false', 'reversed on HTMLOListElement', 'ol', HTMLOListElement);
Boolean attributes problem again

2019-01-24 22:14 UTC, domenic commented on custom-elements/reactions/HTMLTimeElement.html
> +testReflectAttribute('dateTime', 'dateTime', '2018-12-10', '2018-12-12', 'dateTime on HTMLTimeElement', 'time', HTMLTimeElement);
Also fails on Chrome, also I guess for the same reason.

2019-01-25 05:32 UTC, kaixinjxq commented
@domenic, many thanks for your review! I just submit a new commit to address your comments, PTAL.

2019-01-25 18:04 UTC, domenic commented
w3c-test:mirror

2019-01-30 20:52 UTC, domenic approved these changes

2019-01-30 20:52 UTC, merged