Values3 gt pr14
web-platform-tests/wpt pull request #15192
Opened 2019-01-31 18:09 UTC by TalbotG

Trying again to submit 
calc-numbers.html 
calc-percent-number-line-height-crash.html 
reference/calc-percent-number-line-height-crash-ref.html

2019-01-31 18:11 UTC, TalbotG commented
If pull request 15192 succeeds, then I will close pull request 15103 immediately.

2019-02-01 02:56 UTC, frivoal requested changes
One change requested.

As for the crash test, it's not wrong, but I am not sure it is useful.

2019-02-01 02:56 UTC, frivoal commented on css/css-values/calc-numbers.html
> +    verifyComputedStyle("tab-size", "12345", "calc(2 / 4)", "12345", "testing tab-size: calc(2 / 4)");
tab-size accepts numbers, not integers.
```suggestion
    verifyComputedStyle("tab-size", "12345", "calc(2 / 4)", "0.5", "testing tab-size: calc(2 / 4)");
```

2019-02-01 03:06 UTC, frivoal approved these changes
LGTM

2019-02-01 03:20 UTC, merged

2019-02-04 01:20 UTC, TalbotG commented
See Pull Request 15226 for such correction

Credit should go to Emilio Cobos Álvarez ( @emilio ) for his feedback on this