[css-scroll-snap] scroll-snap-type computed value
web-platform-tests/wpt pull request #15311
Opened 2019-02-10 05:12 UTC by ewilligers

Spec: https://drafts.csswg.org/css-scroll-snap-1/

Blink/Safari fail by reporting the scroll-snap-type computed value
as "x proximity" instead of "x".

2019-02-10 06:46 UTC, ewilligers commented
Note the following two principles in [CSSOM](https://drafts.csswg.org/cssom/#serializing-css-values):

> If component values can be omitted or replaced with a shorter representation without changing the meaning of the value, omit/replace them.

> If either of the above syntactic translations would be less backwards-compatible, do not perform them.
 
Blink and Safari are the only browsers that support scroll-snap-type values like "x" and "x proximity", and they give "x proximity" as the computed value, so expecting "x proximity" would be more backwards-compatible.

2019-02-25 11:43 UTC, ewilligers commented
@tabatkins please review

2019-03-14 22:40 UTC, tabatkins requested changes

2019-03-14 22:40 UTC, tabatkins commented on css/css-scroll-snap/parsing/scroll-snap-align-computed.html
> +test_computed_value("scroll-snap-align", "center end");
```suggestion
test_computed_value("scroll-snap-align", "center end");
test_computed_value("scroll-snap-align", "start start", "start");
```

2019-03-14 22:42 UTC, tabatkins commented
> Blink and Safari are the only browsers that support scroll-snap-type values like "x" and "x proximity", and they give "x proximity" as the computed value, so expecting "x proximity" would be more backwards-compatible.

Back-compat is about pages depending on the behavior, not browsers happening to have done it a particular way in the past. (That's colloquially called "bugwards compat". ^_^) This is new enough that I doubt anyone's depending on our too-long serializations, so we should continue to follow shortest-serialization principle until shown evidence otherwise.

2019-05-07 21:17 UTC, tabatkins approved these changes

2019-05-07 21:18 UTC, merged