Update web-nfc nfc_watch.https.html
web-platform-tests/wpt pull request #15666
Opened 2019-03-05 07:04 UTC by kaixinjxq

part of #14389

@Honry, PTAL.

2019-03-06 07:46 UTC, Honry requested changes
You probably need to split this file into two, as triggering "reading" event requires user interaction with an NFC tag.

2019-03-06 08:31 UTC, kaixinjxq commented
@Honry, many thanks for you review! I just submit a new commit to address your comments, PTAL.

2019-03-07 05:44 UTC, Honry commented on web-nfc/NFCReader-manual.https.html
> +<script src="resources/nfc_help.js"></script>
Looks like `nfc_help.js` is never used here. Right? Same as following file.

2019-03-07 05:44 UTC, Honry commented on web-nfc/NFCReader-manual.https.html
> +}, 'Test that nfc watch success if NFC HW is enable.');
Nit: s/enable/enabled

2019-03-07 07:03 UTC, Honry approved these changes
Thanks, LGTM

2019-03-07 07:03 UTC, merged