[css-text-decor] Add text-decoration-line tests
web-platform-tests/wpt pull request #16211
Opened 2019-04-02 09:20 UTC by xfq

This PR ports https://w3c.github.io/i18n-tests/results/line-decoration#text_dec_line to WPT. Currently, the tests are manual tests, since we're unable to come up with a way to automate them.

Similar to #16130, the `-00X.html` tests are in horizontal writing mode, the `-04X.html` tests are in `vertical-rl`, the `-08X.html` tests are in `vertical-lr`, and the `-09X.html` tests are in `sideways-{rl,lr}`. (Currently, only Firefox supports `sideways-{rl,lr}`.)

I didn't include the exploratory tests.

/cc @r12a

2019-04-02 11:04 UTC, sideshowbarker requested changes
> Currently, the tests are manual tests, since we're unable to come up with a way to automate them.

Given that, all the filenames for these tests should be renamed to their `-manual.html` equivalents.

For example, `css/css-text-decor/text-decoration-line-001.html` should be renamed to `css/css-text-decor/text-decoration-line-001-manual.html`

2019-04-03 04:05 UTC, kojiishi commented
Oh? I've never heard of such convention. Can you point to the doc?

IIUC files under `css` requires "-001" suffix, which should come first?

2019-04-03 05:05 UTC, sideshowbarker commented
> Oh? I've never heard of such convention. Can you point to the doc?

https://github.com/web-platform-tests/wpt/blob/master/docs/_writing-tests/file-names.md#test-type
> `-manual` : Indicates that a test is a non-automated test.

(Sorry, I had meant to cite that part of the docs in my previous comment, but forgot…)

> IIUC files under `css` requires "-001" suffix, which should come first?

Per the WPT docs, the `-manual` must come last:

> These flags must be the last element in the filename before the extension e.g. `foo-manual.html` will indicate a manual test, but `foo-manual-other.html` will not.

2019-04-03 09:04 UTC, kojiishi commented
@plinss is that ok for not to have "000" suffix for css tests? IIRC it was required for your build script, but it looks like it now conflicts with another suffix.

2019-04-03 17:10 UTC, plinss commented
Using the -manual suffix after the numbers is fine. The numbers are a convention, the only thing the build scripts really care about is that the test names are unique.

2019-04-04 06:51 UTC, xfq commented
OK. I just pushed a new commit to rename the files.

(I'll also submit a separate PR for the files in #16130.)

2019-04-04 06:59 UTC, r12a commented
I was also unaware of this new test-naming convention to put metadata in the file name. What's the procedure if tests are converted from manual to script-/ref-based? Do we add the new files and leave the old versions in the WPT repo, or delete the old files when adding the new versions? @sideshowbarker @gsnedders

2019-04-04 17:07 UTC, kojiishi approved these changes
lgtm

2019-04-05 05:10 UTC, sideshowbarker commented
> I was also unaware of this new test-naming convention to put metadata in the file name.

For the record, it’s not a new convention. It’s been a documented requirement in the WPT docs for literally years now. It’s required in order to make the harness recognize a manual test as a manual test.

I understand that many (most?) of the CSS tests are manual tests and the many (most?) of the existing CSS manual tests aren’t following that long-documented requirement. I guess the only reason that’s not so far caused problems with the harness is that we added some kind of whitelisting to tell the harness to ignore all the CSS tests. Or something.

Regardless, any newly-added tests should be following the WPT requirements.

> What's the procedure if tests are converted from manual to script-/ref-based? Do we add the new files and leave the old versions in the WPT repo, or delete the old files when adding the new versions? @sideshowbarker @gsnedders

I think the right procedure in that case would be to git-mv (rename) the `-manual.html` files to remove the `-manual` parts. That preserves the change history. And that seems appropriate if the substance of the what’s being tested hasn’t changed — if the test continues to be testing the same spec requirement — and basically all that had changed were just that the test had become automated.

But regardless of the git particulars, if/when newer script-/ref-based replacements are added, there would be no value in keeping the old manual test files around in version control.

2019-04-05 05:12 UTC, sideshowbarker approved these changes

2019-04-05 05:15 UTC, sideshowbarker approved these changes

2019-04-05 05:33 UTC, merged