Fix race condition in servodriver
web-platform-tests/wpt pull request #16819
Opened 2019-05-14 15:58 UTC by georgeroman

Fixes #16754

2019-05-14 16:21 UTC, jdm requested changes

2019-05-14 16:21 UTC, jdm commented on tools/wptrunner/wptrunner/browsers/servodriver.py
> +            ServoWebDriverBrowser.used_ports_lock.release()
Let's do this instead:
```python
with ServoWebDriverBrowser.used_ports_lock:
    self.webdriver_port = get_free_port(4444, exclude=self.used_ports)
    self.used_ports.add(self.webdriver_port)
```

2019-05-14 16:23 UTC, jugglinmike commented on tools/wptrunner/wptrunner/browsers/servodriver.py
> +            ServoWebDriverBrowser.used_ports_lock.release()
You beat me to it!

2019-05-14 16:28 UTC, jdm approved these changes

2019-05-14 18:51 UTC, gsnedders commented
I wonder if every usage of `get_free_port` is racy in the face of parallel test execution?

2019-05-15 13:49 UTC, georgeroman commented
I think it is since every usage of the function follows the same pattern of getting the first available port followed by saving the chosen port in `excluded_ports`.

2019-05-15 13:59 UTC, merged

2019-05-16 17:07 UTC, SimonSapin commented
Binding to port 0 lets the OS pick an available port at semi-random, without the race. `getsockname` can then be used to find out which port was used.

2019-05-16 17:33 UTC, jgraham commented
I seem to recall that there's a problem doing that, at least with the way that marionette works, because we need to pass the port number in to the command line argument rather than bind it ourselves. So we *could* get a socket with a random/unused port then read it's port number and then pass that down after closing it but we can't get a socket on a random port and then use that socket directly.