[docs] Integrate wptserve documentation
web-platform-tests/wpt pull request #17039
Opened 2019-05-27 23:05 UTC by jugglinmike

Relocate instructions that are specifically geared towards test authors
to the "docs" directory. Persist API documentation in its current
location and configure Sphinx to include relevant aspects in the
generated website.

---

The organization of content about "pipes" is a little too focused on implementation details. [Since some of the other documentation also exhibits this problem](https://github.com/bocoup/wpt-docs/issues/3), I suggest we address that issue with more fine-grained restructuring in a follow-up patch.

2019-05-28 16:27 UTC, gsnedders requested changes
This seems wholly like a good move to me.

2019-05-28 16:27 UTC, gsnedders commented on docs/writing-tests/python-handlers/index.md
> +Python file handlers are designed to provide a vaguely PHP-like interface
I strongly dislike calling this "vaguely PHP-like".

2019-05-28 16:27 UTC, gsnedders commented on docs/writing-tests/python-handlers/index.md
> +where each resource corresponds to a particular python file on the
```suggestion
where each resource corresponds to a particular Python file on the
```

2019-05-28 16:27 UTC, gsnedders commented on docs/writing-tests/python-handlers/index.md
> +filesystem. Typically this is hooked up to a route like ``("*",
Let's not say that's "typically"; for WPT it *is*.

2019-05-28 16:27 UTC, gsnedders commented on docs/writing-tests/python-handlers/index.md
> +treated as a handler file (note that this makes python files unsafe in
```suggestion
treated as a handler file (note that this makes Python files unsafe in
```

2019-05-28 16:27 UTC, gsnedders commented on docs/writing-tests/python-handlers/index.md
> +Unlike PHP, the python files don't work by outputting text to stdout
Let's not quite so directly reference PHP (which isn't so useful if you don't know what PHP does!), but instead say something more like, "These Python files are assumed to define a single function `main(request, response)`. Note therefore anything written to stdout is not returned as part of the response, as is the case in PHP.

2019-05-28 17:23 UTC, jugglinmike commented
> This seems wholly like a good move to me.

:)

The content of `docs/writing-tests/python-handlers/index.md` was all cribbed from `tools/wptserve/docs/handlers.rst`. That doesn't make your feedback any less beneficial, but it does inform how I'd like to format the patch.

I started fresh with a commit to improve the existing documentation as per your recommendation. Then, I rebased my original patch over the new commit. This separates the content change from the refactoring, limiting the subjective aspects of the latter and improving the discoverability of the former.

[The previous version of this branch is available here.](https://github.com/web-platform-tests/wpt/compare/master...bocoup:docs-sphinx-3-wptserve-orig)

2019-05-29 12:04 UTC, gsnedders approved these changes
Apart from this one typo, LGTM; sorry for making you fix something I didn't realise was existing content!

2019-05-29 12:04 UTC, gsnedders commented on docs/writing-tests/python-handlers/index.md
> +The Pyton filess must define a single function `main` with the signature::
```suggestion
The Python files must define a single function `main` with the signature::
```

2019-05-29 15:44 UTC, jugglinmike commented
No worries. They were good suggestions, and this was a good time to implement them.

Happy to squash when you think this is ready.

2019-05-29 16:17 UTC, gsnedders commented
@jugglinmike 
> Happy to squash when you think this is ready.

now

2019-05-29 17:10 UTC, jugglinmike commented
Good to go, @gsnedders

2019-05-29 17:47 UTC, merged