[cssom] Add test disallowing non-standard feature
web-platform-tests/wpt pull request #17218
Opened 2019-06-06 20:29 UTC by jugglinmike

Safari 12 on macOS Mojave currently fails all but the `radio` and `checkbox` sub-tests. As noted in the referenced bug, the WebKit maintainers intend to release a fix by September of this year.

2019-06-06 21:37 UTC, zcorpan requested changes

2019-06-06 21:37 UTC, zcorpan commented on css/cssom/cssstyledeclaration-setter-form-controls.html
> +  var element = document.createElement('input');
The tests are very similar, only varying on the element and attribute. Can you make it more DRY?

For example,
```
const tests = [['input', 'text'], ..., ['button']];
for (const t of tests) {
  var [tagName, type] = t;
  test(...);
}
```

2019-06-07 16:54 UTC, jugglinmike commented
I'd rather not use control flow structures to define or execute tests. They can hide test bugs and make it harder for others to understand what's going on. But that doesn't mean we can't reduce repetition! I've refactored to use a few helper functions while keeping the tests declarative.

2019-06-08 16:48 UTC, zcorpan approved these changes

2019-06-17 17:43 UTC, jugglinmike commented
@zcorpan would you like me to receive review from any other maintainers before merging this?

2019-06-17 18:14 UTC, zcorpan commented
Nope, I can merge.

2019-06-17 18:14 UTC, merged