Allow trailing slash in test_get_current_url_file_protocol
web-platform-tests/wpt pull request #17679
Opened 2019-07-08 20:37 UTC by julianrkung

Chrome automatically adds a trailing slash if the suffix of the file protocol is a directory. Chromedriver currently fails this test due to this trailing slash (the rest of the URL is identical). This changelist considers  urls with and without a trailing slash correct.

2019-07-09 13:59 UTC, andreastt commented
But Firefox doesn’t do this? Smells like a web compat issue that should be fixed in Firefox/Chrome.

2019-07-09 14:00 UTC, andreastt requested changes
Deferring this review until we’ve confirmed where this problem lies.

2019-07-09 14:05 UTC, andreastt commented
@denschub pointed me to https://bugs.chromium.org/p/chromium/issues/detail?id=339054.

2019-07-09 23:17 UTC, julianrkung commented
Looks like this particular subject isn't covered by URL standards. If not covered by the standards, shouldn't both (legitimate) implementations be accepted and considered valid? In any case, I believe that since this issue is a Firefox/Chrome standards issue, it is out of the scope of webdrivers (and therefore out of scope for this webdriver test) and shouldn't be considered during this test. If chromedriver adheres to the W3C Get Current URL spec (which it does), it should pass the test.

2019-07-10 12:58 UTC, andreastt commented
My intention wasn’t to block this patch for any of those reasons. I wanted confirmation that we weren’t applying a workaround for what might conceivably be a web compatibility issue.

This is somewhat important to clarify because WebDriver is used extensively to test other web standards.

Anyway, I asked around and found this in the Fetch standard on [scheme fetch](https://fetch.spec.whatwg.org/#scheme-fetch):

> For now, unfortunate as it is, file URLs are left as an exercise for the reader.

That means the behaviour is implementation defined and, as you suggested, that the test should pass regardless what the browser returns.

2019-07-10 12:58 UTC, andreastt approved these changes

2019-07-10 12:59 UTC, merged