html: Update tests for an autofocus algorithm update
web-platform-tests/wpt pull request #17929
Opened 2019-07-19 04:42 UTC by tkent-google

https://github.com/whatwg/html/pull/4763

2019-07-22 20:57 UTC, domenic requested changes
Found a typo bug that needs fixing.

Things I see in the spec but I am not sure if there are tests for:

- Sandboxing should prevent autofocus
- Cross-origin should prevent autofocus
- It should wait for script-blocking style sheets, possibly for a long time. (Best done with a slow server response for a stylesheet.)
- If topDocument's URL fragment is not empty, should not autofocus. (Can test using window.open() to create a new top-level BC)
- Even with no blocking style sheets, if you wait a long time (~100 ms?), and the focus is still on the document itself, inserting an autofocus element will cause that element to be focused after the next frame.

Also worth noting that we should test the exact position in the event loop's "update the rendering" for when autofocusing happens. I'm not sure the best way to do that with the current spec proposal, although I think your use of double-rAF instead of single-rAF is probably because of the fact that it's after rAF. But for example, if we stick with the current spec proposal, we should test that after a single rAF or a single IntersectionObserver callback, there is no autofocus, but before the second resize event, the autofocus does happen.

I don't think it's necessary to land all these tests, but given how historically non-interoperable this attribute is, the more tests we can land, the better.

2019-07-22 20:57 UTC, domenic commented on html/semantics/forms/autofocus/focusable-area-in-top-document.html
> +  input.autocous = true;
```suggestion
  input.autofocus = true;
```

2019-07-22 20:57 UTC, domenic commented on html/semantics/forms/autofocus/skip-document-with-fragment.html
> +}, 'Autofocus element in a document with a URI fragment should be skipped.');
```suggestion
}, 'Autofocus elements in iframed documents with URL fragments should be skipped.');
```

2019-07-26 10:14 UTC, tkent-google commented on html/semantics/forms/autofocus/focusable-area-in-top-document.html
> +  input.autocous = true;
Done.

2019-07-26 10:14 UTC, tkent-google commented on html/semantics/forms/autofocus/skip-document-with-fragment.html
> +}, 'Autofocus element in a document with a URI fragment should be skipped.');
Done.

2019-07-26 10:16 UTC, tkent-google commented
> Sandboxing should prevent autofocus

Added no-sandboxed-automatic-features.html.

> Cross-origin should prevent autofocus

We already have no-cross-origin-autofocus.sub.html.

> It should wait for script-blocking style sheets, possibly for a long time. (Best done with a slow server response for a stylesheet.)

Added spin-by-blocking-style-sheet.html.

> If topDocument's URL fragment is not empty, should not autofocus. (Can test using window.open() to create a new top-level BC)

Added new test case to skip-document-with-fragment.html.

> Even with no blocking style sheets, if you wait a long time (~100 ms?), and the focus is still on the document itself, inserting an autofocus element will cause that element to be focused after the next frame.

Added autofocus-on-stable-document.html.

> Also worth noting that we should test the exact position in the event loop's "update the rendering" for when autofocusing happens. ...

Added update-the-rendering.html.

2019-07-29 08:22 UTC, tkent-google commented
update-the-rendering.html is flaky with Firefox because the order of an animation frame callback and a user interaction task, in which autofocus processing is currently done, is not deterministic.  I have no idea how to fix this issue, and might remove the test.

2019-07-29 17:52 UTC, domenic approved these changes
If Firefox implemented the proposed spec, then the test would not be flaky, right? In that case I think we should keep the test, and ask the admins for an exception to allow merging this.

2019-08-01 09:36 UTC, tkent-google commented
> If Firefox implemented the proposed spec, then the test would not be flaky, right?

That's right.

2019-09-03 11:42 UTC, foolip commented
Should this be merged now? I can admin merge if needed.

2019-09-03 16:08 UTC, domenic commented
@foolip yes, please admin merge!

2019-09-03 22:00 UTC, merged

2019-09-03 22:00 UTC, foolip commented
Done!