Allow to run epiphany browser from inside a flatpak
web-platform-tests/wpt pull request #18603
Opened 2019-08-22 00:15 UTC by clopez

This allows to run epiphany from inside a flatpak like the Epiphany Technology Preview

To run this first install the [Epiphany Technology Preview flatpak](https://webkitgtk.org/epiphany-tech-preview.flatpakref) and then run WPT like follows:
`
./wpt run --flatpak="org.gnome.Epiphany.Devel" epiphany
`

This should work also for running tests with the generic webkit browser (MiniBrowser) inside flatpak, but the Epiphany TP preview flatpak doesn't include the MiniBrowser.

If you need to pass extra arguments to "flatpak run" like `--socket=x11` or `--socket=wayland` then use `--flatpak-args="..."`

The way this works is by starting the WebKitWebDriver inside the flatpak environment, but the test machinery (WPT tools) run outside of flatpak.

2019-09-02 14:41 UTC, jgraham requested changes

2019-09-02 14:41 UTC, jgraham commented on tools/wpt/run.py
> +        if kwargs["flatpak"]:
I don't love putting these things on the class itself. I'd rather have a `browser.set_options(**kwargs)` method that would be called here and pick the browser-specific settings out of the kwargs dict.

2019-09-02 14:41 UTC, jgraham commented on tools/wptrunner/wptrunner/wptcommandline.py
> +    webkit_group = parser.add_argument_group("Epiphany and WebKit-specific")
Do the flatpak things actually apply to anything other than Epiphany? Seems like there could be a seperate group just for these if not.

2019-11-15 10:40 UTC, foolip commented
@clopez this PR can be closed now, right?

2019-11-15 10:43 UTC, clopez commented
I was planning to address the reviewer comments at some point in the future, as time allows, and upload a new patch. I think there is value in being able to test with epiphany tech preview (runs inside a flatpak)

2019-11-15 11:09 UTC, foolip commented
Alright, sounds good!

2020-10-20 15:01 UTC, stephenmcgruer commented
Given no movement in nearly a year, closing. Please re-open if you still intend to work on this.

2020-10-20 15:01 UTC, closed without merging