Improve testharness "function throws" assertions.
web-platform-tests/wpt pull request #19054
Opened 2019-09-13 21:07 UTC by bzbarsky

We add new functions to allow more precise testing of what sorts of
exceptions get thrown.

Fixes https://github.com/web-platform-tests/wpt/issues/11726

2019-09-16 15:13 UTC, Ms2ger requested changes
Please wait for https://github.com/web-platform-tests/rfcs/pull/29

2019-09-16 15:17 UTC, bzbarsky commented on resources/testharness.js
> +            assert(false, "assert_throws_js", description,
Um... I did add those, no?  See `promise_rejects_js` and so forth...

2019-09-16 15:31 UTC, bzbarsky commented on resources/testharness.js
> +            assert(false, "assert_throws_js", description,
Ah, thank you for explaining offline what you meant.  Updated.

2019-09-16 23:32 UTC, jugglinmike commented
Could you also add tests for the new functions? The test suite for testharness.js is in [the `resources/test` directory](https://github.com/web-platform-tests/wpt/tree/master/resources/test). (Although we originally implemented the framework tests as so-called "integration tests," experience has shown that format to be a little awkward. [This test for "exceptional
cases"](https://github.com/web-platform-tests/wpt/blob/4ca7001dcf130f8dad3d831acf0336d889e5c49a/resources/test/tests/unit/exceptional-cases.html) demonstrates a more ergonomic approach.)

2019-09-17 03:35 UTC, bzbarsky commented
I can do that.  Unfortunately, it seems like I can't test "this assertion should _fail_ in this case", as far as I can tell: all assertions in the test have to pass...

2019-09-17 17:53 UTC, bzbarsky commented
> Could you also add tests for the new functions? 

Thank you.  Of course those showed a bug in the code... ;)  Thanks for the pointer to the test setup as well.  Fixed code and tests coming up.

2019-09-19 02:54 UTC, jugglinmike commented
Tests are magic that way :)

2019-09-23 13:33 UTC, jgraham commented
So I just merged the RFC. It seems like using `same_value` rather than `Object.is` is better at this time; I'm hoping with that change @Ms2ger will do another round of review and everything will be fine (@Ms2ger if you aren't able to do that review please let me know).

2019-09-23 13:35 UTC, bzbarsky commented
Updated to `same_value`.

2019-09-23 13:36 UTC, Ms2ger approved these changes
lgtm

2019-09-23 13:45 UTC, merged

2019-09-23 13:51 UTC, domenic commented
I'm so excited for this. /cc @ricea; this can clean up the streams tests a bit. Thanks @bzbarsky for driving this from idea to execution.

2019-10-04 17:00 UTC, jdm commented
Was this change expected to update https://web-platform-tests.org/writing-tests/testharness-api.html or do the docs need a separate change to update them?

2019-10-04 17:45 UTC, bzbarsky commented
@jdm That needs a separate change.  I'll try to get something put together if someone doesn't beat me to it.

2020-02-18 17:59 UTC, bzbarsky commented
> Was this change expected to update https://web-platform-tests.org/writing-tests/testharness-api.html

To close the loop, this got updated in https://github.com/web-platform-tests/wpt/pull/21762