Tweaked, improved sizing-orthog-htb-in-vrl-013-ref.xht
web-platform-tests/wpt pull request #19735
Opened 2019-10-16 16:33 UTC by TalbotG

Right now, the test
sizing-orthog-htb-in-vrl-013.xht
is reported as FAILED by the 4 browsers (Chrome 78, Edge 79, Firefox 71, Safari 82 Preview):

https://wpt.fyi/results/css/css-writing-modes/sizing-orthog-htb-in-vrl-013.xht?label=master

but, in all fairness, the test is passed by Chromium 76 and Firefox 71. The only problem that needed to be fixed was to **make the viewport of the reference file scrolled horizontally** before comparing it with the test. The code modification in this Pull Request does exactly that: 
`document.documentElement.scrollLeft = 105;`

2019-10-16 16:44 UTC, TalbotG commented
@kojiishi , @frivoal ,

Can one of you review this pull request?

2019-12-18 22:26 UTC, fantasai requested changes
Suggest instead of adding JS, to use `direction: rtl` on HTML element, and `direction: ltr` on the TABLE.

r=fantasai with that change.

2019-12-18 23:40 UTC, TalbotG commented
@fantasai or @kojiishi or @frivoal ,
`direction: rtl` on HTML element and `direction: ltr` on the TABLE have been coded. Please approve this pull request.

2019-12-22 02:18 UTC, fantasai approved these changes

2019-12-22 02:19 UTC, merged

2019-12-22 02:46 UTC, TalbotG commented
Thank you @fantasai :)