[mediacapture-streams] Opt-in to single-page test feature
web-platform-tests/wpt pull request #19915
Opened 2019-10-26 01:52 UTC by jugglinmike

testharness.js was recently extended with an API to explicitly opt-in to
the "single page test" feature [1]. As per WPT RFC 28 [2], tests which
do not use this API and which do not declare any subtests will soon be
reported as a harness error.

Update the tests which previously opted in implicitly to use the new
API.

[1] https://github.com/web-platform-tests/wpt/pull/19449
[2] https://github.com/web-platform-tests/rfcs/blob/master/rfcs/single_test.md

2019-10-26 07:14 UTC, foolip requested changes

2019-10-26 07:14 UTC, foolip commented on mediacapture-streams/MediaDevices-SecureContext.html
> +setup({ single_test: true });
I'd prefer wrapping in `test(() => {})`

2019-10-27 17:34 UTC, jugglinmike commented
You got it. Since the commit message would no longer describe this solution, I've amended the proposed commit and force-pushed the result to this branch. [The original version of this branch is available here.](https://github.com/web-platform-tests/wpt/compare/master...bocoup:single-test-opt-in-mediacapture-streams-orig)

2019-10-27 19:51 UTC, foolip approved these changes

2019-10-27 19:51 UTC, merged