Add support for crashtests
web-platform-tests/wpt pull request #20017
Opened 2019-10-31 12:56 UTC by jgraham

See https://github.com/web-platform-tests/rfcs/pull/33

2019-11-28 09:44 UTC, jgraham commented
@emilio you might also be interested in this.

2019-11-29 02:30 UTC, marcoscaceres approved these changes
approving payment request test rename. Thanks!

2019-11-29 12:33 UTC, FremyCompany approved these changes
At first glance, the css-tables related renames seem ok

2019-12-04 03:44 UTC, svgeesus approved these changes
The renames to avoid -crash where it shouldn't be seem good. I skimmed over the python changes but someone else should review those.

2019-12-09 18:55 UTC, gsnedders requested changes
Files that shouldn't have been renamed:

 * adjoining-float-new-fc-thcrash.html (doesn't meet the criteria in the commit message)
 * gradient-thcrash.html (is a reftest?!)
 * extremely-tall-multicol-with-extremely-tall-child-thcrash.html (doesn't meet the criteria in the commit message)
 * before-in-display-none-thcrash.html (ditto)
 * shape-outside-inset-thcrash.html (is a reftest)

I'm not gonna bother going through the rest, something has gone wrong…

2019-12-09 18:55 UTC, gsnedders commented on tools/manifest/sourcefile.py
> +        return self.type_flag == "crashtest" or "crashtests" in self.dir_path.split(os.path.sep)
RFC as approved uses `crash` for the `type_flag`.

2019-12-11 17:51 UTC, gsnedders requested changes
`css/css-position/position-absolute-crash-chrome-005.html` and `css/css-scoping/whitespace-crash-001.html` don't need renamed (they're not crash tests).

I also wonder if we should have a lint for `-crash` tests containing testharness.js? It really is an antipattern, but also something Chrome developers have already done (and AFAIK they run differently as a result in `run-webkit-tests`, @Hexcles?).

2019-12-11 18:07 UTC, jgraham commented
> `css/css-position/position-absolute-crash-chrome-005.html` and `css/css-scoping/whitespace-crash-001.html` don't need renamed (they're not crash tests).

Fixed.

2019-12-11 23:49 UTC, Hexcles commented
> css/css-position/position-absolute-crash-chrome-005.html and css/css-scoping/whitespace-crash-001.html don't need renamed (they're not crash tests).

They could be rewritten to real tests though, but that's for another day.

> I also wonder if we should have a lint for -crash tests containing testharness.js?

I agree. We should.

> It really is an antipattern, but also something Chrome developers have already done (and AFAIK they run differently as a result in run-webkit-tests, @Hexcles?).

Sorry I'm not sure what you're asking? Until today's introduction of crash tests, Chrome developers have written some de facto crash tests with dummy testharness asserts in them. These should not be needed in the future (at least not named with `-crash`). However, it is true that `run_web_tests` might need to be updated to support these assert-free crash tests (well, more importantly the lack of `testharnessreport.js`, due to a hack we use internally).

2019-12-12 13:36 UTC, jgraham commented
>> I also wonder if we should have a lint for -crash tests containing testharness.js?
> I agree. We should.

I think we could leave that to a followup? It doesn't seem critical to landing the patch, and there are already a bunch of exceptions which we could/should fix at the same time, but deciding how to proceed with that is more work.

2019-12-12 15:59 UTC, gsnedders commented
> Until today's introduction of crash tests, Chrome developers have written some de facto crash tests with dummy testharness asserts in them.

AIUI, does run-webkit-tests not run `-crash` tests in WPT as actual crash tests already? i.e., it ignores any asserts (or failing asserts) in them. My concern is people adding new tests like that with actual asserts.

But to me I'm happy to leave it as a followup.

2019-12-12 15:59 UTC, gsnedders approved these changes

2019-12-12 16:27 UTC, merged

2019-12-12 18:56 UTC, Hexcles commented
> AIUI, does run-webkit-tests not run -crash tests in WPT as actual crash tests already? i.e., it ignores any asserts (or failing asserts) in them. My concern is people adding new tests like that with actual asserts.

That's new to me, but it's possible. And yes we should prevent people from adding dummy asserts to crash tests.