Add --ignore-glob flag to wpt lint.
web-platform-tests/wpt pull request #20242
Opened 2019-11-13 20:54 UTC by LukeZielinski

This allows specifying file patterns to ignore via the commandline.

This feature is used inside Chromium CI to skip linting some
auto-generated files that aren't part of WPT. The motivation to make
this change upstream is because we sometimes get conflicts between the
local Chromium copy and the update upstream copy.

2019-11-14 09:09 UTC, Ms2ger submitted a review, later dismissed

2019-11-14 09:10 UTC, Ms2ger commented on tools/lint/lint.py
> +def lint(repo_root, paths, output_format, ignore_glob):
Make it optional.

2019-11-19 02:26 UTC, gsnedders requested changes
Revert the existing test changes, and add a new test that actually checks this works, please?

2019-11-22 18:56 UTC, LukeZielinski commented
> Revert the existing test changes, and add a new test that actually checks this works, please?

Added a new test. I didn't revert the tweak to the existing test to make the mock happy, since we do actually pass another param to the `lint` method now.

2019-11-26 13:42 UTC, gsnedders approved these changes

2019-11-26 13:42 UTC, merged