[docs] Relocate recommendation on git usage
web-platform-tests/wpt pull request #20285
Opened 2019-11-15 22:46 UTC by jugglinmike

Further reduce the size of the project's README file, and extend the
relevant documentation with the distinct recommendation that would
otherwise be lost.

This is in service of gh-5289

2019-11-16 12:37 UTC, sideshowbarker approved these changes

2019-11-16 12:37 UTC, sideshowbarker commented on docs/writing-tests/github-intro.md
> +In the vast majority of cases the **only** upstream branch that you should need
```suggestion
In the vast majority of cases, the **only** upstream branch that you should need
```

2019-11-19 12:37 UTC, zcorpan approved these changes

2019-12-19 11:28 UTC, jgraham requested changes

2019-12-19 11:28 UTC, jgraham commented on README.md
> -Setting Up the Repo
The bit about git configuration and `--prune` seems like it should be in the README if anywhere since it's much more likely to be read there.

2019-12-19 11:28 UTC, jgraham commented on README.md
> -Branches
Agreed that this part can go from the readme.

2020-10-20 02:55 UTC, sideshowbarker commented
This seems to be waiting for changes to be made in response to review comments.

2020-10-20 12:55 UTC, stephenmcgruer commented
I believe jugglinmike does not current work in the WPT space, and is unlikely to get to this PR. I've uploaded a version to https://github.com/web-platform-tests/wpt/pull/26187 which addresses the comments; we should be able to just merge that and let it close this.

2020-10-20 14:44 UTC, closed without merging