Change how wptrunner computes reftests
web-platform-tests/wpt pull request #20459
Opened 2019-11-26 20:15 UTC by gsnedders

This preserves the current data structures within wptrunner as it
passes them onwards to Marionette currently in the Firefox case, and
as such changing them involves changes within Firefox too.

Those changes within Firefox are ones we should make, and is tracked
by https://bugzilla.mozilla.org/show_bug.cgi?id=1598340, before
changing how reftests are represented within wptrunner.

----

That all said, given we necessarily have to regenerate the manifest for this, we may want to re-evaluate how we store references within the manifest, and whether we want to store a list of pass conditions (like #11345 did with our earlier, much more complex logic).

This PR is also gonna need a bunch of test updates; all of the infrastructure tests for reftest chains etc. now inevitably fail.

2019-12-03 02:54 UTC, gsnedders commented
@jgraham why hasn't TC started running this? :(

2019-12-03 17:38 UTC, gsnedders commented
https://community-tc.services.mozilla.com/tasks/groups/FrPCpENuTi-JOgS2Ixyq2w and https://community-tc.services.mozilla.com/tasks/groups/XGmpPteSTGCOEg9U7W8e5g are full Fierfox/Chrome runs for e485b6f47f41310cfedd3d4993a19343d1fd0d9f

2019-12-03 20:35 UTC, jgraham reviewed
Generally this looks pretty good. I wonder if there are required docs changes?

2019-12-03 20:35 UTC, jgraham commented on infrastructure/reftest/reftest_multiple_mismatch-1.html
> +<link rel=mismatch href=red.html>
Can we have one with multiple mismatch and multiple match?

2019-12-03 23:01 UTC, gsnedders commented
> Generally this looks pretty good. I wonder if there are required docs changes?

Oh. Yes.

https://wpt.fyi/results/css?diff&filter=ADC&run_id=363070004&run_id=349640015 is a comparison of Chrome; https://wpt.fyi/results/?diff&filter=ADC&run_id=353360002&run_id=384230010 is a comparison of Firefox (not quite the right base revision, but almost; the right one doesn't seem to have run against nightly but there are only two SVG tests changed between them).

So some broken tests:

* css/CSS2/selectors/universal-selector-002.xht — matches everything because :first-child matches html:first-child and `color` gets inherited.

Every other regression looks like a correct change with mismatch being AND?

2019-12-09 18:43 UTC, gsnedders commented on tools/wptrunner/wptrunner/wpttest.py
> +        mismatch_walk = None
+ unit tests

2019-12-12 13:40 UTC, stephenmcgruer commented
cc @LukeZielinski as an FYI that we will need to roll wptrunner reasonably soon after this lands. It's a low risk, but it would be possible for a Chromium author to write a now-incorrect reftest downstream with the old wptrunner, which then wouldn't work upstream. Probably not a huge problem, but something to keep an eye on.

2019-12-12 13:43 UTC, foolip commented
@LukeZielinski to elaborate on that, we'll "just" need to roll the tools directory and see if it still works. Some small adaptation might be needed in code on our side that interprets the manifest.

2019-12-12 18:49 UTC, LukeZielinski commented
@Hexcles as FYI as well. I'm not sure doing another roll of tools in Chromium before the holidays is wise, since a lot of people are disappearing until January starting in the next few days. Which hopefully also means a lot less test authoring happening, but I'd still say we wait until the new year.

2019-12-18 18:01 UTC, gsnedders commented
Needs docs changes; otherwise complete.

2019-12-18 18:18 UTC, jgraham requested changes

2019-12-18 18:18 UTC, jgraham commented on tools/manifest/manifest.py
> +        # TODO(MANIFESTv7): remove this condition
Now `MANIFESTv8`.

2019-12-20 19:12 UTC, jgraham approved these changes

2019-12-20 19:12 UTC, merged