Add interfaces/permissions-revoke.idl and test
web-platform-tests/wpt pull request #21489
Opened 2020-01-29 12:42 UTC by stephenmcgruer

Closes https://github.com/web-platform-tests/wpt/pull/21315

2020-02-03 14:13 UTC, stephenmcgruer commented
Ping @foolip

2020-02-05 14:37 UTC, foolip requested changes

2020-02-05 14:37 UTC, foolip commented on permissions-revoke/idlharness.any.js
> +      await navigator.permissions.query({ name: "geolocation" });
Same doubt as in https://github.com/web-platform-tests/wpt/pull/21492#discussion_r375290299

2020-02-05 16:19 UTC, foolip approved these changes

2020-02-05 16:19 UTC, merged