Update interfaces/{screen-}wake-lock.idl and test
web-platform-tests/wpt pull request #23115
Opened 2020-04-20 14:42 UTC by stephenmcgruer

The spec was renamed

Closes https://github.com/web-platform-tests/wpt/pull/23106
Closes https://github.com/web-platform-tests/wpt/pull/23107

2020-04-20 19:39 UTC, reillyeon requested changes
This seems to be reverting the specification name change.

2020-04-20 19:44 UTC, stephenmcgruer commented
Good catch! Looks like the spec was renamed *to* screen-wake-lock/, but reffy isn't seeing that so it tried to change it back. I then made this change just based off of what reffy said, without checking. My bad :(

@foolip - can you investigate why reffy hasn't noticed the spec change? Also, should we change interfaces to also say 'ALSO DO NOT MOVE ME BECAUSE A BOT IS JUST GOING TO MOVE IT BACK'... (partially in jest, but clearly the warning isn't working)

2020-05-18 09:45 UTC, foolip commented
@stephenmcgruer https://github.com/web-platform-tests/wpt/pull/23106/files has been updated now after https://github.com/tidoust/reffy/issues/303 was resolved. But the filename hasn't changed, the TR name is used when it exists.

@reillyeon is the idea that https://www.w3.org/TR/screen-wake-lock/ will eventually exist, or that the names will be mismatched indefinitely like for example https://www.w3.org/TR/mediacapture-streams/ and https://w3c.github.io/mediacapture-main/?

2020-05-18 23:37 UTC, reillyeon commented
A candidate recommendation for the renamed specification should eventually be published at which point that URL will be valid.

CC @xfq @anssiko

2020-05-20 11:33 UTC, stephenmcgruer commented
Ok, so based on https://github.com/web-platform-tests/wpt/pull/23106#issuecomment-630767743 I believe the correct behavior for now is still to rename, temporarily. I've updated the description to reflect the reasoning (and will copy the description into the commit when I squash-merge).

2020-05-20 17:09 UTC, reillyeon approved these changes

2020-05-20 17:31 UTC, merged