Add promise rejection tracking tests
web-platform-tests/wpt pull request #2388
Opened 2015-11-30 22:25 UTC by domenic

For https://github.com/whatwg/html/pull/224

Need a few pieces of help:

- Running the allow-crossorigin and disallow-crossorigin tests fails for me locally because the `{{ports[html][0]}}` syntax from /cors/support.js is not getting preprocessed. Any ideas?
- I tried replacing setTimeout with `t.step_timeout` in disallow-crossorigin, but this caused the test to pass even when I changed the URL to be same-origin. I think that section of code probably just needs to be done better; review would be helpful.

I'd appreciate if review was done on GitHub, not Critic.

These tests were done in collaboration with @jeisinger. Apart from the abovementioned issues, they all pass in Chrome Canary with experimental web platform features enabled.

2015-11-30 22:25 UTC, tobie commented
Reviewers for this pull request are: @w3c/html-reviewers.

2015-12-01 08:18 UTC, zcorpan commented on html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events-onerror.html
> +    }
Can use `t.step(function() { p.catch(function() {}); }` instead of try/catch

2015-12-01 08:21 UTC, zcorpan commented on html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events-onerror.html
> +  }, 1);
Doesn't this timeout run after the test has finished?

2015-12-01 16:20 UTC, domenic commented on html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events-onerror.html
> +  }, 1);
No; the seqence is Promise.reject(e); setTimeout 1; p.catch -> causes onrejectionhandled; throw e2 -> causes onerror; t.done().

2015-12-01 16:29 UTC, domenic commented
I pushed a fix for @zcorpan's review and also one for the troublesome issue I mentioned in the OP.

The only remaining potentially major item I can see is a global replacement of setTimeout with t.step_timeout. I'm happy to do that if people advise me it's a good idea. My experience is that they have strangely different semantics which scares me a bit.

2015-12-01 17:47 UTC, zcorpan commented
Maybe best to ask @jgraham about step_timeout

2016-08-28 16:43 UTC, domenic commented
Why close and delete my PR?

2016-08-28 17:48 UTC, gsnedders commented
```
15:01 < aryehgregor> Um, I might have done something wrong by mistake.
15:01 < aryehgregor> I think I pushed to the wrong repo?
```

2016-08-28 17:49 UTC, gsnedders commented
…and then I screw up and press "close and comment". This isn't our day. :\

2017-02-05 23:06 UTC, tobie commented
Ping @wpt-pr-bot.

2017-02-08 21:23 UTC, w3c-bots commented
# Chrome (unstable channel) #
Testing web-platform-tests at revision 2d5a139f5a1eae176ee82edceb9ddac577e8246d
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/2388/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/allow-crossorigin.html">/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/allow-crossorigin.html</a></summary>


|                                    Subtest                                    | Results |
|-------------------------------------------------------------------------------|---------|
|                                                                               | TIMEOUT |
| `Promise rejection event should be received for the cross-origin CORS script` | TIMEOUT |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/2388/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/disallow-crossorigin.html">/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/disallow-crossorigin.html</a></summary>


|                                  Subtest                                   | Results |
|----------------------------------------------------------------------------|---------|
|                                                                            | OK      |
| `Promise rejection event should be muted for cross-origin non-CORS script` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/2388/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events-onerror.html">/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events-onerror.html</a></summary>


|                                  Subtest                                   | Results |
|----------------------------------------------------------------------------|---------|
|                                                                            | OK      |
| `Throwing inside an unhandledrejection handler invokes the error handler.` | PASS    |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/2388/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events.serviceworker.https.html">/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events.serviceworker.https.html</a></summary>


|                                                                                                   Subtest                                                                                                    | Results |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|
|                                                                                                                                                                                                              | ERROR   |
| `unhandledrejection: from a throw in a rejection handler chained off of a setTimeout-delayed rejection`                                                                                                      | PASS    |
| `delayed handling: a nested-postMessageTask after promise creation/rejection, plus many promise microtasks, is too late to attach a rejection handler`                                                       | PASS    |
| `unhandledrejection: from a throw in a rejection handler attached one microtask after a setTimeout-delayed rejection`                                                                                        | PASS    |
| `unhandledrejection: from Promise.reject`                                                                                                                                                                    | PASS    |
| `mutationObserverMicrotask vs. postMessageTask ordering is not disturbed inside unhandledrejection events`                                                                                                   | PASS    |
| `unhandledrejection: from a setTimeout-delayed rejection`                                                                                                                                                    | PASS    |
| `microtask nesting: attaching a handler inside a combination of mutationObserverMicrotask + promise microtasks, all inside a setTimeout`                                                                     | PASS    |
| `delayed handling: delaying handling by setTimeout(,10) will cause both events to fire`                                                                                                                      | PASS    |
| `delayed handling: a microtask delay before attaching a handler prevents both events (immediately-rejected new Promise-created promise)`                                                                     | PASS    |
| `no unhandledrejection/rejectionhandled: rejection handler attached synchronously to a promise created from returning a Promise.reject-created promise in a fulfillment handler`                             | PASS    |
| `delayed handling: a nested-task delay before attaching a handler causes unhandledrejection`                                                                                                                 | PASS    |
| `no unhandledrejection/rejectionhandled: all inside a queued task, a rejection handler attached synchronously to a promise created from returning a Promise.reject-created promise in a fulfillment handler` | PASS    |
| `delayed handling: a nested-postMessageTask after promise creation/rejection, plus promise microtasks, is too late to attach a rejection handler`                                                            | PASS    |
| `delayed handling: a microtask delay before attaching a handler prevents both events (Promise.reject-created promise)`                                                                                       | PASS    |
| `unhandledrejection: from a throw in a fulfillment handler`                                                                                                                                                  | PASS    |
| `microtask nesting: attaching a handler inside a combination of promise microtasks + mutationObserverMicrotask, all inside a postMessageTask`                                                                | PASS    |
| `delayed handling: a microtask delay before attaching the handler, and before rejecting the promise, indirected through Promise.all`                                                                         | PASS    |
| `microtask nesting: attaching a handler inside a combination of mutationObserverMicrotask + promise microtasks`                                                                                              | PASS    |
| `microtask nesting: attaching a handler inside a combination of promise microtasks + mutationObserverMicrotask`                                                                                              | PASS    |
| `unhandledrejection: from a throw in a rejection handler chained off of Promise.reject`                                                                                                                      | PASS    |
| `no unhandledrejection/rejectionhandled: rejection handler attached synchronously to a promise from Promise.reject`                                                                                          | PASS    |
| `Service worker setup`                                                                                                                                                                                       | [...]

2017-02-08 21:23 UTC, w3c-bots commented
# Firefox (nightly channel) #
Testing web-platform-tests at revision 2d5a139f5a1eae176ee82edceb9ddac577e8246d
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/2388/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/allow-crossorigin.html">/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/allow-crossorigin.html</a></summary>


|                                    Subtest                                    | Results |
|-------------------------------------------------------------------------------|---------|
|                                                                               | TIMEOUT |
| `Promise rejection event should be received for the cross-origin CORS script` | TIMEOUT |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/2388/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/disallow-crossorigin.html">/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/disallow-crossorigin.html</a></summary>


|                                  Subtest                                   | Results |
|----------------------------------------------------------------------------|---------|
|                                                                            | OK      |
| `Promise rejection event should be muted for cross-origin non-CORS script` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/2388/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events-onerror.html">/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events-onerror.html</a></summary>


|                                  Subtest                                   | Results |
|----------------------------------------------------------------------------|---------|
|                                                                            | TIMEOUT |
| `Throwing inside an unhandledrejection handler invokes the error handler.` | TIMEOUT |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/2388/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events.serviceworker.https.html">/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-events.serviceworker.https.html</a></summary>


|                                                                                                   Subtest                                                                                                    | Results |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|
|                                                                                                                                                                                                              | TIMEOUT |
| `unhandledrejection: from a throw in a rejection handler chained off of a setTimeout-delayed rejection`                                                                                                      | TIMEOUT |
| `delayed handling: a nested-postMessageTask after promise creation/rejection, plus many promise microtasks, is too late to attach a rejection handler`                                                       | TIMEOUT |
| `unhandledrejection: from a throw in a rejection handler attached one microtask after a setTimeout-delayed rejection`                                                                                        | TIMEOUT |
| `unhandledrejection: from Promise.reject`                                                                                                                                                                    | TIMEOUT |
| `mutationObserverMicrotask vs. postMessageTask ordering is not disturbed inside unhandledrejection events`                                                                                                   | TIMEOUT |
| `unhandledrejection: from a setTimeout-delayed rejection`                                                                                                                                                    | TIMEOUT |
| `microtask nesting: attaching a handler inside a combination of mutationObserverMicrotask + promise microtasks, all inside a setTimeout`                                                                     | PASS    |
| `delayed handling: delaying handling by setTimeout(,10) will cause both events to fire`                                                                                                                      | PASS    |
| `delayed handling: a microtask delay before attaching a handler prevents both events (immediately-rejected new Promise-created promise)`                                                                     | PASS    |
| `no unhandledrejection/rejectionhandled: rejection handler attached synchronously to a promise created from returning a Promise.reject-created promise in a fulfillment handler`                             | PASS    |
| `delayed handling: a nested-task delay before attaching a handler causes unhandledrejection`                                                                                                                 | TIMEOUT |
| `no unhandledrejection/rejectionhandled: all inside a queued task, a rejection handler attached synchronously to a promise created from returning a Promise.reject-created promise in a fulfillment handler` | PASS    |
| `delayed handling: a nested-postMessageTask after promise creation/rejection, plus promise microtasks, is too late to attach a rejection handler`                                                            | TIMEOUT |
| `delayed handling: a microtask delay before attaching a handler prevents both events (Promise.reject-created promise)`                                                                                       | PASS    |
| `unhandledrejection: from a throw in a fulfillment handler`                                                                                                                                                  | TIMEOUT |
| `microtask nesting: attaching a handler inside a combination of promise microtasks + mutationObserverMicrotask, all inside a postMessageTask`                                                                | PASS    |
| `delayed handling: a microtask delay before attaching the handler, and before rejecting the promise, indirected through Promise.all`                                                                         | PASS    |
| `microtask nesting: attaching a handler inside a combination of mutationObserverMicrotask + promise microtasks`                                                                                              | PASS    |
| `microtask nesting: attaching a handler inside a combination of promise microtasks + mutationObserverMicrotask`                                                                                              | PASS    |
| `unhandledrejection: from a throw in a rejection handler chained off of Promise.reject`                                                                                                                      | TIMEOUT |
| `no unhandledrejection/rejectionhandled: rejection handler attached synchronously to a promise from Promise.reject`                                                                                          | PASS    |
| `Service worker setup`                                                                                                                            [...]

2017-02-08 21:35 UTC, domenic commented
@jeisinger I realize we never landed this... do you have any idea why Chrome does not pass allow-crossorigin.html ?

2017-02-15 12:39 UTC, jeisinger requested changes

2017-02-15 12:39 UTC, jeisinger commented on html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/allow-crossorigin.html
> +  scriptEl.src = CROSSDOMAIN + 'support/promise-access-control.py?allow=true';
add `scriptEl.crossOrigin = 'anonymous';` - otherwise CORS won't be used.

2017-02-15 12:39 UTC, jeisinger commented on html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/disallow-crossorigin.html
> +  scriptEl.onload = resolveLoaded;
same here.

2017-02-15 20:45 UTC, merged