Python 3: Port tests in document-policy, dom and import-maps
web-platform-tests/wpt pull request #24084
Opened 2020-06-10 12:13 UTC by ziransun

2020-06-10 13:36 UTC, annevk submitted a review, later dismissed

2020-06-11 20:26 UTC, stephenmcgruer requested changes
This change appears to regress results, e.g. see https://github.com/web-platform-tests/wpt/pull/24084/checks?check_run_id=757832786

Possibly due to the issues jdm raised.

2020-06-12 08:25 UTC, ziransun commented
Couldn't reproduce the test failure locally. Re-triggering the test run. Hope it's okay.

2020-06-12 14:18 UTC, stephenmcgruer commented
> Couldn't reproduce the test failure locally. Re-triggering the test run. Hope it's okay.

Definitely ok, but I can trivially reproduce with your patch:

```
./wpt run --log-mach-level=info --log-mach=- --channel=experimental chrome dom/nodes/Document-characterSet-normalization.html
...
 0:12.47 WARNING No module named html
Traceback (most recent call last):
  File "/home/smcgruer/github/wpt/tools/wptserve/wptserve/server.py", line 267, in finish_handling
    handler(request, response)
  File "/home/smcgruer/github/wpt/tools/wptserve/wptserve/handlers.py", line 294, in __call__
    self._set_path_and_load_file(request, response, func)
  File "/home/smcgruer/github/wpt/tools/wptserve/wptserve/handlers.py", line 274, in _set_path_and_load_file
    exec(compile(f.read(), path, 'exec'), environ, environ)
  File "/home/smcgruer/github/wpt/dom/nodes/encoding.py", line 1, in <module>
    from html import escape
ImportError: No module named html
```

I wonder if you have locally installed [this pip module](https://pypi.org/project/html/)? (which isn't part of the standard lib in Python 2)

2020-06-15 06:28 UTC, ziransun commented on import-maps/common/tools/format_json.py
> +if __name__ == u'__main__':
@Hexcles, there are a few non handlers related python files in other places as well. How do we handle them?

2020-06-15 06:29 UTC, ziransun commented on dom/nodes/encoding.py
> +from html import escape
Code updated. Thank you!

2020-06-15 06:32 UTC, ziransun commented
> I wonder if you have locally installed [this pip module](https://pypi.org/project/html/)? (which isn't part of the standard lib in Python 2)

Yes, doesn't look that it's a built-in module for python 2. Code updated.

2020-06-15 14:59 UTC, stephenmcgruer approved these changes

2020-06-15 15:01 UTC, stephenmcgruer commented on import-maps/common/tools/format_json.py
> +if __name__ == u'__main__':
If it isn't a wptserve handler, they don't need to be updated as part of the wptserve migration. In particular for this case, I believe its only run manually anyway.

2020-06-15 18:57 UTC, ziransun commented on import-maps/common/tools/format_json.py
> +if __name__ == u'__main__':
Right. code updated.

2020-06-25 14:15 UTC, ziransun commented
Can we merge this in?

2020-06-25 14:18 UTC, merged