Relocate to link relationship to HTML spec
web-platform-tests/wpt pull request #24447
Opened 2020-07-06 07:03 UTC by marcoscaceres

2020-07-06 07:58 UTC, christianliebel requested changes
Rename test title to match the primary testing objective

2020-07-06 07:58 UTC, christianliebel commented on html/links/manifest/link-relationship/link-tree-order-manual.html
> +<title>Test that name member is supported</title>
```suggestion
<title>Test that the first "manifest" `link` is used for installing</title>
```

2020-07-06 19:22 UTC, christianliebel approved these changes

2020-07-07 14:29 UTC, stephenmcgruer commented
@marcoscaceres the checks for this PR will be blocked due to the Taskcluster Checks migration (sorry!). You can either rebase/merge-from-master the PR to bring in the new Taskcluster config, or just let me know when you want it merged and I can admin-merge it for you :)

2020-07-15 06:58 UTC, marcoscaceres commented
Thanks again @stephenmcgruer! rebased :)

2020-07-15 08:12 UTC, merged