Add some tests for createDocument with missing arguments.
web-platform-tests/wpt pull request #2468
Opened 2016-01-12 15:34 UTC by Ms2ger

2016-01-12 15:34 UTC, tobie commented
Reviewers for this pull request are: @w3c/dom-reviewers.

2016-01-20 17:32 UTC, merged

2025-06-18 02:13 UTC, samgit520 approved these changes

2025-06-18 02:14 UTC, samgit520 requested changes

2025-06-18 02:14 UTC, samgit520 commented on dom/nodes/DOMImplementation-createDocument.html
> +    document.implementation.createDocument()
Zarde

2025-06-18 02:14 UTC, samgit520 commented on dom/nodes/DOMImplementation-createDocument.html
> +    document.implementation.createDocument()
Yes