Added 2 selection-overlay-* tests with their respective references
web-platform-tests/wpt pull request #24985
Opened 2020-08-12 23:35 UTC by TalbotG

This is a followup to
https://github.com/web-platform-tests/wpt/pull/20032#issuecomment-623866546

selection-overlay-and-spelling-001.html
selection-overlay-and-grammar-001.html
reference/selection-overlay-and-spelling-001-ref.html
reference/selection-overlay-and-grammar-001-ref.html

Latest and most relevant review comments from @fantasai about those tests were:
{
"
if you at least have a solid background on ::spelling-error underneath the semi-transparent highlight, that will at least prove the background layering, and it will distinguish it from not supporting ::spelling-error.
"
}

Those tests and references are on my website (under slightly different filenames):

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-overlay-and-spelling-001-newest.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-overlay-and-grammar-001-newest.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/reference/selection-overlay-and-spelling-001-ref-newest.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/reference/selection-overlay-and-grammar-001-ref-newest.html

**There is a 1px difference between test and reference for Firefox81 ... and I just do not know or see how to neutralize it.**

2020-08-19 00:23 UTC, fantasai requested changes
To fix the 1px difference, set the blue color on an inline element instead of on the DIV.

2020-08-24 21:14 UTC, fantasai commented
@TalbotG I think this is a good test. My main concern is if the color compositing ends up not being an exact match for the reference, the test might fail. I wonder if it's possible to use the same transparency effect in the reference somehow.

2020-08-25 01:34 UTC, TalbotG commented
1st possible replacement (we must specify a line-height in order to accomplish a negative margin-top):
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/reference/selection-overlay-and-spelling-001-ref-newestZ.html

2nd possible replacement  (we must specify a monospace font in order to accomplish a negative margin-left with ch unit):
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/reference/selection-overlay-and-spelling-001-ref-newestZ3.html

and with those, the test when also using `font: 60px/90px monospace`:
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-overlay-and-spelling-001-newest2.html

and the initial reference when relying on color composition and when also using `font: 60px/90px monospace`:
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/reference/selection-overlay-and-spelling-001-ref-newestX.html

2020-08-25 20:31 UTC, fantasai commented
Just for the reference, would need to do something like 
```
  <div style="color: transparent; margin-bottom: -1em">Many <span style="background: yellow">thing</span> can happen.</div>
  <div contenteditable="true" id="reference"><span id="outer">Many <span id="inner">thing</span> can happen.</span></div>
```
to recreate the overlap.

2020-08-26 00:39 UTC, TalbotG commented
With relative positioning:

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/reference/selection-overlay-and-grammar-001-ref-newestZ.html

2020-08-26 01:31 UTC, TalbotG commented
One **possible adjustment to selection-overlay-and-spelling-001.html test** would be to set `line-height` to `1` to avoid/work around Chromium's vertical extension to top and bottom of line height as we know about it ([Issue 5395](https://github.com/w3c/csswg-drafts/issues/5395)).

The correspondent files on my website to this 58ff055 commit are:


http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-overlay-and-spelling-001-newest2.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/reference/selection-overlay-and-spelling-001-ref-newestZ.html

 - - - - 

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/selection-overlay-and-grammar-001-newest.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/reference/selection-overlay-and-grammar-001-ref-newestZ5.html

2020-08-26 05:27 UTC, fantasai commented
Yes, you will need `line-height: 1`, as I mentioned in the comment earlier. The bounds of the selection are not defined, so we should not fail Chromium for this. r=fantasai with that change

2020-08-27 03:59 UTC, fantasai approved these changes

2020-08-27 03:59 UTC, merged