[trusted-types] Test event handler content attrs
web-platform-tests/wpt pull request #25306
Opened 2020-08-31 22:28 UTC by jugglinmike

2021-01-11 11:35 UTC, mikewest commented on trusted-types/event-handler-content-attributes.tentative.html
> +      subject.setAttribute(attribute, 'Why hello there');
I'm not going to type it. You can't make me. :)

2021-01-11 11:35 UTC, mikewest commented on trusted-types/event-handler-content-attributes.tentative.html
> +  ['body', 'onafterprint'],
The ordering here is a little weird. Did you consider just sorting alphabetically (resulting in element first, then attribute)?

2025-03-20 14:03 UTC, fred-wang commented
@jugglinmike  Do we still need this?

There are some tests relying on trusted-types/support/event-handler-attributes.mjs to get a more complete list of event handler attributes.

2025-03-21 07:45 UTC, fred-wang requested changes
`trusted-types/set-event-handlers-content-attributes.tentative.html` verifies more event handler attributes that are TT sinks (or not) by checking whether the default policy applies on a plain string.

This particular test does it in a different way: it tests we can pass assign a TT and that a plain string assignment is rejected when there is no default policy specified. This is covered by other tests for onclick e.g. trusted-types/GlobalEventHandlers-onclick.html and probably others using trusted-types/support/attributes.js

Not sure we need to do these checks for all event handle content attributes, but if you really think we need it then please rely on  trusted-types/support/event-handler-attributes.mjs instead of a hardcoded array.

2025-09-30 04:56 UTC, fred-wang commented
@jugglinmike  I'm closing this PR per the comment above. If you disagree, feel free to open a new PR.

2025-09-30 04:56 UTC, closed without merging