Include testharness in lazy loading reftest-wait tests
web-platform-tests/wpt pull request #25513
Opened 2020-09-14 08:28 UTC by rwlbuis

Include testharness in lazy loading reftest-wait tests since WebKit
uses testharness to enable lazy image loading.

2020-09-14 09:06 UTC, zcorpan commented
> WebKit uses testharness to enable lazy image loading.

Why?

2020-09-14 09:56 UTC, rwlbuis commented
> > WebKit uses testharness to enable lazy image loading.
> 
> Why?

WebKit has been making a move from runtime enabled feature flags to settings. In order to toggle settings per test JS API is exposed on internals.settings. So far this has been used for WebAudio but since a few weeks also for lazy loading in WebKit. To be clear, this is controlled by the vendor specific testharnessreport.js, not the generic one, but it has to be included in order for lazy loading to be enabled.

Note that even in the time of runtime enabled feature flags, a WebKit specific tweak was needed (example <!-- webkit-test-runner [ experimental:AspectRatioOfImgFromWidthAndHeightEnabled=true ] -->), which was not upstreamed to WPT repo, and was a hassle.

2020-09-14 10:16 UTC, annevk commented
I think we should discuss this in https://github.com/web-platform-tests/rfcs as this would affect all reftests and it's not clear to me this is the solution to configuration for those tests. And if it is, perhaps only the second script file should be included.

2020-09-14 11:29 UTC, jgraham requested changes
+1 on an RFC or similar for this.

Including `testharness.js` itself won't work because the harness will detect the tests as testharness tests; see e.g. https://github.com/web-platform-tests/wpt/pull/25513/checks?check_run_id=1111154398 where we end up with 0 tests after this patch.

2020-09-15 17:15 UTC, rwlbuis commented
It turns out this is not needed after all. Sorry for the noise!

2020-09-15 17:15 UTC, closed without merging