Quirks: Add tests for "html fills viewport" and "body fills html"
web-platform-tests/wpt pull request #26438
Opened 2020-11-06 21:06 UTC by andreubotella

The "`html` fills viewport" quirk wasn't tested at all; and the tests for "`body` fills `html`" only covered the exceptions to the quirk rather than the cases where it should apply. This PR adds the missing coverage.

2020-11-13 09:18 UTC, zcorpan requested changes
Thanks! I found one mistake in the ref.

2020-11-13 09:18 UTC, zcorpan commented on quirks/html-fills-viewport-quirk-ref.html
> +<body style="width: 100vw; height: 100vw; margin: 0; padding: 10px; box-sizing: border-box">
The height should be `100vh`

```suggestion
<body style="width: 100vw; height: 100vh; margin: 0; padding: 10px; box-sizing: border-box">
```

2020-11-13 09:28 UTC, zcorpan commented
Hmm, an aspect that the tests don't exercise well is which margins are being substracted from the block-size, since the margins are the same on all sides. Maybe use different margins on all sides, like `10px 11px 12px 14px`?

2020-11-16 21:45 UTC, zcorpan approved these changes

2020-11-16 21:47 UTC, merged

2020-11-16 21:47 UTC, zcorpan commented
Thank you! Are you interested in filing a bug for WebKit?

Test results: https://wpt.fyi/results/quirks?label=pr_head&max-count=1&pr=26438

2020-11-17 04:05 UTC, andreubotella commented
> Thank you! Are you interested in filing a bug for WebKit?

https://bugs.webkit.org/show_bug.cgi?id=219018