Add tests for WebDriver Async Session Creation
web-platform-tests/wpt pull request #26490
Opened 2020-11-11 19:34 UTC by christian-bromann

This patch adds tests for Async Session Creation, proposed in: https://github.com/w3c/webdriver/pull/1561

2020-11-12 09:15 UTC, whimboo requested changes
Thanks Christian. Just some early feedback...

2020-11-12 09:15 UTC, whimboo commented on webdriver/tests/new_session/async.py
> +    new_async_session_response, get_session_response = new_async_session(
In the spec you define that as a new command with a different end-point. As such we should move related tests to a new sub directory called `new_async_session`.

2020-11-12 09:15 UTC, whimboo commented on webdriver/tests/new_session/async.py
> +    bodyValue = get_session(
Same here. Please create a new sub directory with the name `get_session` and move the tests over.

2020-11-12 09:15 UTC, whimboo commented on webdriver/tests/new_session/conftest.py
> +    def new_session(self, body):
Most likely you want `new_async_session` here.

2021-01-27 09:57 UTC, AutomatedTester commented
Thanks for the tests @christian-bromann . Please follow up on @whimboo's comments

2021-03-10 14:32 UTC, christian-bromann commented
Thanks for the feedback all, will close this one given that I am working on modifications to this functionality. Will open a new PR later on.

2021-03-10 14:32 UTC, closed without merging