Added 2 hanging-punctuation tests
web-platform-tests/wpt pull request #26961
Opened 2020-12-20 00:49 UTC by TalbotG

/css/css-text/hanging-punctuation/hanging-punctuation-block-bound-001.html 
/css/css-text/hanging-punctuation/reference/hanging-punctuation-block-bound-001-ref.html /css/css-text/hanging-punctuation/hanging-punctuation-inline-bound-001.html 
/css/css-text/hanging-punctuation/reference/hanging-punctuation-inline-bound-001-ref.html

These 2 tests spun from
[Issue 4222: [css-text-3] hanging-punctuation effect on inline/block bounds](https://github.com/w3c/csswg-drafts/issues/4222)

At my website, the files are:

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/hanging-punctuation/hanging-punctuation-block-bound-001.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/hanging-punctuation/reference/hanging-punctuation-block-bound-001-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/hanging-punctuation/hanging-punctuation-inline-bound-001.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/hanging-punctuation/reference/hanging-punctuation-inline-bound-001-ref.html

Epiphany 3.32.1.2 (WebKitGTK+ 2.30.3) pass these 2 tests perfectly on my system. So I presume that latest Safari version would also pass.

2021-02-04 11:33 UTC, fantasai requested changes
I have slightly different fonts, I think, and hanging-punctuation-block-bound-001-ref.html does not render as expected on my system. This is because in the test, “す。” are part of the same inline context, whereas in the reference they are not.

The way to fix this is the following: 
```
   <div style="background: lime; border: solid black 3px; color: transparent; position: absolute; z-index: -1; width: 240px">まだよく<br>ています。<br>しかし特</div>
   <div style="border: solid 3px transparent; width: 300px">まだよく<br>ています。<br>しかし特</div>
```

In the first case, we draw the box (perfectly fitted to the content in the block axis, because it has the same content) but not the text.
In the second case, we draw the text, but into a wider box so the period will fit.

2021-02-27 02:03 UTC, TalbotG commented
> In the first case, we draw the box (perfectly fitted to the content in the block axis, because it has the same content) but not the text.
In the second case, we draw the text, but into a wider box so the period will fit, and overlap it with the previously-drawn box.

Here's how it looks:
http://www.gtalbot.org/BrowserBugsSection/CSS3Text/hanging-punctuation/reference/hanging-punctuation-block-bound-001.2-ref.html

I am working on another possibility: to force a .woff resource to overcome the font selection issue...

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/hanging-punctuation/hanging-punctuation-block-bound-001-Mplus1p.html

We have already used 
src: url("/fonts/mplus-1p-regular.woff") format("woff");
in many css-writing-modes tests so far...

More later..

2021-03-11 23:49 UTC, TalbotG commented
Okay. I have adjusted the reference according to our phone call.

On my website, the new reference is:

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/hanging-punctuation/reference/hanging-punctuation-block-bound-001.4-ref.html

I will adjust the reference in the PR in a few min.

2021-09-10 00:05 UTC, fantasai approved these changes

2021-09-10 00:05 UTC, merged