fix: make user-timing/mark strict mode compatible
web-platform-tests/wpt pull request #27053
Opened 2021-01-05 21:05 UTC by lucacasonato

Background: Deno runs WPT is strict mode.﻿

2021-01-06 00:19 UTC, hafixo approved these changes

2021-01-06 00:22 UTC, hafixo requested changes
Merge pull requested

2021-01-16 12:53 UTC, lucacasonato commented
@igrigorik @plehegar Any chance you could take a look at this?

2021-01-22 06:59 UTC, annevk approved these changes

2021-01-22 07:00 UTC, merged