Streams: add missing asserts in tee test
web-platform-tests/wpt pull request #28153
Opened 2021-03-19 17:28 UTC by MattiasBuelens

In [_"ReadableStream teeing: failing to cancel the original stream should cause cancel() to reject on branches"_](https://github.com/web-platform-tests/wpt/blob/e5e5e7a10cbb968b31c51ad87ce8a3da62bb1b34/streams/readable-streams/tee.any.js#L235-L246), we error the stream and then cancel both branches. However, we don't check that those `cancel()` promises are actually rejected with the stream's error.

This PR adds those missing asserts. This also ensures that implementations don't accidentally reject these promises with an unexpected reason.

Accompanies whatwg/streams#1112.

2021-03-19 17:30 UTC, MattiasBuelens commented on streams/readable-streams/tee.any.js
> +  const theError = { name: 'You just watch yourself!' };
Apparently the error names in these tests are dialogue lines from Star Wars? No clue why, but I thought I'd stay in the theme. 😛

2021-03-19 17:54 UTC, domenic approved these changes

2021-03-19 17:55 UTC, domenic requested changes

2021-03-19 17:55 UTC, domenic commented on streams/readable-streams/tee.any.js
> +test(t => {
promise_test

2021-03-19 18:18 UTC, MattiasBuelens commented on streams/readable-streams/tee.any.js
> +test(t => {
Woops! Thanks.

2021-03-20 14:27 UTC, domenic approved these changes

2021-03-20 14:28 UTC, merged