Add referrer policy tests for loading the various subresources via a srcdoc iframe.
web-platform-tests/wpt pull request #2851
Opened 2016-04-20 04:20 UTC by bzbarsky

2016-04-20 04:24 UTC, bzbarsky commented
@kristijanburnik could you take a look, please?  I wasn't sure what the best way to add this was; whether we want more subresource types or something else.

Note that ideally we would also add tests for resources in srcdoc in srcdoc in normal document, to check that UAs walk up the srcdoc chain....

And we probably also need tests for sandboxed iframes; while that's out of the scope of what I'm trying to do here, it might affect how we approach setting this up.  Adding three more subresource types for every existing type seems a bit weird to me, but right now the "how to load" functions are just keyed off subresource type...

2016-04-20 04:25 UTC, bzbarsky commented
Oh, and the CI failures are for path length; we can sort that out once we know whether we're doing a new subresource type or not, since that will affect filenames.

2016-04-26 17:49 UTC, bzbarsky commented
@mikewest I'm told @kristijanburnik is no longer active on this stuff, so you own these tests.  Can you take a look at the above questions, please?  And update OWNERS?  ;)

2016-04-26 17:50 UTC, mikewest commented
Hooray. I own things. Yes, I'll look at these in the morning and try to remember how all of it works.

2016-05-04 06:14 UTC, bzbarsky commented
@mikewest It's been a week.  Ping?

2016-05-12 21:21 UTC, hillbrad commented
Looking at this - sorry for the delay -  there are still a number of these tests that use the CSP delivery method, which I believe is no longer current?

https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-delivery

2016-05-13 14:02 UTC, bzbarsky commented
I have no idea.  Given my experience with the similarly written mixed-content tests, there are likely all sorts of bugs in the tests themselves, even if we ignore spec changes...

2016-09-09 13:20 UTC, mikewest commented
I apologize; I didn't get back to this right away, and then it fell off my radar completely.

I think the approach is reasonable in the short term, but, as you note, adds a lot of tests. Since we should probably be doing `srcdoc` tests (and `iframe@sandbox` tests, etc) for resource types other than images, perhaps it makes sense to extend the general test framework to coalesce these new tests into the existing subresource tests without adding a few hundred new tests.

I don't think it's fair to ask you to do that refactoring after ~4 months, though, so I've uploaded a pass at it to https://github.com/w3c/web-platform-tests/tree/referrer-policy. WDYT?

2016-09-09 16:30 UTC, kristijanburnik commented
One does not necessarily need to add a lot of tests. Even a single test can
be generated by a single spec.json rule.

The generating framework allows for suppressing (excluded_tests) or
specifying explicit scenario values (i.e. other than * expansion).

It's up to you if you choose to be more general/specific or prefer
whitelisting to blacklisting. :-)

This is all documented here:
https://github.com/w3c/web-platform-tests/blob/master/referrer-policy/README.md

On Sep 9, 2016 3:20 PM, "Mike West" <notifications@github.com> wrote:

> I apologize; I didn't get back to this right away, and then it fell off my
> radar completely.
>
> I think the approach is reasonable in the short term, but, as you note,
> adds a lot of tests. Since we should probably be doing srcdoc tests (and
> iframe@sandbox tests, etc) for resource types other than images, perhaps
> it makes sense to extend the general test framework to coalesce these new
> tests into the existing subresource tests without adding a few hundred new
> tests.
>
> I don't think it's fair to ask you to do that refactoring after ~4 months,
> though, so I've uploaded a pass at it to https://github.com/w3c/web-
> platform-tests/tree/referrer-policy. WDYT?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/w3c/web-platform-tests/pull/2851#issuecomment-245910439>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHmrGawHtd6UwUCLrVw9N3xwCwWzoDm5ks5qoV0HgaJpZM4ILVdx>
> .
>

2016-09-09 19:25 UTC, bzbarsky commented
> WDYT?

I have a hard time telling whether it works or not, because I have vague memories of the test harness mutating the server state, such that you couldn't do two loads from a single test.  But maybe that was the mixed-content tests instead...  Have you tested the patch?

2016-09-13 09:54 UTC, mikewest commented
> Have you tested the patch?

I have. It works for me locally. I'll turn it into a real PR.

2018-08-16 12:48 UTC, foolip commented
This PR has been sitting without activity for over a year. @mikewest, https://github.com/web-platform-tests/wpt/pull/3700 says it addresses this PR, but there are lots of changes in this PR and only small changes in the other?

@bzbarsky, are there things in this PR that still aren't covered in master?

2018-08-20 14:13 UTC, jeisinger requested changes
lgtm with nits

2018-08-20 14:13 UTC, jeisinger commented on referrer-policy/generic/common.js
> +function loadImage(src, callback, attributes, isSrcDoc)
nit. other arguments use_this_style, so I'd change this to is_src_doc

2018-08-20 14:13 UTC, jeisinger commented on referrer-policy/generic/common.js
> +function decodeImage(url, callback, referrer_policy, isSrcDoc) {
same here

2019-07-31 14:21 UTC, bzbarsky commented
> @bzbarsky, are there things in this PR that still aren't covered in master?

@foolip, I don't know.  It's been a long time (even longer since you asked the question, I know) and at this point I'd have to go and reverse-engineer this harness yet again to figure out what's going on.

2019-07-31 15:47 UTC, foolip commented
Alright, I guess practically speaking the choice is between taking all of these tests and accepting that there's some or a lot of overlap, or throwing them away to avoid possible overlap. I don't know the existing tests or what's in this PR, so @bzbarsky whatever you prefer I can rubberstamp and merge :)

2019-07-31 16:06 UTC, bzbarsky commented
I think we should just throw out this PR at this point.  It's not clear to me that it can even be merged as-is...

2019-07-31 17:09 UTC, closed without merging

2019-07-31 17:09 UTC, foolip commented
It had merge conflicts, so it couldn't have been merged without some work. I've closed it now.