Revert "Switch to Dependabot for Python dependencies"
web-platform-tests/wpt pull request #29235
Opened 2021-06-04 21:17 UTC by foolip

Reverts web-platform-tests/wpt#29161

2021-06-04 21:18 UTC, foolip commented
Hmm, I should trim this revert and keep some of the good changes.

2021-06-07 08:43 UTC, foolip commented
I've filed https://github.com/dependabot/dependabot-core/issues/3856 about the problem we're having. @gsnedders @jgraham do you think we should live with the multiple PRs, or go back to pyup?

2021-06-07 11:18 UTC, jgraham requested changes

2021-06-07 11:18 UTC, jgraham commented on .github/dependabot.yml
> -  directory: tools/wptrunner/
I think we should just remove this rule, but otherwise not revert the patch; it seems dependabot works recursively anyway.

2021-06-07 12:18 UTC, gsnedders commented
> I've filed [dependabot/dependabot-core#3856](https://github.com/dependabot/dependabot-core/issues/3856) about the problem we're having. @gsnedders @jgraham do you think we should live with the multiple PRs, or go back to pyup?

How many things do we have in multiple files?

2021-06-07 13:09 UTC, foolip commented
> How many things do we have in multiple files?

`find * -name 'requirements*.txt' | grep -v third_party | xargs cat | grep == | cut -d= -f1 | sort | uniq -c | sort -n` says it's mozprocess, selenium, requests, html5lib, six, psutil and mozinfo.

2021-06-07 13:13 UTC, foolip commented
I've sent https://github.com/web-platform-tests/wpt/pull/29257.

2021-06-07 13:13 UTC, closed without merging