[css-ruby] Created 2 containing block related tests and 1 reference file
web-platform-tests/wpt pull request #29482
Opened 2021-06-24 18:06 UTC by TalbotG

ruby-abs-pos-001.html
ruby-floats-001.html
reference/ruby-floats-001-ref.html

At my website, the files are:

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/ruby-abs-pos-001.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/ruby-floats-001.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/reference/ruby-floats-001-ref.html

These 2 tests are checking that the containing block for internal ruby boxes (ruby base units and ruby text units) is the containing block of its own ruby container. This is true for absolutely positioned or floating ruby base unit boxes and for absolutely positioned or floating ruby text unit boxes.

2021-09-08 22:26 UTC, fantasai requested changes
The floats test is correct. However, I think it would benefit from some subtests of floats inside the base and annotation (in addition to floats being the base and annotation).

The abspos test... it's correct, but it's only testing that the abspos isn't trapped by the ruby. To really test the case of abspos within ruby, we'd need to check what happens when the DIV has 'position: relative' and when the ruby element itself has 'position: relative'. (But also this last case needs to be made a little clearer in the spec, I think. It should behave as for inlines as specced in https://www.w3.org/TR/CSS2/visudet.html#containing-block-details probably.)

2022-03-31 19:20 UTC, TalbotG commented
> It should behave as for inlines as specced in https://www.w3.org/TR/CSS2/visudet.html#containing-block-details probably.)

"
If the box has position: absolute:
The containing block is established by the nearest ancestor box that establishes an absolute positioning containing block, in the following way:
(...)
If the ancestor is an inline box,
the containing block is formed by the block-start and inline-start content edges of the first box fragment of the ancestor, and the block-end and inline-end content edges of the last box fragment of the ancestor.
Note: If the ancestor breaks across a line, the 'start' position might more end-ward than the 'end' position.
"
coming from
[CSS Positioned Layout 3,
§ 2.1. Containing Blocks of Positioned Boxes](https://www.w3.org/TR/css-position-3/#def-cb)

2022-04-01 22:06 UTC, TalbotG commented
ruby-abs-pos-002.html
ruby-abs-pos-003.html
reference/ruby-abs-pos-002-ref.html
reference/ruby-abs-pos-003-ref.html

At my website:

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/ruby-abs-pos-002.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/reference/ruby-abs-pos-002-ref.html


http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/ruby-abs-pos-003.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/reference/ruby-abs-pos-003-ref.html

These 2 tests cover the code scenarios where the internal ruby elements (a `<rb>` element or a `<rt>` element) are abspos-ed and where both the ruby and the DIV have 'position: relative'.

2022-06-22 22:29 UTC, fantasai commented on css/css-ruby/ruby-abs-pos-003.html
> +      right: 240px;
```suggestion
      right: 50%;
      color: orange;
```

2022-06-22 23:12 UTC, TalbotG commented
We changed the 2 tests but not the related references. Anyways... I believe the `left: 50%` and the `right: 50%` will not be adequate.

Here are my latest efforts:

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/ruby-abs-pos-002-latest.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/reference/ruby-abs-pos-002-latest-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/ruby-abs-pos-003-latest.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Ruby/reference/ruby-abs-pos-003-latest-ref.html

I will make a commit tomorrow, june 23rd 2022.

2022-08-05 13:05 UTC, TalbotG commented
> I will make a commit tomorrow, june 23rd 2022.

Somehow, I forgot about this PR but there was also an [Azure Pipelines Build issue](https://github.com/web-platform-tests/wpt/issues/34760) related. 

**I will close this PR for now and add on my to-do-list for this month (august 2022)**
- **open a new PR (distinct and separate) for the floats test as this one is ready-to-be-approved**
- **open a new PR (distinct and separate) for ruby-abs-pos-002-latest.html**
- **open a new PR (distinct and separate) for ruby-abs-pos-003-latest.html**

2022-08-05 13:05 UTC, closed without merging