Update URL tests to reject hostnames that end in numbers but are not IPv4 IPs
web-platform-tests/wpt pull request #29666
Opened 2021-07-14 21:08 UTC by MattMenke2

This pull request corresponds to the proposed URL spec changes in https://github.com/whatwg/url/pull/619

It also adds a pair of tests for cases that don't seem to be covered by existing tests (A normal IPv4 IP, and a normal IPv4 IP ending in an extra dot)

I moved some pre-existing tests around that were affected by this change, but am also happy to just leave them where they are.

2021-07-14 22:09 UTC, domenic requested changes
After implementing the proposed spec update in jsdom/whatwg-url, things mostly pass but there's a couple extra slashes.

2021-07-14 22:09 UTC, domenic commented on url/resources/urltestdata.json
> +    "origin": "http://1.2.3.4/",
```suggestion
    "origin": "http://1.2.3.4",
```

2021-07-14 22:09 UTC, domenic commented on url/resources/urltestdata.json
> +    "origin": "http://1.2.3.4/",
```suggestion
    "origin": "http://1.2.3.4",
```

2021-07-20 12:28 UTC, annevk approved these changes
This looks good to me (though @domenic probably wants to run them through whatwg-url again), but having read the change proposal I was thinking we might want to cover these scenarios as well:

* Various domains ending in ".09" and ".09." (always failure as far as I can tell)
* Domains such as "test.0." and generally more dot-at-the-end variants

2021-07-20 17:15 UTC, domenic approved these changes
Passes in modified whatwg-url so LGTM. I'll be happy to re-run the tests if you add more cases as well.

2021-07-25 22:34 UTC, MattMenke2 commented
> This looks good to me (though @domenic probably wants to run them through whatwg-url again), but having read the change proposal I was thinking we might want to cover these scenarios as well:
> 
> * Various domains ending in ".09" and ".09." (always failure as far as I can tell)
> * Domains such as "test.0." and generally more dot-at-the-end variants

I've beefed up tests a bit.  Let me know what you think.

I've run url-constructor.any.html against Chromium hacked up to (hopefully) obey the new rules, and all the new/modified cases pass - I did that before, too, just didn't run the origin tests.  This time I've run the origin tests, too, and they also look fine.

2021-07-26 06:22 UTC, annevk approved these changes
Thanks! @domenic will you confirm and merge?

2021-07-26 14:32 UTC, domenic approved these changes

2021-07-26 14:32 UTC, merged