[webdriver]: element cloned into iframe
web-platform-tests/wpt pull request #29877
Opened 2021-08-03 07:02 UTC by MoLow

Added a new test to verify webdriver can access & serialize elements transferred in between iframes
following this [bug](https://bugs.webkit.org/show_bug.cgi?id=228270)

2021-08-03 09:50 UTC, jgraham requested changes
Looks good, just a small piece of cleanup.

2021-08-03 09:50 UTC, jgraham commented on webdriver/tests/switch_to_frame/switch_webelement.py
> +    response = execute_script(session, """
You can just do `session.execute_script` instead of adding the helper.

2021-08-03 16:16 UTC, whimboo commented on webdriver/tests/switch_to_frame/switch_webelement.py
> +            iframe.contentWindow.document.body.appendChild(div);
```suggestion
    session.execute_script("""
        const iframe = document.getElementsByTagName('iframe')[0];
        const div = document.createElement('div');
        div.innerHTML = 'I am a div created in top window and appended into the iframe';
        iframe.contentWindow.document.body.appendChild(div);
```

2021-08-03 16:16 UTC, whimboo commented on webdriver/tests/switch_to_frame/switch_webelement.py
> +    assert element.text == "I am a div created in top window and appended into the iframe"
```suggestion
    assert element.text == "I am a div created in top window and appended into the iframe"

```

2021-08-05 11:32 UTC, whimboo commented
Looks fine to me. I'll leave the final  review for @jgraham including the merge. Thanks for adding this testcase!

2021-08-05 13:04 UTC, jgraham approved these changes

2021-08-05 13:04 UTC, merged

2021-08-05 13:22 UTC, MoLow commented
thanks, @jgraham - who should handle the merging of the releated WebKit issue? https://bugs.webkit.org/show_bug.cgi?id=228270

2021-08-05 13:38 UTC, whimboo commented
That's up to anyone as CC'ed on this bug. Maybe @gsnedders can help? But any disussion for that should happen on this mentioned bug.