Add tests for pagevisibility when minimized/restored
web-platform-tests/wpt pull request #31326
Opened 2021-10-20 05:56 UTC by noamr

Also added required executor infrastructure to minimize/restore the test window, implemented in webdriver+marionette.

2021-10-20 06:30 UTC, yoavweiss reviewed
Non-authoritative LGTM! Someone that knows more about WebDriver should probably take a look

2021-10-28 12:07 UTC, jgraham requested changes

2021-10-28 14:03 UTC, jgraham reviewed
Just a docs update and then this looks good.

2021-11-03 15:05 UTC, noamr commented
@jgraham anything missing? Can you give this another look? Thanks :)

2021-11-08 14:52 UTC, jgraham approved these changes

2021-11-08 15:02 UTC, merged