Fix #31685: ensures run_info gets the actual macOS version
web-platform-tests/wpt pull request #32131
Opened 2021-12-17 18:29 UTC by gsnedders

If the environment variable SYSTEM_VERSION_COMPAT is set to 1, macOS 11 and later pretends to be macOS 10.16; if this is set, we need to rerun mozinfo without it set.

2021-12-17 22:49 UTC, foolip commented
This looks sensible, but I'll have to defer to @jgraham since I don't know this code.

2021-12-18 00:37 UTC, gsnedders commented
I guess there's also the question of whether this should be the behaviour of `mozinfo`, rather than ever giving the compat version number.

2021-12-20 18:01 UTC, jgraham requested changes
I'm also happy to review a change to mozinfo if you want to land this there.

2021-12-20 18:01 UTC, jgraham commented on tools/wptrunner/wptrunner/wpttest.py
> +            os.environ["SYSTEM_VERSION_COMPAT"] = version_compat
I feel like we should unconditionally reset the environment, even if the value isn't `"1"`

2022-02-03 18:57 UTC, gsnedders commented
> I'm also happy to review a change to mozinfo if you want to land this there.

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1747030

But also this can probably be closed anyway, even if we do potentially want (somehow) to store the underlying system version too.

2022-03-10 17:00 UTC, gsnedders commented
No long matters for Azure Pipelines runs given https://github.com/web-platform-tests/wpt/pull/32664; dunno if this matters so much now. (It probably still does, for people running locally?)

2023-03-17 14:36 UTC, closed without merging