Add test to confirm calling Request constructor without `new` throws …
web-platform-tests/wpt pull request #34157
Opened 2022-05-21 17:38 UTC by JakeChampion

This adds tests which confirm that calling many constructors as ordinary functions will throw an error.

This also adds some more error testing scenarios to SharedWorker which looked like it was missing these tests.

This is similar to my other Pull-Request which adds this same test scenario to Request -> https://github.com/web-platform-tests/wpt/pull/34146

This is the part of WebIDL that is being exercised by these tests:
>If the interface is declared with a constructor operation, then the interface object can be called as a constructor to create an object that implements that interface. **Calling that interface as a function will throw an exception.**
> https://webidl.spec.whatwg.org/#interface-object

2022-05-21 22:08 UTC, domenic requested changes
We should instead add this to idlharness.js, so that it is automatically tested for all interfaces with constructors.

(Maybe it is already tested by idlharness.js, actually!)

2022-05-21 22:10 UTC, domenic commented
Basically move this outside of its containing `if` block: https://github.com/web-platform-tests/wpt/blob/b0c18e11e09bf0d47d04bec1766a5d8f4c5d636a/resources/idlharness.js#L1534-L1537

2022-05-21 22:54 UTC, JakeChampion commented
> Basically move this outside of its containing `if` block:
> 
> https://github.com/web-platform-tests/wpt/blob/b0c18e11e09bf0d47d04bec1766a5d8f4c5d636a/resources/idlharness.js#L1534-L1537

Thanks for locating where this change should happy, I'll rebase the commits tomorrow to only have the webidl harness change

2022-05-22 09:45 UTC, JakeChampion commented
@domenic I've rebased and updated the pull-request title and description :+1:

2022-05-23 16:49 UTC, domenic reviewed
Looks good with a nit

2022-05-23 16:49 UTC, domenic commented on resources/idlharness.js
> +        // "If I was not declared with a constructor operation, then throw a TypeError."
This comment should probably be removed as it no longer reflects the current spec. And, it would only apply to the part inside the `if`.

2022-05-23 20:02 UTC, domenic approved these changes

2022-06-01 16:58 UTC, domenic reviewed
Looks good with a minor fix!

2022-06-01 16:58 UTC, domenic commented on resources/idlharness.js
> +        debugger
Please remove

2022-06-01 18:23 UTC, JakeChampion commented on resources/idlharness.js
> +        debugger
removed :+1:

2022-06-01 19:06 UTC, merged