Better tests for L=0% and L=100% in LCH colour functions
web-platform-tests/wpt pull request #34363
Opened 2022-06-09 19:14 UTC by vasilisvg

In the current implementation in Safari L=0% is not always black, and L=100% is not always white. Here are two tests to test this with. In the current implementation these return a dark red and a yellow square, while they should be black and white.

2022-06-10 18:27 UTC, vasilisvg commented
I am not sure if these are the best tests for testing white and black with LCH and OKLCH. I guess the best test would be to test L=0% and L=100% over the complete spectrum. But at least the current Safari TP implementation doesn't pass these.

2022-06-13 10:34 UTC, svgeesus requested changes
Good apart from some copy-paste errors. Thanks!

2022-06-13 10:34 UTC, svgeesus commented on css/css-color/oklch-010.html
> +<link rel="help" href="https://drafts.csswg.org/css-color-4/#specifying-lab-lch">
Should be https://drafts.csswg.org/css-color-4/#specifying-oklab-oklch

2022-06-13 12:47 UTC, svgeesus approved these changes

2022-06-13 12:48 UTC, merged