Align `browsingContext.contextCreated` tests with spec
web-platform-tests/wpt pull request #34641
Opened 2022-06-29 08:12 UTC by sadym-chromium

Align `browsingContext.contextCreated` with spec: 
https://github.com/w3c/webdriver-bidi/issues/220#issuecomment-1145785349

The reason that the URL should always be about:blank is because https://w3c.github.io/webdriver-bidi/#event-browsingContext-contextCreated is invoked after step 19 in https://html.spec.whatwg.org/multipage/browsers.html#creating-a-new-browsing-context before there's been any navigation.

2022-06-29 08:12 UTC, sadym-chromium commented
@whimboo It looks like you were working on the test. WDYT?

2022-06-29 21:43 UTC, juliandescottes approved these changes
Thanks I think this makes sense. Note that both tests will probably start failing on Firefox after you land this.

To make sure we are on the same page, the main motivation to change that is that `children_info[n]["url"]` might already point to the final URL of the new context, whereas live events are always "about:blank", which makes the test flaky?

cc @whimboo or @jgraham: we implemented the exact opposite in Firefox: https://searchfox.org/mozilla-central/rev/2946e9b450cb35afaf8dad927a8d187975dcd74d/remote/webdriver-bidi/modules/root/browsingContext.jsm#517-520

But I think we all agree that based on the current spec and as highlighted in https://github.com/w3c/webdriver-bidi/issues/220#issuecomment-1145785349 the event should be emitted before any navigation happened, and the document should be on about:blank. 

I'm enclined to merge this and address the fallout for Firefox on our side, but I'd still prefer to get feedback from either @whimboo or @jgraham before we merge.

2022-06-29 21:43 UTC, juliandescottes commented on webdriver/tests/bidi/browsing_context/context_created/context_created.py
> +    # https://github.com/w3c/webdriver-bidi/issues/220#issuecomment-1145785349
According to our conversation during the last meeting, only "live" contextCreated events will be created with "about:blank". Cached events should be emitted with the current URL. 

```suggestion
    # Note: Live `browsingContext.contextCreated` events are always created with "about:blank":
    # https://github.com/w3c/webdriver-bidi/issues/220#issuecomment-1145785349
```

2022-06-30 05:35 UTC, whimboo commented
I think that we should get a consensus in how the BiDi spec should actually look like. If we feel that we should report `about:blank`, which seems still inappropriate, the change would be fine. But AFAIR we discussed this topic in some meeting and agreed on that the final URL should be reported. Maybe we just missed to update the BiDi spec accordingly?

2022-06-30 05:37 UTC, whimboo commented
I just remembered that we had this discussion already in https://github.com/w3c/webdriver-bidi/issues/173 but didn't actually updated the spec. So I would propose that we reopen this issue.

2022-06-30 05:40 UTC, whimboo requested changes
Setting to Request changes because of unresolved BiDi spec issue.

2022-06-30 06:55 UTC, juliandescottes commented
Thanks for reopening the spec issue. In my mind we implicitly agreed on about:blank being the URL for live events, but it would probably be worth calling it out in the spec if that's the case.

2022-07-04 09:17 UTC, whimboo approved these changes
Discussed that internally again and as @juliandescottes already mentioned earlier lets get the change landed and we will fix our implementation.

As it looks like CDP also sends out `target.targetCreated` events with `about:blank` so that we are in sync here.

Just a little note and then it's ready to get merged. Thanks!

2022-07-04 09:17 UTC, whimboo commented on webdriver/tests/bidi/browsing_context/context_created/context_created.py
> +    # https://github.com/w3c/webdriver-bidi/issues/220#issuecomment-1145785349
I don't think that we have to explicitly refer to the GitHub issue here. I would be fine with the following:

```suggestion
    # Note: Live events are always created with "about:blank":
```

2022-07-04 09:27 UTC, merged

2022-07-05 07:43 UTC, sadym-chromium commented
thanks for merging this!