Add CSS values test for mixed units in calc & media query
web-platform-tests/wpt pull request #34865
Opened 2022-07-17 11:32 UTC by muan

This is a test for a bug in Chrome [as reported](https://bugs.chromium.org/p/chromium/issues/detail?id=843584).

This works in Firefox and Safari.

|Chrome|Firefox|Safari|
|-|-|-|
|![Chrome: an orange bar is shown](https://user-images.githubusercontent.com/1153134/179395629-5cf3c023-6866-4c46-b45d-2047aa3d9014.png)|![Firefox: a blue bar is shown](https://user-images.githubusercontent.com/1153134/179395623-dd72661c-8337-4e51-8ec9-49bf5c7d0cf9.png)|![Safari: a blue bar is shown](https://user-images.githubusercontent.com/1153134/179395616-dccf2d44-7489-4bf8-9a65-3e59af03085f.png)|

2022-07-18 12:57 UTC, dbaron requested changes
I think it should be possible to make this test quite a bit stronger; see below.

2022-07-18 12:57 UTC, dbaron commented on css/css-values/calc-mixed-units.html
> +<html lang="en">
It's probably better to test in standards mode (i.e., with `<!DOCTYPE HTML>`) unless there's a good reason to test in quirks mode.

2022-07-18 12:57 UTC, dbaron commented on css/css-values/calc-mixed-units.html
> +      @media (min-width: calc(100vw - 1em)) {
I think you should be able to come up with a much stricter test here.  If you put a test inside an iframe with a known size, and assume the default `16px` font size, you should be able to test queries for `width` and `height` exactly without using either `min-` or `max-`.  A few of those (different combinations of `vw`, `em`, and `px`, at least) would seem to be a somewhat comprehensive test for "calc-mixed-units", whereas passing this test alone doesn't ensure very much.

2022-07-18 14:57 UTC, muan commented
@dbaron Thanks for the review. I've updated the test to include a couple unit pairings, and there are now test failures around `vh` in Safari as well.

<img width="1437" alt="Chrome with 6 failed assertions, Firefox with 0 failed assertions, Safari with 3 failed assertions" src="https://user-images.githubusercontent.com/1153134/179539334-529cf6ce-ab53-4763-b752-cd3226af1f4e.png">

2022-07-18 16:27 UTC, dbaron commented on css/css-values/calc-mixed-units.html
> +    <title>test calc with mixed units</title>
The title should probably mention that media queries are involved.

2022-07-18 16:28 UTC, dbaron approved these changes
These look great.  I just noticed (oops, I hit the "Add Single Comment" button instead of the "Start Review" button) that the test doesn't mention media queries at all, though, which it probably should, at least in the title.

I haven't yet looked at why some of the checks are failing...

2022-07-19 06:35 UTC, muan commented
Thanks again! I edited the title and renamed the file so it goes with the rest of `calc-in-media-queries-*.html`.

2022-07-19 12:30 UTC, dbaron approved these changes

2022-07-19 12:36 UTC, merged