Update css/css-flexbox/abspos/flex-abspos-staticpos-align-content test expectations
web-platform-tests/wpt pull request #35426
Opened 2022-08-10 21:29 UTC by rreno-apple

An absolutely positioned child of a multi-line flex container with "align-content" set
to either "stretch" or "normal" (which are equivalent) should fall back to
"align-content: flex-start" when the available space in the flex container is negative.

This updates relevant test expectations to check for that behavior.

See discussion in #35420 

This will cause new test failures in Blink, Gecko, and WebKit.

2022-08-10 22:58 UTC, dholbert requested changes
This looks good to me, except for one change that I think was left out by accident - see inline nit for the -008 test.

2022-08-10 22:58 UTC, dholbert commented on css/css-flexbox/abspos/flex-abspos-staticpos-align-content-008.html
> +         "align-content: flex-start". */
For this test, it looks like this commit is updating the comment but not the test expectation.

This one needs a test expectation update just like the others.  (The `small` `normal`/`stretch` cases should get `data-offset-x="-2"` to match `flex-start`, I think?)

2022-08-10 23:34 UTC, dholbert commented
> This looks good to me, except for one change that I think was left out by accident - see inline nit for the -008 test.

Hmm, as noted in https://github.com/web-platform-tests/wpt/issues/35420#issuecomment-1211401820 , I also worry that this might imply changes to neighboring `align-self` tests that are currently interoperable, and those test changes end up requiring behavior-changes that involve webcompat risk.

2022-08-11 00:54 UTC, rreno-apple commented
Closing this given the webcompat issue and the unresolved conflicts between css-flexbox and css-positioning.

2022-08-11 00:54 UTC, closed without merging