Add two new tests to make sure padding is correctly added to flex items
web-platform-tests/wpt pull request #35714
Opened 2022-08-30 20:55 UTC by sgill26

There was a WebKit bug which was causing border and padding to be incorrectly
added when the size of a flex item was computed through the transferred
constraints. These two tests check that the sizes of these boxes are computed
correctly in both the content-box and border-box cases.

https://bugs.webkit.org/show_bug.cgi?id=243887

2022-08-31 13:55 UTC, rwlbuis requested changes

2022-08-31 13:55 UTC, rwlbuis commented on css/css-flexbox/flex-item-transferred-sizes-padding-content-sizing.html
> +
please remove empty lines.

2022-08-31 13:55 UTC, rwlbuis commented on css/css-flexbox/flex-item-transferred-sizes-padding-border-sizing.html
> +    <div class="flexContainer">
I think it would be nice to have a comment here explaining what the expectation is for the flex item.

2022-08-31 13:55 UTC, rwlbuis commented on css/css-flexbox/flex-item-transferred-sizes-padding-content-sizing.html
> +    <div class="flexContainer">
Ditto.

2022-08-31 15:35 UTC, sgill26 commented on css/css-flexbox/flex-item-transferred-sizes-padding-content-sizing.html
> +    <div class="flexContainer">
Should be fixed!

2022-09-02 21:06 UTC, rwlbuis approved these changes
LGTM.

2022-09-07 19:23 UTC, merged

2022-09-12 22:34 UTC, davidsgrogan commented
These tests fail on all engines because they are set to match ref-filled-green-100px-square.xht but don't have the text from that file. <p>Test passes if there is a filled green square and <strong>no red</strong>.</p>

2022-09-13 04:25 UTC, sgill26 commented
> These tests fail on all engines because they are set to match ref-filled-green-100px-square.xht but don't have the text from that file.
> 
> Test passes if there is a filled green square and **no red**.
> 
> Please fix.

I believe these should now be fixed in https://github.com/web-platform-tests/wpt/pull/35872 but please let me know if you see otherwise!