CORE-AAM: update AXAPI aria-keyshortcuts mapping
web-platform-tests/wpt pull request #36082
Opened 2022-09-26 20:35 UTC by spectranaut

2022-10-18 17:11 UTC, michael-n-cooper approved these changes

2022-11-28 18:15 UTC, cookiecrook reviewed
Was this AX API proposal discussed with any of the platform API owners at Apple? Asking because I don't recall this pattern being discussed in the WG or used anywhere else on the OS.

2022-11-28 18:40 UTC, cookiecrook requested changes

2022-11-28 18:40 UTC, cookiecrook commented on core-aam/aria-keyshortcuts-manual.html
> +               ]
```suggestion
               [
                  "property",
                  "AXCustomContent",
                  "contains",
                  "{ label: \"shortcut\", value: \"Shift+Space\" }"
               ]
```
Need to verify, but more likely this.

2022-11-28 18:41 UTC, cookiecrook commented on core-aam/aria-keyshortcuts-manual.html
> +               ]
Note: Don't commit that diff yet, pls. Thx.

2022-11-28 19:06 UTC, cookiecrook approved these changes

2023-05-16 04:22 UTC, merged