[wptrunner] Allow expectation inheritance from `__dir__.ini`
web-platform-tests/wpt pull request #37037
Opened 2022-11-19 00:41 UTC by jonathan-j-lee

[1] seems to imply a test without per-test metadata can inherit the `expected` key of an ancestor `__dir__.ini`, but this does not actually work currently. This change applies the metadata search the other properties use to `expected` and `known_intermittent`. Special care was taken to ensure `expected` and `known_intermittent` are retrieved from the same key-value node.

One use case for a directory-wide expectation is to suppress failures that share a common cause (e.g., flag-enabled functionality). This avoids the need to create per-test metadata files with repeated contents that are not ergonomic to update.

[1]: https://web-platform-tests.org/tools/wptrunner/docs/expectation.html#directory-metadata

2022-11-19 02:33 UTC, jonathan-j-lee commented
Unrelated CI failure dealt with in #37038.

@jgraham Any (possibly historical) reason why `Test.{expected,known_intermittent}` does not use `itermeta(...)` currently?

cc @WeizhongX

2022-11-22 11:26 UTC, jgraham reviewed
I think this is probably fine. I don't recall why we didn't previously inherit these, but it makes sense in principle (although I'd be a bit wary of relying on it too much, since it does make it harder to figure out what's going on).

2022-11-22 11:26 UTC, jgraham approved these changes

2022-11-22 13:50 UTC, jgraham requested changes
Argh, I just saw your other PR and remembered what the problem is.

We absoutely cannot inherit expectations from tests into subtests. They don't even use the same value space (for testharness tests the test itself can't `PASS`, but the subtest can, meanwhile subtests can't be `OK`).

2023-09-14 22:59 UTC, closed without merging