Update and add tests for navigation during unload
web-platform-tests/wpt pull request #3732
Opened 2016-09-15 17:22 UTC by domenic

This reflects the recent change in https://github.com/whatwg/html/pull/1737 which aligns with Edge, Safari, and (recently) Chrome by disallowing *all* navigations during unload, not just cross-origin ones.

2017-02-09 09:36 UTC, annevk requested changes
Looks okay overall. Bit unsure about the MANIFEST changes since I don't know what that thing is for.

2017-02-09 09:36 UTC, annevk commented on html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-form-submit.html
> +window.onload = function() {
This should be wrapped in test.step_func.

2017-02-09 09:36 UTC, annevk commented on html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-same-origin-fragment.html
> +window.onload = function() {
Same here.

2017-02-09 09:36 UTC, annevk commented on html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-same-origin-fragment.html
> +    i.contentWindow.onunload = function() {
And here.

2017-02-09 09:44 UTC, Ms2ger commented
That manifest hasn't done anything in a long time.

2017-02-09 09:46 UTC, annevk commented
Is it best to just remove it then?

(Also, what are the guidelines for support resources versus actual tests? @gsnedders this might be a thing to fix.)

2017-02-09 12:03 UTC, gsnedders commented
(@annevk you mean where to put them?)

2017-02-09 12:05 UTC, annevk commented
@gsnedders yeah, make it clear how to structure the various resources involved in more complicated tests. (And maybe also have documentation on common resources somewhere so that we don't end up duplicating those throughout forever.)

2017-02-09 18:40 UTC, w3c-bots commented
# Chrome (unstable channel) #
Testing web-platform-tests at revision e3ec4db26d832901d98deaf54017d992d7909f1c
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/3732/html/browsers/browsing-the-web/navigating-across-documents/navigation_unload_same_origin.html">/html/browsers/browsing-the-web/navigating-across-documents/navigation_unload_same_origin.html</a></summary>


|                       Subtest                        | Results |
|------------------------------------------------------|---------|
|                                                      | OK      |
| `Same-origin navigation started from unload handler` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/3732/html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-form-submit.html">/html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-form-submit.html</a></summary>


|                                    Subtest                                    | Results |
|-------------------------------------------------------------------------------|---------|
|                                                                               | OK      |
| `Tests that navigation during an unload caused by a form submit does nothing` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/3732/html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-same-origin-fragment.html">/html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-same-origin-fragment.html</a></summary>


|                                            Subtest                                             | Results |
|------------------------------------------------------------------------------------------------|---------|
|                                                                                                | OK      |
| `Tests that a fragment navigation in the unload handler will not block the initial navigation` | PASS    |

</details>

2017-02-09 18:40 UTC, w3c-bots commented
# Firefox (nightly channel) #
Testing web-platform-tests at revision e3ec4db26d832901d98deaf54017d992d7909f1c
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/3732/html/browsers/browsing-the-web/navigating-across-documents/navigation_unload_same_origin.html">/html/browsers/browsing-the-web/navigating-across-documents/navigation_unload_same_origin.html</a></summary>


|                       Subtest                        | Results |
|------------------------------------------------------|---------|
|                                                      | OK      |
| `Same-origin navigation started from unload handler` | FAIL    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/3732/html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-form-submit.html">/html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-form-submit.html</a></summary>


|                                    Subtest                                    | Results |
|-------------------------------------------------------------------------------|---------|
|                                                                               | OK      |
| `Tests that navigation during an unload caused by a form submit does nothing` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/3732/html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-same-origin-fragment.html">/html/browsers/browsing-the-web/navigating-across-documents/navigation-unload-same-origin-fragment.html</a></summary>


|                                            Subtest                                             | Results |
|------------------------------------------------------------------------------------------------|---------|
|                                                                                                | OK      |
| `Tests that a fragment navigation in the unload handler will not block the initial navigation` | FAIL    |

</details>

2017-02-10 08:04 UTC, annevk approved these changes

2017-02-10 08:05 UTC, merged