Readme change
web-platform-tests/wpt pull request #3824
Opened 2016-09-26 16:33 UTC by thejohnjansen

Adding a list of chapters to help track tests as they either migrate from old-tests, or if we create new tests. Putting this in 'old-tests' because that seems like a good spot to start when creating tests.

2016-09-27 05:49 UTC, sideshowbarker commented
Shouldn’t this change be made to the https://github.com/w3c/web-platform-tests/blob/master/webdriver/README.md file instead? Otherwise, why we do still have webdriver tests in the `oldtests` directory? Is there a plan to move them to the top-level `webdriver` directory eventually?

2016-09-27 12:39 UTC, andreastt commented
The intention is to use the tests in _/old-tests_ for inspiration. This change should go in _/webdriver/README.md_ as you say.

2016-09-27 14:59 UTC, thejohnjansen commented
Updated to put this change into the webdriver directory instead of the old-tests directory.

2016-09-27 15:01 UTC, andreastt commented
Please address code review comments and squash.

2016-09-27 15:01 UTC, andreastt requested changes

2016-09-27 15:01 UTC, andreastt commented on webdriver/README.md
> +## How to run the tests
This whole section is wrong.

2016-09-27 15:01 UTC, andreastt commented on webdriver/README.md
> +## Updating configuration
This should also be removed.

2016-09-27 15:01 UTC, andreastt commented on webdriver/README.md
> +## How to write tests
This is also outdated.

2016-09-27 15:01 UTC, andreastt commented on old-tests/webdriver/README.md
> +To run a specific test file you can just run `python test_file.py`
Please revert changes to the file in old-tests.

2016-09-27 15:25 UTC, thejohnjansen commented on webdriver/README.md
> +## Updating configuration
Fixed

2016-09-27 15:25 UTC, thejohnjansen commented on webdriver/README.md
> +## How to write tests
Fixed

2016-09-27 15:25 UTC, thejohnjansen commented on old-tests/webdriver/README.md
> +To run a specific test file you can just run `python test_file.py`
Done, but for some reason the final line still shows as different. I ran the 'rich diff' and it said there was nothing to show. I'm not sure how to fix that.

2016-09-27 15:26 UTC, thejohnjansen commented on webdriver/README.md
> +## How to run the tests
I didn't write that part, it was already there. Do you want me to remove it for this PR?

2016-09-27 19:12 UTC, andreastt commented on old-tests/webdriver/README.md
> +   test_navigate_and_return_title(self):`
This should not change

2016-09-28 17:36 UTC, thejohnjansen commented on old-tests/webdriver/README.md
> +To run a specific test file you can just run `python test_file.py`
SWEET! Fixed. Thanks for that.

2016-09-28 17:36 UTC, thejohnjansen commented on old-tests/webdriver/README.md
> +   test_navigate_and_return_title(self):`
Fixed

2016-09-28 17:44 UTC, andreastt approved these changes

2016-09-28 17:46 UTC, merged