Move some tests from toascii.json to urltestdata.json
web-platform-tests/wpt pull request #38813
Opened 2023-03-04 07:59 UTC by domenic

These were introduced in e9a106175a02a192a7239f42a94235fbe0f0c7a3. However, these are not tests of the Unicode ToASCII algorithm. They are tests of the extra step introduced in https://github.com/whatwg/url/commit/cceb4356cca233b6dfdaabd888263157b2204e44 to the URL Standard.

Keep toascii.json focused on testing the ToASCII algorithm, so that software which implements it can use that file.

/cc @rmisev

2023-03-04 09:18 UTC, rmisev commented
I agree with moving these tests from `toascii.json`, but in WPT they are also used to test `host` and `hostname` setters.
So maybe add them to the `setters_tests.json` as well?

2023-03-05 15:22 UTC, rmisev commented
Now an idea came to mind: I think even better to move these tests to a new file, say `host_parser_tests.json` and use it in WPT the same way as `toascii.json`. This might be useful for testing the future [URLHost class](https://github.com/whatwg/url/pull/288).
What do you think?

/cc @annevk

2023-03-06 00:59 UTC, domenic commented
I think that might be reasonable, but I'm quickly reaching the limit of the extra effort I'm willing to put in here myself. I'm just trying to correct a bug so that my ToASCII library can be tested properly...

2023-03-06 08:34 UTC, rmisev commented on url/resources/urltestdata.json
> +    "input": "https://\u00AD/",
Add required `base:` key / value.

2023-03-06 08:43 UTC, rmisev requested changes
Overall OK, you just skipped the required `base:` parameter in the last three tests in the `urltestdata.json` file.

2023-03-07 16:39 UTC, rmisev approved these changes

2023-03-07 17:58 UTC, annevk approved these changes

2023-03-07 17:59 UTC, merged