Add tRNS PNG test
web-platform-tests/wpt pull request #38906
Opened 2023-03-09 14:13 UTC by ProgramMax

The PNG spec Third Edition clarified that high bits of a tRNS chunk should be ignored on a lower bit depth image. Previous editions were unclear, which caused divergent behavior.

This commits adds a PNG image which contains a tRNS chunk with non-zero values in its high bits. This commit also adds a test to verify these high bits are ignored.

2023-03-09 14:16 UTC, ProgramMax commented
I would add @svgeesus as a reviewer but I can't seem to.

This should land after https://github.com/web-platform-tests/wpt/pull/37187 because that other pull request adds the META.yml file.

This test is the result of https://github.com/w3c/PNG-spec/issues/29 . The issue at hand is PNG stores tRNS colors as 16-bit-per-channel, even when the image is 8-bit. In that case, the high bits of each color channel should be ignored. Firefox will treat the image as if it contains an error if those high bits aren't zero. This likely came from poor wording in older versions of the PNG spec. But since we're improving that wording, we should also add a test to enforce it.

2023-03-09 16:48 UTC, svgeesus requested changes

2023-03-09 16:48 UTC, svgeesus commented on png/trns-chunk.html
> +<title>PNG test: cICP chunk</title>
Please update the title :)

2023-03-09 16:48 UTC, svgeesus commented on png/trns-chunk.html
> +<title>PNG test: cICP chunk</title>
Add 
```
<link rel="help" href="https://w3c.github.io/PNG-spec/#11tRNS">
```

2023-03-09 16:48 UTC, svgeesus commented on png/trns-chunk.html
> +img.src = "/images/trns.png";
Should that be a relative link?

2023-03-09 17:15 UTC, ProgramMax commented on png/trns-chunk.html
> +<title>PNG test: cICP chunk</title>
Done.

2023-03-09 17:15 UTC, ProgramMax commented on png/trns-chunk.html
> +img.src = "/images/trns.png";
Done.

2023-03-10 14:12 UTC, svgeesus approved these changes

2023-03-10 14:12 UTC, merged