[css-color] Scale down values in oklab/oklch and clamp L > 100% for lab/lch/oklab/oklch
web-platform-tests/wpt pull request #39042
Opened 2023-03-16 21:38 UTC by danburzo

Fixes #39000. 

The PR includes the following changes:

- `oklab()`: divide `l`, `a`, and `b` by 100
- `oklch()`: divide `l`, `c` by 100
- `lab()` / `lch()` / `oklab()` / `oklch()`: clamp `l` to `[0-100]`.   

Changing these across several hundred tests has been quite hypnotic, so any extra pairs of eyes are greatly appreciated!

2023-03-20 19:48 UTC, svgeesus requested changes
Spotted one error otherwise looks good!

2023-03-20 19:48 UTC, svgeesus commented on css/css-color/parsing/color-computed-lab.html
> +test_computed_value("color", "oklab(calc(-0.5 * 3) calc(0.5 + 1) calc(-1.5) / calc(-0.5 * 2))", "oklab(0 1.5 -1.5 / 0)");
lightness should be 0 not 1.5, right? (-0.5 * 3) is -1.5 which clamps to 0

2023-03-20 19:49 UTC, svgeesus commented on css/css-color/parsing/color-computed-lab.html
> +test_computed_value("color", "oklab(calc(-0.5 * 3) calc(0.5 + 1) calc(-1.5) / calc(-0.5 * 2))", "oklab(0 1.5 -1.5 / 0)");
Never mind, I can't read apparently

2023-03-20 19:49 UTC, svgeesus approved these changes

2023-03-20 19:50 UTC, merged

2023-03-21 12:46 UTC, danburzo commented
Awesome, thanks for taking the time to review this, @svgeesus!