Enable WebTransport over H3 server for Firefox nightly
web-platform-tests/wpt pull request #39322
Opened 2023-04-01 04:47 UTC by bashi

Preparation to fix #39309.

2023-04-04 12:53 UTC, gsnedders reviewed
This looks good to me, but given it changes the default status for Firefox @jgraham should probably review this.

2023-04-04 14:21 UTC, jan-ivar approved these changes

2023-04-05 14:31 UTC, jesup commented
This looks good to me (I've been running wpts locally in Mozilla's CI).   jgraham is out, but he knows that we're enabling this; I've been working with him.  Let's merge it

2023-04-12 15:30 UTC, jgraham requested changes
It has also been pointed out to me by @jesup that we have `ini` files checked in with the tests that are being used to disable all the actual tests in !chrome. Although that works it's quite unexpected; we at least need to update those files, but we also need to consider if we can just remove the ini files and let the tests fail in browsers without the webtransport server.

2023-04-12 15:30 UTC, jgraham commented on tools/wpt/run.py
> +        if kwargs["browser_channel"] == "nightly" and kwargs["enable_webtransport_h3"] is None:
Putting this in the frontend seems a bit strange; I guess ideally we want this to be a property of the product. But that's a slightly bigger refactor, so I guess it's fine to do this for now.

2023-04-12 15:51 UTC, jan-ivar commented
> ... let the tests fail in browsers without the webtransport server.

Why not just run the server for these tests regardless of browser?

2023-04-13 01:47 UTC, bashi commented
At the time the WebTransport server was introduced, test infra for browsers other than chrome weren't ready to run the server, mostly due to aioquic dependency (IIUC). I'm not sure the current situation but probably we can run the server on all platforms?

2023-04-14 10:43 UTC, jgraham commented
Yeah, the binary dependency is what makes this tricky; in Gecko CI we've had to add aioquic to our PyPI mirror for this to work, and it's still pretty fragile if we update the version.

2023-04-14 13:33 UTC, jgraham approved these changes

2023-04-14 13:34 UTC, merged