Workers and data URLs
web-platform-tests/wpt pull request #3943
Opened 2016-10-10 10:17 UTC by annevk

Provide basic tests for https://github.com/whatwg/html/pull/1782.

2016-10-12 09:27 UTC, foolip requested changes
I've tested to run these:
https://w3c-test.org/submissions/3943/workers/data-url.html
https://w3c-test.org/submissions/3943/workers/data-url-shared.html

Only Firefox passes, the rest fail with a harness error.

2016-10-12 09:27 UTC, foolip commented on workers/data-url-shared.html
> +var worker = new SharedWorker("data:,onconnect = (e) => { fetch('/').then(() => e.ports[0].postMessage('fail'), () => e.ports[0].postMessage('pass')) }") // not same-origin
https://fetch.spec.whatwg.org/ says that HTML "prevents creation of shared workers from such URLs." but that doesn't seem to match https://html.spec.whatwg.org/#dom-sharedworker

If they shouldn't be created at all, then presumably the constructor should throw?

2016-10-12 09:27 UTC, foolip commented on workers/data-url.html
> +  assert_equals(e.data, "pass")
testharness.js does implicitly create an `async_test` here, but for some reason a failure is still a harness error. @jgraham, how do these implicitly created tests work?

2016-10-12 09:33 UTC, annevk commented on workers/data-url-shared.html
> +var worker = new SharedWorker("data:,onconnect = (e) => { fetch('/').then(() => e.ports[0].postMessage('fail'), () => e.ports[0].postMessage('pass')) }") // not same-origin
Fetch needs to be updated, since we decided to change how shared workers should work.

2016-10-12 09:39 UTC, annevk commented on workers/data-url-shared.html
> +var worker = new SharedWorker("data:,onconnect = (e) => { fetch('/').then(() => e.ports[0].postMessage('fail'), () => e.ports[0].postMessage('pass')) }") // not same-origin
I updated Fetch.

2016-10-12 11:39 UTC, foolip approved these changes

2016-10-12 11:41 UTC, foolip commented
Other now fail in the right way, merging.

2016-10-12 11:44 UTC, merged

2016-10-17 08:06 UTC, zcorpan commented
These already tested data: URLs

workers/constructors/SharedWorker/same-origin.html
workers/constructors/Worker/same-origin.htm

2016-10-17 08:47 UTC, annevk commented
Hmm, I remember running a grep looking for "data:". Weird. But those tests are not testing the origin of the worker itself, so I guess it was still useful for me to write those tests.