Basic <script> and data URL test
web-platform-tests/wpt pull request #3945
Opened 2016-10-10 13:02 UTC by annevk

See https://github.com/whatwg/html/pull/1782 for pointers to more
context.

2016-10-10 13:03 UTC, annevk commented
I can't quite get the `setup()` thing to work. Anyone any idea what I did wrong?

2016-10-10 13:55 UTC, annevk commented
Should be all good now.

2016-10-12 09:42 UTC, foolip requested changes

2016-10-12 09:42 UTC, foolip commented on html/semantics/scripting-1/the-script-element/data-url.html
> +  t.step(() => {
`async_test(t => { ... })` saves a line and one need not look to see if `t` is referenced elsewhere.

2016-10-12 09:42 UTC, foolip commented on html/semantics/scripting-1/the-script-element/data-url.html
> +      if(counter == 3) {
More whitespace

2016-10-12 09:58 UTC, foolip approved these changes

2016-10-12 10:14 UTC, foolip commented
Hmm, https://w3c-test.org/submissions/3945/html/semantics/scripting-1/the-script-element/data-url.html actually fails on all but Firefox.

2016-10-12 10:26 UTC, annevk commented
Yeah, only Fx treats it as same-origin like it should.

2016-10-12 10:36 UTC, foolip commented
But the failures are because of other differences first. Edge only gives 4 arguments on the `onerror` callback, while Chrome and Safari make the 5th argument an object instead of number.

The spec is at https://html.spec.whatwg.org/#the-event-handler-processing-algorithm and Edge is wrong about the number of arguments, not sure about the type though, that probably affects `window.addEventListener('error', ...)` too.

2016-10-12 10:39 UTC, annevk commented
Pretty sure that's because Chrome and Safari treat these as cross-origin and therefore create the Error object with "Script error." as a message.

2016-10-12 10:40 UTC, youennf commented
I would think so as well.
WebKit might change that behavior soon so these tests are most welcome

2016-10-12 11:22 UTC, foolip commented
Ah, yes, the "Script error." check fails if those before it are commented out. Will change the order to make it obvious that it's a real failure to someone investigating the failure.

2016-10-12 11:43 UTC, foolip commented
@mikewest if you want to check this after the fact that'd be nice, but I've looked at it enough to be comfortable merging now.

2016-10-12 11:43 UTC, merged