Add test for CustomElementRegistry getName interface
web-platform-tests/wpt pull request #39640
Opened 2023-04-21 11:43 UTC by keithamus

In CustomElements v0 you could use the `.name` field to get the defined tag name, but CustomElements v1 does not offer such a field. `localName` can be used within an instance but this prohibits use in, for example, static methods.

This was discussed in the WCCG F2F, tracked in
https://github.com/WICG/webcomponents/issues/566. The conclusion of the F2F was to write up a spec change and WPT tests.

2023-04-21 22:15 UTC, rniwa commented on custom-elements/CustomElementRegistry.html
> +
An extra blank line.

2023-04-21 22:34 UTC, rniwa commented on custom-elements/CustomElementRegistry.html
> +    customElements.define('existing-custom-element', ExistingCustomElement);
This will throw because 'existing-custom-element' had already been defined in line 623. Use another name like 'other-custom-element'

2023-04-21 22:36 UTC, rniwa commented on custom-elements/CustomElementRegistry.html
> +test(function () {
We should probably add these test cases as well:

test(function () {
  assert_equals(customElements.getName(undefined), undefined);
}, 'customElements.getName must return undefined when called with undefined');

test(function () {
  assert_equals(customElements.getName(null), undefined);
}, 'customElements.getName must return undefined when called with null');

test(function () {
  assert_equals(customElements.getName(''), undefined);
}, 'customElements.getName must return undefined when called with a string');

2023-04-21 22:37 UTC, rniwa commented on custom-elements/CustomElementRegistry.html
> +    assert_equals(customElements.get(ExistingCustomElement), 'existing-custom-element');
This should call getName, not get.

2023-04-21 22:37 UTC, rniwa requested changes
Please address above comments.

2023-04-25 17:54 UTC, rniwa approved these changes

2023-06-15 20:38 UTC, keithamus commented
Closed by https://github.com/web-platform-tests/wpt/pull/39709

2023-06-15 20:38 UTC, closed without merging