Implement reftest variants
web-platform-tests/wpt pull request #40352
Opened 2023-06-01 23:37 UTC by dlrobertson

Support variants for reftests via a variant meta tag.

Related to: https://github.com/web-platform-tests/rfcs/pull/149

2023-07-06 13:59 UTC, dlrobertson commented
No longer WIP now that https://github.com/web-platform-tests/rfcs/pull/149 has been merged.

2023-07-11 09:37 UTC, jgraham requested changes

2023-07-11 09:37 UTC, jgraham commented on tools/manifest/sourcefile.py
> +                for variant in self.test_variants:
I don't think we ever hit the `else` clause, because `test_variants` seems to always return at least the empty variant.

2023-07-11 13:38 UTC, dlrobertson reviewed
Updated and added a unit test

2023-07-21 10:02 UTC, jgraham approved these changes

2023-07-21 10:03 UTC, merged