miscellaneous lint and clean-up changes to webdriver/tests/support
web-platform-tests/wpt pull request #40470
Opened 2023-06-09 10:30 UTC by thiagowfx

2023-06-09 10:58 UTC, sadym-chromium approved these changes

2023-06-12 15:08 UTC, whimboo requested changes

2023-06-12 15:08 UTC, whimboo commented on webdriver/tests/bidi/session/subscribe/invalid.py
> -        response = await send_blocking_command("session.subscribe", {})
Why do you assign the result to a variable that is not used? Same applies to other tests.

2023-06-12 15:38 UTC, whimboo commented
@thiagowfx is that PR ready for review or are you still working on it? If it's the latter then please mark the PR as draft. Thanks.

2023-06-12 15:40 UTC, thiagowfx commented
@whimboo it's done! I just added two small additional changes just now, but do not plan do add anything else.

2023-06-13 11:47 UTC, nechaev-chromium commented
How can I find what tests are expected to fail for Chrome? For instance it is expected that "test_status_with_session_running_on_endpoint_node" will always fail. This expectation must be documented somewhere.

2023-06-13 11:58 UTC, thiagowfx commented
@nechaev-chromium I wonder if this is the place where it should be documented: https://github.com/web-platform-tests/wpt-metadata/tree/master/webdriver/tests/classic

2023-06-15 06:42 UTC, whimboo commented
> @whimboo it's done! I just added two small additional changes just now, but do not plan do add anything else.

I can still see more updates. So I want to ask again if it's done or if we can expect more changes. Thanks.

2023-06-15 07:15 UTC, whimboo commented
Ok, so if you rebase then please do not force push but run the rebase via `git merge` so that a new commit will be added and it's visible for reviewers. With the huge number of commits it's hard to keep track off.

2023-06-15 07:24 UTC, whimboo approved these changes
Those updates look great. Would be good to have some more linting rules in the future as well so we don't end-up like that again. But that's another topic.

I had a look at the Firefox failures and here it's the merged https://github.com/web-platform-tests/wpt/pull/40122 which causes action tests to fail.

@jgraham I can you please admin merge this PR? Thanks.

2023-06-15 07:57 UTC, thiagowfx commented
> Ok, so if you rebase then please do not force push but run the rebase via git merge so that a new commit will be added and it's visible for reviewers. 

I see, that's a good idea for large PRs like this one. Will keep this in mind for next time, thanks.

2023-06-15 14:18 UTC, thiagowfx commented
I believe the only failure is due to https://github.com/web-platform-tests/wpt/issues/38450 (thus unrealted).

2023-06-16 06:34 UTC, whimboo commented
Thank you @thiagowfx. We need @jgraham here to get this admin merged.

2023-06-16 10:26 UTC, thiagowfx commented
> @thiagowfx this PR has a merge conflict now. Can you please resolve it?

Done. Out of habit I force pushed again, but will reiterate there are no modifications other than `response_completed.py` (removed some extraneous imports while resolving the merge conflict).

2023-06-16 12:21 UTC, whimboo approved these changes

2023-06-16 13:45 UTC, merged