Refactor viewport helpers
web-platform-tests/wpt pull request #40615
Opened 2023-06-19 07:25 UTC by OrKoN

2023-06-19 16:19 UTC, whimboo requested changes
Thanks @OrKoN. Generally it looks all fine. Just some naming and nits to address.

2023-06-19 16:19 UTC, whimboo commented on webdriver/tests/bidi/__init__.py
> +def remote_mapping_to_dict(js_object):
```suggestion
    return text


def remote_mapping_to_dict(js_object):
```

2023-06-19 16:19 UTC, whimboo commented on webdriver/tests/bidi/__init__.py
> +async def get_viewport_dimensions(bidi_session, context):
Always use two empty lines as separator for top-level functions. This also applies to other files in this PR.

```suggestion
    return obj


async def get_viewport_dimensions(bidi_session, context):
```

2023-06-19 16:19 UTC, whimboo commented on webdriver/tests/bidi/browsing_context/capture_screenshot/__init__.py
> +async def device_pixel_ratio(bidi_session, context):
Would you mind adding it as well to the top-level `__init__.py` file? We will also need it for the emulation tests later once we have support for emulating other devices.

```suggestion
async def get_device_pixel_ratio(bidi_session, context):
```

2023-06-19 16:19 UTC, whimboo commented on webdriver/tests/bidi/browsing_context/capture_screenshot/__init__.py
> +async def physical_viewport_dimensions(bidi_session, context):
```suggestion
async def get_physical_viewport_dimensions(bidi_session, context):
```

2023-06-19 16:19 UTC, whimboo commented on webdriver/tests/bidi/browsing_context/capture_screenshot/capture_screenshot.py
> +async def test_capture(bidi_session, url, top_context, inline, compare_png_bidi):
Maybe `url` was there for debugging purposes? I don't see a need to request that fixture here.

```suggestion
async def test_capture(bidi_session, top_context, inline, compare_png_bidi):
```

2023-06-19 16:19 UTC, whimboo commented on webdriver/tests/bidi/input/perform_actions/__init__.py
> +from ... import get_viewport_dimensions, remote_mapping_to_dict
Please separate 3rd party and local imports.

```suggestion

from ... import get_viewport_dimensions, remote_mapping_to_dict
```

2023-06-20 07:28 UTC, whimboo approved these changes
Just a nit. Otherwise it looks fine to get merged. Thanks!

2023-06-20 07:28 UTC, whimboo commented on webdriver/tests/bidi/browsing_context/capture_screenshot/__init__.py
> +from ... import get_viewport_dimensions, get_device_pixel_ratio
Please sort the imports alphabetically. We don't have linting for tests (yet) but this would fail.

2023-06-20 10:14 UTC, whimboo approved these changes

2023-06-20 10:22 UTC, thiagowfx commented on webdriver/tests/bidi/__init__.py
> +    expression = """
```suggestion
async def get_viewport_dimensions(bidi_session, context: str):
```

2023-06-20 10:24 UTC, thiagowfx commented on webdriver/tests/bidi/__init__.py
> +    obj = {}
```suggestion
def remote_mapping_to_dict(js_object: Dict) -> Dict:
```

(please double-check)

2023-06-20 10:24 UTC, thiagowfx approved these changes

2023-06-20 11:02 UTC, merged

2023-06-20 12:46 UTC, thiagowfx commented on webdriver/tests/bidi/__init__.py
> +    obj = {}
Follow-up will live here: https://github.com/web-platform-tests/wpt/pull/40643/files