Add new ImageBitmapRenderingContext tests
web-platform-tests/wpt pull request #4167
Opened 2016-11-03 17:51 UTC by xidachen

The specs for ImageBitmapRenderingContext is here:
https://html.spec.whatwg.org/multipage/scripting.html#the-imagebitmap-rendering-context

This pull request adds some tests to make sure spec compliance.

2016-11-03 18:11 UTC, xidachen commented
@junov : Please review.

2016-11-08 21:28 UTC, junov commented
The test code looks great but the file naming needs to be improved. The directory for imageBitmapRenderingContext should be a sibling, not a child, of 2dcontext. Also, the name ibcontext is not very readable nor is it descriptive of what is being tested.

2016-11-08 21:30 UTC, junov commented
I also think the file should be split by tested sub-feature.  For example, a file just for the alpha creation attribute.

2016-11-09 02:10 UTC, xidachen commented
@junov Thank you for your review. In the second commit, I have put all the tests in a folder imagebitmap-renderingcontext, which is parallel to 2dcontext, and I have break the tests into 5 test files. Please take a look. Thank you.

2016-11-09 14:52 UTC, junov commented on imagebitmap-renderingcontext/context-creation-with-alpha.html
> +}, "Test that canvas.getContext('bitmaprenderer') preserves alpha");
I think the test should go last in this file, and it should entitled "Test that the 'alpha' context creation attribute is true by default."

2016-11-09 14:53 UTC, junov commented on imagebitmap-renderingcontext/context-creation-with-alpha.html
> +    function consumeImageBitmapAlphaTrue(image) {
Could this be refactored to avoid so much repeated code?

2016-11-09 14:59 UTC, junov commented on imagebitmap-renderingcontext/null-source.html
> +    var canvas = document.createElement('canvas');
call this greenCanvas

2016-11-09 14:59 UTC, junov commented on imagebitmap-renderingcontext/null-source.html
> +    var canvas2 = document.createElement('canvas');
redCanvas

2016-11-09 14:59 UTC, junov commented on imagebitmap-renderingcontext/null-source.html
> +    ]).then(([image, image2]) => {
[greenImage, redImage]

2016-11-09 15:04 UTC, junov commented on imagebitmap-renderingcontext/null-source.html
> +},'Test that transferFromImageBitmap(null) should not return any error');
"Test that transferFromImageBitmap(null) discards the previously transferred image"

2016-11-09 15:08 UTC, junov requested changes
Requesting a few tweaks.  Also, we're missing test coverage for the behaviors related to consolidating differences between the canvas element's intrinsic dimensions and the ImageBitmap's dimensions.

2016-11-09 15:08 UTC, junov commented on imagebitmap-renderingcontext/context-creation-with-alpha.html
> +}, "Test that canvas.getContext('bitmaprenderer', alpha:true) preserves the alpha");
I think what you mean is "Test that an ImageBitmapRenderingContext with alpha enabled preserves alpha".

2016-11-09 18:02 UTC, xidachen commented
@junov I have addressed all comments, and added this test: bitmaprenderer-as-imagesource.html

PTAL.

2016-11-09 18:33 UTC, junov commented on imagebitmap-renderingcontext/detached-source.html
> +<!DOCTYPE html>
could you put transferFromImageBitmap in the file name?
Something like transferFromImageBitmap-detached.html

2016-11-09 18:33 UTC, junov commented on imagebitmap-renderingcontext/null-source.html
> +<!DOCTYPE html>
tranferFromImageBitmap-null.html ?

2016-11-09 18:37 UTC, junov requested changes
Looks good. Last nits about file naming.

2016-11-09 18:41 UTC, xidachen commented
@junov: File names are changed. Thanks.

2016-11-09 18:41 UTC, junov commented
One more thing we need to test. When a canvas with a bitmap render is used as an image source, and the transferFromImageBitmap() has never been called, it is supposed to produce a transparent black bitmap of the dimensions given by canvas.width/height.  Same thing should happen after calling transferFromImageBitmap(null)

2016-11-09 19:40 UTC, xidachen commented
@junov I have added two new test cases in bitmaprenderer-as-imagesource.html. PTAL. Thanks

2016-11-09 20:45 UTC, junov approved these changes

2016-11-09 20:52 UTC, junov commented on imagebitmap-renderingcontext/bitmaprenderer-as-imagesource.html
> +        assert_equals(image.width, 10);
should be assert_equals(image.width, width);

2016-11-09 20:54 UTC, junov commented on imagebitmap-renderingcontext/bitmaprenderer-as-imagesource.html
> +        assert_equals(image.width, 10);
same here

2016-11-09 20:56 UTC, junov commented on imagebitmap-renderingcontext/bitmaprenderer-as-imagesource.html
> +    return createImageBitmap(myCanvas).then(t.step_func_done(function(imageBitmap) {
why "return"?

2016-11-09 21:01 UTC, xidachen commented
@junov Done, all comments are addressed.

2016-11-09 21:06 UTC, junov requested changes

2016-11-09 21:06 UTC, junov commented on imagebitmap-renderingcontext/bitmaprenderer-as-imagesource.html
> +        assert_equals(imageBitmap.width, 20);
According to the spec imageBitmap should be 10x10, the size of the image that was transferred into myCtx.  What does Firefox do here?

2016-11-09 21:14 UTC, xidachen commented
OK, I have update the tests. Firefox gives 20*20. I have updated the bug here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1316420

Chrome crashes when doing createImageBitmap(myCanvas), bug filed here:
https://bugs.chromium.org/p/chromium/issues/detail?id=663793

2016-11-09 21:26 UTC, junov commented
> Firefox gives 20*20. I have updated the bug here:
> https://bugzilla.mozilla.org/show_bug.cgi?id=1316420

Actually, what I was going to say in that case is that we should update the spec to reflect the only currently shipping implementation.

2016-11-09 21:34 UTC, xidachen commented
I see, that makes sense. I have reverted the last commit.

2016-11-09 21:38 UTC, junov commented
I retract that last comment, back in April I had an e-mail exchange with the implementer from Mozilla, Morris Tseng, around the time I was finalizing the spec. He was in agreement with what I was proposing, which was different from the Firefox implementation:

>After reading those information, I realized that the purpose of ImageBitmapRenderingContext provided a faster way to display ImageBitmap. So I think option 2 is better approach. If we choose option 2, we don't need keep both original bitmap and displayed bitmap which causes an extra copy. If user want to display ImageBitmap with different intrinsic size (stretch, crop..etc) , he should use drawImage instead.

The option 2 he refers to is the option of using the size of the transferred bitmap as the intrinsic size of the canvas (hence ignoring canvas.width/height)

So let's stick with the spec as it is. It is actually important that it remain this way for perf+memory reasons. 

I guess they just forgot to address this before shipping the feature in FF.

2016-11-10 01:15 UTC, xidachen commented
@junov In the new commits, I have changed the test to follow the spec. A comment is added too. Please review.

2016-11-10 16:04 UTC, junov commented on imagebitmap-renderingcontext/bitmaprenderer-as-imagesource.html
> +        // ImageBitmap (|image| here) should be the intrinsic size of
"should be" -> "must determine"

2016-11-10 16:04 UTC, junov commented on imagebitmap-renderingcontext/bitmaprenderer-as-imagesource.html
> +        // this created |imageBitmap| should have the same size as the |image|.
No need for "this created"

2016-11-10 18:11 UTC, junov approved these changes

2016-11-10 20:27 UTC, merged