[WebDriver BiDi] `userPromptOpened` supports `defaultValue`
web-platform-tests/wpt pull request #41814
Opened 2023-09-05 08:58 UTC by Lightning00Blade

Issue on BiDi spec: https://github.com/w3c/webdriver-bidi/issues/521

2023-09-05 20:53 UTC, whimboo requested changes

2023-09-05 20:53 UTC, whimboo commented on webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py
> +                           wait_for_event, prompt_type):
The indentation is off. Maybe you can fix it? 

Also `prompt_type` is from a parameterization of another test and not used here. It should basically fail that test. Interesting that it doesn't.

```suggestion
async def test_prompt_default_value(
    bidi_session, inline, new_tab, subscribe_events, wait_for_event
):
```

2023-09-06 10:11 UTC, whimboo commented
@Lightning00Blade as it looks like the [Chrome wpt.fyi results are failing](https://github.com/web-platform-tests/wpt/pull/41814/checks?check_run_id=16536380897) because of a test timeout and no results being reported. It doesn't seem to be a regression from this PR but please confirm. Thanks.

2023-09-06 10:14 UTC, whimboo commented
Whereby [checking the real log shows that this newly added test fail](https://community-tc.services.mozilla.com/tasks/DHBE16NeRLi6q9NaMS7T_A/runs/0/logs/live/public/logs/live.log#L658-659)s and maybe as well causes the timeout?

2023-09-12 18:17 UTC, lutien commented on webdriver/tests/bidi/browsing_context/user_prompt_opened/user_prompt_opened.py
> +        "type": prompt_type,
`prompt_type` variable is not defined in this test, maybe that causes the failures.

2023-09-14 06:58 UTC, whimboo approved these changes
That made it! All tests are passing now. Thanks!

2023-09-14 06:58 UTC, merged