Improved 2 border-image-image-type tests
web-platform-tests/wpt pull request #42229
Opened 2023-09-28 22:03 UTC by TalbotG

This is a followup to [Pull Request 21446](https://github.com/web-platform-tests/wpt/pull/21446)

At my website:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-image-type-001-GT.htm

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-image-type-002-GT.htm

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-image-type-001-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/support/9-colored-areas-40-30-20-10.svg

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/support/9-colored-areas-40-30-20-10.png

2023-10-05 15:44 UTC, fantasai requested changes
It looks like you changed the original test's height and width (100px x 100px) to zero (0 x 0). This changes how the test works because the central area is now zero. I think in revising the test, you shouldn't make this change. (You can add additional tests for zero, though, if that seems useful.)

2023-10-08 17:03 UTC, TalbotG commented
I have updated 001 and 002 and created 004 and 005. At my website:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-image-type-004-GT.htm

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-image-type-005-GT.htm

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/border-image-image-type-004-ref.html

I will update the PR in a few min...

2023-10-08 17:39 UTC, TalbotG commented
Closing and reopening PR to trigger Continuous Integration checks...

2023-10-18 17:27 UTC, fantasai approved these changes

2023-10-18 17:27 UTC, merged