Mark invokers tests as non-tentative
web-platform-tests/wpt pull request #42664
Opened 2023-10-20 14:02 UTC by keithamus

See related spec PR https://github.com/whatwg/html/pull/9841

2023-10-20 14:26 UTC, nt1m commented
I would mark this PR as draft until the spec PR lands.

2023-10-20 14:38 UTC, annevk commented
No need to mark as draft. It just needs a label.

2024-11-08 08:40 UTC, annevk commented
It looks like this needs rebasing.

2024-11-08 11:39 UTC, annevk commented
It's a bit weird to have this in an `invokers` directory which isn't really a thing anymore in the specification. Perhaps move it all in the button element directory?

2024-11-08 17:15 UTC, annevk approved these changes
Thanks! These look good and we can land these along with the PR, but I'm assuming that these do not cover the `type` getter of the `button` element as we discussed that today. And they might also not cover the `command` getter in as much detail as is needed? E.g., does it handle `OPEN` becoming `open`, `blah` becoming null, `--BLAH` staying `--BLAH`?

2025-02-07 18:31 UTC, lukewarlow requested changes
There's more tests that need changing since this PR was written.

There's also (going to be) one in the referenceTarget folder which also needs changes: https://github.com/web-platform-tests/wpt/pull/50575

2025-02-07 18:33 UTC, lukewarlow commented
> And they might also not cover the command getter in as much detail as is needed? E.g., does it handle OPEN becoming open, blah becoming null, --BLAH staying --BLAH?

For the record (makes it easier for us to track) this is address by https://github.com/web-platform-tests/wpt/pull/50542/

2025-02-18 10:34 UTC, annevk commented
I don't understand what the state of this is. I don't see the referenceTarget folder being changed here and https://github.com/web-platform-tests/wpt/pull/50542 is an empty PR that does not address my comment.

2025-02-18 10:50 UTC, keithamus commented
@annevk the referencetarget folder has been changed here: https://github.com/web-platform-tests/wpt/pull/42664/files#diff-5a639ea163375c81575b92d7e9c07e7875d8f21beaac1daf1b1e743dd93d5cc8. @lukewarlow's comments are out of date with the current state of this branch. To address your comments:



> Thanks! These look good and we can land these along with the PR, but I'm assuming that these do not cover the `type` getter of the `button` element as we discussed that today.

This PR renames `button-type-behavior` and `button-type-reflection` which cover the `type` getter of the `button` element. These are marked non-tentative in this PR so I'd consider this resolved.

> And they might also not cover the `command` getter in as much detail as is needed? E.g., does it handle `OPEN` becoming `open`, `blah` becoming null, `--BLAH` staying `--BLAH`?

Yes these are all covered in `command-reflection` which has been renamed non-tentative in this PR. Specifically those kinds of tests are here: https://github.com/web-platform-tests/wpt/blob/97c05b771b270ac522fa8d53e6c5d484f911af04/html/semantics/the-button-element/command-and-commandfor/command-reflection.html#L24-L35 which shows `'sHoW-MoDaL'` will reflect as `'show-modal'` while `'--cUsToM'` will reflect as `'--cUsToM'`. I'd consider this resolved as well.

2025-02-18 10:55 UTC, lukewarlow commented
> https://github.com/web-platform-tests/wpt/pull/50542 is an empty PR that does not address my comment.

Apologies, the tests were uploaded separately (via chrome sync iirc) so that PR isn't needed anymore.

2025-02-18 10:55 UTC, lukewarlow approved these changes

2025-02-18 12:50 UTC, annevk approved these changes
Thanks!

It's extremely hard to figure those kind of things out from a force push so next time consider leaving a comment detailing the state of the PR.

2025-02-19 14:55 UTC, merged