Add preload tests from Blink.
web-platform-tests/wpt pull request #4316
Opened 2016-12-12 15:33 UTC by yoavweiss

This PR adds tests for [preload](https://w3c.github.io/preload/) from Blink's [layout tests](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/http/tests/preload/).

These tests are not necessarily a complete test suite as they were built during the feature's implementation, and complemented in Blink by various tests that require internal APIs as well as unit tests. I plan to iterate over these tests and make sure they provide adequate coverage.

/cc @zcorpan @igrigorik

2016-12-12 20:29 UTC, zcorpan commented on preload/avoid_delaying_onload_link_preload.html
> +<link rel=preload href="resources/dummy.js?pipe=trickle(d1)" as=script>
This seems like a possible source of unstable results. Maybe something like 5 seconds? @jgraham

2016-12-12 20:31 UTC, zcorpan commented on preload/single_download_late_used_preload.html
> +        setTimeout(t.step_func(function() {
Use `t.step_timeout` and a longer timeout (2000ms I think)

2016-12-13 18:56 UTC, yoavweiss commented on preload/avoid_delaying_onload_link_preload.html
> +<link rel=preload href="resources/dummy.js?pipe=trickle(d1)" as=script>
Do you think the time it'd take the browser to run the test and get to window.load() would exceed 1 second? I'd hate to make this test slower if it's not a must

2016-12-14 05:26 UTC, igrigorik commented on preload/delaying_onload_link_preload_after_discovery.html
> +    document.write("<!--");
What's the point/purpose of the unclosed comment? Would it be simpler and cleaner to simply build and append a script element?

2016-12-14 05:26 UTC, igrigorik commented on preload/dynamic_remove_preload_href.html
> +        t.done();
Not sure I follow this test. How does this verify that the preload response is aborted? Meta: does abort even make sense? The browser should start a new download if href is mutated, but it's not clear that the old one can/should be stopped.

2016-12-14 05:26 UTC, igrigorik commented on preload/dynamic_removing_preload.html
> +<script src="resources/dummy.js?pipe=trickle(d0.2)"></script>
Ditto to above.

2016-12-14 05:26 UTC, igrigorik commented on preload/onerror_event.html
> +<link rel=preload href="non-existent/dummy.xml" as=foobarxmlthing onerror="gibrishFailed = true;">
gibberish? :P

2016-12-14 08:06 UTC, yoavweiss commented on preload/delaying_onload_link_preload_after_discovery.html
> +    document.write("<!--");
yeah, it would be. I'll switch to that.

2016-12-14 08:19 UTC, yoavweiss commented on preload/onerror_event.html
> +<link rel=preload href="non-existent/dummy.xml" as=foobarxmlthing onerror="gibrishFailed = true;">
didn't bother to typo check that word, apparently :D

2016-12-14 18:51 UTC, nicjansma commented on preload/single_download_preload.html
> +<span>PASS - this text is here just so that the browser will download the font.</span
Missing `>`!

2016-12-16 06:07 UTC, yoavweiss commented on preload/single_download_preload.html
> +<span>PASS - this text is here just so that the browser will download the font.</span
Good catch! :)

2016-12-16 06:21 UTC, igrigorik approved these changes

2016-12-16 08:25 UTC, zcorpan commented
https://github.com/w3c/web-platform-tests/pull/4316#discussion_r92421481 is still outstanding comment. (Making tests take longer to run is bad, but having people spend time analyzing unstable results is worse...)

2016-12-16 10:42 UTC, yoavweiss commented
Changed the trickle values to higher ones. I'll try to see in follow up PRs if I can somehow collapse the tests, so that we'd wait on these long timeouts once, rather than multiple times...

2016-12-16 11:10 UTC, zcorpan commented
Thanks!

Checking test results in https://travis-ci.org/w3c/web-platform-tests/builds/184496213 ...

/preload/preload_with_type.html fails in Chrome. Is that expected?

/preload/dynamic_adding_preload.html times out in Firefox. Could it be made to fail reliably (maybe fail early with a feature-check?)?

2016-12-16 11:17 UTC, yoavweiss commented
The failure in Chrome is expected (Noticed it while writing the tests). I can fix it first before landing the tests, if that helps. I'll look into the Firefox timeouts

2016-12-16 11:33 UTC, zcorpan commented
It's perfectly fine to land tests that fail, just wanted to check that it was expected.

2016-12-16 11:49 UTC, zcorpan requested changes

2016-12-16 11:49 UTC, zcorpan commented on preload/dynamic_adding_preload.html
> +    if(!link.rellist || !link.rellist.supports("preload")) {
Should be `relList`

2016-12-16 11:49 UTC, zcorpan commented on preload/dynamic_adding_preload.html
> +    link.onload = t.step_timeout(function() {
How does this make sense?

2016-12-16 11:49 UTC, zcorpan commented on preload/dynamic_adding_preload.html
> +        t.done();
No need for this line, the line above throws an exception.

2016-12-16 12:07 UTC, yoavweiss commented on preload/dynamic_adding_preload.html
> +    link.onload = t.step_timeout(function() {
There's no spec guaranty that the PerformanceEntry is added to the timeline before the resource's onload handler runs

2016-12-16 13:36 UTC, yoavweiss commented
@z

2016-12-16 13:36 UTC, yoavweiss commented
@zcorpan: addressed your comments

2016-12-16 14:33 UTC, zcorpan commented
w3c-test:mirror

2016-12-16 14:45 UTC, yoavweiss commented on preload/dynamic_adding_preload.html
> +    var link = document.createElement("link");
done

2016-12-16 18:16 UTC, zcorpan approved these changes

2016-12-19 08:42 UTC, merged

2016-12-19 08:45 UTC, yoavweiss commented
Thanks @igrigorik and @zcorpan for reviewing! (and @sideshowbarker for merging :D)