Revert changes to numeric-testcommon.js from commit 383a40f
web-platform-tests/wpt pull request #43314
Opened 2023-11-22 22:28 UTC by nt1m

They regressed Safari Interop 2023 results (which is a Safari bug, but out of scope for this year).

2023-11-22 23:25 UTC, emilio requested changes
If you want to keep using transform, you also need to fix the extractValue implementations. Curious, what's the WebKit bug?

2023-11-24 22:23 UTC, emilio requested changes

2023-11-24 22:23 UTC, emilio commented on css/support/numeric-testcommon.js
> +                    return string.replace(/[/\-\\^$*+?.()|[\]{}]/g, "\\$&");
This probably needs a comment... But is this correct? The previous code would deal with the used `transform` values (so, `matrix(...)`, while this code seems like it wouldn't).

2023-11-24 22:24 UTC, emilio commented
It seems the safari bug is that translate/rotate/etc don't accept math functions or so? If so it might be easier to fix than this tbh. Might even give it a shot this weekend if I find the time :)

2023-11-24 22:38 UTC, nt1m commented
@emilio I looked more into detail into why these tests are failing in Safari. It's just a serialization issue. The computed value of `scale: 1` is `scale: none`. Which arguably isn't incorrect, but trips over all the tests.

2023-11-24 22:42 UTC, nt1m commented
Can we workaround this issue still? Potentially by finding another property to use instead in order to test numbers (like line-height ?)

2023-11-24 23:12 UTC, emilio commented
> @emilio I looked more into detail into why these tests are failing in Safari. It's just a serialization issue. The computed value of `scale: 1` is `scale: none`. Which arguably isn't incorrect, but trips over all the tests.

It is completely incorrect. scale: none doesn't create a containing block for fixed pos descendants etc

2023-11-24 23:14 UTC, emilio commented
> Can we workaround this issue still? Potentially by finding another property to use instead in order to test numbers (like line-height ?)

Not easily because line heights return pixels from gCS. I looked at opacity but it doesn't allow negatives so that's also not good enough. But sure if you find another property that takes and computes to numbers, that sounds good.

2023-12-22 23:12 UTC, nt1m commented
I'm not going to pursue this, it's no longer needed to defend either Safari's experimental or stable score.

2023-12-22 23:13 UTC, closed without merging