More tests for file URL Window drive letter quirk
web-platform-tests/wpt pull request #4382
Opened 2016-12-22 11:41 UTC by zcorpan

2016-12-22 14:18 UTC, Sebmaster commented
There are a few issues with these:
```
  1) Web platform tests parsing </> against <file:///C:/a/b>:

      AssertionError: href
      + expected - actual

      -file:///C:/
      +file:///

      at Context.<anonymous> (test/web-platform.js:20:12)

  2) Web platform tests parsing <//d:> against <file:///C:/a/b>:

      AssertionError: href
      + expected - actual

      -file:///d:
      +file://d:/

      at Context.<anonymous> (test/web-platform.js:20:12)

  3) Web platform tests parsing <//d:/..> against <file:///C:/a/b>:

      AssertionError: href
      + expected - actual

      -file:///d:/
      +file://d:/

      at Context.<anonymous> (test/web-platform.js:20:12)
```

Pretty sure the second and third one are correct failures, not quite sure about the first one.

2016-12-22 16:13 UTC, domenic commented
Not sure exactly what you mean by "correct failures" @Sebmaster, but I agree with jsdom/whatwg-url that the first result should be `file:///C:/`. I don't really know what things of the form `//driveletter:` are supposed to do, but I trust jsdom/whatwg-url, so the "actual" results are probably correct. I think at least the spec takes great pains to ensure that there are always three slashes after `file:`

2016-12-22 16:18 UTC, Sebmaster commented
"correct failures" as in: I'm pretty sure what whatwg-url does is correct here, mainly because of the triple slash thing (also because Chrome agrees with that resolution too).

2017-01-02 14:39 UTC, zcorpan commented
I guess I was confused by reading the spec. But would be nice with confirmation from @annevk that the expected results are actually per spec.

2017-01-03 09:49 UTC, annevk requested changes

2017-01-03 09:49 UTC, annevk commented on url/urltestdata.json
> +  "# More file URL tests by zcorpan",
Why do we put the author here? Should I do that too?

2017-01-03 09:49 UTC, annevk commented on url/urltestdata.json
> +    "href": "file:///d:",
This should end in a slash, no?

2017-01-03 10:10 UTC, zcorpan commented on url/urltestdata.json
> +  "# More file URL tests by zcorpan",
I just wanted to separate these tests from the ones above to direct any blame at me, but of course `git blame` works too. Can remove it though.

2017-01-03 10:25 UTC, zcorpan commented on url/urltestdata.json
> +    "href": "file:///d:",
https://url.spec.whatwg.org/#file-state "/"
https://url.spec.whatwg.org/#file-slash-state "/"
https://url.spec.whatwg.org/#file-host-state "d:" appended to buffer, then EOF. Buffer is a Windows drive letter.
https://url.spec.whatwg.org/#path-state step 1.4.2 appends buffer to path, without adding a trailing slash.

2017-01-03 10:41 UTC, annevk commented on url/urltestdata.json
> +    "href": "file:///d:",
That seems correct, but then pathname wouldn't end in a "/" either. It's also not entirely clear to me that is the desired outcome.

2017-01-03 11:33 UTC, zcorpan commented on url/urltestdata.json
> +    "href": "file:///d:",
https://github.com/whatwg/url/issues/193

2017-01-10 21:46 UTC, domenic approved these changes
Forgot to fixup some pathnames. Let me push an extra commit...

2017-01-10 21:46 UTC, domenic commented on url/urltestdata.json
>      "username": "",
pathname should be "/C:/" not "/"

2017-01-10 21:46 UTC, domenic commented on url/urltestdata.json
> +    "href": "file:///d:",
pathname should be "/d:" not "/d:/"

2017-01-10 21:49 UTC, domenic commented
@annevk all looks good to me now. Can we merge this, and deal with https://github.com/whatwg/url/issues/193 as a follow-up?

2017-01-11 06:47 UTC, annevk approved these changes

2017-01-11 06:48 UTC, annevk commented
I think that's reasonable. Will let @zcorpan merge in case there was anything else.

2017-01-11 18:21 UTC, merged