Add tests for some of the assumptions of the test suite
web-platform-tests/wpt pull request #4411
Opened 2017-01-02 16:52 UTC by gsnedders

This starts to resolve #3827

2017-01-26 08:03 UTC, Ms2ger approved these changes
r+ if you fix the `li`.

2017-01-26 08:03 UTC, Ms2ger commented on assumptions/html-elements.html
> +  var ol_li = document.getElementsByTagName("li")[0];
This one's `ul > li`, not `ol > li`

2017-01-26 08:03 UTC, Ms2ger commented on assumptions/html-elements.html
> +    assert_equals(property, b_styles[i], "Same property on #a and #b");
I'm not quite sure if all of this is guaranteed, but I'm not going to worry about it until someone complains.

2017-01-26 17:51 UTC, gsnedders commented on assumptions/html-elements.html
> +    assert_equals(property, b_styles[i], "Same property on #a and #b");
Not sure why?

2017-01-26 17:51 UTC, gsnedders commented on assumptions/html-elements.html
> +    assert_equals(property, b_styles[i], "Same property on #a and #b");
Like, why aren't you sure if it's all guaranteed?

2017-02-05 23:19 UTC, tobie commented
Pinging @wpt-pr-bot.

2017-02-08 14:30 UTC, w3c-bots commented
# Chrome (unstable channel) #
Testing web-platform-tests at revision 479e16e56853392dd36d2bb3283704443790597c
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/4411/assumptions/initial-color.html">/assumptions/initial-color.html</a></summary>


| Subtest | Results |
|---------|---------|
|         | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4411/assumptions/min-font-size.html">/assumptions/min-font-size.html</a></summary>


| Subtest | Results |
|---------|---------|
|         | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4411/assumptions/html-elements.html">/assumptions/html-elements.html</a></summary>


|                            Subtest                            | Results |
|---------------------------------------------------------------|---------|
|                                                               | OK      |
| `table is display: table`                                     | PASS    |
| `(pre-req for comparison tests) initial CSS value supported`  | PASS    |
| `Compare CSS span definitions (only valid if pre-reqs pass)`  | PASS    |
| `ul > li is display: block`                                   | PASS    |
| `ol > li is display: block`                                   | PASS    |
| `tbody is display: table-row-group`                           | PASS    |
| `(pre-req for comparison tests) all CSS short-hand supported` | PASS    |
| `Compare CSS div definitions (only valid if pre-reqs pass)`   | PASS    |
| `p is display: block`                                         | PASS    |
| `tr is display: table-row`                                    | PASS    |
| `td is display: table-cell`                                   | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4411/assumptions/medium-font-size.html">/assumptions/medium-font-size.html</a></summary>


| Subtest | Results |
|---------|---------|
|         | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4411/assumptions/canvas-background.html">/assumptions/canvas-background.html</a></summary>


| Subtest | Results |
|---------|---------|
|         | PASS    |

</details>

2017-02-08 14:30 UTC, w3c-bots commented
# Firefox (nightly channel) #
Testing web-platform-tests at revision 479e16e56853392dd36d2bb3283704443790597c
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/4411/assumptions/initial-color.html">/assumptions/initial-color.html</a></summary>


| Subtest | Results |
|---------|---------|
|         | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4411/assumptions/min-font-size.html">/assumptions/min-font-size.html</a></summary>


| Subtest | Results |
|---------|---------|
|         | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4411/assumptions/html-elements.html">/assumptions/html-elements.html</a></summary>


|                            Subtest                            | Results |
|---------------------------------------------------------------|---------|
|                                                               | OK      |
| `table is display: table`                                     | PASS    |
| `(pre-req for comparison tests) initial CSS value supported`  | FAIL    |
| `Compare CSS span definitions (only valid if pre-reqs pass)`  | PASS    |
| `ul > li is display: block`                                   | PASS    |
| `ol > li is display: block`                                   | PASS    |
| `tbody is display: table-row-group`                           | PASS    |
| `(pre-req for comparison tests) all CSS short-hand supported` | PASS    |
| `Compare CSS div definitions (only valid if pre-reqs pass)`   | FAIL    |
| `p is display: block`                                         | PASS    |
| `tr is display: table-row`                                    | PASS    |
| `td is display: table-cell`                                   | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4411/assumptions/medium-font-size.html">/assumptions/medium-font-size.html</a></summary>


| Subtest | Results |
|---------|---------|
|         | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4411/assumptions/canvas-background.html">/assumptions/canvas-background.html</a></summary>


| Subtest | Results |
|---------|---------|
|         | PASS    |

</details>

2017-02-08 14:41 UTC, Ms2ger commented
w3c-test:mirror

2017-02-08 15:20 UTC, gsnedders commented
@Ms2ger r?

2017-02-08 15:48 UTC, Ms2ger requested changes

2017-02-08 15:48 UTC, Ms2ger commented on assumptions/html-elements.html
> +                ["rgba(0, 0, 0, 0)", "transparent"]);
Indentation

2017-02-08 15:48 UTC, Ms2ger commented on assumptions/html-elements.html
> +  assert_equals(a_styles.length, b_styles.length, "Same properties on both #a and #b");
Going to fix the `#a` references?

2017-02-08 15:48 UTC, Ms2ger commented on assumptions/html-elements.html
> +}, "ul > li is display: block");
No it isn't

2017-02-08 15:48 UTC, Ms2ger commented on assumptions/html-elements.html
> +  var td = document.getElementsByTagName("td")[0];
Worth testing `th`?

2017-02-08 15:48 UTC, Ms2ger commented on assumptions/min-font-size.html
> +<link rel="mismatch" href="min-font-size-ref.html">
Could use `-notref`. Not sure what our policy is on that.

2017-02-08 15:58 UTC, gsnedders commented on assumptions/html-elements.html
> +  assert_equals(a_styles.length, b_styles.length, "Same properties on both #a and #b");
I thought I'd pushed that fix.

2017-02-08 16:08 UTC, gsnedders commented on assumptions/min-font-size.html
> +<link rel="mismatch" href="min-font-size-ref.html">
There isn't one.

2017-02-09 15:19 UTC, merged