HTML: set location.protocol to non-broken-non-functioning schemes
web-platform-tests/wpt pull request #4502
Opened 2017-01-04 11:08 UTC by annevk

See https://github.com/whatwg/url/issues/61 for context.

https://github.com/w3c/web-platform-tests/pull/4412 tests broken
schemes.

2017-01-04 11:09 UTC, annevk commented
The -weird.html is an earlier iteration of the test (excluding data URL tests) that for some reason never completes running in Firefox. I thought I'd include it since it does show differences between the two ways of testing.

2017-01-04 14:14 UTC, zcorpan requested changes

2017-01-04 14:14 UTC, zcorpan commented on html/browsers/history/the-location-interface/location-protocol-setter-non-broken.html
> +        try {
Remove

2017-01-04 14:14 UTC, zcorpan commented on html/browsers/history/the-location-interface/location-protocol-setter-non-broken-weird.html
> +  })
Include `val` in the test name

2017-01-04 15:44 UTC, annevk commented
Thanks, pushed fixes.

2017-01-05 15:05 UTC, zcorpan approved these changes

2017-01-05 15:15 UTC, merged