Verify that preloads with a "fetch" `as` value have an empty destination
web-platform-tests/wpt pull request #4505
Opened 2017-01-04 14:35 UTC by yoavweiss

@annevk - As discussed on https://github.com/whatwg/fetch/pull/442, here's the corresponding test. Note that it fails in all current implementations.

2017-01-04 16:01 UTC, annevk commented on preload/fetch_destination.https.html
> +    var scope = 'resources/empty.html';
You can use `/common/blank.html` instead.

2017-01-04 16:02 UTC, annevk commented on preload/fetch_destination.https.html
> +    var scope = 'resources/empty.html';
Also, that URL doesn't match the preload URL from later on. Is that intentional?

2017-01-18 11:51 UTC, yoavweiss commented
@annevk - Changed the scope to be the preloaded resource, and added a bunch of needed step_func wrappers around the various async test functions. (due to timeouts I seen locally)

2017-01-18 12:41 UTC, annevk requested changes
Found some more issues.

2017-01-18 12:41 UTC, annevk commented on preload/resources/fetch-destination-worker.js
> +            response.status = 500;
This doesn't match the Preload specification. It doesn't say that an error event is dispatched for such status codes. That would also likely be problematic due to the same-origin policy mostly trying to keep that a secret.

2017-01-18 12:41 UTC, annevk commented on preload/fetch_destination.https.html
> +          link.addEventListener("error", t.step_func(function() { assert_unreached("Fetch destination preload errored"); done(registration); }));
Does this even run? I think that an assert results in an exception.

2017-01-18 13:36 UTC, yoavweiss commented on preload/resources/fetch-destination-worker.js
> +            response.status = 500;
Hmm, I guess we need to tighten the definition of "load was successful" there. I understood it as including the status code. Is there another way that a SW can signal the page that a load was unsuccessful?

2017-01-18 13:50 UTC, yoavweiss commented on preload/fetch_destination.https.html
> +          link.addEventListener("error", t.step_func(function() { assert_unreached("Fetch destination preload errored"); done(registration); }));
It runs and fails in current implementations (which trigger an error when `as=fetch`)

2017-01-18 15:24 UTC, annevk commented on preload/resources/fetch-destination-worker.js
> +            response.status = 500;
I'm not sure. @jakearchibald?

2017-01-18 15:24 UTC, annevk commented on preload/fetch_destination.https.html
> +          link.addEventListener("error", t.step_func(function() { assert_unreached("Fetch destination preload errored"); done(registration); }));
But does it call `done()`?

2017-01-18 15:42 UTC, yoavweiss commented on preload/fetch_destination.https.html
> +          link.addEventListener("error", t.step_func(function() { assert_unreached("Fetch destination preload errored"); done(registration); }));
It fails (immediately) with an assert_unreached().
If this is an issue and done() must be called, what's the proper way define unreachable code without asserting?

2017-01-18 18:42 UTC, annevk commented on preload/fetch_destination.https.html
> +          link.addEventListener("error", t.step_func(function() { assert_unreached("Fetch destination preload errored"); done(registration); }));
I don't think it's an issue, but I would just leave out done(). Come to think of it, you can use `t.step_func_done()` which cleans this up automatically.

2017-01-18 18:48 UTC, annevk commented on preload/resources/fetch-destination-worker.js
> +            response.status = 500;
In theory returning a network error can be done through `Response.error()` per https://fetch.spec.whatwg.org/#dom-response-error.

2017-01-19 11:27 UTC, yoavweiss commented on preload/resources/fetch-destination-worker.js
> +            response.status = 500;
Cool. Using that instead

2017-01-19 11:28 UTC, yoavweiss commented on preload/fetch_destination.https.html
> +          link.addEventListener("error", t.step_func(function() { assert_unreached("Fetch destination preload errored"); done(registration); }));
`step_func_done` it is (plus unregistration)

2017-01-19 11:30 UTC, yoavweiss commented
@annevk - I brought back the old scope (with the empty.html) as I was hitting weird errors related to frame access with the scope and link both pointing at the same URL.

2017-01-19 11:49 UTC, annevk commented
What's wrong with using http://w3c-test.org/common/blank.html as I suggested?

2017-01-19 12:05 UTC, yoavweiss commented
Oh, should've commented on that. It's from a different directory than the SW registered, and the SW registration fails.

2017-01-19 12:25 UTC, annevk commented on preload/fetch_destination.https.html
> +          link.addEventListener("load", t.step_func(function() { done(registration); }));
Use step_func_done here too and inline the unregister call?

Seems okay then.

2017-01-19 12:29 UTC, yoavweiss commented on preload/fetch_destination.https.html
> +          link.addEventListener("load", t.step_func(function() { done(registration); }));
done

2017-01-19 12:30 UTC, yoavweiss commented
Would you like me to squash the commits?

2017-01-19 15:12 UTC, merged