Test new URLSearchParams constructor features
web-platform-tests/wpt pull request #4523
Opened 2017-01-11 10:07 UTC by annevk

The main thing here is new tests for
https://github.com/whatwg/url/pull/175/files but I also found issues
with some existing tests that I’m attempting to fix at the same time.

The current tests assumed the constructor argument was mandatory, but
it’s in fact optional. The other issue was that the current test assume
stringifying DOMException.prototype throws, but I don’t think that’s
the case.

2017-01-11 13:41 UTC, domenic requested changes

2017-01-11 13:41 UTC, domenic commented on url/urlsearchparams-constructor.html
> +}, 'URLSearchParams constructor, empty and unusual input.');
Separate tests per input will make failures clearer.

2017-01-11 13:41 UTC, domenic commented on url/urlsearchparams-constructor.html
> +}, "Evil constructor test")
I don't think this works as expected. `params1[Symbol.iterator] === params2[Symbol.iterator] === URLSearchParams.prototype[Symbol.iterator]`. The assignment is a no-op. The iterator will look up the private data on the instance it's invoked on, so iterating over params2 will always give no params, so params3 should be empty.

2017-01-11 14:21 UTC, annevk commented on url/urlsearchparams-constructor.html
> +}, "Evil constructor test")
Oh, shit. I based that on #4240 which I also wrote. How would I create a custom iterator? Would assigning an array be sufficient?

2017-01-11 14:28 UTC, domenic commented on url/urlsearchparams-constructor.html
> +}, "Evil constructor test")
The easiest way is to use a generator:

```js
params3[Symbol.iterator] = function *() {
  yield [a, b];
  yield [c, d];
};
```

2017-01-11 14:44 UTC, annevk commented on url/urlsearchparams-constructor.html
> +}, "Evil constructor test")
Thanks, used.

2017-01-11 14:44 UTC, annevk commented on url/urlsearchparams-constructor.html
> +}, 'URLSearchParams constructor, empty and unusual input.');
Done this as well.

2017-01-12 00:04 UTC, domenic commented on url/urlsearchparams-constructor.html
>      assert_equals(params + '', '%5Bobject+Object%5D=');
I think this should now be equivalent to no arguments per record semantics. So just empty string.

2017-01-12 00:04 UTC, domenic commented on url/urlsearchparams-constructor.html
> +}, "Evil constructor test")
Maybe "overridden iterator test" is now more accurate.

2017-01-12 06:35 UTC, annevk commented
Thanks!

2017-01-12 15:55 UTC, domenic approved these changes

2017-01-12 16:11 UTC, merged

2017-01-20 02:52 UTC, cdumez commented on url/urlsearchparams-constructor.html
> +    assert_equals(params.toString(), "Error=")
Can you clarify why this is the expected result here. My interpretation of the Web IDL spec [1] is that we should go to step 11.1 and treat the input as a sequence (not a String).

[1] https://heycam.github.io/webidl/#es-union

2017-01-20 02:53 UTC, domenic commented on url/urlsearchparams-constructor.html
> +    assert_equals(params.toString(), "Error=")
Yes but method is undefined so it then continues on with the rest of the steps.

2017-01-20 02:57 UTC, cdumez commented on url/urlsearchparams-constructor.html
> +    assert_equals(params.toString(), "Error=")
How about 11.4 ? We do have a record in there.

2017-01-20 03:02 UTC, domenic commented on url/urlsearchparams-constructor.html
> +    assert_equals(params.toString(), "Error=")
Yeah you're right. I think this is indeed incorrect.

2017-01-20 08:20 UTC, annevk commented on url/urlsearchparams-constructor.html
> +    assert_equals(params.toString(), "Error=")
https://github.com/w3c/web-platform-tests/pull/4581 has the fix. I also commented on the WebKit bug.

2017-01-28 19:20 UTC, TimothyGu commented on url/urlsearchparams-constructor.html
> +  { "input": {"+": "%C2"}, "output": [[" ", "\uFFFD"]], "name": "object with +" },
@annevk, I'm in the process of implementing the URL spec change in Node.js. Where does it say in the URL Standard that keys and values of a record must be unescaped?

2017-01-29 10:23 UTC, annevk commented on url/urlsearchparams-constructor.html
> +  { "input": {"+": "%C2"}, "output": [[" ", "\uFFFD"]], "name": "object with +" },
That's a good question, it doesn't and I'm not sure it should. I filed https://github.com/whatwg/url/issues/220.