Tests for long task observer: https://github.com/wicg/longtasks
web-platform-tests/wpt pull request #4540
Opened 2017-01-15 01:23 UTC by spanicker

@igrigorik PTAL

2017-01-15 01:45 UTC, spanicker commented
Comments on test structuring for parent/child iframes (and cross origin) is appreciated. Thanks.

2017-01-16 20:32 UTC, spanicker commented
@tdresser for comment

2017-01-16 21:17 UTC, tdresser approved these changes
This all looks pretty reasonable to me (I left a couple nits). I don't have thoughts on how to handle the cross process iframe case. @RByers might have thoughts?

2017-01-16 21:17 UTC, tdresser commented on longtask-timing/resources/subframe-with-longtask.html
> +    while (window.performance.now() < begin + 100);
We use 51ms in places - why use 100 here?

2017-01-16 21:17 UTC, tdresser commented on longtask-timing/resources/makelongtask.js
> +/* Generate a slow task */
Missing .

2017-01-16 21:17 UTC, tdresser commented on longtask-timing/resources/subframe-observing-longtask.html
> +      	 // ignore long task generated within here, as part of making this iframe.
Capitalize

2017-01-16 21:29 UTC, igrigorik reviewed
- s/miillisecond/millisecond
- meta: should 'taskattribution' be 'task-attribution' for readability and consistency?

2017-01-16 21:29 UTC, igrigorik commented on longtask-timing/longtask-attributes.html
> +                "startTime expected to have 1 miillisecond granularity");
millisecond typo

2017-01-16 21:29 UTC, igrigorik commented on longtask-timing/longtask-attributes.html
> +            assert_equals(attribution.entryType, "taskattribution");
Hrm, should we be hyphenating these? We do in `name`.

2017-01-16 21:29 UTC, igrigorik commented on longtask-timing/longtask-in-childiframe-crossorigin.html
> +                "startTime expected to have 1 miillisecond granularity");
same typo

2017-01-16 21:29 UTC, igrigorik commented on longtask-timing/longtask-in-childiframe-crossorigin.html
> +<!--TODO(panicker): simulate cross-origin instead -->
Hmm? Confused by the TODO.. What's left for this one?

2017-01-16 21:46 UTC, RByers requested changes

2017-01-16 21:46 UTC, RByers commented on longtask-timing/longtask-in-childiframe-crossorigin.html
> +            assert_equals(attribution.frameSrc, "https://wicg.github.io/longtasks/randomslow.html");
I think web-platform-tests are run in an environment that prevents arbitrary network access, but they [do have a number of different origins available](https://github.com/w3c/web-platform-tests#running-the-tests).  See, for example, [this test](https://github.com/w3c/web-platform-tests/blob/master/html/semantics/embedded-content/the-iframe-element/cross_origin_parentage.html).

2017-01-17 02:12 UTC, spanicker commented on longtask-timing/longtask-attributes.html
> +                "startTime expected to have 1 miillisecond granularity");
Rounding sounds better, but looking at existing code for "clamping resolution" I'm finding floor.
Filed crbug.com/681718 to track this.

2017-01-17 02:12 UTC, spanicker commented on longtask-timing/longtask-attributes.html
> +                "startTime expected to have 1 miillisecond granularity");
Done.

2017-01-17 02:13 UTC, spanicker commented on longtask-timing/longtask-attributes.html
> +            assert_equals(attribution.entryType, "taskattribution");
This is consistent with `entryType` - we don't hyphenate "longtask" for instance. Should we?

2017-01-17 02:13 UTC, spanicker commented on longtask-timing/longtask-in-childiframe-crossorigin.html
> +                "startTime expected to have 1 miillisecond granularity");
Fixed

2017-01-17 02:14 UTC, spanicker commented on longtask-timing/longtask-in-childiframe-crossorigin.html
> +            assert_equals(attribution.frameSrc, "https://wicg.github.io/longtasks/randomslow.html");
This is exactly what I was looking for. Thanks!

2017-01-17 02:14 UTC, spanicker commented on longtask-timing/longtask-in-childiframe-crossorigin.html
> +<!--TODO(panicker): simulate cross-origin instead -->
Updated with Rick's pointer, we shouldn't try to load actual external sites in tests

2017-01-17 02:14 UTC, spanicker commented on longtask-timing/resources/makelongtask.js
> +/* Generate a slow task */
Fixed

2017-01-17 02:15 UTC, spanicker commented on longtask-timing/resources/subframe-observing-longtask.html
> +      	 // ignore long task generated within here, as part of making this iframe.
Fixed

2017-01-17 02:16 UTC, spanicker commented on longtask-timing/resources/subframe-with-longtask.html
> +    while (window.performance.now() < begin + 100);
Good catch, fixed.

2017-01-28 00:17 UTC, spanicker commented
Friendly ping.

2017-01-28 02:30 UTC, igrigorik approved these changes

2017-01-28 02:30 UTC, igrigorik commented
Looks good! @RByers any other feedback from your end, before we merge?

2017-02-05 23:14 UTC, tobie commented
Ping @wpt-pr-bot.

2017-02-05 23:17 UTC, tobie commented
Sorry for the noise, folks.

2017-03-08 03:55 UTC, spanicker commented
Friendly ping!

2017-03-08 11:11 UTC, igrigorik commented
@RByers ptal :-)

2017-03-10 18:55 UTC, RByers commented
Sorry for the delay - I'm now on a flight and so can't look but please
don't block on me landing these tests!

On Mar 8, 2017 6:11 AM, "Ilya Grigorik" <notifications@github.com> wrote:

> @RByers <https://github.com/RByers> ptal :-)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/w3c/web-platform-tests/pull/4540#issuecomment-285013915>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABOJo_Ug7-TFv1xAa8YZlUbA9cio-5Pfks5rjozOgaJpZM4Ljy2z>
> .
>

2017-03-10 22:42 UTC, merged

2017-03-10 22:43 UTC, igrigorik commented
👍

2017-03-13 07:41 UTC, annevk commented
This PR broke master somehow. @jgraham @jugglinmike @bobholt

2017-03-13 17:07 UTC, spanicker commented
Apologies. Too much time elapsed between this CL and merge.
Which tests specifically are failing?
Should I fix or rollback ?

2017-03-13 17:11 UTC, annevk commented
It got fixed by @jgraham in https://github.com/w3c/web-platform-tests/commit/4a28c0eb39b8e217c74bf66da769286745b35e38. What you might want to do though is see if you can use test.step_timeout and remove yourself from the lint exclusion resource though.

2017-03-13 17:13 UTC, spanicker commented
Ok I'll follow up on that. Thanks!