Payment Request: fix permission policy tests
web-platform-tests/wpt pull request #45443
Opened 2024-04-01 04:44 UTC by marcoscaceres

Cleanup the Permission Policy tests for Payments, and set a substitute URL that works with WebKit's infrastructure. 

Fix the tests to use promise_test instead.

2024-04-01 13:06 UTC, rsolomakhin requested changes
Overall looks good! Added a few comments, but they are all for the existing code, not necessarily your patch. It would be great to improve the existing code, but let me know if you think these comments are not relevant.

2024-04-01 13:27 UTC, marcoscaceres commented on permissions-policy/payment-allowed-by-permissions-policy-attribute.https.sub.html
> +                undefined,
Yeah, it’s also why I ran prettier over these files. Super confusing! I had to constantly count with parameter I was on 😠 

The right fix is to allow test_feature_availability() to take an object with named parameters. 

I think it’s worth doing as a follow up.

2024-04-01 13:28 UTC, marcoscaceres commented on permissions-policy/payment-allowed-by-permissions-policy-attribute.https.sub.html
> +        }, feature_name + " can be enabled in same-origin iframe using " + header);
Yes, it’s definitely allowed by default (self).

2024-04-01 13:29 UTC, marcoscaceres commented on permissions-policy/payment-allowed-by-permissions-policy.https.sub.html
> +        }, header + " allows the top-level document.");
I think that’s covered.

2024-04-01 21:25 UTC, marcoscaceres commented on permissions-policy/payment-allowed-by-permissions-policy-attribute.https.sub.html
> +        }, feature_name + " can be enabled in same-origin iframe using " + header);
This is covered in permissions-policy/payment-default-permissions-policy.https.sub.html

2024-04-02 11:27 UTC, rsolomakhin commented on permissions-policy/payment-allowed-by-permissions-policy.https.sub.html
> +        }, header + " allows the top-level document.");
New string look good! 👍

2024-04-02 11:27 UTC, rsolomakhin commented on permissions-policy/payment-allowed-by-permissions-policy.https.sub.html
> +        }, header + " allows same-origin iframes.");
New strings look good! 👍

2024-04-02 11:28 UTC, rsolomakhin approved these changes

2024-04-09 04:56 UTC, merged