fix permissions-policy-payment-extension.html to only check error name
web-platform-tests/wpt pull request #45455
Opened 2024-04-01 21:15 UTC by marcoscaceres

This should fix it... even if it's not as precise as checking the error message.

2024-04-01 22:15 UTC, rsolomakhin requested changes

2024-04-01 22:15 UTC, rsolomakhin commented on permissions-policy/payment-extension-allowed-by-permissions-policy-attribute.https.sub.html
>      }, feature_name + ' is not supported in cross-origin iframe without ' + header);
Could we change the `feature_name` to be `'WebAuthn "payment" extension'` to make it more clear what this test is about?

2024-04-02 06:37 UTC, Noumanluckey8057 approved these changes

2024-04-08 08:54 UTC, Noumanluckey8057 approved these changes
Ok

2024-04-08 10:17 UTC, rsolomakhin approved these changes

2024-05-16 10:04 UTC, merged