[presentation-api] add a step to terminate presentations when the test stops
web-platform-tests/wpt pull request #4562
Opened 2017-01-19 06:42 UTC by tomoyukilabs

This PR partially fixes #4258.

* `startNewPresentation_unsettledpromise-manual.html` now terminates a presentation in `request.start().then()`, since the display selection dialog could appear after the test result would be shown.
* The other tests now terminate a presentation in `t.add_cleanup(function)`.

2017-01-23 16:03 UTC, tidoust requested changes
That looks great. See trivial comments inline about missing ";" for code consistency.

2017-01-23 16:03 UTC, tidoust commented on presentation-api/controlling-ua/startNewPresentation_displaynotallowed-manual.html
> +            })
Just for the sake of code consistency, do you mean adding back the missing ";" here?

2017-01-23 16:03 UTC, tidoust commented on presentation-api/controlling-ua/startNewPresentation_displaynotfound-manual.html
> +            })
Same here, do you mean adding back the missing ";"?

2017-01-24 00:22 UTC, tomoyukilabs commented
Oops. I've added missing semicolon.

2017-01-24 08:29 UTC, merged