make travis directories dynamic
web-platform-tests/wpt pull request #4566
Opened 2017-01-19 16:01 UTC by bobholt

This dynamically sets the directories used in the `check_stability.py` script to be based on the user running the Travis job.

This allows anyone to set up Travis builds on their fork of the web platform tests without modifying `check_stability.py`.

This opts to pass the user value to each method rather than setting a global value. Happy to change if a global value is preferred.

2017-01-19 17:28 UTC, jgraham commented
You might need to rebase onto latest master for this to work.

2017-01-19 17:36 UTC, jgraham commented
Seems OK in principle, but it's pretty noisy. Maybe we should make the base path a global which we write to once?

2017-01-19 17:46 UTC, bobholt commented
@jgraham Agree. I'll make an update.

2017-01-19 18:15 UTC, bobholt commented
Latest push makes that user variable global. Will go further and make that whole path global now.

2017-01-19 19:01 UTC, jgraham approved these changes
Can you just demonstrate this works by pushing a no-op test change, and then removing it again once the checker reports some results?

2017-01-19 19:02 UTC, jgraham requested changes

2017-01-19 19:02 UTC, jgraham commented on check_stability.py
> +    wptrunner_root = os.path.join(wpt_root, "..", "wptrunner")
I think a normalized path here would be nice.

2017-01-19 19:06 UTC, bobholt commented on check_stability.py
> +    wptrunner_root = os.path.join(wpt_root, "..", "wptrunner")
Just had that same thought and pushed another change - rebased because I was getting so many fixups.

2017-01-19 19:06 UTC, bobholt commented
Please bear with me as I work through my python rust. If it's too noisy, I can close and reopen once the light is green on my fork.

2017-01-19 22:04 UTC, jgraham approved these changes

2017-01-20 11:26 UTC, jgraham commented
I don't know what the problem reporting the travis status is, but the build passes and tests run, so I'm happy with this as soon as you remove the example test change.

2017-01-20 12:08 UTC, bobholt commented
Yeah, that status was causing me great consternation yesterday. The test change has been removed.

2017-01-20 12:48 UTC, merged