ARIA: add tests for sectionheader and sectionfooter
web-platform-tests/wpt pull request #45916
Opened 2024-04-25 19:42 UTC by spectranaut

Change in ARIA: https://github.com/w3c/aria/pull/1931

Draft until the linux mappings are confirmed: https://github.com/w3c/core-aam/pull/207

2024-05-05 22:47 UTC, rahimabdi approved these changes

2024-05-05 22:47 UTC, rahimabdi commented on core-aam/sectionfooter-manual.html
> +    <div role='sectionfooter' id='test'>content</div>
Minor nit: the `role` and `id` attributes for this `<div>` use single quotes (which is OK so long as single/double quotes are used in matching pairs from my understanding) but double quotes are used elsewhere in this file.

2024-05-05 22:47 UTC, rahimabdi commented on core-aam/sectionheader-manual.html
> +    <div role='sectionheader' id='test'>content</div>
Minor nit: the `role` and `id` attributes for this `<div>` use single quotes (which is OK so long as single/double quotes are used in matching pairs from my understanding) but double quotes are used elsewhere in this file.

2024-05-07 01:25 UTC, cookiecrook commented on wai-aria/role/roles.html
> +  "sectionfooter",
Since all implementations have a different mappings (to `generic`), should this be a separate PR from the ATTAcomm tests?

2024-05-07 01:26 UTC, cookiecrook commented on wai-aria/role/roles.html
> +  "sectionfooter",
Also, it be in a `.tentative` file until there is a spec change landed and two passing implementations.

2024-05-07 01:33 UTC, cookiecrook requested changes
This would result in new failures for Interop, so please keep the WebDriver role verifications out. Adding to a `roles.tentative.html` file is fine, as those don't affect the score.

Even if we agreed on the test additions, there's a process inside the current Interop project together sign off from implementors before making new changes that would affect the score mid-year.

2024-05-07 16:07 UTC, spectranaut commented
Ok @cookiecrook -- I moved sectionheader and sectionfooter to a tentative file: https://github.com/web-platform-tests/wpt/pull/46142

If we need sign off from implementers for WPT tests of new futures added to ARIA, we should note that in the ARIA process documents, I'll ping you for a review of that draft.

2024-05-29 16:30 UTC, cookiecrook commented
> I moved sectionheader and sectionfooter to a tentative file: https://github.com/web-platform-tests/wpt/pull/46142

Thanks. FYI there is still an accidental white space diff remaining in roles.html.

2024-07-23 20:02 UTC, tranjocelyn commented
Is there a PR to update the header and footer (scoped to main/sectioning content) subtests in html-aam/roles-contextual.html and wai-aria/role/contextual-roles.html? 

I have the implementation for sectionheader and sectionfooter ready for Chrome, but it's currently failing those subtests. I'm holding off on merging the code because it would negatively impact our Interop score.

2024-07-25 18:33 UTC, spectranaut commented
> Is there a PR to update the header and footer (scoped to main/sectioning content) subtests in html-aam/roles-contextual.html and wai-aria/role/contextual-roles.html? 
> 
> I have the implementation for sectionheader and sectionfooter ready for Chrome, but it's currently failing those subtests. I'm holding off on merging the code because it would negatively impact our Interop score.

Hi Joceyln, if there is a missing test or failing test, maybe make an issue on ARIA with the details so we can update it? This PR just has manual tests to keep track of the API mappings.

2024-07-31 20:15 UTC, cookiecrook commented on core-aam/sectionfooter-manual.html
> +                  "sectionfooter"
These are user-presented strings, so two-word role descriptions should include the space. "section footer"

Did you speak to anyone else at Apple about the potential for a new AXSubrole? If not, I'll ask around.

2024-07-31 20:15 UTC, cookiecrook commented on core-aam/sectionfooter-manual.html
> +                  "sectionfooter"
I would expect the same (include the space char) is true for _localized_ control types in UIA, but I don't know.

2024-07-31 20:15 UTC, cookiecrook commented on core-aam/sectionheader-manual.html
> +               ]
ditto

2024-07-31 20:15 UTC, cookiecrook commented on core-aam/sectionheader-manual.html
> +               ]
ditto

2024-08-02 20:38 UTC, cookiecrook approved these changes
Approving with the updates from the spec PR

2024-08-02 20:38 UTC, cookiecrook commented on core-aam/sectionfooter-manual.html
> +                  "sectionfooter"
```suggestion
                  "section footer"
```

2024-08-02 20:38 UTC, cookiecrook commented on core-aam/sectionfooter-manual.html
> +                  "<nil>"
```suggestion
                  "AXSectionFooter"
```

2024-08-02 20:38 UTC, cookiecrook commented on core-aam/sectionfooter-manual.html
> +                  "sectionfooter"
```suggestion
                  "section footer"
```

2024-08-02 20:38 UTC, cookiecrook commented on core-aam/sectionheader-manual.html
> +                  "<nil>"
```suggestion
                  "AXSectionHeader"
```

2024-08-02 20:38 UTC, cookiecrook commented on core-aam/sectionheader-manual.html
> +                  "sectionheader"
```suggestion
                  "section header"
```

2024-08-02 20:38 UTC, cookiecrook commented on core-aam/sectionheader-manual.html
> +                  "sectionheader"
```suggestion
                  "section header"
```

2024-08-11 22:10 UTC, rahimabdi reviewed
@cookiecrook has kindly provided comments/suggested feedback.

2024-08-12 21:32 UTC, merged