Test the docker image from the GitHub registry
web-platform-tests/wpt pull request #46279
Opened 2024-05-15 09:39 UTC by OrKoN

2024-05-17 16:38 UTC, jgraham requested changes
I think actually merging this probably requires an RFC in case anyone is depending on the images in some other workflow.

2024-05-17 16:38 UTC, jgraham commented on tools/docker/README.md
> +`{current-version + 0.01}`
This is now wrong again. Also I'd take this chance to just move to integer version numbers.

2024-05-17 16:39 UTC, jgraham commented
> do we need the local scripts in tools/docker/frontend.py? or is it sufficient to use the GitHub Actions workflow?

Yes, that's extremely useful for using the docker image locally, particularly when experimenting with changes to the image itself.

2024-06-20 16:29 UTC, OrKoN commented
I have updated the PR but publishing a new image tagged `1` failed because launchpad.net is under maintenance so `apt-add-repository -y ppa:deadsnakes/ppa` fails.

<img width="1156" alt="Screenshot 2024-06-20 at 18 26 58" src="https://github.com/web-platform-tests/wpt/assets/399150/e6563e0a-1d38-4618-91e7-8b2cd76c9d74">

Related: https://askubuntu.com/a/1398569/374747

2024-06-20 17:06 UTC, OrKoN commented
I think this PR is ready for review. Apart from landing this PR, an admin should set permissions on the package as documented in the linked RFC https://github.com/web-platform-tests/rfcs/pull/198

2024-07-02 15:54 UTC, past approved these changes
Looks good to me!

2024-07-02 15:54 UTC, jgraham approved these changes
Minor nits, but I think in general I'm OK with this landing.

2024-07-02 15:54 UTC, jgraham commented on tools/docker/frontend.py
> +                        "manifest",
Indentation looks a bit off here.

2024-07-08 09:36 UTC, merged