Add tests for same origin checks in document.open()
web-platform-tests/wpt pull request #4642
Opened 2017-01-27 18:04 UTC by jeisinger

Test for whatwg/html#536 and whatwg/html#2282

2017-01-31 05:35 UTC, jeisinger commented
@zcorpan @annevk ptal

2017-01-31 10:11 UTC, annevk requested changes

2017-01-31 10:11 UTC, annevk commented on html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open.html
> +}, "It should be possible to open same origin documents when setting document.domain.");
Maybe add another one here where you open `/common/blank.html` and only set document.domain on this side?

The only problem with document.domain I think is that it's set for the whole document. So once you set it, it's set for all following tests too. So maybe it's better to have separate HTML files for the tests.

2017-01-31 15:50 UTC, jeisinger commented on html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open.html
> +}, "It should be possible to open same origin documents when setting document.domain.");
ptal

2017-02-01 09:20 UTC, annevk requested changes

2017-02-01 09:20 UTC, annevk commented on html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-document-domain-not-matching.html
> +  assert_throws("SecurityError", docOpen, "Opening a document with non-matching document.domain didn't throw");
I don't think this should throw. Why would it?

2017-02-01 09:20 UTC, annevk commented
@nox these tests might interest you.

2017-02-01 15:39 UTC, jeisinger commented on html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-document-domain-not-matching.html
> +  assert_throws("SecurityError", docOpen, "Opening a document with non-matching document.domain didn't throw");
the test has document.domain set, while /common/blank.html has not, so the "doc" is not "same origin" which is required by step 4

2017-02-01 15:55 UTC, annevk commented on html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-document-domain-not-matching.html
> +  assert_throws("SecurityError", docOpen, "Opening a document with non-matching document.domain didn't throw");
It is same origin. Same origin doesn't look at the domain part of the origin tuple.

2017-02-02 09:20 UTC, annevk reviewed
This looks okay otherwise, but we're no longer really testing the comparison.

2017-02-02 09:20 UTC, annevk commented on html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-same-origin-domain-ports.html
> +}, "It should be possible to open same origin documents (with non-matching ports).");
This should say same origin-domain, twice.

2017-02-02 16:33 UTC, jeisinger commented
done.

I agree that it's unfortunate that we can't test the security check, but as you point out on the html pr, step 4 is redundant with the security check in idl, so I don't know how to write a meaningful test for it.

2017-02-05 23:11 UTC, tobie commented
Ping @wpt-pr-bot.

2017-02-15 11:04 UTC, w3c-bots commented
# Chrome (unstable channel) #
Testing web-platform-tests at revision 61101f3c68ff4d541215830b1e91458342cb156b
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4642/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-basic.html">/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-basic.html</a></summary>


|                        Subtest                         | Results |
|--------------------------------------------------------|---------|
|                                                        | OK      |
| `It should be possible to open same origin documents.` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4642/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-same-origin-domain-ports.html">/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-same-origin-domain-ports.html</a></summary>


|                                         Subtest                                         | Results |
|-----------------------------------------------------------------------------------------|---------|
|                                                                                         | TIMEOUT |
| `It should be possible to open same origin-domain documents (with non-matching ports).` | TIMEOUT |

</details>
</details>

2017-02-15 11:04 UTC, w3c-bots commented
# Firefox (nightly channel) #
Testing web-platform-tests at revision 61101f3c68ff4d541215830b1e91458342cb156b
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>2 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4642/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-basic.html">/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-basic.html</a></summary>


|                        Subtest                         | Results |
|--------------------------------------------------------|---------|
|                                                        | OK      |
| `It should be possible to open same origin documents.` | PASS    |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4642/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-same-origin-domain-ports.html">/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/origin-check-in-document-open-same-origin-domain-ports.html</a></summary>


|                                         Subtest                                         | Results |
|-----------------------------------------------------------------------------------------|---------|
|                                                                                         | OK      |
| `It should be possible to open same origin-domain documents (with non-matching ports).` | FAIL    |

</details>
</details>

2017-02-15 14:18 UTC, annevk approved these changes
This looks good. I can merge this once I or someone else lands the HTML Standard change.

2017-02-15 15:42 UTC, merged