clipboard-api: user WebKit-infra-friendly remote URL
web-platform-tests/wpt pull request #46529
Opened 2024-05-29 05:43 UTC by marcoscaceres

2024-05-29 07:46 UTC, saschanaz commented
Can you check what exactly the URL becomes to and why WebKit fails? It's used by quite several tests that not supporting it sounds problematic.

2024-05-29 08:33 UTC, vinniespina approved these changes

2024-05-29 08:44 UTC, saschanaz requested changes
And thus request-changes.

2024-05-29 14:28 UTC, marcoscaceres commented
Webkit only supports this combination sadly. It’s a long standing issue but unfortunately not one we can fix. 

I’ll check exactly what it is tomorrow, but we use this combination everywhere in WebKit.

2024-05-29 14:42 UTC, marcoscaceres commented
@saschanaz, the tests run under `https://localhost:9443` and `https://{{hosts[alt][]}}:{{ports[https][0]}}` resolves to `https://127.0.0.1:9443`

That allows WebKit to perform cross-origin checks, while allowing the tests to be checked on the same machine.

2024-05-29 14:45 UTC, marcoscaceres commented
Here you can see in our imported tests, we had to make this change manually:
You can also grep for other tests where I've had to make this change. 

https://github.com/WebKit/WebKit/blob/main/LayoutTests/imported/w3c/web-platform-tests/clipboard-apis/feature-policy/clipboard-read/clipboard-read-enabled-on-self-origin-by-feature-policy.tentative.https.sub.html#L15

It would be great if we didn't have to do that when we import tests.

2024-05-29 14:48 UTC, marcoscaceres commented
> It's used by quite several tests that not supporting it sounds problematic.

And yeah... it's super problematic... we know 😭 . But this solves the issue for now.

2024-05-29 17:58 UTC, saschanaz commented
Oh my question was more about what `domains[www]` becomes 👀

But localhost?!?!?

2024-05-29 18:01 UTC, saschanaz commented
The CI somehow did not run wpt.fyi for chrome, any idea how to trigger that?

2024-05-29 18:07 UTC, saschanaz approved these changes
Approving, assuming this probably won't trigger disaster for Chrome.

Quickly checked and Firefox gets `www.web-platform.test` for `domains[www]` and `not-web-platform.test` for `hosts[alt][]`. Interesting ways to have cross origin domains 🙂

2024-05-30 00:34 UTC, merged

2024-05-30 00:35 UTC, marcoscaceres commented
Thanks @saschanaz. I've coordinate a lot with Chrome folks previously on changes like this, so I'm confident they will be fine.