FileAPI: Remove FileReader from Blob reading utilities
web-platform-tests/wpt pull request #46559
Opened 2024-05-31 05:18 UTC by KhafraDev

Some environments that implement Blob do not implement FileReader, forcing them to skip these tests.

For example:
https://github.com/nodejs/node/blob/main/test/wpt/status/FileAPI/blob.json#L7

2024-05-31 06:28 UTC, annevk reviewed
How confident are you that there's identical FileReader coverage elsewhere?

2024-05-31 14:56 UTC, KhafraDev commented
I took a look at as many uses of test_blob and test_blob_binary as I could find and there didn't seem to be anything special about the tests that isn't covered by the dedicated FileReader tests.

I could have missed something, but from what I remember of the FileReader tests, they adequately covered everything from here.

2024-05-31 16:46 UTC, inexorabletash requested changes
Thanks for this; obviously these tests predate the Promise helpers, but if those are supported everywhere these days and WebKit (last to implement them?) doesn't object, then this is nice simplification.

I did spot one apparent gap in current File reader coverage...

2024-05-31 16:46 UTC, inexorabletash commented on FileAPI/support/Blob.js
> -      assert_array_equals(new Uint8Array(this.result), expected);
I couldn't find another place that asserts the bytes given by `readAsArrayBuffer()` are as expected, like this does. FileAPI/reading-data-section/filereader_result.any.js is the logical place, and it validates the contents of `readAsText()`, `readAsDataURL()`, `readAsBinaryString()`, but not `readAsArrayBuffer()` - just that it is an `ArrayBuffer`.

Can you add an equivalent `assert_array_equals` over there?

2024-05-31 22:25 UTC, inexorabletash approved these changes
LGTM, thanks

2024-09-11 18:25 UTC, anonrig approved these changes

2024-09-11 18:25 UTC, merged