Import WebDriver test harness files from wptrunner
web-platform-tests/wpt pull request #4668
Opened 2017-01-31 18:56 UTC by jugglinmike

Previously, WebDriver tests were executed against a WebDriver session
that was managed by the wptrunner tool. Beyond increasing coupling
between this project's tests and that particular test runner, this
factoring made it impossible to write tests against aspects of the
WebDriver protocol that explicitly concern session management.

Update the test logic to explicitly manage connections to the WebDriver
"remote end," (made possible by the runtime specification of host name
and port number), and import the relevant logic from the wptrunner
project.

This depends on https://github.com/w3c/wptrunner/pull/233.

2017-01-31 18:58 UTC, jugglinmike commented on webdriver/util/cleanup.py
> +# You can obtain one at http://mozilla.org/MPL/2.0/.
@jgraham Is this license compatible with this project? If not, could we resolve this with a commit authored by you to remove it?

2017-01-31 23:32 UTC, andreastt commented on webdriver/util/cleanup.py
> +# You can obtain one at http://mozilla.org/MPL/2.0/.
I wrote this code. I hereby relinquish any rights I have on the code to the WPT project default license.

2017-01-31 23:34 UTC, andreastt requested changes

2017-01-31 23:34 UTC, andreastt commented on webdriver/conftest.py
> +import util.cleanup as cleanup
This seems redundant.

2017-01-31 23:34 UTC, andreastt commented on webdriver/conftest.py
> +        if session.session_id:
`is not None`

2017-02-01 15:33 UTC, jugglinmike commented on webdriver/util/cleanup.py
> +# You can obtain one at http://mozilla.org/MPL/2.0/.
Ah, thanks!

2017-02-01 15:33 UTC, jugglinmike commented on webdriver/conftest.py
> +        if session.session_id:
Sorry, still getting a hang of that detail in Python.

2017-02-01 15:35 UTC, jugglinmike commented on webdriver/conftest.py
> +import util.cleanup as cleanup
Do you mean the general pattern (e.g. importing the module and defining the fixture here) or the specific aliasing (e.g. `as cleanup`)?

2017-02-01 15:48 UTC, andreastt commented on webdriver/conftest.py
> +import util.cleanup as cleanup
Sorry, I meant you could just do `from util import cleanup`.

2017-02-01 15:52 UTC, andreastt commented
I also wonder if we should find a better name than `util`. I don’t want to create another kitchen sink.

2017-02-01 17:40 UTC, jugglinmike commented
> I also wonder if we should find a better name than util. I don’t want to
> create another kitchen sink.

I'd suggest `fixtures/`, but I'm anticipating a few more utilities for future
tests. For instance, despite its small size, the `inline` function will be good
to share between many files. Another example is domain-specific assertions.

We could just dump them in the `webdriver/` directory, but I'm pretty averse to
mixing files containing tests with non-test files (even if Pytest is clever
enough to sort out the difference). Would you feel any better about something
like this:

    - webdriver/
      |`- tests/
      |   |`navigation.py
      |    `contexts.py
      |`- fixtures/
      |   `cleanup.py
      |`- inline.py
       `- assert.py

2017-02-03 15:35 UTC, jugglinmike commented
@andreastt I know that my proposal above kind of makes the `webdriver/` directory itself a sort of "kitchen sink," but I'm open to suggestion for alternatives!

2017-02-03 16:10 UTC, andreastt approved these changes

2017-02-03 16:10 UTC, andreastt commented
I think your proposal for document structure makes sense, although I would like the tests to be directly under /webdriver. They are the focus of attention and it should be clear to contributors where to find them.

I don’t however think we need to fix that immediately in this PR. It can come later.

2017-02-03 16:14 UTC, merged

2017-02-03 16:29 UTC, jugglinmike commented
Thanks, Andreas!