Put subsuites with a few tests in one group
web-platform-tests/wpt pull request #47423
Opened 2024-08-01 22:54 UTC by WeizhongX

As we will need to restart the browser when starting a new subsuite, putting tests in one group can help reduce the number of restarts needed.

Keep an up limit of the size of such a group, so that we do not create a huge group that could potentially cause a worker to out live all other workers, thus increase the run time.

Bug: https://buganizer.corp.google.com/issues/341581718

2024-08-06 10:42 UTC, jgraham requested changes
The obvious feedback here is that the subsuite configuration should be allowed to decide, rather than having a hardcoded number. Even if there isn't per-subsuite configuration there should be a way to change this value from the command line.

2024-08-06 14:52 UTC, WeizhongX commented
Having a command line argument sounds good to me.

2024-08-13 22:34 UTC, WeizhongX commented
@jgraham, can you take another look at this? Thanks!

2024-09-13 22:46 UTC, jonathan-j-lee approved these changes

2024-09-13 22:46 UTC, jonathan-j-lee commented on tools/wptrunner/wptrunner/wptcommandline.py
> +                                      help="Maximum number of tests a subsuite can have to be treated as small subsuite."
```suggestion
                                      help="Maximum number of tests a subsuite can have to be treated as small subsuite. "
```

2024-09-16 14:32 UTC, jgraham approved these changes
OK, but see some suggested small refactors to avoid repeating code that does the same thing.

2024-09-16 14:32 UTC, jgraham commented on tools/wptrunner/wptrunner/testloader.py
> +                    test.update_metadata(metadata)
This bit is exactly like the loop below. Can you make the entire bit something like:

```py
in_one_group = self.in_one_group(subsuite, tests)
if in_one_group:
    state["prev_group_key"] = (subsuite, test_type, [""])
    group_metadata = self.group_metadata(state)
    groups.append(TestGroup(deque(), subsuite, test_type, group_metadata))

for test in tests:
    if not in_one_group and self.new_group(state, subsuite, test_type, group_metadata):
        group_metadata = self.group_metadata(state)
        groups.append(TestGroup(deque(), subsuite, test_type, group_metadata))

    group, _, _, metadata = groups[-1]
    group.append(test)
    test.update_metadata(metadata)
````

2024-09-16 14:32 UTC, jgraham commented on tools/wptrunner/wptrunner/testloader.py
> +                continue
Similar comment, or at least use an `else` rather than a `continue`.

2024-09-17 11:28 UTC, jgraham approved these changes

2024-09-17 14:50 UTC, merged