Update base.py
web-platform-tests/wpt pull request #47531
Opened 2024-08-08 21:25 UTC by lilfry14

exception.message was deprecated.

Could also go with getattr(e, "message", "")  if this is the intent as it seems ExecutorException has a message field.

https://peps.python.org/pep-0352/

2024-08-09 07:43 UTC, foolip reviewed
From https://peps.python.org/pep-0352/ it looks like `message` has been deprecated since Python 2.5. Can't we always use `str(e)` or will that return a different string?

Since this has the potential to change error messages and make debugging harder, I think I'll defer this review to @jgraham who probably wrote the code :)

2024-08-09 15:57 UTC, lilfry14 commented
> From https://peps.python.org/pep-0352/ it looks like `message` has been deprecated since Python 2.5. Can't we always use `str(e)` or will that return a different string?

So I encountered the "no attribute message" when updating to python 3.11
As an FYI, there's also line https://github.com/web-platform-tests/wpt/blob/master/tools/wptrunner/wptrunner/executors/base.py#L359

Which on python3.11 would possibly always return ""  if the field doesn't work anymore. Since ExecutorException has a message field though I didn't want to mess with stuff that could potentially do something intended.

2024-08-12 17:36 UTC, lilfry14 commented
Any update on this?

2024-08-14 19:55 UTC, WeizhongX commented
Thanks, looks like there are other usage of Exception.message.

$ grep message ./ -rn | grep getattr
./wptrunner/executors/executorwebdriver.py:632:            message = str(getattr(e, "message", ""))
./wptrunner/executors/executorwebdriver.py:679:            message = str(getattr(e, "message", ""))
./wptrunner/executors/executorwebdriver.py:714:                message = str(getattr(e, "message", ""))
./wptrunner/executors/executorservo.py:270:            message = getattr(e, "message", "")
./wptrunner/executors/executorselenium.py:327:            message = str(getattr(e, "message", ""))
./wptrunner/executors/executorservodriver.py:152:            message = getattr(e, "message", "")
./wptrunner/executors/executorservodriver.py:264:            message = getattr(e, "message", "")
./wptrunner/executors/base.py:359:        message = str(getattr(e, "message", ""))
./wptrunner/executors/base.py:718:            message = getattr(e, "message")
./wptrunner/executors/executormarionette.py:915:                message = getattr(e, "message", "")

2024-08-16 18:30 UTC, lilfry14 commented
> Thanks, looks like there are other usage of Exception.message.
> 
> $ grep message ./ -rn | grep getattr ./wptrunner/executors/executorwebdriver.py:632: message = str(getattr(e, "message", "")) ./wptrunner/executors/executorwebdriver.py:679: message = str(getattr(e, "message", "")) ./wptrunner/executors/executorwebdriver.py:714: message = str(getattr(e, "message", "")) ./wptrunner/executors/executorservo.py:270: message = getattr(e, "message", "") ./wptrunner/executors/executorselenium.py:327: message = str(getattr(e, "message", "")) ./wptrunner/executors/executorservodriver.py:152: message = getattr(e, "message", "") ./wptrunner/executors/executorservodriver.py:264: message = getattr(e, "message", "") ./wptrunner/executors/base.py:359: message = str(getattr(e, "message", "")) ./wptrunner/executors/base.py:718: message = getattr(e, "message") ./wptrunner/executors/executormarionette.py:915: message = getattr(e, "message", "")

Okay, changed all those references to str(e)

2024-08-21 17:46 UTC, WeizhongX commented
jonathan, can you help take a look at this?

2024-08-21 19:09 UTC, jonathan-j-lee requested changes
Sorry for contradicting the earlier review, but I think only changing `getattr(e, "message")` to `getattr(e, "message", "")` in `base.py` would be better.

I believe these `getattr(e, "message", "")` are meant to retrieve a [spec-defined] field from
[`WebDriverException`][1] or [`BidiException`][2]. Most callsites are also already adding the `str(...)`
of `WebDriverException` via `traceback.format_exc()`. That `str(...)` adds a
lengthy stacktrace, so we should avoid repeating it.

[1]: https://github.com/web-platform-tests/wpt/blob/2fd0573aaf9f954bd96a001c2b2030b20802a126/tools/webdriver/webdriver/error.py#L25
[2]: https://github.com/web-platform-tests/wpt/blob/2fd0573aaf9f954bd96a001c2b2030b20802a126/tools/webdriver/webdriver/bidi/error.py#L17
[spec-defined]: https://www.w3.org/TR/webdriver/#errors

2024-08-21 23:34 UTC, lilfry14 commented
Okay, latest patch should be just the minimal change.

2024-08-22 00:44 UTC, jonathan-j-lee approved these changes
Thanks!

2024-08-27 18:45 UTC, jonathan-j-lee commented
Since this fix is straightforward, I will go ahead and merge this to unblock [Chromium's py3.8 &rightarrow; py3.11 migration][1].

[1]: https://chromium-review.googlesource.com/c/chromium/src/+/5629964/comment/f524b541_6d854d77/

2024-08-27 18:46 UTC, merged