[payment-request] show() acceptPromise returned
web-platform-tests/wpt pull request #4768
Opened 2017-02-08 23:32 UTC by stan-stripe

Add a test to the payment-request directory that tests that the acceptPromise is created and returned when show() is called on a PaymentRequest.

2017-02-08 23:37 UTC, w3c-bots commented
# Chrome (unstable channel) #
Testing web-platform-tests at revision 62e45ff4ede58d584b645e65016447e625d5474e
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/4768/payment-request/payment-request-show-accept-promise-returned.html">/payment-request/payment-request-show-accept-promise-returned.html</a></summary>


| Subtest | Results |
|---------|---------|
|         | TIMEOUT |

</details>

2017-02-08 23:37 UTC, w3c-bots commented
# Firefox (nightly channel) #
Testing web-platform-tests at revision 62e45ff4ede58d584b645e65016447e625d5474e
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary><a href="http://w3c-test.org/submissions/4768/payment-request/payment-request-show-accept-promise-returned.html">/payment-request/payment-request-show-accept-promise-returned.html</a></summary>


| Subtest | Results |
|---------|---------|
|         | TIMEOUT |

</details>

2017-02-09 06:42 UTC, sideshowbarker commented
w3c-test:mirror

2017-02-09 07:19 UTC, sideshowbarker requested changes

2017-02-09 07:19 UTC, sideshowbarker commented on payment-request/payment-request-show-accept-promise-returned.html
> +});
You’re missing a needed `</script>` end tag here.

2017-02-09 07:19 UTC, sideshowbarker commented on payment-request/payment-request-show-accept-promise-returned.html
> +    let pr = new PaymentRequest(paymentArgs)
The`PaymentRequest` constructor requires at least two separate arguments: a _methodData_ argument and a _details_ argument, but this is feeding it a single array as an argument.

2017-02-24 20:04 UTC, w3c-bots commented
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/4768)

2017-02-24 20:05 UTC, stan-stripe commented
@sideshowbarker PTAL

Are the tests idiomatic? Happy to use other constructs as adequate.

2017-02-24 20:09 UTC, stan-stripe commented
These tests pass using the reference implementation as Chrome extension available here: https://github.com/stan-stripe/js-payment-request

2017-03-09 14:18 UTC, ianbjacobs commented
Hi gents, I was just checking to see how this is going! I see the tests are available on w3c-test.org; that sounds cool.

2017-03-09 16:04 UTC, stan-stripe commented
@ianbjacobs waiting on review from @sideshowbarker at this stage

2017-03-10 03:19 UTC, sideshowbarker commented
I will try to get the review on this done today

2017-03-10 06:08 UTC, sideshowbarker commented
Do you know why the `frame` and `object` and `embed` tests in https://w3c-test.org/submissions/4768/payment-request/allowpaymentrequest/allowpaymentrequest-attribute-same-origin-bc-containers.https.html are failing?

2017-03-10 06:27 UTC, sideshowbarker commented
All these have tests that are failing. They’re all throwing.

* https://w3c-test.org/submissions/4768/payment-request/allowpaymentrequest/allowpaymentrequest-attribute-same-origin-bc-containers.https.html
* https://w3c-test.org/submissions/4768/payment-request/allowpaymentrequest/no-attribute-same-origin-bc-containers.https.html
* https://w3c-test.org/submissions/4768/payment-request/allowpaymentrequest/removing-allowpaymentrequest.https.sub.html
* https://w3c-test.org/submissions/4768/payment-request/allowpaymentrequest/setting-allowpaymentrequest-timing.https.sub.html
* https://w3c-test.org/submissions/4768/payment-request/allowpaymentrequest/setting-allowpaymentrequest.https.sub.html

I’ve not had time to look at them in detail yet to determine why.

2017-03-10 06:28 UTC, sideshowbarker submitted a review, later dismissed

2017-03-10 09:41 UTC, sideshowbarker commented
Please change the `echo-PaymentRequest.html` filename to `echo-PaymentRequest-support.html`.

That will cause the manifest generator to recognize it as a support file rather than treating it as a test.

2017-06-01 08:19 UTC, marcoscaceres commented
@stan-stripe OMG, I'm so so so terribly sorry! I just found these tests. We've added a bunch of new tests that cover these exact cases. Darn :( this could have saved us some time and duplication.

@stan-stripe Would you like to be part of the testing effort still? We really need more reviewers and people to help us with additional tests.

2017-06-01 08:19 UTC, closed without merging