fix check_stability script to work without TRAVIS_REPO_SLUG env var
web-platform-tests/wpt pull request #4809
Opened 2017-02-13 13:47 UTC by bobholt

allows local running of check_stability.py for testing

I considered moving the `split` out of the default declaration and into the body of the script, because it's kind of a bear, but that would require passing `--user w3c/` instead of the more sensible `--user w3c` when running from the command line.

2017-02-13 13:54 UTC, w3c-bots commented
# Chrome (unstable channel) #
Testing web-platform-tests at revision b73b1ca1691e84fcedb750aa8f36223e81500af0
Using browser at version 58.0.3004.3 dev
Starting 10 test iterations
No tests run.

2017-02-13 13:54 UTC, w3c-bots commented
# Firefox (nightly channel) #
Testing web-platform-tests at revision b73b1ca1691e84fcedb750aa8f36223e81500af0
Using browser at version BuildID 20170123125947; SourceStamp 36486fdc3813ef7943ae5b07b4128866d1938a6c
Starting 10 test iterations
No tests run.

2017-02-13 16:25 UTC, jgraham requested changes

2017-02-13 16:25 UTC, jgraham commented on check_stability.py
> +                        default=(os.environ.get("TRAVIS_REPO_SLUG") or "").split('/')[0],
This doesn't really make sense, does it? If you don't pass anything here you will get a runtime error. So we should either check that or make the default `w3c` i.e. 

`default=os.environ.get("TRAVIS_REPO_SLUG", "w3c").split("/")[0]`

2017-02-13 16:25 UTC, sideshowbarker submitted a review, later dismissed

2017-02-14 12:11 UTC, bobholt commented
Good point, @jgraham. Updated.

2017-04-03 15:24 UTC, jugglinmike commented on check_stability.py
> +                        default=(os.environ.get("TRAVIS_REPO_SLUG") or "w3c").split('/')[0],
It's probably more idiomatic to use `get`'s second parameter here:

```diff
-  default=os.environ.get("TRAVIS_REPO_SLUG").split('/')[0],
+  default=os.environ.get("TRAVIS_REPO_SLUG", "w3c").split('/')[0],
```

2017-04-03 16:11 UTC, bobholt commented on check_stability.py
> +                        default=(os.environ.get("TRAVIS_REPO_SLUG") or "w3c").split('/')[0],
Why do I keep doing this?

2017-04-03 16:13 UTC, w3c-bots commented
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/4809/)

2017-04-06 18:07 UTC, merged