[WebDriver BiDi] Mark iframe screenshot test as optional
web-platform-tests/wpt pull request #48494
Opened 2024-10-07 08:35 UTC by sadym-chromium

As discussed on TPAC 2024 and in https://github.com/w3c/webdriver-bidi/issues/441, mark the iframe screenshot WebDrive BiDi tests as optional.

2024-10-08 12:24 UTC, juliandescottes requested changes
At least in mozilla central, we can't run tests with filenames which include 2 dots. Initially we wanted to use this pattern for tentative tests: "testname.tentative.py", but we ended up with "testname_tentative.py"

Testing locally, I have the same issue with the proposed change here. Also maybe I missed part of that discussion, but is there a reason to prefer "optional" over "tentative" here?

2024-10-15 13:29 UTC, OrKoN requested changes
let's use _tentative like for other files

2024-10-15 13:32 UTC, sadym-chromium commented
> let's use _tentative like for other files

done

2024-10-15 13:34 UTC, OrKoN approved these changes

2024-10-15 13:55 UTC, juliandescottes approved these changes

2024-10-15 13:55 UTC, merged