Test change document location while navigating
web-platform-tests/wpt pull request #48751
Opened 2024-10-22 13:43 UTC by sadym-chromium

Repro of https://github.com/GoogleChromeLabs/chromium-bidi/issues/2709.

2024-10-23 13:23 UTC, juliandescottes commented on webdriver/tests/bidi/browsing_context/navigate/navigate_tentative.py
> +    assert result["url"] == new_url
By definition, one of the two tests will necessarily fail. Given that both chrome and firefox pass test_interactive_change_location_throws at the moment, maybe we should only keep this one and updated when the spec is clarified?

2024-12-04 09:40 UTC, juliandescottes requested changes
I was looking at the two similar tests in bidi/browsing_context/navigation_failed/navigation_failed.py, at the moment they expect a `navigationFailed` event for similar scenarios. If I understand the spec change correctly, this also wrong? Can you check if they need updating?

2024-12-04 12:29 UTC, sadym-chromium commented
> I was looking at the two similar tests in bidi/browsing_context/navigation_failed/navigation_failed.py, at the moment they expect a `navigationFailed` event for similar scenarios. If I understand the spec change correctly, this also wrong? Can you check if they need updating?

I'm working on it from the implementation side: https://github.com/GoogleChromeLabs/chromium-bidi/issues/2856

2024-12-05 09:39 UTC, juliandescottes commented
> > I was looking at the two similar tests in bidi/browsing_context/navigation_failed/navigation_failed.py, at the moment they expect a `navigationFailed` event for similar scenarios. If I understand the spec change correctly, this also wrong? Can you check if they need updating?
> 
> I'm working on it from the implementation side: [GoogleChromeLabs/chromium-bidi#2856](https://github.com/GoogleChromeLabs/chromium-bidi/issues/2856)

Does this mean you will also update those tests here or will it be another PR?

2024-12-16 22:24 UTC, sadym-chromium commented
closing in favor of https://github.com/web-platform-tests/wpt/pull/49718

2024-12-16 22:24 UTC, closed without merging