DOMException: Add test for Error.isError
web-platform-tests/wpt pull request #49133
Opened 2024-11-13 03:09 UTC by lionel-rowe

Supersedes https://github.com/tc39/test262/pull/4322

2024-11-13 06:04 UTC, domenic requested changes

2024-11-13 06:04 UTC, domenic commented on webidl/ecmascript-binding/es-exceptions/DOMException-is-error.any.js
> +  if (typeof Error.isError === 'function') {
This should not be conditional.

2024-11-13 08:54 UTC, domenic approved these changes
LGTM. When https://github.com/whatwg/webidl/pull/1421 is ready to merge, we can merge this.

2024-11-14 00:15 UTC, ptomato commented on webidl/ecmascript-binding/es-exceptions/DOMException-is-error.any.js
> +'use strict';
Consider adding this:

```suggestion
// META: global=window,dedicatedworker,shadowrealm

'use strict';
```

(see #49159)

2024-12-12 22:12 UTC, syg commented
This should be good to merge, yeah? Would like to see these synced up to chromium so I don't have to write my own tests.

2024-12-13 03:06 UTC, merged