[wptrunner] Add a wpewebkit_minibrowser product/browser.
web-platform-tests/wpt pull request #49268
Opened 2024-11-19 18:58 UTC by clopez

This adds a new browser type to run tests with the WPE WebKit port. It can be passed an optional `--headless` parameter to enable headless testing with WPT. Otherwise wayland is required.

A pre-built nightly bundle can be also automatically downloaded and installed by passing `--install-browser` to the WPT runner. It shares with webkitgtk_minibrowser most of the logic to download and install the built product.

Documentation is also added and the webkitgtk_minibrowser one updated accordingly.

2024-11-26 14:01 UTC, Ms2ger requested changes

2024-11-26 15:15 UTC, clopez commented on tools/wpt/browser.py
> -from shutil import which
The reason is that above (line 5) it is already doing an `import shutil` so it feels like redundant to me to do an import of `which` two times, one as `shutil.which` and another one as `which`. It feels like cleaner code to just import it once, don't you think?

2024-11-26 15:18 UTC, Ms2ger commented on tools/wpt/browser.py
> -from shutil import which
Don't feel strongly, but would prefer not mixing it into this PR

2024-11-26 15:36 UTC, clopez commented on tools/wpt/browser.py
> -from shutil import which
allright, fair enough, will move that to another PR

2024-11-26 16:45 UTC, clopez commented on tools/wpt/browser.py
>  class WebKitGTKMiniBrowser(WebKit):
ok, let's do that.. that way is clearer to anyone modifying the gtk class that it can affect the wpe one

2024-11-27 13:42 UTC, Ms2ger approved these changes
Thanks!

2024-11-27 15:51 UTC, merged