Create figure-name-no-figcaption.tentative.html
web-platform-tests/wpt pull request #49647
Opened 2024-12-11 21:40 UTC by scottaohara

a figcaption should not provide a name to a figure element per https://github.com/w3c/aria/pull/2224

2024-12-13 20:15 UTC, cookiecrook requested changes
2 of the 5 tests seem like incorrect expectations to me. See comments.

Update: Scott and I chatted, and are working on a updated that will account for [this HTML text](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element):

> 2. If the image is a descendant of a figure element that has a child figcaption element, and, ignoring the figcaption element and its descendants, the figure element has no [flow content](https://html.spec.whatwg.org/multipage/dom.html#flow-content-2) descendants other than [inter-element whitespace](https://html.spec.whatwg.org/multipage/dom.html#inter-element-whitespace) and the img element, then return the contents of the first such figcaption element.

2024-12-13 20:15 UTC, cookiecrook commented on html-aam/figure-name-no-figcaption.tentative.html
> +<figure data-testname="figure with figcaption and title" title="title" data-expectedlabel="title" class="ex">
Why would we expect title to override the actual `figcaption` here? Firefox and WebKit both agree on the figcaption result.

2024-12-13 20:15 UTC, cookiecrook commented on html-aam/figure-name-no-figcaption.tentative.html
> +<figure data-testname="figure with figcaption - no name" data-expectedlabel="" class="ex">
Why would we expect title to ignore the actual `figcaption` here? Firefox and WebKit both agree on the figcaption result.

2024-12-13 20:20 UTC, cookiecrook commented
also flagged that in the spec PR: https://github.com/w3c/aria/pull/2224#pullrequestreview-2503186046

2025-04-03 17:29 UTC, jnurthen commented on html-aam/figure-name-no-figcaption.tentative.html
> +  <figcaption>y</figcaption>
```suggestion
  <figcaption>y</figcaption>
```

2025-04-03 18:15 UTC, cookiecrook approved these changes

2025-04-03 18:16 UTC, merged