Replace usage of setTimeout with step_timeout in workers/
web-platform-tests/wpt pull request #4984
Opened 2017-02-22 17:16 UTC by gsnedders

This is expected to help test stability on slow configurations, as the
timeouts will be multiplied by the timeout multiplier.

Split out from #1816.

2017-02-22 19:28 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204279379)

# Firefox (nightly channel) #
Testing web-platform-tests at revision b85da5286ca6da6880ff961824d87375030e767e
Using browser at version BuildID 20170221110300; SourceStamp d84beb192e57e26846c82d3df3599381f4663792
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>20 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/WorkerGlobalScope_close.htm">/workers/WorkerGlobalScope_close.htm</a></summary>


|                      Subtest                      | Results | Messages |
|---------------------------------------------------|---------|----------|
|                                                   | OK      |          |
| ` WorkerGlobalScope close(): clear events queue ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/WorkerGlobalScope_setInterval.htm">/workers/WorkerGlobalScope_setInterval.htm</a></summary>


|                 Subtest                  | Results | Messages |
|------------------------------------------|---------|----------|
|                                          | OK      |          |
| ` WorkerGlobalScope API: setInterval() ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/WorkerGlobalScope_setTimeout.htm">/workers/WorkerGlobalScope_setTimeout.htm</a></summary>


|                 Subtest                 | Results | Messages |
|-----------------------------------------|---------|----------|
|                                         | OK      |          |
| ` WorkerGlobalScope API: setTimeout() ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/Worker_terminate_event_queue.htm">/workers/Worker_terminate_event_queue.htm</a></summary>


|                      Subtest                      | Results | Messages |
|---------------------------------------------------|---------|----------|
|                                                   | OK      |          |
| ` AbstractWorker terminate(): clear event queue ` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/constructors/SharedWorker/global-members.html">/workers/constructors/SharedWorker/global-members.html</a></summary>


|               Subtest                | Results |                                               Messages                                              |
|--------------------------------------|---------|-----------------------------------------------------------------------------------------------------|
|                                      | OK      |                                                                                                     |
| `members of SharedWorkerGlobalScope` | FAIL    | `assert_equals: expected "" but got "applicationCache did not exist\nstep_timeout did not exist\n"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/constructors/Worker/terminate.html">/workers/constructors/Worker/terminate.html</a></summary>


|    Subtest    | Results | Messages |
|---------------|---------|----------|
|               | OK      |          |
| `terminate()` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/interfaces/DedicatedWorkerGlobalScope/postMessage/structured-clone-message.html">/workers/interfaces/DedicatedWorkerGlobalScope/postMessage/structured-clone-message.html</a></summary>


|            Subtest            | Results | Messages |
|-------------------------------|---------|----------|
|                               | OK      |          |
| `structured clone of message` | PASS    |          |
| `undefined`                   | PASS    |          |
| `null`                        | PASS    |          |
| `false`                       | PASS    |          |
| `true`                        | PASS    |          |
| `1`                           | PASS    |          |
| `NaN`                         | PASS    |          |
| `Infinity`                    | PASS    |          |
| `string`                      | PASS    |          |
| `date`                        | PASS    |          |
| `regexp`                      | PASS    |          |
| `self`                        | PASS    |          |
| `array`                       | PASS    |          |
| `object`                      | PASS    |          |
| `error`                       | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/interfaces/WorkerGlobalScope/close/incoming-message.html">/workers/interfaces/WorkerGlobalScope/close/incoming-message.html</a></summary>


|            Subtest             | Results | Messages |
|--------------------------------|---------|----------|
|                                | OK      |          |
| `close() and incoming message` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/interfaces/WorkerGlobalScope/close/setInterval.html">/workers/interfaces/WorkerGlobalScope/close/setInterval.html</a></summary>


|          Subtest          | Results |                                      Messages                                     |
|---------------------------|---------|-----------------------------------------------------------------------------------|
|                           | OK      |                                                                                   |
| `close() and setInterval` | FAIL    | `uncaught exception: Error: assert_unreached: Got error Reached unreachable code` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/interfaces/WorkerGlobalScope/close/setTimeout.html">/workers/interfaces/WorkerGlobalScope/close/setTimeout.html</a></summary>


|         Subtest          | Results |                                      Messages                                     |
|--------------------------|---------|-----------------------------------------------------------------------------------|
|                          | OK      |                                                                                   |
| `close() and setTimeout` | FAIL    | `uncaught exception: Error: assert_unreached: Got error Reached unreachable code` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/interfaces/WorkerGlobalScope/onerror/handled.html">/workers/interfaces/WorkerGlobalScope/onerror/handled.html</a></summary>


|       Subtest        | Results | Messages |
|----------------------|---------|----------|
|                      | OK      |          |
| `onerror, "handled"` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/interfaces/WorkerUtils/WindowTimers/001.html">/workers/interfaces/WorkerUtils/WindowTimers/001.html</a></summary>


|    Subtest     | Results | Messages |
|----------------|---------|----------|
|                | OK      |          |
| `step_timeout` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/interfaces/WorkerUtils/WindowTimers/002.html">/workers/interfaces/WorkerUtils/WindowTimers/002.html</a></summary>


|    Subtest     | Results | Messages |
|----------------|---------|----------|
|                | OK      |          |
| `clearTimeout` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/4984/workers/interfaces/WorkerUtils/WindowTimers/004.html">/workers/interfaces/WorkerUtils/WindowTimers/004.html</a></summary>


|     Subtest     | Results | Messages |
|-----------------|---------|----------|
|                 | OK      |          |
| `clearInterval` | PASS    |          |

</details>
< [...]

2017-02-22 19:28 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/204279383)

# Chrome (unstable channel) #
Testing web-platform-tests at revision b85da5286ca6da6880ff961824d87375030e767e
Using browser at version 58.0.3013.3 dev
Starting 10 test iterations

2017-02-23 11:47 UTC, zcorpan requested changes

2017-02-23 11:47 UTC, zcorpan commented on workers/constructors/SharedWorker/global-members.html
> +var expected = 'self location close onerror importScripts navigator addEventListener removeEventListener dispatchEvent name applicationCache onconnect step_timeout clearTimeout setInterval clearInter
Revert this

2017-02-23 11:47 UTC, zcorpan commented on workers/interfaces/WorkerUtils/WindowTimers/001.html
> +<title>step_timeout</title>
Revert this

2017-02-23 11:47 UTC, zcorpan commented on workers/semantics/reporting-errors/001.html
> +  timeout = step_timeout(function() { port.postMessage('self.onerror was not invoked'); }, 250);
This won't work without rewriting the test

2017-02-23 11:47 UTC, zcorpan commented on workers/semantics/reporting-errors/002.html
> +  timeout = step_timeout(function() { port.postMessage('No error event fired'); }, 250);
This won't work without rewriting the test

2017-02-23 11:47 UTC, zcorpan commented on workers/semantics/reporting-errors/003.html
> +  step_timeout(function() { e.ports[0].postMessage(''); }, 250);
This won't work without rewriting the test

2017-02-23 11:47 UTC, zcorpan commented on workers/semantics/reporting-errors/004.html
> +  step_timeout(function() { e.ports[0].postMessage(i); }, 250);
This won't work without rewriting the test

2017-10-22 22:47 UTC, gsnedders commented
Closing without prejudice; we need to fix lots of failing lints but this PR to fix it isn't going anywhere.

2017-10-22 22:47 UTC, closed without merging