Stop the stability checker running on multiple commits on master.
web-platform-tests/wpt pull request #5196
Opened 2017-03-22 12:22 UTC by jgraham

The stability checker tried to work out which commits to test by
looking at all the commits on the current branch that aren't on
another branch. But if the current branch is e.g. master then this
will produce many more commits than intended. To fix this use the
merge-base with master when it's closer to HEAD than the last commit
not on another branch.

2017-03-22 12:22 UTC, w3c-bots commented
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5196/)

2017-03-22 12:28 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213807706)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 87edb59c7438ebe3b8796d634b1ae0e74ef1d15e
Using browser at version BuildID 20170321110237; SourceStamp ca4ae502156eaea6fffb296bb9c3b3930af8ab58
Using browser at version BuildID 20170321110237; SourceStamp ca4ae502156eaea6fffb296bb9c3b3930af8ab58
Starting 10 test iterations
Starting 10 test iterations
No tests run.

2017-03-22 12:28 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213807707)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 87edb59c7438ebe3b8796d634b1ae0e74ef1d15e
Using browser at version 59.0.3047.0 dev
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
Starting 10 test iterations
No tests run.

2017-03-22 16:33 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213904513)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 13094b03638ea1cd029c4ac8e58506a0df556284
Using browser at version BuildID 20170321110237; SourceStamp ca4ae502156eaea6fffb296bb9c3b3930af8ab58
Using browser at version BuildID 20170321110237; SourceStamp ca4ae502156eaea6fffb296bb9c3b3930af8ab58
Starting 10 test iterations
Starting 10 test iterations
No tests run.

2017-03-22 16:33 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/213904515)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 13094b03638ea1cd029c4ac8e58506a0df556284
Using browser at version 59.0.3047.0 dev
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
Starting 10 test iterations
No tests run.

2017-03-22 17:31 UTC, jugglinmike requested changes
What a complicated situation! I verified this locally by:

1. applying your changes to my local `master` branch
2. disabling the `fetch_wpt` function
3. adding two empty commits to my local `master` branch
4. pushing my local `master` branch to my "origin" remote (my fork of the project)
5. running the stability checker

In this case, the stability checker identified the "branch point" as the first of
the two commits I added in step 3 (whereas with the change disabled, it
identifies the *parent* of that commit).

There's just one small technical issue to resolve.

2017-03-22 17:31 UTC, jugglinmike commented on check_stability.py
> +        # preceeding changes that were rebased and so aren't on any other branch. To avoid
Typo: "preceding"

2017-03-24 19:49 UTC, merged

2017-03-24 19:49 UTC, jugglinmike commented
Thanks, James!