HTML: test coverage 7.1.5: `_top`, `_self`, existing contexts
web-platform-tests/wpt pull request #5233
Opened 2017-03-27 19:07 UTC by lyzadanger

This PR is the final set of related test-coverage work on 7.1.5 Browsing Context Names.

This set of tests pertains to:

* `_top` named context
* `_self` named context
* The selection of existing contexts

It also takes care of some needed housekeeping and organization.

Unsurprisingly, the case-sensitivity issue for Webkit, Chrome is manifest again in `_top` and `_self`; I'll open bugs accordingly.

2017-03-27 19:07 UTC, w3c-bots commented
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5233/)

2017-03-27 19:49 UTC, lyzadanger commented
`_top`, `_self` case-sensitivity:

* Webkit bug: https://bugs.webkit.org/show_bug.cgi?id=170128
* Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=705646

2017-03-27 22:00 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/215656435)

# Firefox (nightly channel) #
Testing web-platform-tests at revision abe54d7bf90939ace4fc5378131f764ede2ba884
Using browser at version BuildID 20170326110231; SourceStamp f5e214144799889e2408c4841351f4053f00544e
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>15 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_blank-001.html">/html/browsers/windows/browsing-context-names/choose-_blank-001.html</a></summary>


|                                 Subtest                                  | Results | Messages |
|--------------------------------------------------------------------------|---------|----------|
|                                                                          | OK      |          |
| `window.open into _blank should create a new browsing context each time` | PASS    |          |
| `_blank should be ASCII case-insensitive`                                | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_blank-002.html">/html/browsers/windows/browsing-context-names/choose-_blank-002.html</a></summary>


|                                          Subtest                                           | Results | Messages |
|--------------------------------------------------------------------------------------------|---------|----------|
|                                                                                            | OK      |          |
| `Context for opened noreferrer link targeted to "_blank" should not have opener reference` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_blank-003.html">/html/browsers/windows/browsing-context-names/choose-_blank-003.html</a></summary>


|                                   Subtest                                   | Results | Messages |
|-----------------------------------------------------------------------------|---------|----------|
|                                                                             | OK      |          |
| `Context created by link targeting "_blank" should retain opener reference` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_parent-001.html">/html/browsers/windows/browsing-context-names/choose-_parent-001.html</a></summary>


|                                  Subtest                                  | Results | Messages |
|---------------------------------------------------------------------------|---------|----------|
|                                                                           | OK      |          |
| `The parent browsing context must be chosen if the given name is _parent` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_parent-002.html">/html/browsers/windows/browsing-context-names/choose-_parent-002.html</a></summary>


|                       Subtest                        | Results | Messages |
|------------------------------------------------------|---------|----------|
|                                                      | OK      |          |
| `choosing _parent context: multiple nested contexts` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_parent-003.html">/html/browsers/windows/browsing-context-names/choose-_parent-003.html</a></summary>


|                   Subtest                    | Results |     Messages     |
|----------------------------------------------|---------|------------------|
|                                              | TIMEOUT |                  |
| `_parent should reuse window.parent context` | TIMEOUT | `Test timed out` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_parent-004.html">/html/browsers/windows/browsing-context-names/choose-_parent-004.html</a></summary>


|                        Subtest                        | Results | Messages |
|-------------------------------------------------------|---------|----------|
|                                                       | OK      |          |
| `choosing _parent context should be case-insensitive` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_self-001.html">/html/browsers/windows/browsing-context-names/choose-_self-001.html</a></summary>


|                                  Subtest                                   | Results | Messages |
|----------------------------------------------------------------------------|---------|----------|
|                                                                            | OK      |          |
| `The current browsing context must be chosen if the given name is "_self"` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_self-002.html">/html/browsers/windows/browsing-context-names/choose-_self-002.html</a></summary>


|                       Subtest                       | Results | Messages |
|-----------------------------------------------------|---------|----------|
|                                                     | OK      |          |
| `choosing _self context should be case-insensitive` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_top-001.html">/html/browsers/windows/browsing-context-names/choose-_top-001.html</a></summary>


|                                Subtest                                | Results | Messages |
|-----------------------------------------------------------------------|---------|----------|
|                                                                       | OK      |          |
| `Should choose current browsing context for "_top" if current is top` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_top-002.html">/html/browsers/windows/browsing-context-names/choose-_top-002.html</a></summary>


|                                Subtest                                | Results | Messages |
|-----------------------------------------------------------------------|---------|----------|
|                                                                       | OK      |          |
| `Should choose top browsing context for "_top" if current is not top` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_top-003.html">/html/browsers/windows/browsing-context-names/choose-_top-003.html</a></summary>


|                      Subtest                       | Results | Messages |
|----------------------------------------------------|---------|----------|
|                                                    | OK      |          |
| `choosing _top context should be case-insensitive` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-default-001.html">/html/browsers/windows/browsing-context-names/choose-default-001.html</a></summary>


|                                                      Subtest                                                       | Results |       [...]

2017-03-27 22:00 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/215656436)

# Chrome (unstable channel) #
Testing web-platform-tests at revision abe54d7bf90939ace4fc5378131f764ede2ba884
Using browser at version 59.0.3047.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>15 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_blank-001.html">/html/browsers/windows/browsing-context-names/choose-_blank-001.html</a></summary>


|                                 Subtest                                  | Results |                              Messages                              |
|--------------------------------------------------------------------------|---------|--------------------------------------------------------------------|
|                                                                          | OK      |                                                                    |
| `window.open into _blank should create a new browsing context each time` | PASS    |                                                                    |
| `_blank should be ASCII case-insensitive`                                | FAIL    | `assert_not_equals: got disallowed value object "[object Window]"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_blank-002.html">/html/browsers/windows/browsing-context-names/choose-_blank-002.html</a></summary>


|                                          Subtest                                           | Results | Messages |
|--------------------------------------------------------------------------------------------|---------|----------|
|                                                                                            | OK      |          |
| `Context for opened noreferrer link targeted to "_blank" should not have opener reference` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_blank-003.html">/html/browsers/windows/browsing-context-names/choose-_blank-003.html</a></summary>


|                                   Subtest                                   | Results | Messages |
|-----------------------------------------------------------------------------|---------|----------|
|                                                                             | OK      |          |
| `Context created by link targeting "_blank" should retain opener reference` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_parent-001.html">/html/browsers/windows/browsing-context-names/choose-_parent-001.html</a></summary>


|                                  Subtest                                  | Results | Messages |
|---------------------------------------------------------------------------|---------|----------|
|                                                                           | OK      |          |
| `The parent browsing context must be chosen if the given name is _parent` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_parent-002.html">/html/browsers/windows/browsing-context-names/choose-_parent-002.html</a></summary>


|                       Subtest                        | Results | Messages |
|------------------------------------------------------|---------|----------|
|                                                      | OK      |          |
| `choosing _parent context: multiple nested contexts` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_parent-003.html">/html/browsers/windows/browsing-context-names/choose-_parent-003.html</a></summary>


|                   Subtest                    | Results | Messages |
|----------------------------------------------|---------|----------|
|                                              | OK      |          |
| `_parent should reuse window.parent context` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_parent-004.html">/html/browsers/windows/browsing-context-names/choose-_parent-004.html</a></summary>


|                        Subtest                        | Results |                     Messages                     |
|-------------------------------------------------------|---------|--------------------------------------------------|
|                                                       | OK      |                                                  |
| `choosing _parent context should be case-insensitive` | FAIL    | `assert_equals: expected "false" but got "true"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_self-001.html">/html/browsers/windows/browsing-context-names/choose-_self-001.html</a></summary>


|                                  Subtest                                   | Results | Messages |
|----------------------------------------------------------------------------|---------|----------|
|                                                                            | OK      |          |
| `The current browsing context must be chosen if the given name is "_self"` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_self-002.html">/html/browsers/windows/browsing-context-names/choose-_self-002.html</a></summary>


|                       Subtest                       | Results |                     Messages                     |
|-----------------------------------------------------|---------|--------------------------------------------------|
|                                                     | OK      |                                                  |
| `choosing _self context should be case-insensitive` | FAIL    | `assert_equals: expected "false" but got "true"` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_top-001.html">/html/browsers/windows/browsing-context-names/choose-_top-001.html</a></summary>


|                                Subtest                                | Results | Messages |
|-----------------------------------------------------------------------|---------|----------|
|                                                                       | OK      |          |
| `Should choose current browsing context for "_top" if current is top` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_top-002.html">/html/browsers/windows/browsing-context-names/choose-_top-002.html</a></summary>


|                                Subtest                                | Results | Messages |
|-----------------------------------------------------------------------|---------|----------|
|                                                                       | OK      |          |
| `Should choose top browsing context for "_top" if current is not top` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5233/html/browsers/windows/browsing-context-names/choose-_top-003.html">/html/browsers/windows/browsing-context-names/choose-_top-003.html</a></summary>


|                      Subtest                       | Results |                      Messages                     |
|------------------------------------ [...]

2017-03-28 14:54 UTC, zcorpan commented
I can't reproduce this failure in Firefox (for me it passes):

/html/browsers/windows/browsing-context-names/choose-default-001.html

> A browsing context has an empty-string default name	FAIL	assert_equals: expected "" but got "d208530f-3697-46ed-9292-a1d280783d81";assert_equals: expected "" but got "adb66ab9-9c3c-4052-9eb2-ddb43461fab0";assert_equals: expected "" but got "fc8f00bb-a2b2-420f-9d93-638d8f7e403e";assert_equals: expected "" but got "3a9cc2a9-56b0-4f8b-b475-911f187b1179";assert_equals: expected "" but got "70ea815d-039b-40bc-b797-f5cdd7fd7885";assert_equals: expected "" but got "9077b74a-103b-44e3-82f6-96bb56d4b710";assert_equals: expected "" but got "9fa3fccf-4c43-4f2b-804a-930f61019a96";assert_equals: expected "" but got "1bdc8530-1b67-453f-b6e5-e938f740ba17";assert_equals: expected "" but got "c3e531d0-48e5-4b08-a175-003ebb3b5730";assert_equals: expected "" but got "9e3cf826-fa39-47aa-b290-7c2845fdc138"

Do you have a clue?

2017-03-28 14:56 UTC, zcorpan requested changes
LGTM % nits and uncertainty with a result in Firefox

2017-03-28 14:56 UTC, zcorpan commented on html/browsers/windows/browsing-context-names/choose-_parent-004.html
> +</body>
Remove this line (or move down)

2017-03-28 14:56 UTC, zcorpan commented on html/browsers/windows/browsing-context-names/resources/choose-_parent-004-iframe-1.html
> +</body>
Remove (or move down)

2017-03-29 13:55 UTC, lyzadanger commented
@zcorpan 

> I can't reproduce this failure in Firefox (for me it passes):

> /html/browsers/windows/browsing-context-names/choose-default-001.html

> Do you have a clue?

I have a clue...ish. This is one of the tests that I inherited, and I had observed the behavior you're seeing, too. For posterity, here's the test, which is _super_ basic:

```
//This test must be run when the current browsing context's name is not set
test(t => {
  assert_equals(window.name, "");
}, "A browsing context has an empty-string default name");
```

(Comments pre-exist my changes, also).

This test will pass when run directly and individually in a browser, but will fail when the test is run in a window opened (and ostensibly named) by a test runner. e.g. if I run the whole suite of tests in `browsing-context-names` in a browser (any browser, in my experience, not just FF):

![image](https://cloud.githubusercontent.com/assets/439947/24457921/88947d76-1465-11e7-80ed-0bdd75d28b02.png)

it will fail.

I'm not sure of the best course of action here. I don't think the test adds a whole lot of value, and the default-window-name-is-empty-string notion is tested elsewhere (e.g. line 13 of the same test file). So part of me wants to yank it altogether.

Another part of me thinks that removing it is just patching over the fact that I'm not sure how to get it to work correctly in the test harnesses we've got, which is not ideal :).

So I'm not sure! Thoughts?

2017-03-30 09:03 UTC, jgraham commented
Does the test work if you first `window.open` a new window and run the test in that?

2017-03-30 09:09 UTC, zcorpan commented
Yeah that's already tested as well in the same file:
https://github.com/lyzadanger/web-platform-tests/blob/ece4f79e73629689bf99096fddef84160f3bcda9/html/browsers/windows/browsing-context-names/choose-default-001.html#L20

I suppose we should drop that part of the test. But it seems a bit limiting to not be able to assert `window.name` without creating a separate browsing context.

2017-03-31 21:08 UTC, lyzadanger commented
Welp, for now, I've removed that test!

2017-04-05 03:18 UTC, cdumez commented
Is this in landing shape now? Looking forward to getting more coverage in this area 👍

2017-04-05 10:30 UTC, zcorpan approved these changes

2017-04-05 10:31 UTC, zcorpan commented
Yep! But should try to get CI checks green before landing. @lyzadanger can you squash and rebase on latest master and see if the bots are happy then?

2017-04-06 20:22 UTC, merged