streams: make sure ToString() is/isn't performed on arguments
web-platform-tests/wpt pull request #5260
Opened 2017-03-29 19:07 UTC by isonmad

2017-03-29 22:46 UTC, w3c-bots commented
*This report has been truncated because the total content is 184816 characters in length, which is in excess of GitHub.com's limit for comments (65536 characters).

 [View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/216478935)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 337611e61e6e0f653f0bce6f4efedb61243a9b10
Using browser at version BuildID 20170329100319; SourceStamp 272ce6c2572164f5f6a9fba2a980ba9ccf50770c
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>30 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-error-event-fires.html">/content-security-policy/style-src/style-src-error-event-fires.html</a></summary>


|                   Subtest                   | Results | Messages |
|---------------------------------------------|---------|----------|
|                                             | TIMEOUT |          |
| `Test error event fires on stylesheet link` | PASS    |          |
| `Test error event fires on inline style`    | NOTRUN  |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-hash-allowed.html">/content-security-policy/style-src/style-src-hash-allowed.html</a></summary>


|                             Subtest                              | Results | Messages |
|------------------------------------------------------------------|---------|----------|
|                                                                  | OK      |          |
| `All style elements should load because they have proper hashes` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-hash-blocked.html">/content-security-policy/style-src/style-src-hash-blocked.html</a></summary>


|                     Subtest                      | Results | Messages |
|--------------------------------------------------|---------|----------|
|                                                  | TIMEOUT |          |
| `Should load the style with a correct hash`      | PASS    |          |
| `Should not load style that does not match hash` | PASS    |          |
| `Should fire a securitypolicyviolation event`    | NOTRUN  |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-hash-default-src-allowed.html">/content-security-policy/style-src/style-src-hash-default-src-allowed.html</a></summary>


|                             Subtest                              | Results |                Messages                |
|------------------------------------------------------------------|---------|----------------------------------------|
|                                                                  | OK      |                                        |
| `All style elements should load because they have proper hashes` | FAIL    | `assert_true: expected true got false` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-imported-style-allowed.sub.html">/content-security-policy/style-src/style-src-imported-style-allowed.sub.html</a></summary>


|                        Subtest                        | Results | Messages |
|-------------------------------------------------------|---------|----------|
|                                                       | OK      |          |
| `Imported style that violates policy should not load` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-imported-style-blocked.html">/content-security-policy/style-src/style-src-imported-style-blocked.html</a></summary>


|                                 Subtest                                  | Results | Messages |
|--------------------------------------------------------------------------|---------|----------|
|                                                                          | TIMEOUT |          |
| `@import stylesheet should not load because it does not match style-src` | PASS    |          |
| `Should fire a securitypolicyviolation event`                            | NOTRUN  |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-injected-inline-style-allowed.html">/content-security-policy/style-src/style-src-injected-inline-style-allowed.html</a></summary>


|                         Subtest                          | Results | Messages |
|----------------------------------------------------------|---------|----------|
|                                                          | OK      |          |
| `Injected inline style should load with 'unsafe-inline'` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-injected-inline-style-blocked.html">/content-security-policy/style-src/style-src-injected-inline-style-blocked.html</a></summary>


|                      Subtest                      | Results | Messages |
|---------------------------------------------------|---------|----------|
|                                                   | TIMEOUT |          |
| `Injected style attributes should not be applied` | PASS    |          |
| `Should fire a securitypolicyviolation event`     | NOTRUN  |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-injected-stylesheet-allowed.sub.html">/content-security-policy/style-src/style-src-injected-stylesheet-allowed.sub.html</a></summary>


|                      Subtest                      | Results | Messages |
|---------------------------------------------------|---------|----------|
|                                                   | OK      |          |
| `Programatically injected stylesheet should load` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-injected-stylesheet-blocked.sub.html">/content-security-policy/style-src/style-src-injected-stylesheet-blocked.sub.html</a></summary>


|                        Subtest                        | Results | Messages |
|-------------------------------------------------------|---------|----------|
|                                                       | TIMEOUT |          |
| `Programatically injected stylesheet should not load` | PASS    |          |
| `Should fire a securitypolicyviolation event`         | NOTRUN  |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-inline-style-allowed.html">/content-security-policy/style-src/style-src-inline-style-allowed.html</a></summary>


|                     Subtest                      | Results | Messages |
|--------------------------------------------------|---------|----------|
|                                                  | OK      |          |
| `Inline style should apply with 'unsafe-inline'` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-inline-style-attribute-allowed.html">/content-security-policy/style-src/style-src-inline-style-attribute-allowed.html</a></summary>


|                          Subtest                           | Results | Messages |
|------------------------------------------------------------|---------|----------|
|                                                            | OK      |          |
| `Inline style attribute should apply with 'unsafe-inline'` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/ [...]

2017-03-29 22:46 UTC, w3c-bots commented
*This report has been truncated because the total content is 107712 characters in length, which is in excess of GitHub.com's limit for comments (65536 characters).

 [View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/216478936)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 337611e61e6e0f653f0bce6f4efedb61243a9b10
Using browser at version 59.0.3053.3 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>30 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-error-event-fires.html">/content-security-policy/style-src/style-src-error-event-fires.html</a></summary>


|                   Subtest                   | Results | Messages |
|---------------------------------------------|---------|----------|
|                                             | OK      |          |
| `Test error event fires on stylesheet link` | PASS    |          |
| `Test error event fires on inline style`    | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-hash-allowed.html">/content-security-policy/style-src/style-src-hash-allowed.html</a></summary>


|                             Subtest                              | Results | Messages |
|------------------------------------------------------------------|---------|----------|
|                                                                  | OK      |          |
| `All style elements should load because they have proper hashes` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-hash-blocked.html">/content-security-policy/style-src/style-src-hash-blocked.html</a></summary>


|                     Subtest                      | Results | Messages |
|--------------------------------------------------|---------|----------|
|                                                  | OK      |          |
| `Should load the style with a correct hash`      | PASS    |          |
| `Should not load style that does not match hash` | PASS    |          |
| `Should fire a securitypolicyviolation event`    | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-hash-default-src-allowed.html">/content-security-policy/style-src/style-src-hash-default-src-allowed.html</a></summary>


|                             Subtest                              | Results | Messages |
|------------------------------------------------------------------|---------|----------|
|                                                                  | OK      |          |
| `All style elements should load because they have proper hashes` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-imported-style-allowed.sub.html">/content-security-policy/style-src/style-src-imported-style-allowed.sub.html</a></summary>


|                        Subtest                        | Results | Messages |
|-------------------------------------------------------|---------|----------|
|                                                       | OK      |          |
| `Imported style that violates policy should not load` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-imported-style-blocked.html">/content-security-policy/style-src/style-src-imported-style-blocked.html</a></summary>


|                                 Subtest                                  | Results | Messages |
|--------------------------------------------------------------------------|---------|----------|
|                                                                          | OK      |          |
| `@import stylesheet should not load because it does not match style-src` | PASS    |          |
| `Should fire a securitypolicyviolation event`                            | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-injected-inline-style-allowed.html">/content-security-policy/style-src/style-src-injected-inline-style-allowed.html</a></summary>


|                         Subtest                          | Results | Messages |
|----------------------------------------------------------|---------|----------|
|                                                          | OK      |          |
| `Injected inline style should load with 'unsafe-inline'` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-injected-inline-style-blocked.html">/content-security-policy/style-src/style-src-injected-inline-style-blocked.html</a></summary>


|                      Subtest                      | Results | Messages |
|---------------------------------------------------|---------|----------|
|                                                   | OK      |          |
| `Injected style attributes should not be applied` | PASS    |          |
| `Should fire a securitypolicyviolation event`     | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-injected-stylesheet-allowed.sub.html">/content-security-policy/style-src/style-src-injected-stylesheet-allowed.sub.html</a></summary>


|                      Subtest                      | Results | Messages |
|---------------------------------------------------|---------|----------|
|                                                   | OK      |          |
| `Programatically injected stylesheet should load` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-injected-stylesheet-blocked.sub.html">/content-security-policy/style-src/style-src-injected-stylesheet-blocked.sub.html</a></summary>


|                        Subtest                        | Results | Messages |
|-------------------------------------------------------|---------|----------|
|                                                       | OK      |          |
| `Programatically injected stylesheet should not load` | PASS    |          |
| `Should fire a securitypolicyviolation event`         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-inline-style-allowed.html">/content-security-policy/style-src/style-src-inline-style-allowed.html</a></summary>


|                     Subtest                      | Results | Messages |
|--------------------------------------------------|---------|----------|
|                                                  | OK      |          |
| `Inline style should apply with 'unsafe-inline'` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-inline-style-attribute-allowed.html">/content-security-policy/style-src/style-src-inline-style-attribute-allowed.html</a></summary>


|                          Subtest                           | Results | Messages |
|------------------------------------------------------------|---------|----------|
|                                                            | OK      |          |
| `Inline style attribute should apply with 'unsafe-inline'` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5260/content-security-policy/style-src/style-src-inline-style-attribute-blocked.html">/content-security-policy/style-src/style-src-inline-style-attribute-blocked.html</a [...]

2017-03-30 02:11 UTC, ricea commented on streams/readable-streams/general.js
> +  assert_throws(error1, () => new ReadableStream({ type: { get toString() {throw error1;} } }), 'constructor should throw when ToString() throws');
Looks like toString should be a method, not an accessor?

2017-03-30 02:22 UTC, domenic requested changes

2017-03-30 02:22 UTC, domenic commented on streams/readable-byte-streams/general.js
> +  new ReadableStream({ type: { toString: null, valueOf() {return 'bytes';} } });
These don't seem to actually test that ToString happens. To do that you'd need to set a flag and then assert that it was set afterward.

2017-03-30 02:22 UTC, domenic commented on streams/readable-byte-streams/general.js
> +}, 'getReader({mode}) must only accept an actual string');
This is a spec bug!! ToString should always be performed on string-expecting arguments. Thank you for finding.

2017-03-30 02:22 UTC, domenic commented on streams/readable-streams/general.js
> +  assert_throws(error1, () => new ReadableStream({ type: { get toString() {throw error1;} } }), 'constructor should throw when ToString() throws');
Both tests would be valid; to call a method you need to get it first. But it'd be good to add both tests.

2017-04-01 17:50 UTC, w3c-bots commented
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5260/)

2017-04-03 02:55 UTC, merged