[presentation-api] add several tests for a receiving browsing context
web-platform-tests/wpt pull request #5562
Opened 2017-04-14 04:46 UTC by tomoyukilabs

This PR adds three tests for the following events in a receiving browsing context:

- a `connectionavailable` event fired at PresentationConnectionList
- a `close` event fired at PresentationConnection
- terminating a presentation in a receiving browsing context

Now I'm wondering whether a test for `connect` events at a receiving side is needed or not, since state of a presentation connection at the receiving side is already set to `connected` when it is added to the set of presentation controllers.

2017-04-14 04:56 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/221971297)

# Lint #

Passed

2017-04-14 04:56 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/221971299)

# Firefox (nightly channel) #
Testing web-platform-tests at revision b41b8bd37824d6578d02d6aad9cfcfd69eddcc07
Using browser at version BuildID 20170413100144; SourceStamp 819a666afddc804b6099ee1b3cff3a0fdf35ec15
Starting 10 test iterations
No tests run.

2017-04-14 04:56 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/221971300)

# Chrome (unstable channel) #
Testing web-platform-tests at revision b41b8bd37824d6578d02d6aad9cfcfd69eddcc07
Using browser at version 59.0.3067.0 dev
Starting 10 test iterations
No tests run.

2017-04-14 15:32 UTC, tidoust requested changes
Hi @tomoyukilabs,

First, thanks a ton for these tests. As usual, reviewing these has proved immensely useful for me as I had to dig into algorithms and wonder about what the spec says (or should say).

I see one issue with termination, and issues due to the use of SHOULD in the spec.

2017-04-14 15:32 UTC, tidoust commented on presentation-api/receiving-ua/support/iframe.html
> +        c.onterminate = () => {
Same SHOULD problem as above. There is no real guarantee that a "terminate" signal from the receiving side will not be ignored by the controlling user agent.

2017-04-14 15:32 UTC, tidoust commented on presentation-api/receiving-ua/support/PresentationConnection_onclose_receiving-ua.html
> +        return watchClose.wait_for('close');
Same SHOULD problem as mentioned elsewhere, see related open issue w3c/presentation-api#423

2017-04-14 16:38 UTC, mfoltzgoogle commented
Regarding the isTrusted property on `connectionavailable` and `close`, I filed https://bugs.chromium.org/p/chromium/issues/detail?id=711687 to investigate.

2017-04-17 00:09 UTC, tomoyukilabs commented on presentation-api/receiving-ua/support/PresentationConnectionList_onconnectionavailable_receiving-ua.html
> +      let eventNotFired = false;
Sorry, but I forgot to remove it. Thanks! I'll drop it in the next update.

2017-04-17 04:36 UTC, tomoyukilabs commented on presentation-api/receiving-ua/support/PresentationConnection_terminate_receiving-ua.html
> +      stash.send({ type: 'error' });
Right. I'll change the code into the following:

```js
stash.send({ type: (window.closed ? 'ok' : 'error') }); 
```

FYI: As far as I have tested on Firefox Nightly for Android, `window.closed` is not set to `true` yet as soon as calling "terminate",  and it becomes `true` when an `unload` event is fired. Anyway, I will fix the codes as you mentioned above.

2017-04-17 04:37 UTC, tomoyukilabs commented on presentation-api/receiving-ua/support/PresentationConnection_onclose_receiving-ua.html
> +        assert_true(!!evt, 'A presentation connection is closed when its controller\'s browsing context is discarded.');
Okay, I'll separate it as an optional test.

2017-04-17 05:49 UTC, w3c-bots commented
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5562/)

2017-04-17 05:53 UTC, tomoyukilabs commented
I have fixed several bugs except ones related to https://github.com/w3c/presentation-api/issues/422 and https://github.com/w3c/presentation-api/issues/423.

2017-04-20 04:29 UTC, tomoyukilabs commented on presentation-api/receiving-ua/support/PresentationConnection_onclose_receiving-ua.html
> +        assert_true(!!evt, 'A presentation connection is closed when its controller\'s browsing context is discarded.');
Now that this SHOULD has been changed to MUST in the current spec, I'll cancel the change to "[Optional]".

2017-04-20 04:40 UTC, tomoyukilabs commented on presentation-api/receiving-ua/PresentationConnection_terminate-manual.https.html
> +        const eventWatcher1 = new EventWatcher(t, connection, 'terminate');
Since this SHOULD has been changed to MUST, I leave this code as it is.

2017-04-20 04:43 UTC, tomoyukilabs commented on presentation-api/receiving-ua/support/iframe.html
> +        c.onterminate = () => {
Same change from SHOULD to MUST as above.

2017-04-20 04:44 UTC, tomoyukilabs commented on presentation-api/receiving-ua/support/PresentationConnection_onclose_receiving-ua.html
> +        return watchClose.wait_for('close');
Same change from SHOULD to MUST as mentioned below.

2017-04-20 07:56 UTC, tidoust approved these changes

2017-04-20 07:58 UTC, tidoust approved these changes

2017-04-20 07:59 UTC, merged