Cue text parsing tests
web-platform-tests/wpt pull request #5570
Opened 2017-04-15 15:25 UTC by BenjaminSchaaf

Improved test build script to handle character escape sequences, use python3 and put newlines at end of files.
Replaced special characters with escape sequences.
Added missing tests for cue-text parsing, specifically for handling tag annotations/classes for all tag types.

There might be an issue with timestamp tags. On firefox they serialize like this: `<01:00:00.000> → <?timestamp 3600>`, which seems reasonable but not what the tests expect. I haven't been able to determine which one the spec demands.

I'm also a little unsure as to why `&quot;` would not be converted to `"` in `entities.dat`.

2017-04-15 15:25 UTC, w3c-bots commented
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5570/)

2017-04-15 15:33 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/222369063)

# Lint #

Passed

2017-04-15 15:33 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/222369065)

# Firefox (nightly channel) #
Testing web-platform-tests at revision d44f68edfa759bf0b4e6b8c05ac06f45f5b3ca12
Using browser at version BuildID 20170415100141; SourceStamp 9379831bb9c3d9abfea7dbf8dd06dbdab1d81dc4
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>5 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5570/webvtt/parsing/cue-text-parsing/tests/entities.html">/webvtt/parsing/cue-text-parsing/tests/entities.html</a></summary>


|                                      Subtest                                      | Results | Messages |
|-----------------------------------------------------------------------------------|---------|----------|
|                                                                                   | OK      |          |
| `WebVTT cue data parser test entities - 3686fc0cdc60dc536e75df054b0bd372273db2cc` | PASS    |          |
| `WebVTT cue data parser test entities - f1869f6e2853635eec81cc3afa3e2b8148ccbdc0` | PASS    |          |
| `WebVTT cue data parser test entities - 92d76530d723b6b4e4ef8280c01cf1c80f9bebdb` | PASS    |          |
| `WebVTT cue data parser test entities - 261cd4e9df4a12535b66a0c39e9635aab2bb19aa` | PASS    |          |
| `WebVTT cue data parser test entities - 1a2269cdb73bf97ec6a99b0edabfe646c471b67e` | PASS    |          |
| `WebVTT cue data parser test entities - 44ceb90884cceeeccb4f7024e3598f7dc5ceebfa` | PASS    |          |
| `WebVTT cue data parser test entities - 05def72af03fc2b1617da950d871b9fd0ba20e5a` | PASS    |          |
| `WebVTT cue data parser test entities - da999a55445eca43aa41e039ec439c1a812db297` | PASS    |          |
| `WebVTT cue data parser test entities - 0fd9e3823b62c028c1d50e35b1f3ee3df02a62eb` | PASS    |          |
| `WebVTT cue data parser test entities - e7387003fbacb22b706796c98b781eb4ebf5ff85` | PASS    |          |
| `WebVTT cue data parser test entities - 216cd0e914b9f2ccd04eff6d02a0b1ce24441d95` | PASS    |          |
| `WebVTT cue data parser test entities - 2cdf20980d17a5d077299215e6a7e97f3c6b07e2` | PASS    |          |
| `WebVTT cue data parser test entities - 83f4500c0bd8598480713997a041d8f70fd3f11e` | PASS    |          |
| `WebVTT cue data parser test entities - 2c6b2ba38a08eca45370f28a5b7df2aa463fb3dc` | PASS    |          |
| `WebVTT cue data parser test entities - f4bb977c0a06851bdd19260c035a766c5c8ea093` | PASS    |          |
| `WebVTT cue data parser test entities - b1fff1ac42688d16e00f6c758d84e5152e39702d` | PASS    |          |
| `WebVTT cue data parser test entities - bd68f6beda2c2264e61dff7359c1ad48bc0a9934` | PASS    |          |
| `WebVTT cue data parser test entities - 5b77a0be23453dfe6eea59d43bb0708f89e1df82` | PASS    |          |
| `WebVTT cue data parser test entities - 87986551b0e6180cb279f2aa4cdddf77daa90c11` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5570/webvtt/parsing/cue-text-parsing/tests/tags.html">/webvtt/parsing/cue-text-parsing/tests/tags.html</a></summary>


|                                    Subtest                                    | Results | Messages |
|-------------------------------------------------------------------------------|---------|----------|
|                                                                               | OK      |          |
| `WebVTT cue data parser test tags - d49e42f7582c6f00b2569f2d14629611c0c6b0e6` | PASS    |          |
| `WebVTT cue data parser test tags - 9dd187edd10c907e6b92148fd82940e401dbe79f` | PASS    |          |
| `WebVTT cue data parser test tags - 2d2c4333983e23a4962083e8120e5d42c839f77b` | PASS    |          |
| `WebVTT cue data parser test tags - 94f898df44b470e2d05d74c6816fd908e55c9fdf` | PASS    |          |
| `WebVTT cue data parser test tags - 2fdc1b84ba41ec98833851e80781df1fbe72182f` | PASS    |          |
| `WebVTT cue data parser test tags - 487690a6f5da4666f9caaf3a3ecc10992aca1414` | PASS    |          |
| `WebVTT cue data parser test tags - 0d7df935b172f2a1b357b94596d68f2443f30f8b` | PASS    |          |
| `WebVTT cue data parser test tags - cd1d6dd274e03ae8fc56bc4ef163998d9ff24496` | PASS    |          |
| `WebVTT cue data parser test tags - fca1a11d42b735453117f42456360e88082a3fd7` | PASS    |          |
| `WebVTT cue data parser test tags - fe3b6277edf5c2f84e7a6779eddd0cac30552bca` | PASS    |          |
| `WebVTT cue data parser test tags - 6ceded63b53eeab3681a0fc540e959ca88f7dce9` | PASS    |          |
| `WebVTT cue data parser test tags - cdcdb0d5d6a975c5612eabcbea5d732ff3bc9f56` | PASS    |          |
| `WebVTT cue data parser test tags - 71de37451e7d5524eacc8a190d21cd64c4304e14` | PASS    |          |
| `WebVTT cue data parser test tags - 70f72cc4d2139d9e8c33189a1a9b89ecd6014a15` | PASS    |          |
| `WebVTT cue data parser test tags - 985284b688a09f1f55e3c9aab49d7e4ca11f870a` | PASS    |          |
| `WebVTT cue data parser test tags - 39c36af6d6850bc474f1d9962c1133933fd50dd0` | PASS    |          |
| `WebVTT cue data parser test tags - fa6993eaa94404648d8b52e2830e53369404fdcb` | PASS    |          |
| `WebVTT cue data parser test tags - 45221829445210412642152bfb22fa2ed222d46e` | PASS    |          |
| `WebVTT cue data parser test tags - e4d351e1a6b40a7dace801b722efaa200c4895f2` | PASS    |          |
| `WebVTT cue data parser test tags - a8481eabd1dcac1d02e57e74d499e2395ac171cd` | PASS    |          |
| `WebVTT cue data parser test tags - 68e1d0376f827ebe0c047751a2067594ff41b612` | PASS    |          |
| `WebVTT cue data parser test tags - ab2024b4e65ed64a751adbe8aae1e84ee61bf3e6` | PASS    |          |
| `WebVTT cue data parser test tags - 10f4823ffb17c71654c4602bc45c58300e3ecbcc` | PASS    |          |
| `WebVTT cue data parser test tags - 909924ef392fb20c9526acfa4f18f891eda61a0c` | PASS    |          |
| `WebVTT cue data parser test tags - e5ca35cc29404efc0ebd58aa5f6efefc86fc5287` | PASS    |          |
| `WebVTT cue data parser test tags - e535c486dac7dc571463b150adc55fd841bc3008` | PASS    |          |
| `WebVTT cue data parser test tags - bb7abafab60a0ea63f57420759fac4093148ecc8` | PASS    |          |
| `WebVTT cue data parser test tags - b53365151e0b2434837d6cce15c3d51e666a813e` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5570/webvtt/parsing/cue-text-parsing/tests/text.html">/webvtt/parsing/cue-text-parsing/tests/text.html</a></summary>


|                                    Subtest                                    | Results | Messages |
|-------------------------------------------------------------------------------|---------|----------|
|                                                                               | OK      |          |
| `WebVTT cue data parser test text - aa785adca3fcdfe1884ae840e13c6d294a2414e8` | PASS    |          |
| `WebVTT cue data parser test text - 3979f3c0c7664ee8a9f78854626bc7bc39b86c96` | PASS    |          |
| `WebVTT cue data parser test text - 6805ac5ddce21cfceb4eccf04a6a9013760f5d5b` | PASS    |          |
| `WebVTT cue data parser test text - 5cfbdbe32701516fc90c3786da1db4716ac09fb8` | PASS    |          |
| `WebVTT cue data parser test text - a34d27ca7b23f07db6ec2e32226fca105e958db6` | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5570/webvtt/parsing/cue-text-parsing/tests/timestamps.html">/webvtt/parsing/cue-text-parsing/tests/timestamps.html</a></summary>


|                                       Subtest                                       | Results | Messages |
|-------------------------------------------------------------------------------------|---------|----------|
|                                                                                     | OK      |          |
| `WebVTT cue data parser test timestamps - 54c245f3fbe7a3e25398b13971d44f2bb3a5f947` | PASS    |          |
| `WebV [...]

2017-04-15 15:33 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/222369066)

# Chrome (unstable channel) #
Testing web-platform-tests at revision d44f68edfa759bf0b4e6b8c05ac06f45f5b3ca12
Using browser at version 59.0.3067.0 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>5 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5570/webvtt/parsing/cue-text-parsing/tests/entities.html">/webvtt/parsing/cue-text-parsing/tests/entities.html</a></summary>


|                                      Subtest                                      | Results |                           Messages                           |
|-----------------------------------------------------------------------------------|---------|--------------------------------------------------------------|
|                                                                                   | OK      |                                                              |
| `WebVTT cue data parser test entities - 3686fc0cdc60dc536e75df054b0bd372273db2cc` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - f1869f6e2853635eec81cc3afa3e2b8148ccbdc0` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - 92d76530d723b6b4e4ef8280c01cf1c80f9bebdb` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - 261cd4e9df4a12535b66a0c39e9635aab2bb19aa` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - 1a2269cdb73bf97ec6a99b0edabfe646c471b67e` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - 44ceb90884cceeeccb4f7024e3598f7dc5ceebfa` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - 05def72af03fc2b1617da950d871b9fd0ba20e5a` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - da999a55445eca43aa41e039ec439c1a812db297` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - 0fd9e3823b62c028c1d50e35b1f3ee3df02a62eb` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - e7387003fbacb22b706796c98b781eb4ebf5ff85` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - 216cd0e914b9f2ccd04eff6d02a0b1ce24441d95` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - 2cdf20980d17a5d077299215e6a7e97f3c6b07e2` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - 83f4500c0bd8598480713997a041d8f70fd3f11e` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - 2c6b2ba38a08eca45370f28a5b7df2aa463fb3dc` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - f4bb977c0a06851bdd19260c035a766c5c8ea093` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - b1fff1ac42688d16e00f6c758d84e5152e39702d` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - bd68f6beda2c2264e61dff7359c1ad48bc0a9934` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - 5b77a0be23453dfe6eea59d43bb0708f89e1df82` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test entities - 87986551b0e6180cb279f2aa4cdddf77daa90c11` | FAIL    | `assert_unreached: got error event Reached unreachable code` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/5570/webvtt/parsing/cue-text-parsing/tests/tags.html">/webvtt/parsing/cue-text-parsing/tests/tags.html</a></summary>


|                                    Subtest                                    | Results |                           Messages                           |
|-------------------------------------------------------------------------------|---------|--------------------------------------------------------------|
|                                                                               | OK      |                                                              |
| `WebVTT cue data parser test tags - d49e42f7582c6f00b2569f2d14629611c0c6b0e6` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - 9dd187edd10c907e6b92148fd82940e401dbe79f` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - 2d2c4333983e23a4962083e8120e5d42c839f77b` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - 94f898df44b470e2d05d74c6816fd908e55c9fdf` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - 2fdc1b84ba41ec98833851e80781df1fbe72182f` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - 487690a6f5da4666f9caaf3a3ecc10992aca1414` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - 0d7df935b172f2a1b357b94596d68f2443f30f8b` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - cd1d6dd274e03ae8fc56bc4ef163998d9ff24496` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - fca1a11d42b735453117f42456360e88082a3fd7` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - fe3b6277edf5c2f84e7a6779eddd0cac30552bca` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - 6ceded63b53eeab3681a0fc540e959ca88f7dce9` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - cdcdb0d5d6a975c5612eabcbea5d732ff3bc9f56` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - 71de37451e7d5524eacc8a190d21cd64c4304e14` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - 70f72cc4d2139d9e8c33189a1a9b89ecd6014a15` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - 985284b688a09f1f55e3c9aab49d7e4ca11f870a` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - 39c36af6d6850bc474f1d9962c1133933fd50dd0` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - fa6993eaa94404648d8b52e2830e53369404fdcb` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - 45221829445210412642152bfb22fa2ed222d46e` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - e4d351e1a6b40a7dace801b722efaa200c4895f2` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - a8481eabd1dcac1d02e57e74d499e2395ac171cd` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - 68e1d0376f827ebe0c047751a2067594ff41b612` | FAIL    | `assert_unreached: got error event Reached unreachable code` |
| `WebVTT cue data parser test tags - ab2024b4e65ed [...]

2017-04-18 08:53 UTC, zcorpan commented
About the timestamp, filed https://github.com/w3c/webvtt/issues/345

Which version of Firefox did you test?

2017-04-18 08:56 UTC, zcorpan commented
> I'm also a little unsure as to why `&quot;` would not be converted to `"` in `entities.dat`.

This was per an earlier revision of the spec. See https://github.com/w3c/webvtt/pull/253

2017-04-18 11:05 UTC, BenjaminSchaaf commented
@zcorpan I'm using Firefox 52.0.2

2017-04-18 13:34 UTC, zcorpan commented
OK, I guess that was changed recently, maybe as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1347829

2017-06-25 08:54 UTC, silviapfeiffer approved these changes
WFM

2017-06-30 05:52 UTC, sideshowbarker commented
Can this be merged?

2017-07-04 11:33 UTC, silviapfeiffer commented
I think so, but Simon is on holidays right now.

2017-08-17 06:01 UTC, zcorpan requested changes

2017-08-17 06:01 UTC, zcorpan commented on webvtt/parsing/cue-text-parsing/dat/entities.dat
>  &quot;
This test (at least) is wrong per the current spec, since we changed to support all of HTML's charrefs.

2017-08-17 06:35 UTC, zcorpan commented
@BenjaminSchaaf can you allow edits from maintainers on your branch? I would like to push a fix here.

2017-08-17 06:41 UTC, BenjaminSchaaf commented
@zcorpan done

2017-08-17 10:30 UTC, zcorpan approved these changes
OK, rebased and added a fix for entities.dat.

2017-08-17 19:45 UTC, silviapfeiffer approved these changes

2017-08-18 05:34 UTC, merged