Require Chrome stability check to pass before merge
web-platform-tests/wpt pull request #5640
Opened 2017-04-21 18:35 UTC by jgraham

Now that the issue with Chrome hanging is believed to be fixed it
makes sense to require Chrome stability tests to pass before PRs are merged.

2017-04-21 18:35 UTC, w3c-bots commented
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5640/)

2017-04-21 18:42 UTC, jugglinmike commented
Just to be extra sure, I'd like to let that workaround run a few times before merging this.

2017-04-21 19:09 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224457380)

# Lint #

Passed

2017-04-21 19:09 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224457382)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 491d4bb25c73142c8e575661b4cd06222f2a6cb0
Using browser at version BuildID 20170420100256; SourceStamp 27311156637f9b5d4504373967e01c4241902ae7
Starting 10 test iterations
No tests run.

2017-04-21 19:09 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/224457383)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 491d4bb25c73142c8e575661b4cd06222f2a6cb0
Using browser at version 59.0.3071.15 dev
Starting 10 test iterations
No tests run.

2017-04-21 19:36 UTC, jgraham commented
Yep agreed, just want the PR to be ready.

2017-04-21 19:38 UTC, jugglinmike commented
Oh thank goodness, another human.

2017-04-26 18:17 UTC, jugglinmike requested changes
Unfortunately, it looks like the workaround did not actually resolve the issue. The following TravisCI job logs (gathered from the latest 27 ["pull request" builds](https://travis-ci.org/w3c/web-platform-tests/pull_requests)) demonstrate the timeout occurring even after DBUS is explicitly started:

- https://travis-ci.org/w3c/web-platform-tests/jobs/225920026#L423
- https://travis-ci.org/w3c/web-platform-tests/jobs/225955571#L460
- https://travis-ci.org/w3c/web-platform-tests/jobs/226085200#L420

I am going to increase the logging verbosity and attempt to reproduce the timeout.

For the short term, this patch is not suitable for `master`.

2017-10-05 06:45 UTC, foolip commented
@lukebjerring, FYI, I think we should strive towards merging a PR just like this.

However, this has been sitting open for a while and now has merge conflicts, so I'll close it, I doubt we'll forget that Chrome isn't blocking :)

2017-10-05 06:45 UTC, closed without merging