[selectors4] Add test for `:focus-within` after `display: none`
web-platform-tests/wpt pull request #5685
Opened 2017-04-25 13:21 UTC by mrego

Chrome is the only browser with this behavior, but it seems the rest of them
agree this is a bug on their side. See http://crbug.com/491828 for more info.

This test is extracted from https://codereview.chromium.org/2795143004
and has been extended to check also what happens if `display: none` is used
on the input's parent.

Please @frivoal and/or @rune-opera, could you take a look? Thanks!

2017-04-25 13:22 UTC, w3c-bots commented
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5685/)

2017-04-25 13:23 UTC, mrego commented
BTW, I'm wondering what we should do with: http://w3c-test.org/css/selectors4/focus-within-009.html
It's currently passing on Chrome, but it's just a matter of luck because after `display: none` it doesn't lose focus synchronously.
Maybe now that we're adding a new test for this, we could remove the `display: none` checks in `focus-within-009.html`. WDYT?

2017-04-25 13:32 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225603015)

# Lint #

Passed

2017-04-25 13:32 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225603017)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 25c95dc7245d484a7fc182ab7d2f95ee069debf4
Using browser at version BuildID 20170425101537; SourceStamp a30dc237c3a600a5231f2974fc2b85dfb5513414
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5685/css/selectors4/focus-within-010.html">/css/selectors4/focus-within-010.html</a></summary>


|                            Subtest                            | Results |                                                   Messages                                                  |
|---------------------------------------------------------------|---------|-------------------------------------------------------------------------------------------------------------|
|                                                               | OK      |                                                                                                             |
| `Test ':focus-within' after 'display:none' on input`          | FAIL    | `assert_false: Check input doesn't match ':focus' after getting 'display: none' expected false got true`    |
| `Test ':focus-within' after 'display:none' on input's parent` | FAIL    | `assert_false: Check input doesn't match ':focus' after parent got 'display: none' expected false got true` |

</details>
</details>

2017-04-25 13:32 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/225603023)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 25c95dc7245d484a7fc182ab7d2f95ee069debf4

2017-04-26 07:04 UTC, mrego commented
I've been doing some changes here.

This patch now adds 2 new tests:
* `focus-display-none-001.html`
* `focus-within-display-none-001.html`
    
And also modifies and old test `focus-within-009.html`. This test was checking that after `display: none` the element was still focused. It was passing in Chrome just by chance, as the focus removal is done asynchronously. It seems better to remove those cases from this test, as now we've explicit tests to check `display: none` behavior.

2017-04-26 10:42 UTC, ghost requested changes

2017-04-26 10:42 UTC, rune-opera commented on css/selectors4/focus-display-none-001.html
> +        input.style.display = "inline-block";
Why not just inline? inline-block is effectively inline for replaced content?

2017-04-26 10:42 UTC, rune-opera commented on css/selectors4/focus-within-display-none-001.html
> +        input.style.display = "inline-block";
"inline-block" -> "inline"?

2017-04-26 11:57 UTC, mrego commented on css/selectors4/focus-display-none-001.html
> +        input.style.display = "inline-block";
I used it because it's what Chrome returns for `getComputedStyle(input).display`.
But it seems Firefox returns `inline`, so I'll change it.

2017-04-26 18:42 UTC, ghost approved these changes

2017-04-27 07:45 UTC, merged

2017-04-27 07:45 UTC, mrego commented
Thanks @rune-opera for the review.