Accept partial dictionary definition in idlharness.js
web-platform-tests/wpt pull request #5717
Opened 2017-04-27 10:03 UTC by soareschen

Quick fix for #5714.

I am not sure if this alone correctly fix the handling of partial dictionary. At least it stops idlharness from raising error.

2017-04-27 10:10 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226337051)

# Lint #

Passed

2017-04-27 10:10 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226337053)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 85b8af53ce3f876246749fc7f08019e708b7b555
Ignoring 1 changed files:
No files changed

2017-04-27 10:10 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/226337059)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 85b8af53ce3f876246749fc7f08019e708b7b555
Ignoring 1 changed files:
No files changed

2017-05-14 01:48 UTC, gsnedders commented
cc/ @tobie given I think you're maintaining

2017-06-01 04:56 UTC, jdm requested changes
I am surprised that this seems to work, since the code at https://github.com/soareschen/web-platform-tests/blob/dc6297c8b5ec90665a497ad7d6b017183327d99b/resources/idlharness.js#L373-L379 looks like it should throw an exception.

2017-06-01 09:38 UTC, tobie commented
> cc/ @tobie given I think you're maintaining

I have no idea how to effectively review PRs on software with absolutely no test suite. :(

2017-10-04 11:23 UTC, bobholt commented
This is a one-line change that impacts https://github.com/w3c/web-platform-tests/issues/5714 and has been open since April. Can someone with IDL experience come to a determination about this and either merge or close?

2017-10-04 11:43 UTC, tobie commented
So idlharness now has a test suite. I'd be much more confortable merging this if it came with a couple of tests.

2018-03-28 21:28 UTC, foolip commented
Closing this in favor of https://github.com/w3c/web-platform-tests/pull/10159 which has also has tests.

(I found this when looking at the status:needs-owners label.)

2018-03-28 21:28 UTC, closed without merging