Adding tests for RTCDataChannel id attribute.
web-platform-tests/wpt pull request #5742
Opened 2017-04-30 04:48 UTC by taylor-b

When no ID argument is provided, and the DTLS role hasn't been
determined, the id attribute should return `null`.

After the DTLS role is determined by an answer being applied with
"a=setup:active" (or "passive"), the null IDs should be replaced with
either odd or even IDs, depending on the negotiated role.

2017-04-30 04:49 UTC, taylor-b commented
This is the thing @foolip requested on https://github.com/w3c/webrtc-pc/pull/1137, with an additional test for the odd/even ID selection after `setRemoteDescription`.

2017-04-30 04:53 UTC, agouaillard commented
Read the thread, looked at the code. LGTM. As soon as folio approve, (and travis is happy) I will merge.

2017-04-30 04:56 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/227285403)

# Lint #

Passed

2017-04-30 04:56 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/227285405)

# Firefox (nightly channel) #
Testing web-platform-tests at revision 43bcbca9214c7ff34a2a5c3aab37fa41f4e00e93
Using browser at version BuildID 20170429100354; SourceStamp 308cdb913d717f8edc932f5bac93854e3e54b84d
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5742/webrtc/RTCPeerConnection-createDataChannel.html">/webrtc/RTCPeerConnection-createDataChannel.html</a></summary>


|                              Subtest                               | Results |                                                                                                                                                  Messages                                                                                                                                                  |
|--------------------------------------------------------------------|---------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                    | OK      |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel required arguments`                             | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with closed connection`                         | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel defaults`                                       | FAIL    | `RTCDataChannel is not defined`                                                                                                                                                                                                                                                                            |
| `DTLS client uses odd data channel IDs`                            | FAIL    | `assert_unreached: Error Error: assert_equals: id expected 1 but got 65535 Reached unreachable code`                                                                                                                                                                                                       |
| `DTLS server uses even data channel IDs`                           | FAIL    | `assert_unreached: Error Error: assert_equals: id expected 0 but got 65535 Reached unreachable code`                                                                                                                                                                                                       |
| `createDataChannel with label "foo"`                               | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with label null`                                | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with label undefined`                           | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with label lone surrogate`                      | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with ordered false`                             | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with ordered null/undefined`                    | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with maxPacketLifeTime 0`                       | FAIL    | `assert_equals: expected (number) 0 but got (undefined) undefined`                                                                                                                                                                                                                                         |
| `createDataChannel with maxRetransmits 0`                          | FAIL    | `assert_equals: expected (number) 0 but got (undefined) undefined`                                                                                                                                                                                                                                         |
| `createDataChannel with both maxPacketLifeTime and maxRetransmits` | FAIL    | `assert_throws: function "() => pc.createDataChannel('', {\n    maxPacketLifeTime: 0,\n    maxRetransmits: 0\n  })" threw object "InvalidParameterError: Both maxPacketLifeTime and maxRetransmits cannot be provided" that is not a DOMException SyntaxError: property "code" is equal to 0, expected 12` |
| `createDataChannel with protocol "foo"`                            | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with protocol null`                             | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with protocol undefined`                        | PASS    |                                                                       [...]

2017-04-30 04:56 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/227285411)

# Chrome (unstable channel) #
Testing web-platform-tests at revision 43bcbca9214c7ff34a2a5c3aab37fa41f4e00e93

2017-04-30 05:38 UTC, taylor-b commented
The new tests are failing on Firefox because it looks like Firefox only assigns the ID after the DTLS (and SCTP?) handshake completes. But the spec currently says it should be assigned by setting an answer. This was discussed briefly [in a virtual interim](https://www.w3.org/2017/03/01-webrtc-minutes#item03), and changed in this PR: https://github.com/w3c/webrtc-pc/pull/1038

But there wasn't a lot of discussion. @jesup, @jan-ivar, any opinions? Should the spec be more loose about when the ID is assigned? I

2017-05-01 04:36 UTC, agouaillard commented
This is a spec question. If the test as is tests the current spec draft, I am tempted to merge it in, and let the discussion happen in the spec repository.

 If / when there is a spec change, then this test will be modified accordingly. 

The risk is that any test could be otherwise stay on hold waiting for the final version of the spec.

Unless there is a strong objection, I will merge it Tuesday evening end of day pacific time.

Sent from my iPhone

> On 30 Apr 2017, at 1:38 pm, Taylor Brandstetter <notifications@github.com> wrote:
> 
> The new tests are failing on Firefox because it looks like Firefox only assigns the ID after the DTLS (and SCTP?) handshake completes. But the spec currently says it should be assigned by setting an answer. This was discussed briefly in a virtual interim, and changed in this PR: w3c/webrtc-pc#1038
> 
> But there wasn't a lot of discussion. @jesup, @jan-ivar, any opinions? Should the spec be more loose about when the ID is assigned? I
> 
> ―
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-05-01 19:34 UTC, jan-ivar commented on webrtc/RTCPeerConnection-createDataChannel.html
> +    });
@agouaillard By that standard we shouldn't use the legacy [RTCSessionDescription constructor](http://w3c.github.io/webrtc-pc/#dom-rtcsessiondescription) ;)

2017-05-01 20:27 UTC, jesup requested changes

2017-05-01 20:27 UTC, jesup commented on webrtc/RTCPeerConnection-createDataChannel.html
> +    assert_equals(another_channel.id, 2, 'id');
I don't think the spec says the next channel must be '2', just that it must be even.

2017-05-01 20:27 UTC, jesup commented on webrtc/RTCPeerConnection-createDataChannel.html
> +    assert_equals(channel.id, 0, 'id');
I don't think the spec says this must be 0, just that it must be even

2017-05-01 20:27 UTC, jesup commented on webrtc/RTCPeerConnection-createDataChannel.html
> +    assert_equals(channel.id, 1, 'id');
I don't think the spec says this must be 1, just that it must be odd:
"If the side is the DTLS client, it MUST choose an even
   Stream Identifier, if the side is the DTLS server, it MUST choose an
   odd one.  "

2017-05-01 20:27 UTC, jesup commented on webrtc/RTCPeerConnection-createDataChannel.html
> +    assert_equals(another_channel.id, 3, 'id');
I don't think the spec says this must be 3, just that it must be odd

2017-05-01 20:30 UTC, jesup commented
The interim discussion was on "what do we return before the id is established", and agreed null made more sense than the current impl's 65535.

Assigning the ID when setting the answer would require we inform the DataChannel code of the DTLS roles that *will* be negotiated, assuming one is guaranteed to know that at Answer time.  Right now as stated we (firefox) assign them on DTLS negotiation, which gates us being able to actually send the Open packets on a specific id.

2017-05-01 21:16 UTC, w3c-bots commented
These tests are now available on [w3c-test.org](https://w3c-test.org/submissions/5742/)

2017-05-01 21:16 UTC, taylor-b commented on webrtc/RTCPeerConnection-createDataChannel.html
> +    assert_equals(channel.id, 1, 'id');
Fixed. Now only testing that the IDs are odd, and distinct from each other.

2017-05-01 21:32 UTC, taylor-b commented
@jesup 

> Assigning the ID when setting the answer would require we inform the DataChannel code of the DTLS roles that will be negotiated, assuming one is guaranteed to know that at Answer time.

Since the answer contains the answerer's selected role, this should be guaranteed. Would it be feasible to change Firefox's behavior? Or should the spec's requirements be made more loose (for example, "the ID will be assigned at some point before `readyState` changes to `"open"`")?

2017-05-03 13:21 UTC, foolip requested changes

2017-05-03 13:21 UTC, foolip commented on webrtc/RTCPeerConnection-createDataChannel.html
> +  .catch(test.step_func(function(e) {
This test would probably be slightly smaller using `promise_test`, which would avoid the need for this.

2017-05-03 13:21 UTC, foolip commented on webrtc/RTCPeerConnection-createDataChannel.html
> +  .then(function(offer) {
This could be `offer => pc.setLocalDescription(offer)`

2017-05-07 22:24 UTC, taylor-b commented
@foolip Addressed your comments; take another look.

2017-05-09 13:52 UTC, foolip approved these changes

2017-05-09 13:53 UTC, merged