[presentation-api] Update tests for onconnect, onclose and onterminate
web-platform-tests/wpt pull request #5794
Opened 2017-05-05 08:30 UTC by tomoyukilabs

This PR upgrades #4330 and fixes #4040 as well as several additional issues.

* `async_test` and `step_func` are replaced with `promise_test` and `EventWatcher`.
* Each file name is corrected and `.https` is added to the file name.
* The `onclose` and `onterminate` tests check behavior in each connection state: `connecting`, `connected`, `closed` and `terminated`.
* The `onterminate` test also checks behavior of another presentation connection in a nested browsing context.
* The `onterminate` test now supposes that calling `connection.terminate()` must set state of presentation connections in `connecting` and `connected` state to `terminated` as defined in the current spec: https://github.com/w3c/presentation-api/pull/427

2017-05-05 08:38 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/229034890)

# Firefox (nightly channel) #
Testing web-platform-tests at revision ad7f2f216d5d98f044446b0df903debfc079ecba
Using browser at version BuildID 20170504100357; SourceStamp 33b92d9c40562dab3d7b602368c75619f1d793f7
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>4 tests ran</summary>
<details>
<summary><a href="https://w3c-test.org/submissions/5794/presentation-api/controlling-ua/PresentationRequest_sandboxing_error.https.html">/presentation-api/controlling-ua/PresentationRequest_sandboxing_error.https.html</a></summary>


|                                                   Subtest                                                   | Results |                                                       Messages                                                       |
|-------------------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------|
|                                                                                                             | OK      |                                                                                                                      |
| `Sandboxing: Creating a PresentationRequest from a nested context fails when allow-presentation is not set` | FAIL    | `assert_equals: Presentation sandboxing did not work as expected. expected "SecurityError" but got "ReferenceError"` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5794/presentation-api/controlling-ua/PresentationRequest_sandboxing_success.https.html">/presentation-api/controlling-ua/PresentationRequest_sandboxing_success.https.html</a></summary>


|                                                  Subtest                                                   | Results |                                                    Messages                                                    |
|------------------------------------------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------|
|                                                                                                            | OK      |                                                                                                                |
| `Sandboxing: Creating a PresentationRequest from a nested context succeeds when allow-presentation is set` | FAIL    | `assert_equals: Presentation sandboxing did not work as expected. expected "success" but got "ReferenceError"` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5794/presentation-api/controlling-ua/getAvailability_sandboxing_success.https.html">/presentation-api/controlling-ua/getAvailability_sandboxing_success.https.html</a></summary>


|                                                   Subtest                                                   | Results |                                                               Messages                                                               |
|-------------------------------------------------------------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                             | OK      |                                                                                                                                      |
| `Sandboxing: Retrieving display availability from a nested context succeeds when allow-presentation is set` | FAIL    | `assert_equals: Presentation sandboxing did not work as expected. expected "success" but got "Could not create PresentationRequest"` |

</details>
<details>
<summary><a href="https://w3c-test.org/submissions/5794/presentation-api/controlling-ua/reconnectToPresentation_sandboxing_success.https.html">/presentation-api/controlling-ua/reconnectToPresentation_sandboxing_success.https.html</a></summary>


|                                                 Subtest                                                 | Results |                                                                  Messages                                                                  |
|---------------------------------------------------------------------------------------------------------|---------|--------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                         | OK      |                                                                                                                                            |
| `Sandboxing: Reconnecting a presentation from a nested context succeeds when allow-presentation is set` | FAIL    | `assert_equals: Presentation sandboxing did not work as expected. expected "NotFoundError" but got "Could not create PresentationRequest"` |

</details>
</details>

2017-05-05 08:38 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/229034896)

# Chrome (unstable channel) #
Testing web-platform-tests at revision ad7f2f216d5d98f044446b0df903debfc079ecba

2017-05-05 12:14 UTC, tidoust requested changes
I see a couple of errors to fix in the "onclose" test. Please see inline.

2017-05-06 01:31 UTC, tomoyukilabs commented on presentation-api/controlling-ua/PresentationConnection_onclose-manual.https.html
> +      // Step 1: close the presentation connection in "connecting" state
Oops, that's right. I'll move `stash.init()` somewhere else.

By the way, while I'm not sure whether it is correct or not, Chrome Canary throws an exception like `"InvalidAccessError: PresentationRequest::start() requires user gesture."` when `request.start()` is called within `stash.init().then()`. This is the reason why I avoided calling `stash.init()` before `request.start()`.

2017-05-06 01:31 UTC, tomoyukilabs commented on presentation-api/controlling-ua/PresentationConnection_onclose-manual.https.html
> +      return Promise.all([
Oops, I'll fix it.

2017-05-09 04:15 UTC, tomoyukilabs commented
I have fixed a couple of bugs in the "onclose" test. Also, I have updated the three tests so that they check both `on(connect|close|terminate)` and addEventListener (used in `EventWatcher`).

2017-05-09 13:46 UTC, tidoust commented on presentation-api/controlling-ua/PresentationConnection_onclose-manual.https.html
> +      // Step 1: close the presentation connection in "connecting" state
I don't know. I believe the behavior is somewhat up to implementations in practice, see end of third bullet point in definition of [allowed to show a popup](http://www.w3.org/TR/html51/browsers.html#allowed-to-show-a-popup).

It's interesting that `Promise.all` seems to solve the problem.

2017-05-09 13:46 UTC, tidoust approved these changes

2017-05-09 14:11 UTC, merged