Add test for RTCIceCandidate constructor
web-platform-tests/wpt pull request #5917
Opened 2017-05-15 07:31 UTC by soareschen

The test follows the latest webrtc-pc spec on the correct way to construct `RTCIceCandidate`. The current browser implementations behave very differently from the spec, and this test attempt to iron out all inconsistencies.

2017-05-15 07:39 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232324967)

# Firefox (nightly) #
Testing web-platform-tests at revision cdce6c033f9ec0d5f16e91e084bb2579fd0bdb0e
Using browser at version BuildID 20170514100406; SourceStamp 73b3fc64525b6816842c737e104ef2ac5482d217
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5917/webrtc/RTCIceCandidate-constructor.html">/webrtc/RTCIceCandidate-constructor.html</a></summary>


|                                 Subtest                                 | Results |                                                                                        Messages                                                                                        |
|-------------------------------------------------------------------------|---------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                         | OK      |                                                                                                                                                                                        |
| `new RTCIceCandidate()`                                                 | PASS    |                                                                                                                                                                                        |
| `new RTCIceCandidate({})`                                               | PASS    |                                                                                                                                                                                        |
| `new RTCIceCandidate({ ... }) with manually filled default values`      | FAIL    | `assert_throws: function "() => new RTCIceCandidate({\n        candidate: '',\n        sdpMid: null,\n        sdpMLineIndex: null,\n        ufrag: undefined\n      })" did not throw` |
| `new RTCIceCandidate({ candidate: '' })`                                | FAIL    | `assert_throws: function "() => new RTCIceCandidate({\n        candidate: ''\n      })" did not throw`                                                                                 |
| `new RTCIceCandidate({ ... }) with valid candidate string only`         | FAIL    | `assert_throws: function "() => new RTCIceCandidate({\n        candidate: candidateString\n      })" did not throw`                                                                    |
| `new RTCIceCandidate({ sdpMid: 'audio' })`                              | FAIL    | `Missing required 'candidate' member of RTCIceCandidateInit.`                                                                                                                          |
| `new RTCIceCandidate({ sdpMLineIndex: 0 })`                             | FAIL    | `Missing required 'candidate' member of RTCIceCandidateInit.`                                                                                                                          |
| `new RTCIceCandidate({ sdpMid: 'audio', sdpMLineIndex: 0 })`            | FAIL    | `Missing required 'candidate' member of RTCIceCandidateInit.`                                                                                                                          |
| `new RTCIceCandidate({ candidate: '', sdpMid: 'audio' }`                | FAIL    | `candidate is not defined`                                                                                                                                                             |
| `new RTCIceCandidate({ candidate: '', sdpMLineIndex: 0 }`               | FAIL    | `candidate is not defined`                                                                                                                                                             |
| `new RTCIceCandidate({ ... }) with valid candidate string and sdpMid`   | FAIL    | `assert_equals: expected (object) null but got (undefined) undefined`                                                                                                                  |
| `new RTCIceCandidate({ ... }) with invalid candidate string and sdpMid` | FAIL    | `assert_equals: expected (object) null but got (undefined) undefined`                                                                                                                  |
| `new RTCIceCandidate({ ... }) with non default value for all fields`    | FAIL    | `assert_equals: expected (string) "test" but got (undefined) undefined`                                                                                                                |
| `new RTCIceCandidate({ ... }) with random sdpMid`                       | FAIL    | `Missing required 'candidate' member of RTCIceCandidateInit.`                                                                                                                          |
| `new RTCIceCandidate({ ... }) with random sdpMLineIndex`                | FAIL    | `Missing required 'candidate' member of RTCIceCandidateInit.`                                                                                                                          |

</details>
</details>

2017-05-15 07:39 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232324973)

# Chrome (unstable) #
Testing web-platform-tests at revision cdce6c033f9ec0d5f16e91e084bb2579fd0bdb0e

2017-05-15 18:52 UTC, rwaldron commented on webrtc/RTCIceCandidate-constructor.html
> +      () => new RTCIceCandidate());
nit: this can be on line 17 (easier to read that way)

2017-05-15 19:05 UTC, rwaldron commented on webrtc/RTCIceCandidate-constructor.html
> +    assert_throws(new TypeError,
I know that invocation parens are technically "optional", but the use of an actual TypeError  instance object is so weird (albeit, out of our control), that this is strange to look at. I was curious about conventions used throughout web-platform-tests, so I did a search of the entire repo and found 97 occurrences of `assert_throws(new TypeError,` and 1457 occurrences of `assert_throws(new TypeError(),`. Anyway, I don't think this should be considered a blocker, but I think for future reader sake, the code should be written such that it's intention is as clear and consistent as possible, which means inclusion of invocation parens whenever an invocation occurs.

2017-05-15 19:05 UTC, rwaldron commented on webrtc/RTCIceCandidate-constructor.html
> +    // Further tests below are used to differentiate the errors.
This is an excellent comment—I appreciate the clarity that conveyed here.

2017-05-15 20:23 UTC, rwaldron commented
I've updated my annotated copy of the spec to indicate which portions of the RTCIceCandidate Interface spec are not covered by this PR: https://rwaldron.github.io/webrtc-pc/#rtcicecandidate-interface

2017-05-15 20:23 UTC, rwaldron requested changes
See https://rwaldron.github.io/webrtc-pc/#rtcicecandidate-interface for coverage annotations

2017-05-15 20:23 UTC, rwaldron commented on webrtc/RTCIceCandidate-constructor.html
> +  }, 'new RTCIceCandidate({ ... }) with random sdpMid');
Since it's not really random, let's call it something else more appropriate.

2017-05-16 02:50 UTC, soareschen commented on webrtc/RTCIceCandidate-constructor.html
> +    assert_throws(new TypeError,
Agree, I personally prefer and use parenthesis for all new operators in my own code. I just saw the omittance of paren in some other test files and thought that's the style convention I should follow.

Anyway good to know people actually use both styles in this repo. I have updated the code to use the paren-all style we preferred.

2017-05-16 02:55 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232665690)

# Sauce (safari) #
Testing web-platform-tests at revision 444e8ff1dca8b0ff766a50570aae2f9b3b285edc
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5917/webrtc/RTCIceCandidate-constructor.html">/webrtc/RTCIceCandidate-constructor.html</a></summary>


|                                 Subtest                                 | Results |                                                                                                                                                  Messages                                                                                                                                                 |
|-------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                         | OK      |                                                                                                                                                                                                                                                                                                           |
| `new RTCIceCandidate()`                                                 | FAIL    | `assert_throws: function "() => new RTCIceCandidate()" threw object "ReferenceError: Can't find variable: RTCIceCandidate" ("ReferenceError") expected object "TypeError" ("TypeError")`                                                                                                                  |
| `new RTCIceCandidate({})`                                               | FAIL    | `assert_throws: function "() => new RTCIceCandidate({})" threw object "ReferenceError: Can't find variable: RTCIceCandidate" ("ReferenceError") expected object "TypeError" ("TypeError")`                                                                                                                |
| `new RTCIceCandidate({ ... }) with manually filled default values`      | FAIL    | `assert_throws: function "() => new RTCIceCandidate({\n        candidate: '',\n        sdpMid: null,\n        sdpMLineIndex: null,\n        ufrag: undefined\n      })" threw object "ReferenceError: Can't find variable: RTCIceCandidate" ("ReferenceError") expected object "TypeError" ("TypeError")` |
| `new RTCIceCandidate({ sdpMid: null, sdpMLineIndex: null })`            | FAIL    | `assert_throws: function "() => new RTCIceCandidate({\n        sdpMid: null,\n        sdpMLineIndex: null\n      })" threw object "ReferenceError: Can't find variable: RTCIceCandidate" ("ReferenceError") expected object "TypeError" ("TypeError")`                                                    |
| `new RTCIceCandidate({ candidate: '' })`                                | FAIL    | `assert_throws: function "() => new RTCIceCandidate({\n        candidate: ''\n      })" threw object "ReferenceError: Can't find variable: RTCIceCandidate" ("ReferenceError") expected object "TypeError" ("TypeError")`                                                                                 |
| `new RTCIceCandidate({ ... }) with valid candidate string only`         | FAIL    | `assert_throws: function "() => new RTCIceCandidate({\n        candidate: candidateString\n      })" threw object "ReferenceError: Can't find variable: RTCIceCandidate" ("ReferenceError") expected object "TypeError" ("TypeError")`                                                                    |
| `new RTCIceCandidate({ sdpMid: 'audio' })`                              | FAIL    | `Can't find variable: RTCIceCandidate`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ sdpMLineIndex: 0 })`                             | FAIL    | `Can't find variable: RTCIceCandidate`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ sdpMid: 'audio', sdpMLineIndex: 0 })`            | FAIL    | `Can't find variable: RTCIceCandidate`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ candidate: '', sdpMid: 'audio' }`                | FAIL    | `Can't find variable: RTCIceCandidate`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ candidate: '', sdpMLineIndex: 0 }`               | FAIL    | `Can't find variable: RTCIceCandidate`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ ... }) with valid candidate string and sdpMid`   | FAIL    | `Can't find variable: RTCIceCandidate`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ ... }) with invalid candidate string and sdpMid` | FAIL    | `Can't find variable: RTCIceCandidate`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ ... }) with non default value for all fields`    | FAIL    | `Can't find variable: RTCIceCandidate`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ ... }) with invalid sdpMid`                      | FAIL    | `Can't find variable: RTCIceCandidate`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ ... }) with random sdpMLineIndex`                | FAIL    | `Can't find variable: RTCIceCandidate`                                                                                                                                                                                                                                                                    |

</details>
</details>

2017-05-16 02:55 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/232665691)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 444e8ff1dca8b0ff766a50570aae2f9b3b285edc
Using browser at version 14.14393
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5917/webrtc/RTCIceCandidate-constructor.html">/webrtc/RTCIceCandidate-constructor.html</a></summary>


|                                 Subtest                                 | Results |                                                                                                                                               Messages                                                                                                                                              |
|-------------------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                         | OK      |                                                                                                                                                                                                                                                                                                     |
| `new RTCIceCandidate()`                                                 | FAIL    | `assert_throws: function "() => new RTCIceCandidate()" threw object "ReferenceError: 'RTCIceCandidate' is undefined" ("ReferenceError") expected object "TypeError" ("TypeError")`                                                                                                                  |
| `new RTCIceCandidate({})`                                               | FAIL    | `assert_throws: function "() => new RTCIceCandidate({})" threw object "ReferenceError: 'RTCIceCandidate' is undefined" ("ReferenceError") expected object "TypeError" ("TypeError")`                                                                                                                |
| `new RTCIceCandidate({ ... }) with manually filled default values`      | FAIL    | `assert_throws: function "() => new RTCIceCandidate({\n        candidate: '',\n        sdpMid: null,\n        sdpMLineIndex: null,\n        ufrag: undefined\n      })" threw object "ReferenceError: 'RTCIceCandidate' is undefined" ("ReferenceError") expected object "TypeError" ("TypeError")` |
| `new RTCIceCandidate({ sdpMid: null, sdpMLineIndex: null })`            | FAIL    | `assert_throws: function "() => new RTCIceCandidate({\n        sdpMid: null,\n        sdpMLineIndex: null\n      })" threw object "ReferenceError: 'RTCIceCandidate' is undefined" ("ReferenceError") expected object "TypeError" ("TypeError")`                                                    |
| `new RTCIceCandidate({ candidate: '' })`                                | FAIL    | `assert_throws: function "() => new RTCIceCandidate({\n        candidate: ''\n      })" threw object "ReferenceError: 'RTCIceCandidate' is undefined" ("ReferenceError") expected object "TypeError" ("TypeError")`                                                                                 |
| `new RTCIceCandidate({ ... }) with valid candidate string only`         | FAIL    | `assert_throws: function "() => new RTCIceCandidate({\n        candidate: candidateString\n      })" threw object "ReferenceError: 'RTCIceCandidate' is undefined" ("ReferenceError") expected object "TypeError" ("TypeError")`                                                                    |
| `new RTCIceCandidate({ sdpMid: 'audio' })`                              | FAIL    | `'RTCIceCandidate' is undefined`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ sdpMLineIndex: 0 })`                             | FAIL    | `'RTCIceCandidate' is undefined`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ sdpMid: 'audio', sdpMLineIndex: 0 })`            | FAIL    | `'RTCIceCandidate' is undefined`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ candidate: '', sdpMid: 'audio' }`                | FAIL    | `'RTCIceCandidate' is undefined`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ candidate: '', sdpMLineIndex: 0 }`               | FAIL    | `'RTCIceCandidate' is undefined`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ ... }) with valid candidate string and sdpMid`   | FAIL    | `'RTCIceCandidate' is undefined`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ ... }) with invalid candidate string and sdpMid` | FAIL    | `'RTCIceCandidate' is undefined`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ ... }) with non default value for all fields`    | FAIL    | `'RTCIceCandidate' is undefined`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ ... }) with invalid sdpMid`                      | FAIL    | `'RTCIceCandidate' is undefined`                                                                                                                                                                                                                                                                    |
| `new RTCIceCandidate({ ... }) with random sdpMLineIndex`                | FAIL    | `'RTCIceCandidate' is undefined`                                                                                                                                                                                                                                                                    |

</details>
</details>

2017-05-16 02:57 UTC, soareschen commented on webrtc/RTCIceCandidate-constructor.html
> +  }, `new RTCIceCandidate({ candidate: '' })`);
My interpretation based on WebIDL spec is that they are indeed default to null if unspecified. All fields in a dictionary is optional unless specified. The fields with default values would convert `undefined` to the default value. (https://heycam.github.io/webidl/#dfn-dictionary)

I think the test should follow as faithful as what the spec currently specifies. Using this we can then point out flaws in the specs using these tests and then improve/clarify the spec if necessary.

2017-05-16 03:01 UTC, soareschen commented on webrtc/RTCIceCandidate-constructor.html
> +        ufrag: undefined
Added that one. And Firefox actually pass the test with different reason. :O

2017-05-16 03:02 UTC, soareschen commented on webrtc/RTCIceCandidate-constructor.html
> +  }, 'new RTCIceCandidate({ ... }) with random sdpMid');
Ok. I now call them arbitrary/invalid.

2017-05-16 14:46 UTC, rwaldron commented on webrtc/RTCIceCandidate-constructor.html
> +        ufrag: undefined
Yeah, the differences across implementations is surprising :|

2017-05-16 14:49 UTC, rwaldron commented on webrtc/RTCIceCandidate-constructor.html
> +  }, `new RTCIceCandidate({ candidate: '' })`);
> My interpretation based on WebIDL spec is that they are indeed default to null if unspecified. All fields in a dictionary is optional unless specified. The fields with default values would convert undefined to the default value. (https://heycam.github.io/webidl/#dfn-dictionary)

Yes, that's not in contention. My concern is really: why are they nullable, not `required`, but will throw if both are not present and defaulting to null, or both are explicitly null. I think the spec itself needs to address this. 

> Using this we can then point out flaws in the specs using these tests and then improve/clarify the spec if necessary.

Ok, I agree with this.

2017-05-16 14:50 UTC, rwaldron commented on webrtc/RTCIceCandidate-constructor.html
> +  const arbitraryString = '<arbitrary string[0] content>;';
👍

2017-05-16 15:52 UTC, rwaldron requested changes
Thanks for making the recommended changes from my review! Will this PR be updated to include coverage for the missing portions of the `RTCIceCandidate` spec?

- Attributes \*: 
  - [x] `candidate`
  - [x] `sdpMid`
  - [x] `sdpMLineIndex`
  - [ ] `foundation`
  - [ ] `priority`
  - [ ] `ip`
  - [ ] `protocol`
  - [ ] `port`
  - [ ] `type`
  - [ ] `tcpType`
  - [ ] `relatedAddress`
  - [ ] `relatedPort`
  - [x] `ufrag`
- [ ] Serializer


\* These should all have the appropriate value based on the candidate string, parsed per https://tools.ietf.org/html/rfc5245#section-15.1

2017-05-16 22:09 UTC, foolip commented on webrtc/RTCIceCandidate-constructor.html
> +    assert_throws(new TypeError,
I enjoy omitting the parens, but there is no style requirement.

As for "the use of an actual TypeError instance object is so weird (albeit, out of our control)" it's something that could well be changed in testharness.js, although converting to some other style would be a fair bit of work.

2017-05-17 01:48 UTC, agouaillard commented
We wanted to go chapter by chapter, but if another approach makes your life easier and is more sync'ed with the way you check against spec and compute coverage, by all means go ahead @soares

Sent from my iPhone

> On 16 May 2017, at 11:52 pm, Rick Waldron <notifications@github.com> wrote:
> 
> @rwaldron requested changes on this pull request.
> 
> Thanks for making the recommended changes from my review! Will this PR be updated to include coverage for the missing portions of the RTCIceCandidate spec?
> 
> Attributes:
>  candidate
>  sdpMid
>  sdpMLineIndex
>  foundation
>  priority
>  ip
>  protocol
>  port
>  type
>  tcpType
>  relatedAddress
>  relatedPort
>  ufrag
>  Serializer
> ―
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-05-17 02:29 UTC, soareschen commented
> Will this PR be updated to include coverage for the missing portions of the RTCIceCandidate spec?

I think it is better to leave those out for another PR. Current browsers have not implemented these fields, and the spec have not been clear on how to handle the parsing, i.e. it is undefined what happen when `RTCIceCandidate` is constructed with invalid candidate string.

For serializer is there any simple way to test that with testharness? There is no loose equality assert so is the only way compare the fields one by one?

2017-05-17 02:29 UTC, Soares commented
I think you tagged the wrong person :-) (@soareschen, looks like the tag was meant for you.)

2017-05-17 02:45 UTC, soareschen commented
> I think you tagged the wrong person :-) (@soareschen, looks like the tag was meant for you.)

Haha nice catch :P

> We wanted to go chapter by chapter, but if another approach makes your life easier and is more sync'ed with the way you check against spec and compute coverage, by all means go ahead

For now I try to test on the things have been implemented by browsers and see if they match the spec. And if there are inconsistency in the spec I'd try to iron that out first. Now still mostly stuck at chapter 4.

2017-05-17 11:10 UTC, foolip commented
> is undefined what happen when `RTCIceCandidate` is constructed with invalid candidate string

Yep, ideally the `RTCIceCandidate` constructor should explicitly handle all of the dictionary members and assign all of the instance attributes.

A shorthand for that from https://dom.spec.whatwg.org/#constructing-events is "For each dictionary member present in defaultEventInitDict, find the attribute on event whose identifier matches the key of the dictionary member and then set the attribute to the default value of that dictionary member."

2017-05-17 11:10 UTC, foolip commented
That being said, my take of the current spec is that any `candidate` value (including the empty string) is allowed and simply forwarded to the instance.

2017-05-17 20:46 UTC, rwaldron commented
> I think it is better to leave those out for another PR. Current browsers have not implemented these fields, and the spec have not been clear on how to handle the parsing, i.e. it is undefined what happen when RTCIceCandidate is constructed with invalid candidate string.

The whole point of writing these tests from the spec is so that implementers have something to implement against. 

> That being said, my take of the current spec is that any candidate value (including the empty string) is allowed and simply forwarded to the instance.

Right. And those implementations that do not do this are incomplete and non-conformant.

2017-05-17 21:06 UTC, snuggs commented
This is a godsend. I've been wanting to test my WEBRTC Apps with jsdom for the longest. Didn't quite know how.

THis is for the ICE candidate. Not to diverge the flow but are RTCPeerConnection and "Offer/Challenge"s implemented? If so can you link me to the source?  Thanks so much! @foolip @soareschen

2017-05-18 02:47 UTC, soareschen commented
> The whole point of writing these tests from the spec is so that implementers have something to implement against

What I mean is there is no normative definition that require implementers to parse the candidate string and populate for fields for`foundation`, `priority`, etc. Since it does not say the string need to be parsed, it also does not say if implementer should ignore any parsing error and leave the fields undefined, or throw an error from the constructor. We cannot write the test unless all that become normative.

I will draft a PR for w3c/webrtc-pc#1165. And if the reviewers there agree with the proposed normative definition, then we'll work on the test for the remaining fields.

2017-05-18 16:21 UTC, rwaldron commented
> What I mean is there is no normative definition that require implementers to parse the candidate string and populate for fields for foundation, priority, etc

You're right, there is no normative definition of such semantics, I believe this needs to be resolved with spec changes. In the meantime, the tests should at very least include checks for:

- the existence of the properties
- the default values of the properties
- the expected type of the default value


I will write up a spec issue for the parsing question

2017-05-18 16:24 UTC, rwaldron commented
https://github.com/w3c/webrtc-pc/issues/1224

2017-05-18 21:24 UTC, rwaldron commented
While we wait to hear back on that issue, this still needs Serializer coverage. I suspect that's as easy as: 

- `JSON.stringify(ic) === JSON.stringify(ic.toJSON())`
- `JSON.parse(JSON.stringify(ic))` then verify the properties

2017-05-19 12:25 UTC, rwaldron approved these changes
LGTM

2017-05-19 12:27 UTC, merged