DOM: AbortController and AbortSignal
web-platform-tests/wpt pull request #5960
Opened 2017-05-17 09:23 UTC by annevk

For https://github.com/whatwg/dom/pull/437.

2017-05-17 09:54 UTC, w3c-bots commented
*This report has been truncated because the total content is 2959803 characters in length, which is in excess of GitHub.com's limit for comments (65536 characters).

 [View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233161320)

# Firefox (nightly) #
Testing web-platform-tests at revision ff8348b390226829d80831f8950b64829f0f2faa
Using browser at version BuildID 20170516192431; SourceStamp b8e9b674033bcd1f3a4c59b9d0ee7619c1a17cc5
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>7 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5960/XMLHttpRequest/interfaces.html">/XMLHttpRequest/interfaces.html</a></summary>


|                                                                            Subtest                                                                             | Results | Messages |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|----------|
|                                                                                                                                                                | OK      |          |
| `Test driver`                                                                                                                                                  | PASS    |          |
| `XMLHttpRequestEventTarget interface: existence and properties of interface object`                                                                            | PASS    |          |
| `XMLHttpRequestEventTarget interface object length`                                                                                                            | PASS    |          |
| `XMLHttpRequestEventTarget interface object name`                                                                                                              | PASS    |          |
| `XMLHttpRequestEventTarget interface: existence and properties of interface prototype object`                                                                  | PASS    |          |
| `XMLHttpRequestEventTarget interface: existence and properties of interface prototype object's "constructor" property`                                         | PASS    |          |
| `XMLHttpRequestEventTarget interface: attribute onloadstart`                                                                                                   | PASS    |          |
| `XMLHttpRequestEventTarget interface: attribute onprogress`                                                                                                    | PASS    |          |
| `XMLHttpRequestEventTarget interface: attribute onabort`                                                                                                       | PASS    |          |
| `XMLHttpRequestEventTarget interface: attribute onerror`                                                                                                       | PASS    |          |
| `XMLHttpRequestEventTarget interface: attribute onload`                                                                                                        | PASS    |          |
| `XMLHttpRequestEventTarget interface: attribute ontimeout`                                                                                                     | PASS    |          |
| `XMLHttpRequestEventTarget interface: attribute onloadend`                                                                                                     | PASS    |          |
| `XMLHttpRequestUpload interface: existence and properties of interface object`                                                                                 | PASS    |          |
| `XMLHttpRequestUpload interface object length`                                                                                                                 | PASS    |          |
| `XMLHttpRequestUpload interface object name`                                                                                                                   | PASS    |          |
| `XMLHttpRequestUpload interface: existence and properties of interface prototype object`                                                                       | PASS    |          |
| `XMLHttpRequestUpload interface: existence and properties of interface prototype object's "constructor" property`                                              | PASS    |          |
| `XMLHttpRequestEventTarget interface: (new XMLHttpRequest()).upload must inherit property "onloadstart" with the proper type (0)`                              | PASS    |          |
| `XMLHttpRequestEventTarget interface: (new XMLHttpRequest()).upload must inherit property "onprogress" with the proper type (1)`                               | PASS    |          |
| `XMLHttpRequestEventTarget interface: (new XMLHttpRequest()).upload must inherit property "onabort" with the proper type (2)`                                  | PASS    |          |
| `XMLHttpRequestEventTarget interface: (new XMLHttpRequest()).upload must inherit property "onerror" with the proper type (3)`                                  | PASS    |          |
| `XMLHttpRequestEventTarget interface: (new XMLHttpRequest()).upload must inherit property "onload" with the proper type (4)`                                   | PASS    |          |
| `XMLHttpRequestEventTarget interface: (new XMLHttpRequest()).upload must inherit property "ontimeout" with the proper type (5)`                                | PASS    |          |
| `XMLHttpRequestEventTarget interface: (new XMLHttpRequest()).upload must inherit property "onloadend" with the proper type (6)`                                | PASS    |          |
| `XMLHttpRequest interface: existence and properties of interface object`                                                                                       | PASS    |          |
| `XMLHttpRequest interface object length`                                                                                                                       | PASS    |          |
| `XMLHttpRequest interface object name`                                                                                                                         | PASS    |          |
| `XMLHttpRequest interface: existence and properties of interface prototype object`                                                                             | PASS    |          |
| `XMLHttpRequest interface: existence and properties of interface prototype object's "constructor" property`                                                    | PASS    |          |
| `XMLHttpRequest interface: attribute onreadystatechange`                                                                                                       | PASS    |          |
| `XMLHttpRequest interface: constant UNSENT on interface object`                                                                                                | PASS    |          |
| `XMLHttpRequest interface: constant UNSENT on interface prototype object`                                                                                      | PASS    |          |
| `XMLHttpRequest interface: constant OPENED on interface object`                                                                                                | PASS    |          |
| `XMLHttpRequest interface: constant OPENED on interface prototype object`                                                                                      | PASS    |          |
| `XMLHttpRequest interface: constant HEADERS_RECEIVED on interface object`                                                                                      | PASS    |          |
| `XMLHttpRequest interface: constant HEADERS_RECEIVED on interface prototype object`                      [...]

2017-05-17 09:54 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233161321)

# Sauce (safari) #
Testing web-platform-tests at revision ff8348b390226829d80831f8950b64829f0f2faa
Using browser at version 10.0
Starting 10 test iterations

2017-05-17 09:54 UTC, w3c-bots commented
*This report has been truncated because the total content is 3027058 characters in length, which is in excess of GitHub.com's limit for comments (65536 characters).

 [View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233161322)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision ff8348b390226829d80831f8950b64829f0f2faa
Using browser at version 14.14393
Starting 10 test iterations
## Unstable results ##


|             Test            |                                                              Subtest                                                               |          Results           |                                  Messages                                 |
|-----------------------------|------------------------------------------------------------------------------------------------------------------------------------|----------------------------|---------------------------------------------------------------------------|
| `/html/dom/interfaces.html` | `Document interface: document.implementation.createDocument(null, "", null) must inherit property "all" with the proper type (75)` | **FAIL: 3/10, PASS: 7/10** | `assert_true: wrong type: not object or function expected true got false` |

## All results ##
<details>
<summary>7 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/5960/XMLHttpRequest/interfaces.html">/XMLHttpRequest/interfaces.html</a></summary>


|                                                                            Subtest                                                                             | Results |                                                                                  Messages                                                                                 |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                                                                | OK      |                                                                                                                                                                           |
| `Test driver`                                                                                                                                                  | PASS    |                                                                                                                                                                           |
| `XMLHttpRequestEventTarget interface: existence and properties of interface object`                                                                            | FAIL    | `assert_own_property: self does not have own property "XMLHttpRequestEventTarget" expected property "XMLHttpRequestEventTarget" missing`                                  |
| `XMLHttpRequestEventTarget interface object length`                                                                                                            | FAIL    | `assert_own_property: self does not have own property "XMLHttpRequestEventTarget" expected property "XMLHttpRequestEventTarget" missing`                                  |
| `XMLHttpRequestEventTarget interface object name`                                                                                                              | FAIL    | `assert_own_property: self does not have own property "XMLHttpRequestEventTarget" expected property "XMLHttpRequestEventTarget" missing`                                  |
| `XMLHttpRequestEventTarget interface: existence and properties of interface prototype object`                                                                  | FAIL    | `assert_own_property: self does not have own property "XMLHttpRequestEventTarget" expected property "XMLHttpRequestEventTarget" missing`                                  |
| `XMLHttpRequestEventTarget interface: existence and properties of interface prototype object's "constructor" property`                                         | FAIL    | `assert_own_property: self does not have own property "XMLHttpRequestEventTarget" expected property "XMLHttpRequestEventTarget" missing`                                  |
| `XMLHttpRequestEventTarget interface: attribute onloadstart`                                                                                                   | FAIL    | `assert_own_property: self does not have own property "XMLHttpRequestEventTarget" expected property "XMLHttpRequestEventTarget" missing`                                  |
| `XMLHttpRequestEventTarget interface: attribute onprogress`                                                                                                    | FAIL    | `assert_own_property: self does not have own property "XMLHttpRequestEventTarget" expected property "XMLHttpRequestEventTarget" missing`                                  |
| `XMLHttpRequestEventTarget interface: attribute onabort`                                                                                                       | FAIL    | `assert_own_property: self does not have own property "XMLHttpRequestEventTarget" expected property "XMLHttpRequestEventTarget" missing`                                  |
| `XMLHttpRequestEventTarget interface: attribute onerror`                                                                                                       | FAIL    | `assert_own_property: self does not have own property "XMLHttpRequestEventTarget" expected property "XMLHttpRequestEventTarget" missing`                                  |
| `XMLHttpRequestEventTarget interface: attribute onload`                                                                                                        | FAIL    | `assert_own_property: self does not have own property "XMLHttpRequestEventTarget" expected property "XMLHttpRequestEventTarget" missing`                                  |
| `XMLHttpRequestEventTarget interface: attribute ontimeout`                                                                                                     | FAIL    | `assert_own_property: self does not have own property "XMLHttpRequestEventTarget" expected property "XMLHttpRequestEventTarget" missing`                                  |
| `XMLHttpRequestEventTarget interface: attribute onloadend`                                                                                                     | FAIL    | `assert_own_property: self does not have own property "XMLHttpRequestEventTarget" expected property "XMLHttpRequestEventTarget" missing`                                  |
| `XMLHttpRequestUpload interface: existence and properties of interface object`                                                                                 | FAIL    | `assert_own_property: should inherit from XMLHttpRequestEventTarget, but self has no such property expected property "XMLHttpRequestEventTarget" missing`                 |
| `XMLHttpRequestUpload interface object length`                                                                                                                 | FAIL    | `assert_own_property: expected property "length" missing`                                                                                                                 |
| `XMLHttpRequestUpload interface object name`                                                                                                                   | PASS    |                                                                                                                                                         [...]

2017-05-17 09:54 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/233161328)

# Chrome (unstable) #

2017-05-17 16:47 UTC, domenic requested changes

2017-05-17 16:47 UTC, domenic commented on dom/abort/event.any.js
> +async_test(t => {
This can be a sync test (and it's good to test that things happen synchronously)

2017-05-17 16:47 UTC, domenic commented on dom/abort/event.any.js
> +    t.step_func_done(e => {
This will done() the test twice, once via the step_func_done and once via t.done() below

2017-05-17 16:47 UTC, domenic commented on dom/abort/event.any.js
> +done();
Another good test (optional) would be that aborting twice does not fire the event twice.

2017-05-17 18:11 UTC, domenic approved these changes

2017-05-31 07:31 UTC, zcorpan commented
I guess this is ready but @annevk should merge together with the spec change when he gets back.

2017-06-27 23:39 UTC, annevk commented
I kinda want to know from @domenic and @jakearchibald what the MVP is. Mozilla would also need the Fetch part to be defined in order to ship something, though potentially just Streams could work.

2017-06-28 09:30 UTC, jakearchibald commented
I think cancelling a fetch needs to be part of the MVP. Passing the signal through to the service worker could come later (but conscious we've left people waiting a long time here).

2017-07-14 14:08 UTC, merged