Migrating PaintWorklet layout tests to wpt
web-platform-tests/wpt pull request #6163
Opened 2017-06-06 12:34 UTC by xidachen

We have a set of layout tests under chromium repo for PaintWorklet. Before shipping PaintWorklet, we would want to migrate the tests wpt.

The set of tests in this pull request are all ref tests. More tests will come soon.

Please review. @bfgeek @foolip

2017-06-06 12:48 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239945709)

# Firefox (nightly) #
Testing web-platform-tests at revision 114231ef27d73ccd458480ba25fc9e9654d7fae1
Using browser at version BuildID 20170605100313; SourceStamp 275588f4d852d7dc183a9dcc70a311413dc7a063
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>19 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/background-image-alpha.html">/css-paint-api/background-image-alpha.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/background-image-multiple.html">/css-paint-api/background-image-multiple.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/background-image-tiled.html">/css-paint-api/background-image-tiled.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/invalid-image-constructor-error.html">/css-paint-api/invalid-image-constructor-error.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/invalid-image-paint-error.html">/css-paint-api/invalid-image-paint-error.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/invalid-image-pending-script.html">/css-paint-api/invalid-image-pending-script.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/overdraw.html">/css-paint-api/overdraw.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint-arguments.html">/css-paint-api/paint-arguments.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint-function-arguments.html">/css-paint-api/paint-function-arguments.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-composite.html">/css-paint-api/paint2d-composite.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-filter.html">/css-paint-api/paint2d-filter.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-gradient.html">/css-paint-api/paint2d-gradient.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-image.html">/css-paint-api/paint2d-image.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-paths.html">/css-paint-api/paint2d-paths.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-rects.html">/css-paint-api/paint2d-rects.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-shadows.html">/css-paint-api/paint2d-shadows.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-transform.html">/css-paint-api/paint2d-transform.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/valid-image-after-load.html">/css-paint-api/valid-image-after-load.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/valid-image-before-load.html">/css-paint-api/valid-image-before-load.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

2017-06-06 12:48 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239945712)

# Sauce (safari) #
Testing web-platform-tests at revision 114231ef27d73ccd458480ba25fc9e9654d7fae1
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>19 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/background-image-alpha.html">/css-paint-api/background-image-alpha.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/background-image-multiple.html">/css-paint-api/background-image-multiple.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/background-image-tiled.html">/css-paint-api/background-image-tiled.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/invalid-image-constructor-error.html">/css-paint-api/invalid-image-constructor-error.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/invalid-image-paint-error.html">/css-paint-api/invalid-image-paint-error.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/invalid-image-pending-script.html">/css-paint-api/invalid-image-pending-script.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/overdraw.html">/css-paint-api/overdraw.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint-arguments.html">/css-paint-api/paint-arguments.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint-function-arguments.html">/css-paint-api/paint-function-arguments.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-composite.html">/css-paint-api/paint2d-composite.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-filter.html">/css-paint-api/paint2d-filter.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-gradient.html">/css-paint-api/paint2d-gradient.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-image.html">/css-paint-api/paint2d-image.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-paths.html">/css-paint-api/paint2d-paths.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-rects.html">/css-paint-api/paint2d-rects.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-shadows.html">/css-paint-api/paint2d-shadows.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-transform.html">/css-paint-api/paint2d-transform.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/valid-image-after-load.html">/css-paint-api/valid-image-after-load.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/valid-image-before-load.html">/css-paint-api/valid-image-before-load.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

2017-06-06 12:48 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239945725)

# Chrome (unstable) #
Testing web-platform-tests at revision 114231ef27d73ccd458480ba25fc9e9654d7fae1
Using browser at version 60.0.3112.10 dev
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>19 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/background-image-alpha.html">/css-paint-api/background-image-alpha.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/background-image-multiple.html">/css-paint-api/background-image-multiple.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/background-image-tiled.html">/css-paint-api/background-image-tiled.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/invalid-image-constructor-error.html">/css-paint-api/invalid-image-constructor-error.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/invalid-image-paint-error.html">/css-paint-api/invalid-image-paint-error.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/invalid-image-pending-script.html">/css-paint-api/invalid-image-pending-script.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/overdraw.html">/css-paint-api/overdraw.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint-arguments.html">/css-paint-api/paint-arguments.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint-function-arguments.html">/css-paint-api/paint-function-arguments.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-composite.html">/css-paint-api/paint2d-composite.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-filter.html">/css-paint-api/paint2d-filter.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-gradient.html">/css-paint-api/paint2d-gradient.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-image.html">/css-paint-api/paint2d-image.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-paths.html">/css-paint-api/paint2d-paths.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-rects.html">/css-paint-api/paint2d-rects.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-shadows.html">/css-paint-api/paint2d-shadows.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/paint2d-transform.html">/css-paint-api/paint2d-transform.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/valid-image-after-load.html">/css-paint-api/valid-image-after-load.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6163/css-paint-api/valid-image-before-load.html">/css-paint-api/valid-image-before-load.html</a></summary>


| Subtest | Results | Messages |
|---------|---------|----------|
|         | FAIL    |          |

</details>
</details>

2017-06-06 12:48 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/239945726)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 114231ef27d73ccd458480ba25fc9e9654d7fae1
Using browser at version 14.14393
Starting 10 test iterations

2017-06-07 12:20 UTC, foolip commented
@xidachen, working directly in this repository is just fine, but if you'd like, you can move them, deleting the old tests, in a Chromium CL directly. It saves you a bit of work in total.

I'll review this though.

2017-06-07 12:29 UTC, foolip requested changes
I've only skimmed the changes since these are converted from existing tests that have already been reviewed.

2017-06-07 12:29 UTC, foolip commented on common/css-paint-tests.js
> +        testRunner.waitUntilDone();
These are WebKit/Blink internals and shouldn't be included in wpt. The `class="reftest-wait"` mechanism is probably what's needed, so common/reftest-wait.js for a script wrapping that.

2017-06-07 12:29 UTC, foolip commented on common/css-paint-tests.js
> +function takeScreenshot(frame_cnt) {
How about introducing a `waitForAnimationFrames(n)` or similar, and using, `waitForAnimationFrames(n).then(takeScreenshot)`, where `takeScreenshot` comes from common/reftest-wait.js?

2017-06-07 12:29 UTC, foolip commented on css-paint-api/background-image-alpha-ref.html
> +function drawCanvas(canvasID, hasAlpha) {
This seems a bit elaborate for the reference file, would divs with `box-sizing: border-box; border: 4px solid blue` achieve the same result?

2017-06-07 12:29 UTC, foolip commented on css-paint-api/background-image-alpha.html
> +<script src="../common/css-paint-tests.js"></script>
Use absolute paths for /common/*

2017-06-07 12:29 UTC, xidachen commented
@foolip thanks for pointing it out. I didn't even know that it is a two way sync between chromium and wpt. For the rest of the tests, I will do that in a chromium CL instead of doing it in two steps :)

2017-06-07 12:30 UTC, foolip commented
I will be away for the rest of the week so someone else needs to follow up, or you could move the review to Chromium. So that my review doesn't block merging, I'll approve it now, treat as LGTM % nits.

2017-06-07 12:30 UTC, foolip approved these changes

2017-06-07 13:44 UTC, foolip commented on css-paint-api/background-image-alpha.html
> +<script src="/common/css-paint-tests.js"></script>
Do the tests still work, or do they all need to include /common/reftest-wait.js?

2017-06-07 13:51 UTC, xidachen commented on css-paint-api/background-image-alpha.html
> +<script src="/common/css-paint-tests.js"></script>
Sorry, I am writing another patch, will be up in a few mins.

2017-06-07 14:04 UTC, xidachen commented
@foolip I have made changes, tested locally and all of them passed.

2017-06-10 01:37 UTC, closed without merging