Add new test for createDataChannel
web-platform-tests/wpt pull request #6176
Opened 2017-06-07 10:02 UTC by soareschen

Adds type coverage annotation and a few new tests for `createDataChannel`.

2017-06-07 10:13 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240303275)

# Firefox (nightly) #
Testing web-platform-tests at revision cc3c579b9e12864cd4a49bd1fb1a1b7cd51f802e
Using browser at version BuildID 20170606100219; SourceStamp 58ce95bc58ce4ba200413c8bed87786dccf3d105
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6176/webrtc/RTCPeerConnection-createDataChannel.html">/webrtc/RTCPeerConnection-createDataChannel.html</a></summary>


|                                       Subtest                                       | Results |                                                                                                                                                  Messages                                                                                                                                                  |
|-------------------------------------------------------------------------------------|---------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                     | OK      |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel required arguments`                                              | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with closed connection`                                          | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel defaults`                                                        | FAIL    | `RTCDataChannel is not defined`                                                                                                                                                                                                                                                                            |
| `createDataChannel with label "foo"`                                                | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with label null`                                                 | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with label undefined`                                            | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with label lone surrogate`                                       | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with ordered false`                                              | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with ordered null/undefined`                                     | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with maxPacketLifeTime 0`                                        | FAIL    | `assert_equals: expected (number) 0 but got (undefined) undefined`                                                                                                                                                                                                                                         |
| `createDataChannel with maxRetransmits 0`                                           | FAIL    | `assert_equals: expected (number) 0 but got (undefined) undefined`                                                                                                                                                                                                                                         |
| `createDataChannel with both maxPacketLifeTime and maxRetransmits`                  | FAIL    | `assert_throws: function "() => pc.createDataChannel('', {\n    maxPacketLifeTime: 0,\n    maxRetransmits: 0\n  })" threw object "InvalidParameterError: Both maxPacketLifeTime and maxRetransmits cannot be provided" that is not a DOMException SyntaxError: property "code" is equal to 0, expected 12` |
| `createDataChannel with protocol "foo"`                                             | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with protocol null`                                              | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with protocol undefined`                                         | PASS    |                                                                                                                                                                                                                                                                                                            |
| `createDataChannel with protocol lone surrogate`                                    | PASS    |                                                                                                                                          [...]

2017-06-07 10:13 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240303276)

# Sauce (safari) #
Testing web-platform-tests at revision cc3c579b9e12864cd4a49bd1fb1a1b7cd51f802e
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>1 test ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6176/webrtc/RTCPeerConnection-createDataChannel.html">/webrtc/RTCPeerConnection-createDataChannel.html</a></summary>


|                                       Subtest                                       | Results |                 Messages                 |
|-------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                     | OK      |                                          |
| `createDataChannel required arguments`                                              | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with closed connection`                                          | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel defaults`                                                        | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with label "foo"`                                                | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with label null`                                                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with label undefined`                                            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with label lone surrogate`                                       | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with ordered false`                                              | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with ordered null/undefined`                                     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with maxPacketLifeTime 0`                                        | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with maxRetransmits 0`                                           | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with both maxPacketLifeTime and maxRetransmits`                  | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with protocol "foo"`                                             | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with protocol null`                                              | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with protocol undefined`                                         | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with protocol lone surrogate`                                    | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with negotiated true`                                            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with id -1`                                                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with id 0`                                                       | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with id 1`                                                       | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with id 65534`                                                   | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with id 65535`                                                   | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with id 65536`                                                   | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with priority "high"`                                            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with invalid priority should throw TypeError`                    | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with negotiated false and long label should throw TypeError`     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with negotiated false and long protocol should throw TypeError`  | FAIL    | `Can't find variable: RTCPeerConnection` |
| `createDataChannel with negotiated true and long label and protocol should succeed` | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
</details>

2017-06-07 10:13 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240303282)

# Chrome (unstable) #
Testing web-platform-tests at revision cc3c579b9e12864cd4a49bd1fb1a1b7cd51f802e
Using browser at version 60.0.3112.20 dev
Starting 10 test iterations

2017-06-07 10:13 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/240303283)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision cc3c579b9e12864cd4a49bd1fb1a1b7cd51f802e
Using browser at version 14.14393
Starting 10 test iterations

2017-06-07 18:28 UTC, rwaldron requested changes

2017-06-07 18:28 UTC, rwaldron commented on webrtc/RTCPeerConnection-createDataChannel.html
> +}
This is unnecessary, just use `" ".repeat(65536)`

2017-06-07 18:28 UTC, rwaldron commented on webrtc/RTCPeerConnection-createDataChannel.html
> +      label: longString,
use `" ".repeat(65536)`

2017-06-07 18:28 UTC, rwaldron commented on webrtc/RTCPeerConnection-createDataChannel.html
> +      protocol: longString,
use `" ".repeat(65536)`

2017-06-07 18:28 UTC, rwaldron commented on webrtc/RTCPeerConnection-createDataChannel.html
> +    protocol: longString,
use `" ".repeat(65536)`

2017-06-07 18:28 UTC, rwaldron commented on webrtc/RTCPeerConnection-createDataChannel.html
> +  const protocol = generateLongString(65536);
Delete this line, it's not used

2017-06-07 18:29 UTC, rwaldron commented on webrtc/RTCPeerConnection-createDataChannel.html
>  <script>
Above this line, change the title to "RTCPeerConnection.prototype.createDataChannel"

2017-06-08 03:46 UTC, soareschen commented on webrtc/RTCPeerConnection-createDataChannel.html
> +}
Ah nice. Didn't know about that.

2017-06-08 03:49 UTC, soareschen commented
Fixed the feedback. I also restyled the old code a bit to make it look more consistent with the new style I adopt.

2017-06-08 13:25 UTC, rwaldron approved these changes

2017-06-08 13:25 UTC, rwaldron commented on webrtc/RTCPeerConnection-createDataChannel.html
> +<title>RTCPeerConnection.prototype.createDataChannel</title>
Thank you!

2017-06-08 13:25 UTC, rwaldron commented on webrtc/RTCPeerConnection-createDataChannel.html
> +}, 'createDataChannel with no argument should throw TypeError');
Excellent!!

2017-06-08 13:25 UTC, rwaldron commented on webrtc/RTCPeerConnection-createDataChannel.html
> +}
👍

2017-06-08 13:25 UTC, rwaldron commented on webrtc/RTCPeerConnection-createDataChannel.html
>  }
👍

2017-06-08 13:25 UTC, rwaldron commented on webrtc/RTCPeerConnection-createDataChannel.html
> +        agents maximum value.
Once again, thank you for providing this TODO section :)

2017-06-08 13:25 UTC, merged