[css-tables] Add tests for visibility: collapse, visibility:hidden
web-platform-tests/wpt pull request #6199
Opened 2017-06-09 17:04 UTC by joysyu

2017-06-09 17:27 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241274160)

# Firefox (nightly) #
Testing web-platform-tests at revision ed9dc414128617653dcfcac55b58989cfad4540b
Using browser at version BuildID 20170609100251; SourceStamp f4262773c4331d4ae139be536ce278ea9aad3436
Starting 10 test iterations
No tests run.

2017-06-09 17:27 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241274161)

# Sauce (safari) #
Testing web-platform-tests at revision ed9dc414128617653dcfcac55b58989cfad4540b
Using browser at version 10.0
Starting 10 test iterations
No tests run.

2017-06-09 17:27 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241274169)

# Chrome (unstable) #
Testing web-platform-tests at revision ed9dc414128617653dcfcac55b58989cfad4540b
Using browser at version 60.0.3112.20 dev
Starting 10 test iterations
No tests run.

2017-06-09 17:27 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241274170)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision ed9dc414128617653dcfcac55b58989cfad4540b
Using browser at version 14.14393
Starting 10 test iterations
No tests run.

2017-06-09 18:19 UTC, joysyu commented
Looks like the timeout isn't related to my tests, but I'm not sure. Can someone confirm? Thanks!

2017-06-10 00:12 UTC, sideshowbarker commented
w3c-test:mirror

2017-06-22 00:52 UTC, gregwhitworth requested changes
Overall it looks good @joysu. One thing that I'm not seeing is any testing of replaced elements nor dynamic modifications. Knowing that Edge currently has a bug in invalidation it would be useful to ensure that we're mimicking a user invalidation of some type. Thanks.

2017-06-22 00:52 UTC, gregwhitworth commented on css/work-in-progress/microsoft/css-tables/visibility-collapse-col-002.html
> +    generate_tests(assert_equals, [
Please do not use `generate_tests()` - we are actively discouraging it. I know that we have throughout the testcases that are currently in WIP and you probably got that pattern from us. To fix this, use a for loop and then `assert_equals()`. You can see more on this on the [WPT Documentation](http://web-platform-tests.org/writing-tests/testharness.html).

2017-06-22 00:52 UTC, gregwhitworth commented on css/work-in-progress/microsoft/css-tables/visibility-collapse-col-003.html
> +    generate_tests(assert_equals, [
same comment as above

2017-06-22 00:52 UTC, gregwhitworth commented on css/work-in-progress/microsoft/css-tables/visibility-collapse-non-rowcol-001.html
> +    generate_tests(assert_equals, [
same comment as above

2017-06-22 00:52 UTC, gregwhitworth commented on css/work-in-progress/microsoft/css-tables/visibility-collapse-row-002.html
> +    generate_tests(assert_equals, [
same comment as above

2017-06-22 00:52 UTC, gregwhitworth commented on css/work-in-progress/microsoft/css-tables/visibility-collapse-row-003.html
> +    generate_tests(assert_equals, [
same comment as above

2017-06-22 00:52 UTC, gregwhitworth commented on css/work-in-progress/microsoft/css-tables/visibility-hidden-col-001.html
> +    generate_tests(assert_equals, [
same comment as above

2017-06-22 00:52 UTC, gregwhitworth commented on css/work-in-progress/microsoft/css-tables/visibility-hidden-nested-001.html
> +    generate_tests(assert_equals, [
same comment as above

2017-06-22 00:52 UTC, gregwhitworth commented on css/work-in-progress/microsoft/css-tables/visibility-hidden-nested-002.html
> +    generate_tests(assert_equals, [
same comment as above

2017-06-22 00:52 UTC, gregwhitworth commented on css/work-in-progress/microsoft/css-tables/visibility-hidden-row-001.html
> +    generate_tests(assert_equals, [
same comment as above

2017-06-22 00:52 UTC, gregwhitworth commented on css/work-in-progress/microsoft/css-tables/visibility-hidden-row-002.html
> +    generate_tests(assert_equals, [
same comment as above

2017-06-22 00:52 UTC, gregwhitworth commented on css/work-in-progress/microsoft/css-tables/visibility-collapse-col-002.html
> +    generate_tests(assert_equals, [
In addition, I know that I initially spoke with @davidsgrogan and we planned to put them in WIP, and he had the good point of just putting them into CSS3 tables path. We should begin on doing this, the path is `css/css-tables-3`. I won't block on this as @FremyCompany or myself will move them a bit later. I also think it's imperative that we resolve on the spec language for the sizing and painting of `visibility: collapse` within [issue 478](https://github.com/w3c/csswg-drafts/issues/478). @FremyCompany and myself will try to land this, so if you could please stage these in the actual tables folder that would be greatly appreciated, but not required for my sign off. Thanks!

2017-06-23 22:27 UTC, joysyu commented
Thanks so much @gregwhitworth for the code review! In addition to moving the tests to css-tables-3 and taking our generate_tests, I added three row span tests. I also added three tests with dynamic changes: visibility-collapse-col-004.html, visibility-collapse-row-004.html, and visibility-collapse-row-005.html (this also collapses an image). I'm not too sure what you mean by replaced elements; does collapsing an image count?

2017-06-23 22:29 UTC, joysyu commented
Also, visibility-collapse-nested-001.html addresses the Edge bug :)

2017-07-11 00:15 UTC, gregwhitworth requested changes
@joysyu Overall this is really great. We're almost there, a few more changes as I tested them in FF/Edge and cross compared with the spec. Thank you so much - great work!

2017-07-11 00:15 UTC, gregwhitworth commented on css/css-tables-3/visibility-collapse-row-005.html
> +<!doctype html>
add dynamic to the end of this file name.

2017-07-11 00:15 UTC, gregwhitworth commented on css/css-tables-3/visibility-collapse-row-005.html
> +    colgroup = document.getElementById("collapse");
you are getting a row, not a colgroup - change the variable name accordingly.

2017-07-11 00:15 UTC, gregwhitworth commented on css/css-tables-3/visibility-collapse-rowspan-002.html
> +<!doctype html>
Can you please create a copy of `rowspan-002` & `rowspan-003` and create ones that are in `border-collapse: seperate` mode? Make sure this is reflected in the name so it's easy to differentiate the tests.

2017-07-17 22:40 UTC, joysyu commented on css/css-tables-3/visibility-collapse-rowspan-002.html
> +<!doctype html>
Done

2017-07-17 22:40 UTC, joysyu commented on css/css-tables-3/visibility-collapse-row-005.html
> +    colgroup = document.getElementById("collapse");
Done

2017-07-17 22:40 UTC, joysyu commented on css/css-tables-3/visibility-collapse-row-005.html
> +<!doctype html>
Done

2017-07-17 22:40 UTC, joysyu commented on css/css-tables-3/visibility-collapse-row-003.html
> +        116,
Sorry this is actually the exact same test as visibility-collapse-nested-001, so I've deleted that and fixed this test to be more complex to catch Edge's bug. Thanks for catching this!

2017-07-17 22:40 UTC, joysyu commented on css/css-tables-3/visibility-collapse-nested-001.html
> +<link rel="help" href="https://drafts.csswg.org/css-x-tables-3/#computing-the-x-table-height">
Done

2017-07-17 22:59 UTC, joysyu commented
Thank you @gregwhitworth! I've made the changes :) Let me know what you think!

2017-11-07 22:34 UTC, gsnedders commented
@gregwhitworth @FremyCompany ping?

2017-11-07 23:09 UTC, davidsgrogan commented
Joy eventually landed these through chromium's sync. This can be closed.

2017-11-07 23:11 UTC, closed without merging