Install Firefox from Beta channel in CI
web-platform-tests/wpt pull request #6204
Opened 2017-06-09 22:09 UTC by jugglinmike

The latest build of Firefox available on the "Nightly" channel suffers
from timeout errors in automation. Switch the installation procedure to
instead source from the Beta channel in order to use a build that is
known to work today and is less susceptible to future regressions.

2017-06-09 22:19 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241372948)

# Firefox (nightly) #
Testing web-platform-tests at revision d0a56903a2704df60e9c2681a61ff83135a5f4b6
Using browser at version BuildID 20170601203257; SourceStamp cb4a4275b365b126ae56b1df5521756b693d8ff9
Starting 10 test iterations
No tests run.

2017-06-09 22:19 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241372949)

# Sauce (safari) #
Testing web-platform-tests at revision d0a56903a2704df60e9c2681a61ff83135a5f4b6
Using browser at version 10.0
Starting 10 test iterations
No tests run.

2017-06-09 22:19 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241372955)

# Chrome (unstable) #
Testing web-platform-tests at revision d0a56903a2704df60e9c2681a61ff83135a5f4b6
Using browser at version 60.0.3112.20 dev
Starting 10 test iterations
No tests run.

2017-06-09 22:19 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/241372956)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision d0a56903a2704df60e9c2681a61ff83135a5f4b6

2017-06-09 23:29 UTC, jugglinmike commented
This patch has failed the CI build because the `testharness.js` tests rely on a feature that is currently only available in the "Nightly" Firefox release channel (assignment of a `stack` parameter for rejected promises). Although the new failure demonstrates that use of the "Beta" channel resolves issue gh-6202 as intended, it cannot be merged in its current state due to this new failure.

@jgraham It may be worth temporarily disabling the `testharness.js` tests and landing this. Because it is now late on a Friday, the problem is unlikely to cause immediate problems, and it's unclear what anyone's availability will be like to support changes in the interim.

[I have reported this bug to Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1371868) to help see this resolved in a future Nightly release.

2017-06-12 10:19 UTC, jgraham requested changes
I think this is the wrong appraoch. We really want to run stability checks on nightly builds. The problem here is with the testharness.js tests. Running those on e.g. dev edition seems fine, but there should be a separate codepath for that. Note that today is merge day so beta will soon be like current nightly (approximately). Also note that gecko's beta is pretty unlike the Chrome dev channel since it's released every six weeks and frozen.

2017-06-12 14:49 UTC, jugglinmike commented
@jgraham Judging from the latest builds on `master`, it looks like this was a hiccup that was resolved in subsequent builds of Nightly. Even so, I want to respond to the following because it sounds like I may be misunderstanding something:

> We really want to run stability checks on nightly builds. The problem here is
> with the testharness.js tests. Running those on e.g. dev edition seems fine,
> but there should be a separate codepath for that.

Because the problem concerned the Firefox-to-WebDriver communication channel, it effected any job that used WebDriver to automate Firefox Nightly. Judging from this build for this specific patch, that might appear to be only the jobs that ran the tests for the `testharness.js` framework, but that is because no "typical" WPT tests were added/modified. If they had been, then the stability checker would have attempted to validate them, and the subsequent Firefox job would have timed out as well.

For example, see [the build](https://travis-ci.org/w3c/web-platform-tests/builds/241391067) for gh-6175 (as performed on Friday afternoon).

Does that sound right to you? If so, I think we'll need to consider another strategy that will be acceptable for both the tests for the `testharness.js` framework and the "typical" WPT tests.

2017-06-12 16:05 UTC, jgraham commented
Yeah, I hadn't realised when I wrote the above that all Fx jobs were affected. But I'm now inclined to do even less; unless you are volunteering to build an infrastructure to smoketest the builds we use and roll back to an earlier one if that fails, I suggest we treat occasional failures of this kind as part of the cost of testing the bleeding edge of the platform. It seems like this particular kind of failure should be very rare (and I don't understand this one) because all wpt tests are run on m-c and I would expect this level of failure to stop the build ever becoming a nightly. Still it obviously can happen sometimes.

2017-06-12 16:17 UTC, jugglinmike commented
> unless you are volunteering to build an infrastructure to smoketest the
> builds we use and roll back to an earlier one if that fails

This sounds like too big a job to complete on a voluntary basis, but there are some folks at Bocoup who would be well-suited to this. Then again, given what you've said about the expected frequency of the issue, we will probably be hard-pressed to fund a dedicated effort.

I'm satisfied with taking this as a cost of testing the bleeding edge. We can revisit your smoketest idea if that cost starts to seem to high.

2017-06-12 16:17 UTC, closed without merging