Add new test for RTCConfiguration iceTransportPolicy
web-platform-tests/wpt pull request #6479
Opened 2017-07-06 07:56 UTC by soareschen

This moves the constructor test for `iceTransportPolicy` out from RTCPeerConnection-constructor.html to a new file RTCConfiguration-iceTransportPolicy.html. It also tests on getConfiguration() and setConfiguration() and that `iceTransportPolicy` can be changed via setConfiguration().

2017-07-07 16:34 UTC, rwaldron requested changes
Needs rebase

2017-07-07 16:34 UTC, rwaldron commented
Once this is rebased, I will merge

2017-07-10 04:32 UTC, soareschen commented
Rebased now.

2017-07-12 16:52 UTC, rwaldron approved these changes
Coverage spec updated!

- https://rwaldron.github.io/webrtc-pc/#rtcconfiguration-dictionary
- https://rwaldron.github.io/webrtc-pc/#dom-rtcconfiguration-icetransportpolicy
- https://rwaldron.github.io/webrtc-pc/#dom-rtcicetransportpolicy

2017-07-12 16:52 UTC, merged