Add new test for RTCConfiguration rtcpMuxPolicy
web-platform-tests/wpt pull request #6480
Opened 2017-07-06 09:13 UTC by soareschen

This fixes a few issues with the old constructor tests for rtcpMuxPolicy. 

- It read the configuration value back using `getConfiguration()` to make sure that the configuration field is actually implemented by the browsers. 
- Recent spec also make the `negotiate` optional, and allow browsers to throw `NotSupportedError` if `negotiate` is not supported.
- Test `setConfiguration()` to make sure that `rtcpMuxPolicy` cannot be changed.

2017-07-07 16:35 UTC, rwaldron requested changes
Needs rebase

2017-07-07 16:35 UTC, rwaldron commented
Once this is rebased, I will merge

2017-07-10 04:32 UTC, soareschen commented
Rebased now.

2017-07-12 16:58 UTC, rwaldron approved these changes
Coverage spec updated:

- https://rwaldron.github.io/webrtc-pc/#rtcconfiguration-dictionary
- https://rwaldron.github.io/webrtc-pc/#dom-rtcconfiguration-rtcpmuxpolicy
- https://rwaldron.github.io/webrtc-pc/#dom-rtcrtcpmuxpolicy
- https://rwaldron.github.io/webrtc-pc/#constructor (step 3)

2017-07-12 16:58 UTC, rwaldron commented on webrtc/RTCConfiguration-rtcpMuxPolicy.html
> +  }, `with { rtcpMuxPolicy: 'invalid' } should throw TypeError`);
👍

2017-07-12 16:58 UTC, rwaldron commented on webrtc/RTCConfiguration-rtcpMuxPolicy.html
> +  }, `setConfiguration({}) with initial rtcpMuxPolicy negotiate should throw InvalidModificationError`);
👍

2017-07-12 16:58 UTC, rwaldron commented
Needs to be rebased, then can be merged

2017-07-12 17:00 UTC, rwaldron commented
If you make me a collaborator on your fork of the repo, I can resolve these minor conflicts and push to your PR'ed branches—which will let me then merge PRs that are approved.

2017-07-13 03:25 UTC, soareschen commented
> If you make me a collaborator on your fork of the repo, I can resolve these minor conflicts and push to your PR'ed branches—which will let me then merge PRs that are approved.

Agree. I have sent you an invite for collaborator at my forked repo. Thanks!

2017-07-13 03:37 UTC, merged