Add transceiver test for set session description
web-platform-tests/wpt pull request #6511
Opened 2017-07-11 06:59 UTC by soareschen

This is added to a new file RTCPeerConnection-setDescription-transceiver.html in attempt to better organize the tests for setting session description.

2017-07-12 17:21 UTC, rwaldron requested changes
Issues with test code that need to be addressed

2017-07-12 17:21 UTC, rwaldron commented on webrtc/RTCPeerConnection-setDescription-transceiver.html
> +      return pc.setLocalDescription(offer);
`offer` is not defined anywhere in this scope

2017-07-12 17:21 UTC, rwaldron commented on webrtc/RTCPeerConnection-setDescription-transceiver.html
> +        assert_equals(offer.sdp.includes(`\r\na=mid:${transceiver2.mid}`), true,
`offer` is not defined anywhere in this scope

2017-07-13 04:29 UTC, soareschen commented on webrtc/RTCPeerConnection-setDescription-transceiver.html
> +        assert_equals(offer.sdp.includes(`\r\na=mid:${transceiver2.mid}`), true,
Thanks for spotting. I have rebased and fixed the errors.

2017-07-19 16:50 UTC, rwaldron approved these changes

2017-07-19 16:50 UTC, merged