Add test for RTCDtlsTransport.prototype.getRemoteCertificates
web-platform-tests/wpt pull request #6513
Opened 2017-07-11 08:36 UTC by soareschen

2017-07-12 17:23 UTC, rwaldron requested changes
This file has a JS SyntaxError on line 99

2017-07-13 03:53 UTC, soareschen commented
Oops, forgot to rerun test after refactoring. Rebased and fixed.

2017-07-19 16:57 UTC, rwaldron approved these changes

2017-07-19 16:57 UTC, rwaldron commented
- Coverage spec updated:
    - https://rwaldron.github.io/webrtc-pc/#rtcdtlstransport-interface

2017-07-19 16:57 UTC, merged