Split tests for setting session description into multiple files
web-platform-tests/wpt pull request #6537
Opened 2017-07-13 05:31 UTC by soareschen

The tests for setting session description is rather large, with 50+ steps involved in the spec. Currently the tests are located among RTCPeerConnection-setLocalDescription.html and RTCPeerConnection-setRemoteDescription.html, but the number of tests are getting large that it is becoming difficult to organize and keep track of the tests.

This PR is a succession of #6491 in effort to reorganize the session description tests. It split the tests further into smaller files. Specifically there are 4 more files for the combinations of setting local/remote offer/answer descriptions.

The tests are moved as is to the new files, with the coverage report file updated to reflect the changes.

2017-07-19 17:15 UTC, rwaldron requested changes
Only minor spec numbering fixes and then this can land

2017-07-19 17:15 UTC, rwaldron commented on webrtc/RTCPeerConnection-setLocalDescription-answer.html
> +      2.  If description is set as a local description, then run one of the following
`2.` => `2.2.2`

2017-07-19 17:15 UTC, rwaldron commented on webrtc/RTCPeerConnection-setLocalDescription-answer.html
> +      4.  If description.sdp is null and description.type is answer, set description.sdp
This completes all steps for `setLocalDescription`!!

2017-07-19 17:15 UTC, rwaldron commented on webrtc/RTCPeerConnection-setLocalDescription-offer.html
> +      2.2.  If description is set as a local description, then run one of the following
`2.2.` => `2.2.2.`

2017-07-19 17:15 UTC, rwaldron commented on webrtc/coverage/set-session-description.txt
>    Total         58
Coverage spec updated to match

2017-07-20 03:10 UTC, soareschen commented on webrtc/RTCPeerConnection-setLocalDescription-answer.html
> +      4.  If description.sdp is null and description.type is answer, set description.sdp
Hope so. The tests have been so enormous that I have lost track of what's been covered countless times.

2017-07-20 03:11 UTC, soareschen commented on webrtc/RTCPeerConnection-setLocalDescription-answer.html
> +      2.  If description is set as a local description, then run one of the following
Fixed and rebased.

2017-07-20 03:24 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255509947)

# Firefox (nightly) #
Testing web-platform-tests at revision 44713b1fb271bbf881d7012725003132a39503c9
Using browser at version BuildID 20170719100147; SourceStamp 1b065ffd8a535a0ad4c39a912af18e948e6a42c1
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>6 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6537/webrtc/RTCPeerConnection-setLocalDescription-answer.html">/webrtc/RTCPeerConnection-setLocalDescription-answer.html</a></summary>


|                                                      Subtest                                                      | Results |                                                                                                                              Messages                                                                                                                             |
|-------------------------------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                   | OK      |                                                                                                                                                                                                                                                                   |
| `setLocalDescription() with valid answer should succeed`                                                          | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                                                   |
| `setLocalDescription() with type answer and null sdp should use lastAnswer generated from createAnswer`           | FAIL    | `promise_test: Unhandled rejection with value: object "InvalidParameterError: Empty or null SDP provided to setLocalDescription"`                                                                                                                                 |
| `setLocalDescription() with answer not created by own createAnswer() should reject with InvalidModificationError` | FAIL    | `assert_throws: function "function() { throw e }" threw object "InvalidStateError: Calling SetLocal without first calling CreateOffer/Answer is not supported." that is not a DOMException InvalidModificationError: property "code" is equal to 11, expected 13` |
| `Calling setLocalDescription(answer) from stable state should reject with InvalidStateError`                      | FAIL    | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."`                                                                                            |
| `Calling setLocalDescription(answer) from have-local-offer state should reject with InvalidStateError`            | FAIL    | `promise_test: Unhandled rejection with value: object "InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."`                                                                                            |
| `Test onsignalingstatechange event for setLocalDescription() with valid answer should succeed`                    | PASS    |                                                                                                                                                                                                                                                                   |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6537/webrtc/RTCPeerConnection-setLocalDescription-offer.html">/webrtc/RTCPeerConnection-setLocalDescription-offer.html</a></summary>


|                                                     Subtest                                                     | Results |                                                                                                                              Messages                                                                                                                             |
|-----------------------------------------------------------------------------------------------------------------|---------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                 | OK      |                                                                                                                                                                                                                                                                   |
| `setLocalDescription with valid offer should succeed`                                                           | FAIL    | `assert_not_equals: Expect session description to be defined, but got undefined got disallowed value undefined`                                                                                                                                                   |
| `setLocalDescription with type offer and null sdp should use lastOffer generated from createOffer`              | FAIL    | `promise_test: Unhandled rejection with value: object "InvalidParameterError: Empty or null SDP provided to setLocalDescription"`                                                                                                                                 |
| `setLocalDescription() with offer not created by own createOffer() should reject with InvalidModificationError` | FAIL    | `assert_throws: function "function() { throw e }" threw object "InvalidStateError: Calling SetLocal without first calling CreateOffer/Answer is not supported." that is not a DOMException InvalidModificationError: property "code" is equal to 11, expected 13` |
| `Set created offer other than last offer should reject with InvalidModificationError`                           | FAIL    | `assert_throws: function "function() { throw e }" threw object "InvalidSessionDescriptionError: Changing the media-type of m-sections is not allowed" that is not a DOMException InvalidModificationError: property "code" is equal to 0, expected 13`            |
| `Creating and setting offer multiple times should succeed`                                                      | FAIL    | `promise_test: Unhandled rejection with value: object "InvalidStateError: Cannot create offer in state have-local-offer"`                                                                                                                                         |
| `setLocalDescription(offer) should never resolve if connection is closed in parallel`                           | FAIL    | `assert_unreached: Pending promise should never be resolved. Instead it is rejected with: InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel. Reached unreachable code`                                 |
| `Test onsignalingstatechange event for setLocalDescription with valid offer should succeed`                     | PASS    |                                                                                                    [...]

2017-07-20 03:24 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255509948)

# Sauce (safari) #
Testing web-platform-tests at revision 44713b1fb271bbf881d7012725003132a39503c9
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>6 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6537/webrtc/RTCPeerConnection-setLocalDescription-answer.html">/webrtc/RTCPeerConnection-setLocalDescription-answer.html</a></summary>


|                                                      Subtest                                                      | Results |                 Messages                 |
|-------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                                                   | OK      |                                          |
| `setLocalDescription() with valid answer should succeed`                                                          | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription() with type answer and null sdp should use lastAnswer generated from createAnswer`           | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription() with answer not created by own createAnswer() should reject with InvalidModificationError` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setLocalDescription(answer) from stable state should reject with InvalidStateError`                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setLocalDescription(answer) from have-local-offer state should reject with InvalidStateError`            | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6537/webrtc/RTCPeerConnection-setLocalDescription-offer.html">/webrtc/RTCPeerConnection-setLocalDescription-offer.html</a></summary>


|                                                     Subtest                                                     | Results |                 Messages                 |
|-----------------------------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                                                 | OK      |                                          |
| `setLocalDescription with valid offer should succeed`                                                           | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription with type offer and null sdp should use lastOffer generated from createOffer`              | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription() with offer not created by own createOffer() should reject with InvalidModificationError` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Set created offer other than last offer should reject with InvalidModificationError`                           | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Creating and setting offer multiple times should succeed`                                                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setLocalDescription(offer) should never resolve if connection is closed in parallel`                           | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6537/webrtc/RTCPeerConnection-setLocalDescription.html">/webrtc/RTCPeerConnection-setLocalDescription.html</a></summary>


|                                                       Subtest                                                       | Results |                 Messages                 |
|---------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                                                     | OK      |                                          |
| `Calling createOffer() and setLocalDescription() again after one round of local-offer/remote-answer should succeed` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Switching role from answerer to offerer after going back to stable state should succeed`                           | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6537/webrtc/RTCPeerConnection-setRemoteDescription-answer.html">/webrtc/RTCPeerConnection-setRemoteDescription-answer.html</a></summary>


|                                                 Subtest                                                  | Results |                 Messages                 |
|----------------------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                                          | OK      |                                          |
| `setRemoteDescription() with valid state and answer should succeed`                                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setRemoteDescription(answer) from stable state should reject with InvalidStateError`            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setRemoteDescription(answer) from have-remote-offer state should reject with InvalidStateError` | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6537/webrtc/RTCPeerConnection-setRemoteDescription-offer.html">/webrtc/RTCPeerConnection-setRemoteDescription-offer.html</a></summary>


|                                                Subtest                                                 | Results |                 Messages                 |
|--------------------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                                        | OK      |                                          |
| `setRemoteDescription with valid offer should succeed`                                                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Setting remote description multiple times with different offer should succeed`                        | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription(offer) should never resolve if connection is closed in parallel`                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `setRemoteDescription(offer) with invalid SDP should reject with RTCError`                             | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Calling setRemoteDescription(offer) from have-local-offer state should reject with InvalidStateError` | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6537/webrtc/RTCPeerConnection-setRemoteDescription.html">/webrtc/RTCPeerConnection-setRemoteDescription.html</a></summary>


|                                              Subtest                                               | Results |                 Messages                 |
|----------------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                                    | OK      |                        [...]

2017-07-20 03:24 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255509954)

# Chrome (unstable) #
Testing web-platform-tests at revision 44713b1fb271bbf881d7012725003132a39503c9

2017-07-20 03:24 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/255509955)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 44713b1fb271bbf881d7012725003132a39503c9
Using browser at version 14.14393
Starting 10 test iterations

2017-07-26 15:57 UTC, rwaldron approved these changes
This needs to be rebased, but since you've done all the other work and I don't want to block this anymore I will do the rebase and get review from @bobholt

2017-07-26 15:57 UTC, rwaldron commented on webrtc/RTCPeerConnection-setLocalDescription-answer.html
> +      4.  If description.sdp is null and description.type is answer, set description.sdp
You're doing a great job

2017-07-26 19:43 UTC, rwaldron commented
I rebased this for you and it's now merged! https://github.com/w3c/web-platform-tests/pull/6629

2017-07-26 19:43 UTC, closed without merging