Add initial test for RTCStats and RTCPeerConnection.prototype.getStats
web-platform-tests/wpt pull request #6539
Opened 2017-07-13 10:18 UTC by soareschen

This is work in progress. There are still a few tests and checking to be done.

This tests the `getStats()` method as well as the webrtc-stats specs. The RTCStats-helper.js file is created for validation of stats objects returned from `getStats()`.

Given the lack of tools in idlharness to test dictionaries, and to test the special ID fields in stats, I have written adhoc validation functions for each type of stats objects. The validation functions are not the prettiest code, but for testing considerations I have make it the least abstractions possible to make it easy for readers and reviewers.

2017-07-14 05:11 UTC, w3c-bots commented
*This report has been truncated because the total content is 283802 characters in length, which is in excess of GitHub.com's limit for comments (65536 characters).

 [View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253475990)

# Firefox (nightly) #
Testing web-platform-tests at revision 63641a5676493700d5cbdf535ec0e5ef2b5bd8b6
Using browser at version BuildID 20170713100259; SourceStamp 30ea2905130e85f9e1d8d56fa3097901eec6514b
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>23 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6539/webrtc/RTCDataChannel-bufferedAmount.html">/webrtc/RTCDataChannel-bufferedAmount.html</a></summary>


|                                    Subtest                                     | Results |                                                                                              Messages                                                                                             |
|--------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                | OK      |                                                                                                                                                                                                   |
| `bufferedAmount should increase to byte length of encoded unicode string sent` | FAIL    | `assert_equals: Expect bufferedAmount to be the byte length of the unicode string expected 12 but got 0`                                                                                          |
| `bufferedAmount should increase to byte length of buffer sent`                 | FAIL    | `assert_equals: Expect bufferedAmount to increase to byte length of sent buffer expected 5 but got 0`                                                                                             |
| `bufferedAmount should increase to size of blob sent`                          | FAIL    | `assert_equals: Expect bufferedAmount to increase to size of sent blob expected 5 but got 0`                                                                                                      |
| `bufferedAmount should increase by byte length for each message sent`          | FAIL    | `assert_unreached: Unexpected promise rejection: Error: assert_equals: Expect bufferedAmount to be the total length of all messages queued to send expected 5 but got 0 Reached unreachable code` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6539/webrtc/RTCDataChannel-send.html">/webrtc/RTCDataChannel-send.html</a></summary>


|                                         Subtest                                          | Results | Messages |
|------------------------------------------------------------------------------------------|---------|----------|
|                                                                                          | OK      |          |
| `Calling send() when data channel is in connecting state should throw InvalidStateError` | PASS    |          |
| `Data channel should be able to send simple string and receive as string`                | PASS    |          |
| `Data channel should be able to send unicode string and receive as unicode string`       | PASS    |          |
| `Data channel should ignore binaryType and always receive string message as string`      | PASS    |          |
| `Data channel should be able to send Uint8Array message and receive as ArrayBuffer`      | PASS    |          |
| `Data channel should be able to send ArrayBuffer message and receive as ArrayBuffer`     | PASS    |          |
| `Data channel should be able to send Blob message and receive as ArrayBuffer`            | PASS    |          |
| `Data channel should be able to send ArrayBuffer message and receive as Blob`            | PASS    |          |
| `Data channel binaryType should receive message as Blob by default`                      | PASS    |          |
| `Sending multiple messages with different types should succeed and be received`          | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6539/webrtc/RTCPeerConnection-addIceCandidate.html">/webrtc/RTCPeerConnection-addIceCandidate.html</a></summary>


|                                                      Subtest                                                      | Results |                                                                                                                                              Messages                                                                                                                                             |
|-------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                   | OK      |                                                                                                                                                                                                                                                                                                   |
| `Add null candidate should reject with TypeError`                                                                 | FAIL    | `assert_unreached: Should have rejected: undefined Reached unreachable code`                                                                                                                                                                                                                      |
| `Add ICE candidate before setting remote description should reject with InvalidStateError`                        | PASS    |                                                                                                                                                                                                                                                                                                   |
| `Add candidate when remote description is null should never resolve when pc is closed`                            | PASS    |                                                                                                                                                                                                                                                                                                   |
| `Add ICE candidate after setting remote description should succeed`                                               | PASS    |                                                                                                                                                                                                                                                                                                   |
| `Add ICE candidate with RTCIceCandidate should succeed`                                                           | PASS    |                                                                                                                                                                                                                                                                                                   |
| `Add candidate with only valid sdpMid should su [...]

2017-07-14 05:11 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253475991)

# Sauce (safari) #
Testing web-platform-tests at revision 63641a5676493700d5cbdf535ec0e5ef2b5bd8b6
Using browser at version 10.0
Starting 10 test iterations
All results were stable
## All results ##
<details>
<summary>23 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6539/webrtc/RTCDataChannel-bufferedAmount.html">/webrtc/RTCDataChannel-bufferedAmount.html</a></summary>


|                                    Subtest                                     | Results |                 Messages                 |
|--------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                | OK      |                                          |
| `bufferedAmount should increase to byte length of encoded unicode string sent` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `bufferedAmount should increase to byte length of buffer sent`                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `bufferedAmount should increase to size of blob sent`                          | FAIL    | `Can't find variable: RTCPeerConnection` |
| `bufferedAmount should increase by byte length for each message sent`          | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6539/webrtc/RTCDataChannel-send.html">/webrtc/RTCDataChannel-send.html</a></summary>


|                                         Subtest                                          | Results |                 Messages                 |
|------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                          | OK      |                                          |
| `Calling send() when data channel is in connecting state should throw InvalidStateError` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should be able to send simple string and receive as string`                | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should be able to send unicode string and receive as unicode string`       | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should ignore binaryType and always receive string message as string`      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should be able to send Uint8Array message and receive as ArrayBuffer`      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should be able to send ArrayBuffer message and receive as ArrayBuffer`     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should be able to send Blob message and receive as ArrayBuffer`            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should be able to send ArrayBuffer message and receive as Blob`            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel binaryType should receive message as Blob by default`                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Sending multiple messages with different types should succeed and be received`          | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6539/webrtc/RTCPeerConnection-addIceCandidate.html">/webrtc/RTCPeerConnection-addIceCandidate.html</a></summary>


|                                                      Subtest                                                      | Results |                 Messages                 |
|-------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                                                   | OK      |                                          |
| `Add null candidate should reject with TypeError`                                                                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add ICE candidate before setting remote description should reject with InvalidStateError`                        | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate when remote description is null should never resolve when pc is closed`                            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add ICE candidate after setting remote description should succeed`                                               | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add ICE candidate with RTCIceCandidate should succeed`                                                           | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with only valid sdpMid should succeed`                                                             | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with only valid sdpMLineIndex should succeed`                                                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `addIceCandidate with first sdpMid and sdpMLineIndex add candidate to first media stream`                         | FAIL    | `Can't find variable: RTCPeerConnection` |
| `addIceCandidate with second sdpMid and sdpMLineIndex should add candidate to second media stream`                | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate for first media stream with null ufrag should add candidate to first media stream`                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Adding multiple candidates should add candidates to their corresponding media stream`                            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add with empty candidate string (end of candidate) should succeed`                                               | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with both sdpMid and sdpMLineIndex manually set to null should reject with TypeError`              | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with only valid candidate string should reject with TypeError`                                     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with invalid candidate string and both sdpMid and sdpMLineIndex null should reject with TypeError` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with empty dict should reject with TypeError`                                                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with manually filled default values should reject with TypeError`                                  | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with invalid sdpMid should reject with OperationError`                                             | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with invalid sdpMLineIndex should reject with OperationError`                                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Invalid sdpMLineIndex should be ignored if valid sdpMid is provided`                                             | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate for media stream 2 with null ufrag should succeed`                                                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with invalid ufrag should reject with OperationError`                                              | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with invalid  [...]

2017-07-14 05:11 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253475997)

# Chrome (unstable) #
Testing web-platform-tests at revision 63641a5676493700d5cbdf535ec0e5ef2b5bd8b6
Using browser at version 61.0.3153.4 dev
Starting 10 test iterations

2017-07-14 05:11 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/253475998)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 63641a5676493700d5cbdf535ec0e5ef2b5bd8b6

2017-07-19 17:25 UTC, rwaldron requested changes
- Coverage spec updated:
    - https://rwaldron.github.io/webrtc-pc/rtcpeerconnection-interface-extensions-2

2017-07-19 17:25 UTC, rwaldron commented on webrtc/RTCPeerConnection-getStats.html
> +          rejected with a newly created TypeError.
I don't see a test for this

2017-07-20 03:03 UTC, soareschen commented on webrtc/RTCPeerConnection-getStats.html
> +          rejected with a newly created TypeError.
I skipped this one because it has been covered by WebIDL and shouldn't reach the step. Has filed w3c/webrtc-pc#1498 for that.

2017-07-26 20:07 UTC, rwaldron approved these changes
- Coverage spec updated: 
    - https://rwaldron.github.io/webrtc-pc/#dom-rtcpeerconnection-getstats()

2017-07-26 20:07 UTC, merged