Add initial test for get/set RTCRtpParameters
web-platform-tests/wpt pull request #6572
Opened 2017-07-18 09:48 UTC by soareschen

This adds tests for `get`/`setParameters()` methods on `RTCRtpSender` and `RTCRtpReceiver`.

Helper functions has been added to help testing the dictionary objects returned from `getParameters()`. The helper functions are almost identical to the ones in #6539, which I will refactor out later on.

There is also some minor modifications on transceiver tests to properly assert the existence of the `addTransceiver()` function in the prototype chain.

The majority of the tests is on modifying the individual fields in `RTCRtpParameters` and check whether they fail or succeed as specified by the specs. The modification tests are non-exhaustive, but there are enough of them that I feel need to add more only in future PRs.

As the specs currently do not require any field to be set, the tests have to take into account undefined fields during modification and result in more verbose code written. I have raised this issue in w3c/webrtc-pc#1493 and seek clarification if any field is required.

2017-07-18 10:05 UTC, w3c-bots commented
*This report has been truncated because the total content is 294482 characters in length, which is in excess of GitHub.com's limit for comments (65536 characters).

 [View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254788133)

# Firefox (nightly) #
Testing web-platform-tests at revision 8a6974db333ca409e35b1c7c6c44ed1c99c25e82
Using browser at version BuildID 20170717100212; SourceStamp aff336ac161daa3ea350e59a288963edbd58ed39
Starting 10 test iterations
## Unstable results ##


|                    Test                   |                                            Subtest                                             |     Results     |                Messages               |
|-------------------------------------------|------------------------------------------------------------------------------------------------|-----------------|---------------------------------------|
| `/webrtc/RTCRtpParameters-encodings.html` | `setParameters() with modified encoding.rtx field should reject with InvalidModificationError` | **FAIL: 20/10** | `pc.addTransceiver is not a function` |

## All results ##
<details>
<summary>31 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6572/webrtc/RTCDataChannel-bufferedAmount.html">/webrtc/RTCDataChannel-bufferedAmount.html</a></summary>


|                                    Subtest                                     | Results |                                                                                              Messages                                                                                             |
|--------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                | OK      |                                                                                                                                                                                                   |
| `bufferedAmount should increase to byte length of encoded unicode string sent` | FAIL    | `assert_equals: Expect bufferedAmount to be the byte length of the unicode string expected 12 but got 0`                                                                                          |
| `bufferedAmount should increase to byte length of buffer sent`                 | FAIL    | `assert_equals: Expect bufferedAmount to increase to byte length of sent buffer expected 5 but got 0`                                                                                             |
| `bufferedAmount should increase to size of blob sent`                          | FAIL    | `assert_equals: Expect bufferedAmount to increase to size of sent blob expected 5 but got 0`                                                                                                      |
| `bufferedAmount should increase by byte length for each message sent`          | FAIL    | `assert_unreached: Unexpected promise rejection: Error: assert_equals: Expect bufferedAmount to be the total length of all messages queued to send expected 5 but got 0 Reached unreachable code` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6572/webrtc/RTCDataChannel-send.html">/webrtc/RTCDataChannel-send.html</a></summary>


|                                         Subtest                                          | Results | Messages |
|------------------------------------------------------------------------------------------|---------|----------|
|                                                                                          | OK      |          |
| `Calling send() when data channel is in connecting state should throw InvalidStateError` | PASS    |          |
| `Data channel should be able to send simple string and receive as string`                | PASS    |          |
| `Data channel should be able to send unicode string and receive as unicode string`       | PASS    |          |
| `Data channel should ignore binaryType and always receive string message as string`      | PASS    |          |
| `Data channel should be able to send Uint8Array message and receive as ArrayBuffer`      | PASS    |          |
| `Data channel should be able to send ArrayBuffer message and receive as ArrayBuffer`     | PASS    |          |
| `Data channel should be able to send Blob message and receive as ArrayBuffer`            | PASS    |          |
| `Data channel should be able to send ArrayBuffer message and receive as Blob`            | PASS    |          |
| `Data channel binaryType should receive message as Blob by default`                      | PASS    |          |
| `Sending multiple messages with different types should succeed and be received`          | PASS    |          |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6572/webrtc/RTCPeerConnection-addIceCandidate.html">/webrtc/RTCPeerConnection-addIceCandidate.html</a></summary>


|                                                      Subtest                                                      | Results |                                                                                                                                              Messages                                                                                                                                             |
|-------------------------------------------------------------------------------------------------------------------|---------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|                                                                                                                   | OK      |                                                                                                                                                                                                                                                                                                   |
| `Add null candidate should reject with TypeError`                                                                 | FAIL    | `assert_unreached: Should have rejected: undefined Reached unreachable code`                                                                                                                                                                                                                      |
| `Add ICE candidate before setting remote description should reject with InvalidStateError`                        | PASS    |                                                                                                                                                                                                                                                                                                   |
| `Add candidate when remote description is null should never resolve when pc is closed`                            | PASS    |                                                                                                                                                                                                                                                                                                   |
| `Add ICE candidate after setting remote description should succeed`                                               | PASS    |                                                                                                                                                              [...]

2017-07-18 10:05 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254788135)

# Sauce (safari) #
Testing web-platform-tests at revision 8a6974db333ca409e35b1c7c6c44ed1c99c25e82
Using browser at version 10.0
Starting 10 test iterations
## Unstable results ##


|                    Test                   |                                            Subtest                                             |     Results     |                 Messages                 |
|-------------------------------------------|------------------------------------------------------------------------------------------------|-----------------|------------------------------------------|
| `/webrtc/RTCRtpParameters-encodings.html` | `setParameters() with modified encoding.rtx field should reject with InvalidModificationError` | **FAIL: 20/10** | `Can't find variable: RTCPeerConnection` |

## All results ##
<details>
<summary>31 tests ran</summary>
<details>
<summary><a href="http://w3c-test.org/submissions/6572/webrtc/RTCDataChannel-bufferedAmount.html">/webrtc/RTCDataChannel-bufferedAmount.html</a></summary>


|                                    Subtest                                     | Results |                 Messages                 |
|--------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                | OK      |                                          |
| `bufferedAmount should increase to byte length of encoded unicode string sent` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `bufferedAmount should increase to byte length of buffer sent`                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `bufferedAmount should increase to size of blob sent`                          | FAIL    | `Can't find variable: RTCPeerConnection` |
| `bufferedAmount should increase by byte length for each message sent`          | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6572/webrtc/RTCDataChannel-send.html">/webrtc/RTCDataChannel-send.html</a></summary>


|                                         Subtest                                          | Results |                 Messages                 |
|------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                          | OK      |                                          |
| `Calling send() when data channel is in connecting state should throw InvalidStateError` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should be able to send simple string and receive as string`                | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should be able to send unicode string and receive as unicode string`       | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should ignore binaryType and always receive string message as string`      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should be able to send Uint8Array message and receive as ArrayBuffer`      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should be able to send ArrayBuffer message and receive as ArrayBuffer`     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should be able to send Blob message and receive as ArrayBuffer`            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel should be able to send ArrayBuffer message and receive as Blob`            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Data channel binaryType should receive message as Blob by default`                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Sending multiple messages with different types should succeed and be received`          | FAIL    | `Can't find variable: RTCPeerConnection` |

</details>
<details>
<summary><a href="http://w3c-test.org/submissions/6572/webrtc/RTCPeerConnection-addIceCandidate.html">/webrtc/RTCPeerConnection-addIceCandidate.html</a></summary>


|                                                      Subtest                                                      | Results |                 Messages                 |
|-------------------------------------------------------------------------------------------------------------------|---------|------------------------------------------|
|                                                                                                                   | OK      |                                          |
| `Add null candidate should reject with TypeError`                                                                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add ICE candidate before setting remote description should reject with InvalidStateError`                        | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate when remote description is null should never resolve when pc is closed`                            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add ICE candidate after setting remote description should succeed`                                               | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add ICE candidate with RTCIceCandidate should succeed`                                                           | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with only valid sdpMid should succeed`                                                             | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with only valid sdpMLineIndex should succeed`                                                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `addIceCandidate with first sdpMid and sdpMLineIndex add candidate to first media stream`                         | FAIL    | `Can't find variable: RTCPeerConnection` |
| `addIceCandidate with second sdpMid and sdpMLineIndex should add candidate to second media stream`                | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate for first media stream with null ufrag should add candidate to first media stream`                 | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Adding multiple candidates should add candidates to their corresponding media stream`                            | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add with empty candidate string (end of candidate) should succeed`                                               | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with both sdpMid and sdpMLineIndex manually set to null should reject with TypeError`              | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with only valid candidate string should reject with TypeError`                                     | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with invalid candidate string and both sdpMid and sdpMLineIndex null should reject with TypeError` | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with empty dict should reject with TypeError`                                                      | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with manually filled default values should reject with TypeError`                                  | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with invalid sdpMid should reject with OperationError`                                             | FAIL    | `Can't find variable: RTCPeerConnection` |
| `Add candidate with invalid sdpMLineIndex should reject with OperationError`                       [...]

2017-07-18 10:05 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254788142)

# Chrome (unstable) #
Testing web-platform-tests at revision 8a6974db333ca409e35b1c7c6c44ed1c99c25e82
Using browser at version 61.0.3153.4 dev
Starting 10 test iterations

2017-07-18 10:05 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/254788143)

# Sauce (MicrosoftEdge) #
Testing web-platform-tests at revision 8a6974db333ca409e35b1c7c6c44ed1c99c25e82

2017-07-19 19:32 UTC, rwaldron approved these changes
- Coverage spec updated:
    - https://rwaldron.github.io/webrtc-pc/#dom-rtcpeerconnection-addtransceiver
    - https://rwaldron.github.io/webrtc-pc/#dom-rtcrtpsender-setparameters
    - https://rwaldron.github.io/webrtc-pc/#dom-rtcrtpsender-getparameters()
    - https://rwaldron.github.io/webrtc-pc/#dom-rtcpeerconnection-getsenders
    - https://rwaldron.github.io/webrtc-pc/#dom-rtcpeerconnection-getreceivers
    - https://rwaldron.github.io/webrtc-pc/#dom-rtcpeerconnection-gettransceivers

2017-07-19 19:32 UTC, rwaldron commented on webrtc/dictionary-helper.js
> +}
I definitely prefer these assertions over using idlharness

2017-07-19 19:37 UTC, rwaldron commented
I've restarted the two failing CI tasks

2017-07-19 19:51 UTC, rwaldron requested changes

2017-07-19 19:51 UTC, rwaldron commented on webrtc/RTCRtpParameters-encodings.html
> +  }, `setParameters() with modified encoding.rtx field should reject with InvalidModificationError`);
This is a duplicate test name

2017-07-20 02:43 UTC, soareschen commented on webrtc/RTCRtpParameters-encodings.html
> +  }, `setParameters() with modified encoding.rtx field should reject with InvalidModificationError`);
Oops, should be `encoding.fec`

2017-07-26 20:24 UTC, rwaldron requested changes

2017-07-26 20:24 UTC, rwaldron commented on webrtc/RTCPeerConnection-addTransceiver.html
> +  }, 'addTransceiver() with rid containing invalid non-alphanumeric characters should throw TypeError');
👍

2017-07-26 20:24 UTC, rwaldron commented on webrtc/RTCPeerConnection-addTransceiver.html
> +  }, 'addTransceiver() with rid longer than 16 characters should throw TypeError');
👍

2017-07-26 20:24 UTC, rwaldron commented on webrtc/RTCPeerConnection-addTransceiver.html
> +  }, `addTransceiver() with valid rid value should succeed`);
👍

2017-07-26 20:24 UTC, rwaldron commented on webrtc/RTCRtpParameters-degrationPreference.html
> +<title>RTCRtpParameters degrationPreference</title>
typo: `degrationPreference`=> `degradationPreference`

(The filename needs to be updated as well)

2017-07-26 20:24 UTC, rwaldron commented on webrtc/RTCRtpParameters-degrationPreference.html
> +    assert_equals(param.degrationPreference, 'balanced',
`degrationPreference` => `degradationPreference`

2017-07-26 20:24 UTC, rwaldron commented on webrtc/RTCRtpParameters-degrationPreference.html
> +      'Expect initial param.degrationPreference to be balanced');
`degrationPreference` => `degradationPreference`

2017-07-26 20:24 UTC, rwaldron commented on webrtc/RTCRtpParameters-degrationPreference.html
> +    param.degrationPreference = 'maintain-framerate';
`degrationPreference` => `degradationPreference`

2017-07-26 20:24 UTC, rwaldron commented on webrtc/RTCRtpParameters-degrationPreference.html
> +    param.degrationPreference = 'maintain-framerate';
And all other occurrences.

2017-07-26 20:24 UTC, rwaldron commented on webrtc/RTCRtpParameters-codecs.html
> +      codec.mimeType = 'audio/piedpiper';
![](https://ih0.redbubble.net/image.222702072.4474/flat,800x800,075,f.jpg)

2017-07-27 03:21 UTC, soareschen commented on webrtc/RTCRtpParameters-degrationPreference.html
> +<title>RTCRtpParameters degrationPreference</title>
Oops, I have been reading the word wrong the whole time!

2017-07-27 03:22 UTC, soareschen commented on webrtc/RTCRtpParameters-degrationPreference.html
> +<title>RTCRtpParameters degrationPreference</title>
Have rebased and fixed it.

2017-07-27 20:58 UTC, rwaldron requested changes
I believe all that remains is the duplicate test name

2017-07-28 02:24 UTC, soareschen commented on webrtc/RTCRtpParameters-encodings.html
> +  }, `setParameters() with modified encoding.rtx field should reject with InvalidModificationError`);
Oops, think I patched that on a different computer and forgot to sync with local computer before force pushing. Have fixed that again.

2017-07-28 18:53 UTC, rwaldron approved these changes
Thanks for the final fixup!

2017-07-31 19:55 UTC, rwaldron commented
I don't know why this is failing in CI

2017-07-31 19:55 UTC, rwaldron commented
@jgraham Any ideas?

2017-08-02 19:31 UTC, rwaldron commented
Sorry to be a pest... @jgraham @bobholt any ideas for what's causing this CI failure?

2017-08-03 02:29 UTC, soareschen commented
I'll try rebase and see if it fixes the problem.

2017-08-03 11:35 UTC, bobholt commented
There are 3 different (possibly related) issues happening in 3 browsers.

- Safari: [The Sauce Labs Virtual Machine Failed to Start the Browser or Device](https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages#CommonErrorMessages-TheSauceLabsVirtualMachineFailedtoStarttheBrowserorDevice)
- Chrome: Unsupported test type wdspec for product chrome
- Edge: Times out

The Sauce docs (linked above) suggest that our Selenium version doesn't match our browser choice or our browser choice isn't supported. AFAIK that hasn't changed recently. I just restarted that job again to see if it clears. If not, I'll look deeper.

Chrome and Edge won't block the build, but that Chrome problem looks like perhaps the logic to drop wdspec from non-geckodriver tests in `tools/wpt/run.py` isn't working (cc @jgraham). So far I've only looked at it to see that it's a place in the code that mentions `wdspec`.

So I don't know why any of it's failing for sure, but I can dig at it for a while.

2017-08-03 12:50 UTC, bobholt commented
Update: The Sauce job still failed, but this time in a timeout. It's still intermittently hitting that Sauce error, but not as frequently, which makes me think it's Sauce that's flaky.

Aside: These changes cause 42 tests and their subtests to run which generates a massive amount of data ([nearly 1200 lines of results](https://gist.github.com/bobholt/e37c16c1647e26eaff8dab0e7b54e565))  and took over 30 minutes in Firefox. If there's a way to break up this PR into multiple, it might fit down Travis/Sauce's throat a little better. If not, I'll keep digging.

2017-08-03 13:02 UTC, jgraham commented
Chrome isn't failing because of the wdspec thing; it's failing because it hangs at some point. This looks surprsingly like the DBUS issues that were fixed, but is presumably actually something else.

2017-08-03 15:56 UTC, rwaldron commented
>  If there's a way to break up this PR into multiple, it might fit down Travis/Sauce's throat a little better

I think I will do this for @soareschen to get his work landed.

2017-08-03 16:23 UTC, rwaldron commented
Ok, on further consideration, I figured out a way to do it that was actually painless.

2017-08-03 16:27 UTC, rwaldron commented
Each of the PRs that I created will be rebased after the one before it lands

2017-08-03 16:29 UTC, bobholt commented
:+1: Breaking it down might also help narrow down what's actually causing the failures.

2017-08-03 17:34 UTC, rwaldron commented
@bobholt and I were able to determine that the timeout is the result of changes made to RTCPeerConnection-helper.js, which is required by 32 files in this directory. As it was explained to me: each file that was affected by that change, ie. all 32 files, is run 10 times by the stability check to determine stability. If all 10 runs produce the same results, then the stability check is passed. The problem here is that we have: 

```
32 * 10 * t
```

Where `t` is the time to run each of the 32 files, which in this PR's case is exceeding the 50 minute timeout imposed by travis CI and causing us to fail.

2017-08-03 17:42 UTC, rwaldron commented
cc @jgraham any suggestions for how we might resolve this?

2017-08-04 02:27 UTC, soareschen commented
Thanks @rwaldron and @bobholt for investigating.

Hmm we might have to break down RTCPeerConnection-helper.js into individual helper files, or inline them with each test case. Then again the refactoring PR might fail the CI because it is modifying the helper file.

I could undo the "bug fix" in RTCPeerConnection-helper.js first and see if can prevent the timeout from happening.

2017-08-04 04:08 UTC, soareschen commented
Looks like not touching RTCPeerConnection-helper.js works. I'll merge this first.

2017-08-04 04:08 UTC, merged

2017-08-04 15:02 UTC, rwaldron commented
👏