Split tests for setting session description into multiple files (rebase only)
web-platform-tests/wpt pull request #6629
Opened 2017-07-26 16:18 UTC by rwaldron

@bobholt This is just a rebasing of a PR that I previously reviewed and approved. I didn't want to block @soareschen anymore so I offered to resolve the conflict myself—which this PR is the result of.

2017-07-26 16:22 UTC, bobholt requested changes

2017-07-26 16:22 UTC, bobholt commented on webrtc/coverage/set-session-description.txt
> +>>>>>>> Update coverage report for set-session-description
Looks like remainder from a merge conflict resolution.

2017-07-26 16:23 UTC, rwaldron commented on webrtc/coverage/set-session-description.txt
> +>>>>>>> Update coverage report for set-session-description
Derp. Will fix that now

2017-07-26 17:36 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257797258)

# Firefox (nightly) #

2017-07-26 17:36 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257797259)

# Sauce (safari) #

2017-07-26 17:36 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257797268)

# Chrome (unstable) #

2017-07-26 17:36 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/257797270)

# Sauce (MicrosoftEdge) #

2017-07-26 17:47 UTC, bobholt approved these changes

2017-07-26 19:42 UTC, merged

2017-07-26 19:42 UTC, rwaldron commented
Thanks @bobholt!

2017-07-27 03:41 UTC, soareschen commented
Oops, this undo some of the removals in #6616. I will make another PR to remove the isClosed-then-abort tests again.