Add initial test for RTCDTMFSender
web-platform-tests/wpt pull request #6659
Opened 2017-07-31 10:40 UTC by soareschen

This adds test for the final uncovered section in webrtc-pc.

This test makes the assumption discussed in w3c/webrtc-pc#1415, that the `dtmf` attribute for `RTCRtpSender` is always set for audio transceivers. This is required as otherwise it is impossible to reliably obtain an instance of RTCDTMFSender.

2017-07-31 11:36 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259316793)

# Firefox (nightly) #

2017-07-31 11:36 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259316794)

# Sauce (safari) #

2017-07-31 11:36 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259316800)

# Chrome (unstable) #

2017-07-31 11:36 UTC, w3c-bots commented
[View the complete job log.](https://travis-ci.org/w3c/web-platform-tests/jobs/259316801)

# Sauce (MicrosoftEdge) #

2017-08-07 19:47 UTC, rwaldron requested changes

2017-08-16 04:35 UTC, soareschen commented on webrtc/RTCPeerConnection-helper.js
> +
Missed your comment. Have fixed it now. Hope the CI will pass now.

2017-08-17 18:41 UTC, rwaldron requested changes
Minor fixes needed

2017-08-18 08:51 UTC, soareschen commented on webrtc/RTCDTMFSender-ontonechange.html
> +            RTCDTMFSender object.
Nice catch! I have fixed them now.

Step 5 is excluded because it is untestable.

2017-08-18 13:31 UTC, rwaldron commented on webrtc/RTCDTMFSender-ontonechange.html
> +            RTCDTMFSender object.
Got it!

2017-08-18 14:56 UTC, rwaldron commented
I tried to add you as a CC on this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1290948 but bugzilla could not find your email address.

2017-08-18 15:07 UTC, rwaldron approved these changes

2017-08-18 15:07 UTC, merged

2017-08-21 02:29 UTC, soareschen commented
> I tried to add you as a CC on this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1290948 but bugzilla could not find your email address.

Hmm I do have an account on Bugzilla. Did you use my main email soares.chen@gmail.com?