[testharness] add link_to_spec and link_name properties to test().
web-platform-tests/wpt pull request #6754
Opened 2017-08-04 14:37 UTC by tobie

This allows idlharness to link to relevant sections of WebIDL.

2017-08-04 14:39 UTC, tobie commented
Note: I voluntarily left this undocumented because of link-rot issues.

2017-08-04 16:52 UTC, jgraham commented
Rebase this on master to pass travis.

2017-08-04 16:53 UTC, jgraham requested changes

2017-08-04 16:53 UTC, jgraham commented on resources/testharness.js
> +            var link_name = tests[i].properties.link_name || "spec";
I think this should be documented.

2017-08-04 17:17 UTC, tobie commented on resources/testharness.js
> +            var link_name = tests[i].properties.link_name || "spec";
In `/docs/` or in the src code itself?

2017-08-04 17:23 UTC, jgraham commented on resources/testharness.js
> +            var link_name = tests[i].properties.link_name || "spec";
In `/docs/`

2017-08-17 11:39 UTC, zcorpan reviewed
I think some tests use a "help" property for this purpose (though not actually used by anything). Does this replace that? Should this support multiple links per test?

2017-10-05 10:12 UTC, Ms2ger commented on resources/testharness.js
> +                " (<a href=" + JSON.stringify(link_url) + ">" + escape_html(link_name) + "</a>)" : "";
Why JSON?

2017-11-15 22:38 UTC, sideshowbarker reviewed
(Didn’t review this; was pinged by wpt-prbot to review it, so just commenting to remove it from my review queue)

2020-10-20 02:57 UTC, sideshowbarker commented
This seems to be waiting on responses to review comments. (And will need rebasing and conflict-fixing if we are to merge it.)

2020-10-20 06:57 UTC, Ms2ger commented
I think a proposal like this would require an RFC if it were made now, and I doubt CI will cope with this PR even if rebased, so I'll just close it. Feel free to reopen the discussion if you still believe this is useful.

2020-10-20 06:57 UTC, closed without merging

2020-10-20 07:16 UTC, sideshowbarker commented
> Feel free to reopen the discussion if you still believe this is useful.

I’m fine with having it closed — just wanted to get it resolved one way or the other