Add a lint check for 'web-platform.test.
web-platform-tests/wpt pull request #6868
Opened 2017-08-14 09:59 UTC by mikewest

Silly developers, including myself in #6849, tend to hard-code the string
'web-platform.test' when developing tests locally. This patch adds a lint
check to make that kind of mistake harder to make. Closes #6556.

2017-08-14 10:00 UTC, mikewest commented
@gsnedders, FYI. This bit me, so I'm adding a lint check. :)

2017-08-14 10:03 UTC, jgraham commented
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/web-platform-tests/6868)*
<!-- Sent from Reviewable.io -->

2017-08-14 10:19 UTC, w3c-bots commented
# Build PASSED

Started: 2017-08-14 10:00:52
Finished: 2017-08-14 10:18:59



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17346)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264300977)

2017-08-14 13:29 UTC, jgraham commented
Please rebase onto master

2017-09-04 20:54 UTC, gsnedders commented
@mikewest ping!

2017-09-12 14:08 UTC, jgraham approved these changes

2017-09-12 14:14 UTC, jgraham requested changes
Need to fix up existing uses.

2017-09-12 14:16 UTC, w3c-bots commented
# Build PASSED

Started: 2017-08-14 10:00:52
Finished: 2017-08-14 10:18:59





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17346)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/264300977)

2017-10-19 16:53 UTC, jdm commented
It would be great to get this merged, even if the existing uses were added to the whitelist.

2017-11-07 22:57 UTC, gsnedders commented
@jgraham r? just whitelisted everything, but we can at least land it

2017-11-07 23:14 UTC, jdm commented
.travis.yml is triggering the lint now :)

2017-11-07 23:28 UTC, gsnedders commented
@jdm well, I'm good at managing to do things!

2017-11-08 00:17 UTC, jgraham commented
Can you file issues on the entries that should probably be removed?

2017-11-08 00:26 UTC, gsnedders commented
@jgraham we haven't required that when adding new lints before… we have hundreds of things that should be fixed generally

2017-11-24 13:51 UTC, gsnedders commented
@jgraham ok, done

2017-11-29 14:12 UTC, gsnedders commented
@jgraham ping?

2017-12-04 19:59 UTC, jgraham approved these changes

2017-12-04 20:00 UTC, merged