[css-grid] Updated meta-data tags to refer the relevant spec section.
web-platform-tests/wpt pull request #6917
Opened 2017-08-17 11:25 UTC by javifernandez

The alignment related tests are not being indexed correctly in the test suite. The reason is that none of these tests refer to the relevant spec section. 

This change adds the meta-data links to refer the appropriated spec section for each group of tests.

2017-08-17 12:09 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17495)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/265535354)

2017-08-17 12:09 UTC, w3c-bots commented
# Build ERRORED

Started: 2017-08-17 11:26:34
Finished: 2017-08-17 12:09:12



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17495)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/265535354)

2017-08-31 13:22 UTC, frivoal requested changes
Nice patch. Just one little issue (repeated over all files), 1 typo, and 1 question, and we're good to go.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-010.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#grid-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-012.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#grid-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-017.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#grid-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-024.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#grid-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-005.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#collapsed-track">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-008.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#collapsed-track">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-009.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#collapsed-track">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-012.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#grid-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-012.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#collapsed-track">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-013.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#collapsed-track">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-014.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#grid-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-015.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#collapsed-track">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-016.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#collapsed-track">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-018.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#collapsed-track">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-020.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#grid-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-023.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#grid-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-024.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#grid-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-002.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-003.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-004.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-005.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-006.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-007.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-008.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-009.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-011.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-012.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-013.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-014.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-015.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-016.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-001.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-002.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-003.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-004.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-005.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-006.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-007.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-008.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-009.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-010.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-011.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-012.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-013.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-014.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-015.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-lr-016.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-001.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-002.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-003.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-004.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-005.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-006.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-007.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-008.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-009.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-010.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-011.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-012.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-013.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-014.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-015.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-016.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#alignment">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/grid-self-alignment-stretch-vertical-rl-016.html
> +<link rel="help" href="https://drafts.csswg.org/css-align/#valdef-align-self-stretch">
Same as above, use `css-align-3` rather than `css-align`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/self-baseline/grid-self-baseline-changes-grid-area-size-001.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#column-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/self-baseline/grid-self-baseline-changes-grid-area-size-002.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#column-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/self-baseline/grid-self-baseline-changes-grid-area-size-003.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#column-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/self-baseline/grid-self-baseline-changes-grid-area-size-004.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#column-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/self-baseline/grid-self-baseline-changes-grid-area-size-005.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#column-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/self-baseline/grid-self-baseline-changes-grid-area-size-006.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#column-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/self-baseline/grid-self-baseline-changes-grid-area-size-007.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#row-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/self-baseline/grid-self-baseline-changes-grid-area-size-008.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#row-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/self-baseline/grid-self-baseline-changes-grid-area-size-009.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#row-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/self-baseline/grid-self-baseline-changes-grid-area-size-010.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#row-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/self-baseline/grid-self-baseline-changes-grid-area-size-011.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#row-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 13:22 UTC, frivoal commented on css/css-grid-1/alignment/self-baseline/grid-self-baseline-changes-grid-area-size-012.html
> +<link rel="help" href="https://drafts.csswg.org/css-grid/#row-align">
Same as above, use `css-grid-1` rather than `css-grid`.

2017-08-31 14:04 UTC, javifernandez commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-001.html
> -<link rel="help" href="https://drafts.csswg.org/css-align-3/#distribution-values">
Yes, as we don't include that info in the rest of the tests of this kind, which focus on the collapsed tracks issues. We already provide that info in the Content Distribution related tests. 

If you consider is still relevant info, I should add it to all these tests, for consistency.

2017-08-31 14:05 UTC, javifernandez commented
Thanks for the review. I replied to your question and of course agree with the rest of the comments. I'll provide a new patch addressing all the issues ASAP.

2017-08-31 14:29 UTC, w3c-bots commented
# Build PASSED

Started: 2017-08-17 14:54:53
Finished: 2017-08-17 15:31:22


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

<li>chrome:unstable</li>

<li>safari:10.0</li>

<li>MicrosoftEdge:14.14393</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17510)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/265610372)

2017-08-31 14:33 UTC, frivoal commented on css/css-grid-1/alignment/grid-content-distribution-with-collapsed-tracks-001.html
> -<link rel="help" href="https://drafts.csswg.org/css-align-3/#distribution-values">
I see. No, it's ok, no need to add it everywhere.

2017-08-31 14:37 UTC, frivoal commented
The patch fixes most of the problems, but not all. See the comments above that are still open.

2017-08-31 16:17 UTC, javifernandez commented
Last patch addresses the pending issues.

2017-09-01 00:28 UTC, frivoal approved these changes

2017-09-01 00:28 UTC, merged