Avoid visual comparisons with lang="ja-jp"
web-platform-tests/wpt pull request #6926
Opened 2017-08-17 20:27 UTC by kahsieh

The reference file `attribute-value-selector-001-ref.xht` does not specify `lang="ja-jp"` on the first `div` while this file does. This causes the two pages to look different because a Japanese font is selected in this file. Changing "ja-jp" to a language written in Latin letters, "fr-fr", avoids this problem.

2017-08-17 20:37 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17528)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/265728775)

2017-08-17 20:37 UTC, w3c-bots commented
# Build PASSED

Started: 2017-08-17 20:28:37
Finished: 2017-08-17 20:37:43



View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17528)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/265728775)

2017-08-17 23:36 UTC, dbaron requested changes
Seems like that's fine if you're running an English build of a browser, but what if you're running a Japanese build?  Perhaps it should instead specify the same language on both test and reference?

2017-08-17 23:42 UTC, gsnedders commented
Or it should be rewritten to not use the `lang` attribute and avoid this quirkiness altogether.

As an aside, I can't see anything in any spec that would seem to permit what browsers actually do with language-specific generics; spec bug forthcoming.

2017-08-17 23:51 UTC, kahsieh commented
For now, if we want to have such consistency, more extensive changes would be needed (please see revised commit).

2017-08-21 05:28 UTC, sideshowbarker commented
w3c-test:mirror

2017-09-01 16:03 UTC, kojiishi commented
@dbaron's comment above looks reasonable, was that addressed? I can see only 1 commit.

2017-09-01 16:17 UTC, kahsieh commented
Yes, it has been addressed. I applied the same language tags to the reference and all three tests that use it.

2017-09-01 16:24 UTC, dbaron approved these changes

2017-09-01 16:25 UTC, w3c-bots commented
# Build PASSED

Started: 2017-08-18 00:01:48
Finished: 2017-08-18 00:04:16


<h2>Failing Jobs</h2>
<ul>

<li>build_css</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17533)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/265789484)

2017-09-01 16:25 UTC, merged