Make use of RTCPeerConnection.prototype.{getConfiguration, setConfiguration} defensive
web-platform-tests/wpt pull request #7025
Opened 2017-08-28 15:09 UTC by rwaldron

2017-08-28 15:23 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/17830)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/269233631)

2017-08-29 14:27 UTC, rwaldron commented
Before:

![](https://i.gyazo.com/babcf5c03631d0eaf60943b7b93c1efe.png)

After:

![](https://i.gyazo.com/9ef97c72f03fbf4927ccacd77f71fd32.png)

2017-08-31 07:23 UTC, soareschen commented
Hmm why does it throw `InvalidAccessError` on your side. I thought it would throw something like "pc.setConfiguration is not a function". It is also weird that testharness doesn't catch the error and just abort remaining tests.

2017-08-31 07:25 UTC, soareschen requested changes

2017-08-31 07:25 UTC, soareschen commented on webrtc/RTCConfiguration-iceCandidatePoolSize.html
> +  const pc = new RTCPeerConnection({});
`pc` can be constructed with no argument, i.e. `new RTCPeerConnection()`

2017-08-31 07:25 UTC, soareschen commented on webrtc/RTCConfiguration-iceCandidatePoolSize.html
>    assert_equals(typeof pc.setConfiguration, "function", "RTCPeerConnection.prototype.setConfiguration is not implemented");
This become redundant with the `assert_idl_attribute` above. We probably don't want to assert everything too defensively.

2017-09-13 03:32 UTC, soareschen approved these changes

2017-09-13 03:32 UTC, merged