'CSS2/syntax/core-syntax-*.xht' lack 'invalid' flag.
web-platform-tests/wpt pull request #7264
Opened 2017-09-05 17:41 UTC by tgraham-antenna

Also, 'CSS2/syntax/core-syntax-008.xht' tests invalid 'color', not invalid '!'.

2017-09-05 17:52 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/18197)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/272158799)

2017-09-05 18:39 UTC, gsnedders requested changes
For some reason the manifest is picking up `css/CSS2/syntax/core-syntax-008.xht` as a support file, may just be the duplicated style tag making the DOM somehow odd. Will look closer if it still fails after that is fixed.

2017-09-05 18:39 UTC, gsnedders commented on css/CSS2/syntax/core-syntax-008.xht
> +  <style type="text/css">
This is duplicated.

2017-09-05 18:53 UTC, gsnedders reviewed
I'll let someone else actually check they are invalid, now this is passing.

2017-09-06 15:28 UTC, bert-github commented
On Tuesday, September 5, 2017 6:54:06 PM CEST Geoffrey Sneddon wrote:
> I'll let someone else actually check they are invalid, now this is
> passing.

AFAICS, all eight tests are indeed testing invalid CSS. The change to 
the title is useful, too. I'm in favor of this proposed patch.



Bert
-- 
  Bert Bos                                ( W 3 C ) http://www.w3.org/
  http://www.w3.org/people/bos                               W3C/ERCIM
  bert@w3.org                             2004 Rt des Lucioles / BP 93
  +33 (0)4 92 38 76 92            06902 Sophia Antipolis Cedex, France

2017-09-06 16:16 UTC, gsnedders approved these changes

2017-09-06 16:16 UTC, merged