Introduce a new test_idl function that simplifies using idlharness with external IDL files.
web-platform-tests/wpt pull request #7559
Opened 2017-10-03 14:48 UTC by Ms2ger

2017-10-03 14:56 UTC, foolip reviewed
Can you also convert webrtc/interfaces.html to show that this helper can deal well (enough) with the case where the objects for testing aren't known synchronously?

2017-10-03 14:57 UTC, foolip commented on cssom-view/interfaces.html
> +addEventListener("load", function() {
Why wait for the load event?

2017-10-03 15:00 UTC, foolip commented on resources/idlharness.js
> +                throw new TypeError("Response is not ok for " + response.url);
What are the cases where the response is not ok but the promise isn't rejected? Seems odd :)

2017-10-03 15:05 UTC, jdm requested changes

2017-10-03 15:05 UTC, jdm commented on cssom/interfaces.html
> +var xmlss_pi = document.getElementById('xmlssPiIframe').contentDocument.firstChild;
There's no guarantee that the content document has finished loading yet, right? Shouldn't this be in the load handler?

2017-10-03 15:05 UTC, jdm commented on resources/idlharness.js
> +    tested_code = "",
I don't see any users of tested_code.

2017-10-03 16:55 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19087)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/282767247)

2018-08-10 12:44 UTC, Ms2ger commented
#11833 did basically this, but actually landed.

2018-08-10 12:44 UTC, closed without merging