Make 039.html deterministic
web-platform-tests/wpt pull request #7689
Opened 2017-10-12 06:52 UTC by hajimehoshi

We found that 039.html was flaky after changing schedulers in Chromium (crbug.com/771729). Now the test expects that loading all the iframes ends within 200[ms] after window.onload. It looks like the scheduler change affected the result.

This PR fixes the test more deterministic by confirming all the iframe loaded before the assertion.

2017-10-12 07:04 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19362)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/286888682)

2017-10-12 12:23 UTC, jdm commented
I don't understand how this change avoids your flakiness. The window's load event should not be dispatched until the iframes are loaded; if that occurs, that sounds like a bug in the engine that needs to be investigated.

2017-10-12 13:37 UTC, hajimehoshi commented
Thank you

> The window's load event should not be dispatched until the iframes are loaded

Is that true? An iframe's onload event are fired when the source is loaded, and I think this has nothing to do with window's onload.

2017-10-12 13:44 UTC, jdm commented
Just after [this bit of the specification](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#iframe-load-event-steps), there is this paragraph:
```
When the iframe's browsing context's active document is not ready for post-load tasks, and when anything in the iframe is delaying the load event of the iframe's browsing context's active document, and when the iframe's browsing context is in the delaying load events mode, the iframe must delay the load event of its document.
```
This means that a document that contains an iframe that has not yet received a load event will itself have its load event delayed.

2017-10-13 12:05 UTC, gsnedders requested changes
As @jdm says, the flakiness seen in Chrome appears to be a bug in Chrome per spec.

2017-10-13 13:32 UTC, hajimehoshi commented
OK, thanks

2017-10-13 13:32 UTC, closed without merging