Added test for percentage definiteness change
web-platform-tests/wpt pull request #7949
Opened 2017-10-23 16:30 UTC by gregwhitworth

This test is similar to the one shown in [this issue](https://github.com/w3c/csswg-drafts/issues/1679) and in staying with our resolution of providing test cases for changes I'd like to land this PR ASAP. For those reviewing, it is worth noting that this change doesn't directly impact the inline direction with ltr/rtl writing-modes as the %s resolve as you'd expect. As such I only am providing a test case for testing percentage heights with both a non-wrapping flex and a wrapping flex.

2017-10-23 19:19 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/19821)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/291636112)

2017-10-28 14:39 UTC, gsnedders requested changes
This file has a horrible mix of tabs and spaces, sometimes within the same block. Per policy, everything should be using spaces. Otherwise, this LGTM.

2017-11-01 18:32 UTC, gregwhitworth commented
@gsnedders alrighty - fixed the mix of tabs/spaces

2017-11-03 15:49 UTC, gregwhitworth commented
@gsnedders We should be good to go now - mind completing the review and pulling it in?

2017-11-03 16:48 UTC, gsnedders approved these changes

2017-11-03 16:48 UTC, gsnedders commented
Feel free to merge when CI finishes.

2017-11-03 17:05 UTC, merged