Introduce the new WebIDL mixin syntax interfaces/*
web-platform-tests/wpt pull request #8092
Opened 2017-11-07 13:01 UTC by romandev

This patch includes the following things:
  - Remove any tests for `implements` statements.
  - Remove any tests for non-legacy usage of the `[NoInterfaceObject]`
    extended attribute.
  - Add tests for `includes` statements and interface mixins.

This fixes some parts of #8054 issue.

2017-11-07 13:05 UTC, tobie requested changes
So what's important is that the IDL in the `interfaces/` directory reflects the IDL contained in the specs. It seems that this pull request changes the IDL locally only, and not in the specs upstreams. So that's really where you want to start.

2017-11-07 13:22 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/20260)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/298533044)

2017-11-29 10:03 UTC, marcoscaceres reviewed
Couple of questions....

2017-11-29 10:03 UTC, marcoscaceres commented on payment-handler/payment-instruments.https.html
> +  try {
Won’t this throw because of the permission check?

2017-11-29 10:03 UTC, marcoscaceres commented on payment-handler/payment-instruments.https.html
> +    console.log(e);
If it throws, we probably want the test to fail, no?

2017-11-29 10:37 UTC, romandev commented
Sorry for noise.. This is my mistake.. I'll close this.

2017-11-29 10:37 UTC, closed without merging