webdriver: Add tests to check alerts happening in a script execution
web-platform-tests/wpt pull request #8413
Opened 2017-11-23 16:15 UTC by carlosgcampos

15.2 Executing Script

The rules to execute a function body are as follows. The algorithm
will return success with the JSON representation of the function’s
return value, or an error if the evaluation of the function results
in a JavaScript exception being thrown or at any point during its
execution an unhandled user prompt appears.

If at any point during the algorithm a user prompt appears, the user
prompt handler must be invoked. If its return value is an error, it
must immediately return with that error and abort all subsequent
substeps of this algorithm.

2017-11-23 16:23 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21009)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/306396201)

2017-11-23 18:01 UTC, andreastt requested changes
Can you please put this under /webdriver/tests/execute_script/user_prompts.py and replicate the file for the Execute Async Script command?

2017-11-23 18:01 UTC, andreastt commented on webdriver/tests/script_execution/alerts.py
> +def test_execute_script_handle_prompt_accept(new_session, add_browser_capabilites):
s/execute_script//g

2017-11-27 10:03 UTC, andreastt approved these changes

2017-11-27 10:03 UTC, merged