Close peer connection and tracks after end of each test
web-platform-tests/wpt pull request #8542
Opened 2017-12-02 05:51 UTC by soareschen

Fixes #8301.

This PR introduce add hoc clean up of peer connections and tracks using `t.add_cleanup()` in each test. This approach is use so that we can have minimal disruption to existing tests and make the changes more easily reviewable.

An alternative approach along the line of using a helper function like `makePeerConnection(t)` has been attempted before. But I discovered it is much harder to verify whether the refactoring has been done correctly or not.

This PR affects almost all tests in /webrtc, but it should _not_ affect the results of existing tests. I have tried to make sure that the test results remain the same as before, but there might be lurking mistakes
not yet executed by failing tests.

Some of the async tests require careful refactoring, in particular test of signaling state changes as closing pc too early may produce wrong assertion during event callback.

It may not be worthwhile to merge the whole PR if we find this too difficult or too large to review. If that is the case we may consider to only add the cleanup to the most resource intensive tests, and then gradually introduce cleanup to other small tests at a later time.

2017-12-02 06:23 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21369)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/310388569)

2017-12-08 13:32 UTC, snuggs requested changes
Nicely done and very meticulous. Great catch on the audio stop as well. Had a few suggestions inline.

2017-12-08 13:32 UTC, snuggs commented on webrtc/RTCConfiguration-helper.js
> +      return pc;
Do we explicitly need to return `pc` here?

2017-12-08 13:32 UTC, snuggs commented on webrtc/RTCPeerConnection-canTrickleIceCandidates.html
> +  test(t => {
Nice!

2017-12-08 13:32 UTC, snuggs commented on webrtc/RTCPeerConnection-helper.js
> +    });
Can you explain the logic here a bit? I think it can be refactored to be more terse. However unsure of the intent.

Thanks in advance!

2017-12-08 13:32 UTC, snuggs commented on webrtc/RTCPeerConnection-setRemoteDescription-tracks.https.html
> +    return getUserMediaTracksAndStreams(t, 1)
Should we extrapolate this magic number into a variable?

2017-12-08 13:32 UTC, snuggs commented on webrtc/RTCPeerConnection-setRemoteDescription-tracks.https.html
> +    return getUserMediaTracksAndStreams(t, 1)
Should we extrapolate this magic number into a variable?

2017-12-08 13:32 UTC, snuggs commented on webrtc/RTCPeerConnection-setRemoteDescription-tracks.https.html
> +    return getUserMediaTracksAndStreams(t, 1)
Should we extrapolate this magic number into a variable?

2017-12-08 13:32 UTC, snuggs commented on webrtc/RTCPeerConnection-setRemoteDescription-tracks.https.html
> +    return getUserMediaTracksAndStreams(t, 1)
Should we extrapolate this magic number into a variable?

2017-12-08 13:32 UTC, snuggs commented on webrtc/RTCPeerConnection-setRemoteDescription-tracks.https.html
> +    return getUserMediaTracksAndStreams(t, 1)
Should we extrapolate this magic number into a variable?

2017-12-08 13:32 UTC, snuggs commented on webrtc/RTCRtpSender-replaceTrack.html
> +    t.add_cleanup(() => track.stop());
Nice catch!

2017-12-08 13:32 UTC, snuggs commented on webrtc/RTCRtpSender-replaceTrack.html
> +    t.add_cleanup(() => track1.stop());
Nice catch!

2017-12-08 13:32 UTC, snuggs commented on webrtc/RTCRtpSender-replaceTrack.html
> +    t.add_cleanup(() => track2.stop());
Nice catch (again) !

2017-12-08 21:16 UTC, snuggs commented
@soareschen looks like we're going to need a rebase due to some recently conflicting introductions to master.

2018-06-25 09:16 UTC, soareschen commented
Yes this has been fixed by #11455. Closing it.

2018-06-25 09:16 UTC, closed without merging