[css-grid-1] Add test for percentage gaps in shrinkwrap width / content-based height using float.
web-platform-tests/wpt pull request #8576
Opened 2017-12-06 02:46 UTC by fantasai

https://github.com/w3c/csswg-drafts/issues/509

2017-12-06 02:55 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21496)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/312199920)

2017-12-15 10:21 UTC, mrego requested changes
Thanks for the test but I believe there's a mistake.

2017-12-15 10:21 UTC, mrego commented on css/css-grid/alignment/grid-gutters-011.html
> +        width: 100px;
We cannot have a fixed width here, otherwise the 10% column gap will be resolved to 10px and we'll have a red vertical stripe.

2017-12-15 10:21 UTC, mrego commented on css/css-grid/alignment/grid-gutters-011.html
> +<link rel="author" title="Elika J. Etemad" href="http://fantasai.inkedblade.net/contact">
Nit: I'd add an assert explaining what this is specifically testing.

2019-10-19 11:20 UTC, foolip commented
Closing and reopening to retrigger all CI.

2019-10-19 11:22 UTC, foolip commented
That didn't work, the branch is too far behind master where the CI config is. @fantasai can you rebase the branch?

2019-10-22 19:06 UTC, foolip commented
I was able to rebase the branch following [these instructions](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork), kinda.

The test had to be renamed to -014 since other tests have been added in the meantime. The comments on the original test presumably still apply, however.

2019-10-23 08:28 UTC, mrego commented
Mmmm, this is quite old. I've just checked the test and it shows red in all browsers, even without the fixed width.
This is because a while ago we changed the behavior of percentage tracks/gaps on indefinite size situations. Some related issues:
* https://github.com/w3c/csswg-drafts/issues/509
* https://github.com/w3c/csswg-drafts/issues/1921

So probably we can just forget about this test at this stage, sorry @foolip for having you spending time on the rebase and all that. :disappointed:

2019-10-23 08:28 UTC, closed without merging

2019-10-23 08:45 UTC, foolip commented
Thanks @mrego for getting to the bottom of this!