Add in more references for css-color tests
web-platform-tests/wpt pull request #8715
Opened 2017-12-18 03:11 UTC by csnardi

These should be the last tests missing references in css-color.

The tests `t32-opacity-basic-0.6-a.xht`, `t422-rgba-a0.6-a.xht`, and `t425-hsla-basic-a.xht` are failing on all platforms with Travis, but the references are basically verifying the reference `<div>` in the test itself, so I'm not sure if this is just something that all implementations have done incorrectly or what.

2017-12-18 03:33 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/21897)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/317897142)

2017-12-26 23:39 UTC, gsnedders commented
> The tests `t32-opacity-basic-0.6-a.xht`, `t422-rgba-a0.6-a.xht`, and `t425-hsla-basic-a.xht` are failing on all platforms with Travis, but the references are basically verifying the reference `<p>` in the test itself, so I'm not sure if this is just something that all implementations have done incorrectly or what.

I'm not sure we define the alpha blend mode well enough to actually assert that they exactly match, hence we may just be very slightly out. (I haven't actually looked at the screenshots here, but I expect we're just slightly out colour-wise.) @svgeesus?

2018-05-01 13:51 UTC, svgeesus reviewed
Sorry to have missed this PR. Will look into this in detail. Two aspects to consider:
- numerically accurate result and error limits
- actual spec text backing up exactly what the test is checking

2018-05-01 13:59 UTC, svgeesus requested changes

2018-05-01 13:59 UTC, svgeesus commented on css/css-color/t421-rgb-hex3-expand-b-ref.html
> +    <tr><td style="background: #ee9922">&nbsp;</td><td style="background: #e09020">&nbsp;</td></tr>
Those three changes are clearly correct, astonished the earlier values were in the test to be honest

2018-05-01 13:59 UTC, svgeesus commented on css/css-color/t422-rgba-a0.6-a.xht
> +		<p id="one">This text should be the same color as the line below.</p>
yes

2018-05-01 13:59 UTC, svgeesus commented on css/css-color/t425-hsla-basic-a.xht
> -		p { font-weight: bold; margin: 0; }
No, leave the bold in there. It is easier to see the correct color on bolder text.

2018-05-01 13:59 UTC, svgeesus commented on css/css-color/t32-opacity-zorder-c-ref.html
> +  very-nearly-green square inside of it:</p>
Not super happy on 'very-nearly-green' but ok. 
Suggest adding explicit  "and no red"

2018-05-01 13:59 UTC, svgeesus commented on css/css-color/t32-opacity-basic-0.6-a-ref.html
> +    <p class="test">This text should be the same color as the line below.</p>
Yes, clearly

2018-06-02 03:28 UTC, svgeesus commented
Still waiting for small changes requested in review.

2018-08-16 17:01 UTC, svgeesus commented
@csnardi waiting for your changes based on review

2018-12-10 17:49 UTC, svgeesus commented
> @csnardi waiting for your changes based on review

Small changes were requested a while ago. Should be easy.

2020-03-16 21:51 UTC, svgeesus commented
Looks like the requested changes are not going to be made. Maybe someone else should take over the changes?

2020-07-18 03:59 UTC, svgeesus commented
OK, given the original poster seems disinterested in making any suggested changes, I'm going to change my review to accept and then work on improvements on top of that. Not ideal, but the only way to unblock.

2020-07-18 03:59 UTC, svgeesus approved these changes

2020-07-18 19:18 UTC, merged

2020-07-18 19:18 UTC, gsnedders commented
> Not ideal, but the only way to unblock.

You could've just created a new PR that's a superset of this!