Expand the 2d.gradient.object.invalidcolour test.
web-platform-tests/wpt pull request #8751
Opened 2017-12-20 14:40 UTC by Ms2ger

2017-12-20 14:50 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22024)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/319203122)

2017-12-20 14:56 UTC, jdm requested changes

2017-12-20 14:56 UTC, jdm commented on 2dcontext/fill-and-stroke-styles/2d.gradient.object.invalidcolour.html
> +var g = ctx.createLinearGradient(0, 0, 100, 0);
This doesn't match the yaml source - linear vs radial.

2017-12-21 14:19 UTC, Ms2ger commented
@jdm fixed

2017-12-21 14:52 UTC, jdm approved these changes

2017-12-21 14:52 UTC, merged