Add AnimationTiming tests
web-platform-tests/wpt pull request #8782
Opened 2017-12-22 06:24 UTC by kaixinjxq

1.Check window.requestAnimationFrame can return a valid callback handle.
 2.Check FrameRequestCallback has a DOMHighResTimeStamp argument.
 3.Check cancelAnimationFrame used to cancel request callback.

2017-12-22 06:31 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22122)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/320080838)

2018-12-21 02:21 UTC, kaixinjxq commented
This PR is blocked on the required "Travis CI - Pull Request" check after #14499. In order to trigger it, I will close and reopen this PR.

2018-12-21 17:35 UTC, domenic requested changes

2018-12-21 17:35 UTC, domenic commented on html/webappapis/animation-frames/callback-handle.html
> +    function callback(time) {
This test would be much simpler as a sync test that just did the assert after calling requestAnimationFrame, and passed an empty function to rAF.

2018-12-21 17:35 UTC, domenic commented on html/webappapis/animation-frames/callback-timestamp.html
> +    let requestAnimation = window.requestAnimationFrame;
This line is not necessary.

2018-12-21 17:35 UTC, domenic commented on html/webappapis/animation-frames/callback-timestamp.html
> +    requestAnimation(callback);
This can be rewritten more simply as

```js
requestAnimationFrame(t.step_func_done(() => {
  assert_equals(...);
});
```

2018-12-21 17:35 UTC, domenic commented on html/webappapis/animation-frames/callback-handle.html
> +<link rel="help" href="http://www.w3.org/TR/animation-timing/#Window-interface-extensions">
These URLs are incorrect. Use https://html.spec.whatwg.org/multipage/#animation-frames instead.

2018-12-21 17:35 UTC, domenic commented on html/webappapis/animation-frames/cancel-handle-manual.html
> +<meta name="flags" content="interact">
I've never seen this used before; what does it do?

2018-12-25 08:45 UTC, kaixinjxq commented
@domenic, many thanks for your review! I just submit a new commit to address your comments, PTAL.

2018-12-30 23:24 UTC, domenic approved these changes

2019-01-02 02:06 UTC, kaixinjxq commented
@domenic, CI checks are all pass, it's ready for merge. :)

2019-01-02 15:19 UTC, merged