Correct CSS2/values/color-000.xht
web-platform-tests/wpt pull request #8997
Opened 2018-01-11 15:38 UTC by csnardi

According to Color 4, decimal values are acceptable in the rgb functions. Additionally, percent channels should be rounded appropriately (49.99% -> 127). Fix these two issues in color-000.xht.

2018-01-11 15:47 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/22648)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/327732552)

2018-01-26 10:28 UTC, Ms2ger requested changes
Can you point out where we have coverage for the number-with-decimal case now?

2018-01-26 19:01 UTC, csnardi commented
See e.g. https://github.com/w3c/web-platform-tests/blob/master/css/css-color/rgb-002.html and the other even-numbered RGB test cases.

2018-01-29 09:31 UTC, Ms2ger approved these changes

2018-01-29 09:33 UTC, merged