Create permissions test suite with IDL tests
web-platform-tests/wpt pull request #9301
Opened 2018-01-31 07:40 UTC by Honry

2018-01-31 07:51 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/23605)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/335506252)

2018-01-31 08:48 UTC, Honry commented
@jyasskin, @mounirlamouri, @marcoscaceres, I added you in the OWNERS file to help review Permissions API tests as you are spec editors, which means you'll get pinged on new PRs.  Please let me know if you want to be removed.

2018-01-31 10:22 UTC, mounirlamouri commented
sgtm. @Honry did you look at the Blink tests? I wonder if there are some that could be moved to WPT.

2018-01-31 12:30 UTC, Honry commented
> sgtm. @Honry did you look at the Blink tests? I wonder if there are some that could be moved to WPT.

Yeah, they are located at [here](https://chromium.googlesource.com/chromium/src.git/+/master/third_party/WebKit/LayoutTests/http/tests/permissions/), and I would like to move them to WPT.

2018-02-01 07:11 UTC, Honry commented
@mounirlamouri, most of Blink tests require user interaction to invoke/revoke permissions, which is under implementing at #5671, so I will go back to it once the new WebDriver feature is online.

2018-06-06 19:06 UTC, lukebjerring commented
What's happening with this PR?

2018-06-07 01:44 UTC, marcoscaceres commented
I guess these could land to start testing the IDL? @Honry, is the IDL still up to date?

2018-06-07 01:51 UTC, Honry commented
> @Honry, is the IDL still up to date?

@marcoscaceres, no, I will do it soon.

2018-06-07 02:52 UTC, marcoscaceres commented on permissions/interfaces.any.js
> +  done();
`done()` should be outside the test.

2018-06-07 02:52 UTC, marcoscaceres requested changes
apart from `done()`, looks great @Honry!

2018-06-07 03:08 UTC, Honry commented
@marcoscaceres, thanks for your review! `done()` is removed.

2018-06-07 04:09 UTC, marcoscaceres approved these changes
👌✨

2018-06-07 04:10 UTC, merged