Update the css-properties-values-api IDL file
web-platform-tests/wpt pull request #9774
Opened 2018-03-02 19:31 UTC by lukebjerring

2018-03-02 22:47 UTC, w3c-bots commented
# Build PASSED

Started: 2018-03-02 22:32:05
Finished: 2018-03-02 22:41:58


<h2>Failing Jobs</h2>
<ul>

<li>safari:11.0</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25200)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/348432487)

2018-07-16 13:23 UTC, foolip requested changes

2018-07-16 13:23 UTC, foolip commented on interfaces/css-properties-values-api.idl
> +           boolean   inherits     = false;
@lukebjerring this is out of sync with the spec, can you update this PR?

2018-07-26 14:30 UTC, lukebjerring commented
Updated. PTAL.

2018-07-26 14:32 UTC, lukebjerring commented
Note that we'll have an unimportant failure for the partial CSS namespace until #11819 lands.

2018-07-27 10:32 UTC, foolip approved these changes

2018-07-27 10:33 UTC, merged