Update the feature-policy IDL file
web-platform-tests/wpt pull request #9783
Opened 2018-03-02 19:31 UTC by lukebjerring

2018-03-07 05:51 UTC, foolip requested changes
Needs a test to use it, and I should go home.

2018-03-07 05:51 UTC, foolip commented on interfaces/feature-policy.idl
> +partial interface HTMLIFrameElement {
Wow, this is the least amount of IDL I've seen in any spec:
https://wicg.github.io/feature-policy/#integrations

2018-03-08 02:15 UTC, w3c-bots commented
# Build PASSED

Started: 2018-03-08 02:08:10
Finished: 2018-03-08 02:15:23





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25511)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/350509931)

2018-03-14 14:40 UTC, lukebjerring commented
Added a test, PTAL.

2018-03-14 16:05 UTC, foolip approved these changes
LGTM % the extra bits

2018-03-14 16:05 UTC, foolip commented on feature-policy/interfaces.any.js
> +if (self.importScripts) {
This bits ought to not be needed, sent https://github.com/w3c/web-platform-tests/pull/10033 to confirm.

2018-03-14 18:37 UTC, merged