Removing ES6 constructs from WebDriver send_keys test
web-platform-tests/wpt pull request #9820
Opened 2018-03-05 17:01 UTC by jimevans

2018-03-05 18:44 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25266)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/349392999)

2018-03-06 11:10 UTC, andreastt requested changes
Just a minor nit.

2018-03-06 11:10 UTC, andreastt commented on webdriver/tests/element_send_keys/form_controls.py
> +        var trackedEvents = ["focus", "change", "keypress", "keydown", "keyup", "input"]
Missing semicolon.

2018-03-06 12:52 UTC, andreastt approved these changes

2018-03-06 14:07 UTC, merged