Update the screen-orientation IDL file
web-platform-tests/wpt pull request #9827
Opened 2018-03-05 18:51 UTC by lukebjerring

2018-03-05 21:47 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25287)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/349439063)

2018-03-09 02:38 UTC, foolip requested changes
Indentation needs collapsing here too. (People will read these in order to understand test failures, so it's not just input for the tests.)

2018-03-14 15:16 UTC, lukebjerring commented
Added indent leading spaces trimming in https://github.com/GoogleChromeLabs/webidl-diff/commit/aaaf4d3d1bada7fa8c09c81713ae4cd9a642eaa7 .

PTAL.

2018-03-14 15:45 UTC, foolip approved these changes

2018-03-14 15:55 UTC, merged