Update the web-share IDL file
web-platform-tests/wpt pull request #9843
Opened 2018-03-05 19:09 UTC by lukebjerring

2018-03-05 23:19 UTC, w3c-bots commented
# Build BROKEN

Started: 2018-03-05 23:14:08
Finished: 2018-03-05 23:18:28


<h2>Failing Jobs</h2>
<ul>

<li>firefox:nightly</li>

<li>chrome:dev</li>

<li>safari:11.0</li>

<li>MicrosoftEdge:16.16299</li>

</ul>




View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25305)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/349449162)

2018-03-09 02:36 UTC, foolip requested changes
The indentation of this one is extra unusual. That is what the spec source text says, because ReSpec does things first.

I think some very simple scheme of collapsing all "extra" indentation per block of IDL we find would do the trick to make it nice enough, without parse+serialize.

2018-03-15 15:19 UTC, lukebjerring commented
Updated with leading whitespace trimming - PTAL.

2018-03-20 13:10 UTC, foolip approved these changes

2018-03-20 13:10 UTC, merged