Catch up the rename of white-space-collapse to text-space-collapse
web-platform-tests/wpt pull request #9915
Opened 2018-03-08 04:32 UTC by kojiishi

The `white-space-collapse` was renamed to `text-space-collapse`,
with some values moved to `text-space-trim`, and moved to CSS
Text level 4.

2018-03-08 13:06 UTC, w3c-bots commented
# Build PENDING

Started: None
Finished: None





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25588)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/350667232)

2018-03-08 13:15 UTC, frivoal requested changes

2018-03-08 13:15 UTC, frivoal commented on css/css-text/white-space/white-space-collapsing-discard-001.xht
> +					text-space-collapsing: discard;
The property is now called `text-space-collapse` not `text-space-collapsing`.

2018-03-08 13:15 UTC, frivoal commented on css/css-text/white-space/white-space-collapsing-preserve-breaks-001.xht
> +					text-space-collapsing: preserve-breaks;
The property is now called `text-space-collapse` not `text-space-collapsing`.

2018-12-26 04:58 UTC, frivoal commented
Fixed in a separate PR (5ab74422c00). Closing.

2018-12-26 04:58 UTC, closed without merging