Removes lines containing `GLib-GObject-CRITICAL` from the logs
web-platform-tests/wpt pull request #9924
Opened 2018-03-08 14:27 UTC by kritisingh1

Closes #9657

2018-03-08 15:26 UTC, jgraham requested changes
I think this generally looks good, but let's make the small fixup.

2018-03-08 15:26 UTC, jgraham commented on tools/wptrunner/wptrunner/browsers/firefox.py
> +            line = "";
I think just return should be sufficient.

2018-03-08 16:55 UTC, kritisingh1 commented
@jgraham I have updated the PR. Please review. Thanks

2018-03-08 20:15 UTC, w3c-bots commented
# Build PASSED

Started: 2018-03-08 20:00:36
Finished: 2018-03-08 20:15:04





View more information about this build on:

- [WPT PR Status](http://pulls.web-platform-tests.org/build/25633)
- [TravisCI](https://travis-ci.org/w3c/web-platform-tests/builds/350898943)

2018-03-12 16:43 UTC, gsnedders commented on tools/wptrunner/wptrunner/browsers/firefox.py
> +        if(line):
Tiny nit: this should be `if line:`. Otherwise, this looks good to me. (But I'd still like @jgraham to check.)

2018-03-12 22:39 UTC, jgraham approved these changes

2018-03-12 22:39 UTC, merged

2018-03-13 02:57 UTC, foolip commented
Yay, finally less verbose, thank you @kritisingh1!